module_name     = "openMTPK"


input           = ["../../include/arithmetic/arith_base.hpp",
                "../../include/arithmetic/arith_ops.hpp",
                "../../include/calculus/deriv.hpp",
                "../../include/linalg/matrix.hpp",
                "../../include/nt/primes.hpp"]

cxx-std         = "c++20"


