/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: arithmetic.i

package arithmetic

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
extern void _wrap_Swig_free_arithmetic_6002ede0108886c2(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_arithmetic_6002ede0108886c2(swig_intgo arg1);
extern swig_type_1 _wrap_Basics_greatest_power_arithmetic_6002ede0108886c2(uintptr_t arg1, swig_type_2 arg2, swig_type_3 arg3);
extern swig_type_4 _wrap_Basics_op_gcd_arithmetic_6002ede0108886c2(uintptr_t arg1, swig_type_5 arg2, swig_type_6 arg3);
extern uintptr_t _wrap_new_Basics_arithmetic_6002ede0108886c2(void);
extern void _wrap_delete_Basics_arithmetic_6002ede0108886c2(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_arithmetic_6002ede0108886c2(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_arithmetic_6002ede0108886c2(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrBasics uintptr

func (p SwigcptrBasics) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBasics) SwigIsBasics() {
}

func (arg1 SwigcptrBasics) Greatest_power(arg2 int64, arg3 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_Basics_greatest_power_arithmetic_6002ede0108886c2(C.uintptr_t(_swig_i_0), C.swig_type_2(_swig_i_1), C.swig_type_3(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrBasics) Op_gcd(arg2 int64, arg3 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_Basics_op_gcd_arithmetic_6002ede0108886c2(C.uintptr_t(_swig_i_0), C.swig_type_5(_swig_i_1), C.swig_type_6(_swig_i_2)))
	return swig_r
}

func NewBasics() (_swig_ret Basics) {
	var swig_r Basics
	swig_r = (Basics)(SwigcptrBasics(C._wrap_new_Basics_arithmetic_6002ede0108886c2()))
	return swig_r
}

func DeleteBasics(arg1 Basics) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Basics_arithmetic_6002ede0108886c2(C.uintptr_t(_swig_i_0))
}

type Basics interface {
	Swigcptr() uintptr
	SwigIsBasics()
	Greatest_power(arg2 int64, arg3 int64) (_swig_ret int64)
	Op_gcd(arg2 int64, arg3 int64) (_swig_ret int64)
}


