openGPMP: modules/ml/TEST.cpp File Reference
TEST.cpp File Reference
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
Classes
class NeuralNetwork
Functions
double sigmoid (double x)
double sigmoidDerivative (double x)
std::vector< std::vector< double > > multiply (const std::vector< std::vector< double > > &a, const std::vector< std::vector< double > > &b)
double computeLoss (const std::vector< double > &output, int label)
std::vector< double > loadImage (const std::string &imagePath)
std::vector< double > preprocessImage (const std::vector< double > &imagePixels)
int main ()
Variables
const int inputSize = 100
const int hiddenSize = 64
const int outputSize = 2
const double learningRate = 0.1
const int numEpochs = 100
Function Documentation
computeLoss()
double computeLoss (const std::vector< double > & output, int label)
Definition at line 166 of file TEST.cpp.
{
    double target = (label == 0) ? 0.0 : 1.0;
    double error = output[0] - target;
    return error * error;
}
Referenced by main().
loadImage()
std::vector< double > loadImage (const std::string & imagePath)
Definition at line 173 of file TEST.cpp.
{
    std::ifstream file(imagePath, std::ios::binary | std::ios::ate);
    if (!file) {
        std::cerr << "Failed to open image: " << imagePath << std::endl;
        exit(1);
    }
    std::streamsize fileSize = file.tellg();
    file.seekg(0, std::ios::beg);
    std::vector<uint8_t> imageBuffer(fileSize);
    if (!file.read(reinterpret_cast<char *>(imageBuffer.data()), fileSize)) {
        std::cerr << "Failed to read image: " << imagePath << std::endl;
        exit(1);
    }
    std::vector<double> imagePixels(imageBuffer.size());
    for (size_t i = 0; i < imageBuffer.size(); i++) {
        imagePixels[i] = static_cast<double>(imageBuffer[i]) / 255.0;
    }
    return imagePixels;
}
Referenced by main().
main()
int main (void)
Definition at line 204 of file TEST.cpp.
           {
    // Load the training images and labels
    std::vector<std::string> imagePaths = {"../../data/cat1.jpg",
                                           "../../data/cat2.jpg",
                                           "../../data/cat3.jpg",
                                           "../../data/cat4.jpg",
                                           "../../data/cat5.jpg",
                                           "../../data/dog1.jpg",
                                           "../../data/dog2.jpg",
                                           "../../data/dog3.jpg",
                                           "../../data/dog4.jpg",
                                           "../../data/dog5.jpg"};
    std::vector<double> labels = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1};
    // Preprocess the training images
    std::vector<std::vector<double>> preprocessedImages;
    for (const std::string &imagePath : imagePaths) {
        std::vector<double> imagePixels = loadImage(imagePath);
        std::vector<double> preprocessedImage = preprocessImage(imagePixels);
        preprocessedImages.push_back(preprocessedImage);
    }
    // Initialize the neural network
    NeuralNetwork neuralNetwork;
    // Train the network
    for (int epoch = 0; epoch < numEpochs; epoch++) {
        double totalLoss = 0.0;
        for (int i = 0; i < preprocessedImages.size(); i++) {
            // Forward pass
            std::vector<double> output =
                neuralNetwork.forward(preprocessedImages[i]);
            // Compute the loss
            double loss = computeLoss(output, labels[i]);
            totalLoss += loss;
            // Backward pass and weight update
            neuralNetwork.backward(preprocessedImages[i], labels[i]);
        }
        // Print average loss for the epoch
        double averageLoss = totalLoss / preprocessedImages.size();
        std::cout << "Epoch " << epoch << " Loss: " << averageLoss << std::endl;
    }
    // Classify new images
    std::string newImagePath = "../../data/staffy.jpg";
    std::vector<double> newImagePixels = loadImage(newImagePath);
    std::vector<double> preprocessedNewImage = preprocessImage(newImagePixels);
    // Forward pass
    std::vector<double> output = neuralNetwork.forward(preprocessedNewImage);
    // Perform classification based on the output
    return 0;
}
References NeuralNetwork::backward(), computeLoss(), NeuralNetwork::forward(), loadImage(), numEpochs, and preprocessImage().
multiply()
std::vector< std::vector< double > > multiply (const std::vector< std::vector< double > > & a, const std::vector< std::vector< double > > & b)
Definition at line 29 of file TEST.cpp.
{
    int rowsA = a.size();
    int colsA = a[0].size();
    int colsB = b[0].size();
    std::vector<std::vector<double>> result(rowsA,
                                            std::vector<double>(colsB, 0.0));
    for (int i = 0; i < rowsA; i++) {
        for (int j = 0; j < colsB; j++) {
            for (int k = 0; k < colsA; k++) {
                result[i][j] += a[i][k] * b[k][j];
            }
        }
    }
    return result;
}
Referenced by NeuralNetwork::backward(), and NeuralNetwork::forward().
preprocessImage()
std::vector< double > preprocessImage (const std::vector< double > & imagePixels)
Definition at line 197 of file TEST.cpp.
{
    // Perform image preprocessing steps (e.g., resize, normalize, etc.)
    // Placeholder implementation: return the original image as is
    return imagePixels;
}
Referenced by main().
sigmoid()
double sigmoid (double x)
Definition at line 17 of file TEST.cpp.
{
    return 1 / (1 + exp(-x));
}
Referenced by NeuralNetwork::backward(), gpmp::ml::VariationalAutoEncoder::decoder(), gpmp::ml::VariationalAutoEncoder::encoder(), gpmp::ml::AutoEncoder::forward(), NeuralNetwork::forward(), gpmp::ml::RecurrentAutoEncoder::recurr_fwd(), sigmoidDerivative(), and gpmp::ml::AutoEncoder::train().
sigmoidDerivative()
double sigmoidDerivative (double x)
Definition at line 22 of file TEST.cpp.
{
    double sigmoidX = sigmoid(x);
    return sigmoidX * (1 - sigmoidX);
}
References sigmoid().
Referenced by NeuralNetwork::backward().
Variable Documentation
hiddenSize
const int hiddenSize = 64
Definition at line 11 of file TEST.cpp.
Referenced by NeuralNetwork::backward(), NeuralNetwork::forward(), and NeuralNetwork::NeuralNetwork().
inputSize
const int inputSize = 100
Definition at line 10 of file TEST.cpp.
Referenced by NeuralNetwork::backward(), and NeuralNetwork::NeuralNetwork().
learningRate
const double learningRate = 0.1
Definition at line 13 of file TEST.cpp.
Referenced by NeuralNetwork::backward().
numEpochs
const int numEpochs = 100
Definition at line 14 of file TEST.cpp.
Referenced by main().
outputSize
const int outputSize = 2
Definition at line 12 of file TEST.cpp.
Referenced by NeuralNetwork::backward(), NeuralNetwork::forward(), and NeuralNetwork::NeuralNetwork().