openGPMP: gpmp::linalg::Matrix< Type > Class Template Reference
gpmp::linalg::Matrix< Type > Class Template Reference
Matrix and Scalar operations.
#include <mtx_tmpl.hpp>
Public Member Functions
Matrix (size_t mtx_rows, size_t mtx_cols)
Matrix Class constructor initializing empty vector.
Matrix ()
Type & operator() (size_t row, size_t col)
Overload operator.
Matrix mult (Matrix &target)
Matrix Multiplication.
Matrix scalar_mult (Type scalar)
Matrix hadamard (Matrix &target)
Matrix sqr_err ()
Matrix add (Matrix &target)
Matrix operator+ (Matrix &target)
Matrix scalar_add (Type scalar)
Matrix operator- ()
Matrix sub (Matrix &target)
Matrix operator- (Matrix &target)
Matrix< unsigned short > operator== (Matrix &target)
bool all ()
Matrix transpose ()
Matrix T ()
Matrix sum ()
Matrix sum (size_t dimension)
Matrix mean ()
Matrix mean (size_t dimension)
Matrix concatenate (Matrix target, size_t dimension)
Matrix diag ()
Matrix apply_func (const std::function< Type(const Type &)> &function)
void print_shape ()
void print_mtx ()
void fill_index (Type val)
Public Attributes
size_t cols
size_t rows
std::vector< Type > data
std::tuple< size_t, size_t > dim
int64_t num_elements = rows * cols
Detailed Description
template<typename Type>
class gpmp::linalg::Matrix< Type >
Matrix and Scalar operations.
Definition at line 61 of file mtx_tmpl.hpp.
Constructor & Destructor Documentation
Matrix() [1/2]
template<typename Type > gpmp::linalg::Matrix< Type >::Matrix (size_t mtx_rows, size_t mtx_cols) inline
Matrix Class constructor initializing empty vector.
Parameters
[in] rows : size of rows
[in] cols : size of columns
Definition at line 77 of file mtx_tmpl.hpp.
        : cols(cols), rows(rows), data({}) {
        // initialize an empty vector for storage
        data.resize(cols * rows, Type());
        dim = std::make_tuple(rows, cols);
    }
Matrix() [2/2]
template<typename Type > gpmp::linalg::Matrix< Type >::Matrix () inline
Definition at line 83 of file mtx_tmpl.hpp.
             : cols(0), rows(0), data({}) {
        dim = {rows, cols};
    };
Member Function Documentation
add()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::add (Matrix< Type > & target) inline
Definition at line 165 of file mtx_tmpl.hpp.
{
        assert(dim == target.dim);
        Matrix res(rows, target.cols);
        for (size_t r = 0; r < res.rows; ++r) {
            for (size_t c = 0; c < res.cols; ++c) {
                res(r, c) = (*this)(r, c) + target(r, c);
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, gpmp::linalg::Matrix< Type >::dim, and gpmp::linalg::Matrix< Type >::rows.
Referenced by gpmp::linalg::Matrix< Type >::operator+(), gpmp::ml::SecondaryMLP< T >::prop_backwards(), and gpmp::linalg::Matrix< Type >::sub().
all()
template<typename Type > bool gpmp::linalg::Matrix< Type >::all () inline
Definition at line 235 of file mtx_tmpl.hpp.
               {
        int64_t counter{0};
        for (int64_t r = 0; r < rows; ++r) {
            for (int64_t c = 0; c < cols; ++c) {
                if ((*this)(r, c))
                    counter++;
            }
        }
        return (counter == num_elements);
    }
References gpmp::linalg::Matrix< Type >::cols, gpmp::linalg::Matrix< Type >::num_elements, and gpmp::linalg::Matrix< Type >::rows.
apply_func()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::apply_func (const std::function< Type(const Type &)> & function) inline
Definition at line 368 of file mtx_tmpl.hpp.
{
        Matrix res((*this));
        for (size_t r = 0; r < rows; ++r) {
            for (size_t c = 0; c < cols; ++c) {
                res(r, c) = function((*this)(r, c));
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
concatenate()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::concatenate (Matrix< Type > target, size_t dimension) inline
Definition at line 320 of file mtx_tmpl.hpp.
{
        (dimension == 0) ? assert(rows == target.rows)
                         : assert(cols == target.cols);
        auto res = (dimension == 0) ? Matrix{rows + target.rows, cols}
                                    : Matrix{rows, cols + target.cols};
        // copy self
        for (size_t r = 0; r < rows; ++r) {
            for (size_t c = 0; c < cols; ++c) {
                res(r, c) = (*this)(r, c);
            }
        }
        // copy target
        if (dimension == 0) {
            for (size_t r = 0; r < target.rows; ++r) {
                for (size_t c = 0; c < cols; ++c) {
                    res(r + rows, c) = target(r, c);
                }
            }
        } else {
            for (size_t r = 0; r < rows; ++r) {
                for (size_t c = 0; c < target.cols; ++c) {
                    res(r, c + cols) = target(r, c);
                }
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
diag()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::diag () inline
Definition at line 351 of file mtx_tmpl.hpp.
                  {
        assert((rows == 1 || cols == 1) || (rows == cols));
        if (rows == 1 || cols == 1) {
            Matrix res{std::max(rows, cols), std::max(rows, cols)};
            for (size_t i = 0; i < rows; ++i)
                res(i, i) = (*this)(i, 0);
            return res;
        } else {
            assert(rows == cols);
            Matrix res{rows, 1};
            for (size_t i = 0; i < rows; ++i)
                res(i, 0) = (*this)(i, i);
            return res;
        }
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
fill_index()
template<typename Type > void gpmp::linalg::Matrix< Type >::fill_index (Type val) inline
Definition at line 394 of file mtx_tmpl.hpp.
{
        for (size_t r = 0; r < rows; ++r) {
            for (int64_t c = 0; c < cols; ++c) {
                (*this)(r, c) = val;
            }
        }
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
hadamard()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::hadamard (Matrix< Type > & target) inline
Definition at line 139 of file mtx_tmpl.hpp.
{
        assert(dim == target.dim);
        Matrix res((*this));
        for (size_t r = 0; r < res.rows; ++r) {
            for (size_t c = 0; c < res.cols; ++c) {
                res(r, c) = target(r, c) * (*this)(r, c);
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::dim.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards(), and gpmp::linalg::Matrix< Type >::sqr_err().
mean() [1/2]
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::mean () inline
Definition at line 304 of file mtx_tmpl.hpp.
                  {
        auto m = Type(num_elements);
        return sum().scalar_mult(1 / m);
    }
References gpmp::linalg::Matrix< Type >::num_elements, gpmp::linalg::Matrix< Type >::scalar_mult(), and gpmp::linalg::Matrix< Type >::sum().
mean() [2/2]
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::mean (size_t dimension) inline
Definition at line 312 of file mtx_tmpl.hpp.
{
        auto m = (dimension == 0) ? Type(rows) : Type(cols);
        return sum().scalar_mult(1 / m);
    }
References gpmp::linalg::Matrix< Type >::cols, gpmp::linalg::Matrix< Type >::rows, gpmp::linalg::Matrix< Type >::scalar_mult(), and gpmp::linalg::Matrix< Type >::sum().
mult()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::mult (Matrix< Type > & target) inline
Matrix Multiplication.
Parameters
[in]
Todo
optimize this with threading
Definition at line 107 of file mtx_tmpl.hpp.
{
        assert(cols == target.rows);
        Matrix res(rows, target.cols);
        for (size_t r = 0; res.rows; ++r) {
            for (size_t c = 0; res.cols; ++c) {
                for (size_t n = 0; n < target.rows; ++n) {
                    res(r, c) += (*this)(r, n) * target(n, c);
                }
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards(), and gpmp::ml::SecondaryMLP< T >::prop_forwards().
operator()()
template<typename Type > Type & gpmp::linalg::Matrix< Type >::operator() (size_t row, size_t col) inline
Overload operator.
Parameters
[in] row : size of rows
[in] col : size of columns
Definition at line 93 of file mtx_tmpl.hpp.
{
        assert(0 <= row && row < rows);
        assert(0 <= col && col < cols);
        return data[row * cols + col];
    }
References gpmp::linalg::Matrix< Type >::cols, gpmp::linalg::Matrix< Type >::data, and gpmp::linalg::Matrix< Type >::rows.
operator+()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::operator+ (Matrix< Type > & target) inline
Definition at line 176 of file mtx_tmpl.hpp.
{
        return add(target);
    }
References gpmp::linalg::Matrix< Type >::add().
operator-() [1/2]
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::operator- () inline
Definition at line 194 of file mtx_tmpl.hpp.
                       {
        Matrix res(rows, cols);
        for (size_t r = 0; r < rows; ++r) {
            for (size_t c = 0; c < cols; ++c) {
                res(r, c) = -(*this)(r, c);
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
operator-() [2/2]
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::operator- (Matrix< Type > & target) inline
Definition at line 212 of file mtx_tmpl.hpp.
{
        return sub(target);
    }
References gpmp::linalg::Matrix< Type >::sub().
operator==()
template<typename Type > Matrix< unsigned short > gpmp::linalg::Matrix< Type >::operator== (Matrix< Type > & target) inline
Definition at line 216 of file mtx_tmpl.hpp.
{
        assert(dim == target.dim);
        Matrix<unsigned short> res(rows, cols);
        for (int64_t r = 0; r < rows; ++r) {
            for (int64_t c = 0; c < cols; ++c) {
                if ((*this)(r, c) - target(r, c) == 0.)
                    res(r, c) = 1;
                else
                    res(r, c) = 0;
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, gpmp::linalg::Matrix< Type >::dim, and gpmp::linalg::Matrix< Type >::rows.
print_mtx()
template<typename Type > void gpmp::linalg::Matrix< Type >::print_mtx () inline
Definition at line 384 of file mtx_tmpl.hpp.
                     {
        for (size_t r = 0; r < rows; ++r) {
            for (int64_t c = 0; c < cols; ++c) {
                std::cout << (*this)(r, c) << " ";
            }
            std::cout << std::endl;
        }
        std::cout << std::endl;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
print_shape()
template<typename Type > void gpmp::linalg::Matrix< Type >::print_shape () inline
Definition at line 379 of file mtx_tmpl.hpp.
                       {
        std::cout << "Matrix Size([" << rows << ", " << cols << "])"
                  << std::endl;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
scalar_add()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::scalar_add (Type scalar) inline
Definition at line 183 of file mtx_tmpl.hpp.
{
        Matrix res((*this));
        for (size_t r = 0; r < rows; ++r) {
            for (size_t c = 0; c < cols; ++c) {
                res(r, c) = (*this)(r, c) + scalar;
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
scalar_mult()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::scalar_mult (Type scalar) inline
Definition at line 124 of file mtx_tmpl.hpp.
{
        Matrix res((*this));
        for (size_t r = 0; r < res.rows; ++r) {
            for (size_t c = 0; c < res.cols; ++c) {
                res(r, c) = scalar * (*this)(r, c);
            }
        }
        return res;
    }
Referenced by gpmp::linalg::Matrix< Type >::mean(), gpmp::linalg::Matrix< Type >::mean(), and gpmp::ml::SecondaryMLP< T >::prop_backwards().
sqr_err()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::sqr_err () inline
Definition at line 155 of file mtx_tmpl.hpp.
                     {
        Matrix res((*this));
        res = hadamard(res);
        return res;
    }
References gpmp::linalg::Matrix< Type >::hadamard().
sub()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::sub (Matrix< Type > & target) inline
Definition at line 208 of file mtx_tmpl.hpp.
{
        Matrix target_neg = -target;
        return add(target_neg);
    }
References gpmp::linalg::Matrix< Type >::add().
Referenced by gpmp::linalg::Matrix< Type >::operator-().
sum() [1/2]
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::sum () inline
Definition at line 269 of file mtx_tmpl.hpp.
                 {
        Matrix res{1, 1};
        for (size_t r = 0; r < rows; ++r) {
            for (size_t c = 0; c < cols; ++c) {
                res(0, 0) += (*this)(r, c);
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
Referenced by gpmp::linalg::Matrix< Type >::mean(), and gpmp::linalg::Matrix< Type >::mean().
sum() [2/2]
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::sum (size_t dimension) inline
Definition at line 283 of file mtx_tmpl.hpp.
{
        assert(0 <= dimension && dimension < 2);
        auto res = (dimension = 0) ? Matrix{1, cols} : Matrix{rows, 1};
        if (dimension == 0) {
            for (size_t c = 0; c < cols; ++c) {
                for (size_t r = 0; r < rows; ++r) {
                    res(0, c) += (*this)(r, c);
                }
            }
        } else {
            for (size_t r = 0; r < rows; ++r) {
                for (size_t c = 0; c < cols; ++c) {
                    res(r, 0) += (*this)(r, c);
                }
            }
        }
        return res;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
T()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::T () inline
Definition at line 262 of file mtx_tmpl.hpp.
               {
        return (*this).transpose();
    }
References gpmp::linalg::Matrix< Type >::transpose().
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards().
transpose()
template<typename Type > Matrix gpmp::linalg::Matrix< Type >::transpose () inline
Definition at line 250 of file mtx_tmpl.hpp.
                       {
        size_t new_rows{cols}, new_cols{rows};
        Matrix transposed(new_rows, new_cols);
        for (size_t r = 0; r < new_rows; ++r) {
            for (size_t c = 0; c < new_cols; ++c) {
                transposed(r, c) = (*this)(c, r);
            }
        }
        return transposed;
    }
References gpmp::linalg::Matrix< Type >::cols, and gpmp::linalg::Matrix< Type >::rows.
Referenced by gpmp::linalg::Matrix< Type >::T().
Member Data Documentation
cols
template<typename Type > size_t gpmp::linalg::Matrix< Type >::cols
Definition at line 63 of file mtx_tmpl.hpp.
Referenced by gpmp::linalg::Matrix< Type >::add(), gpmp::linalg::Matrix< Type >::all(), gpmp::linalg::Matrix< Type >::apply_func(), gpmp::linalg::Matrix< Type >::concatenate(), gpmp::linalg::Matrix< Type >::diag(), gpmp::linalg::Matrix< Type >::fill_index(), gpmp::linalg::Matrix< Type >::mean(), gpmp::linalg::Matrix< Type >::mult(), gpmp::linalg::Matrix< Type >::operator()(), gpmp::linalg::Matrix< Type >::operator-(), gpmp::linalg::Matrix< Type >::operator==(), gpmp::linalg::Matrix< Type >::print_mtx(), gpmp::linalg::Matrix< Type >::print_shape(), gpmp::linalg::Matrix< Type >::scalar_add(), gpmp::linalg::Matrix< Type >::sum(), gpmp::linalg::Matrix< Type >::sum(), and gpmp::linalg::Matrix< Type >::transpose().
data
template<typename Type > std::vector<Type> gpmp::linalg::Matrix< Type >::data
Definition at line 66 of file mtx_tmpl.hpp.
Referenced by gpmp::linalg::Matrix< Type >::operator()().
dim
template<typename Type > std::tuple<size_t, size_t> gpmp::linalg::Matrix< Type >::dim
Definition at line 67 of file mtx_tmpl.hpp.
Referenced by gpmp::linalg::Matrix< Type >::add(), gpmp::linalg::Matrix< Type >::hadamard(), and gpmp::linalg::Matrix< Type >::operator==().
num_elements
template<typename Type > int64_t gpmp::linalg::Matrix< Type >::num_elements = rows * cols
Definition at line 69 of file mtx_tmpl.hpp.
Referenced by gpmp::linalg::Matrix< Type >::all(), and gpmp::linalg::Matrix< Type >::mean().
rows
template<typename Type > size_t gpmp::linalg::Matrix< Type >::rows
Definition at line 64 of file mtx_tmpl.hpp.
Referenced by gpmp::linalg::Matrix< Type >::add(), gpmp::linalg::Matrix< Type >::all(), gpmp::linalg::Matrix< Type >::apply_func(), gpmp::linalg::Matrix< Type >::concatenate(), gpmp::linalg::Matrix< Type >::diag(), gpmp::linalg::Matrix< Type >::fill_index(), gpmp::linalg::Matrix< Type >::mean(), gpmp::linalg::Matrix< Type >::mult(), gpmp::linalg::Matrix< Type >::operator()(), gpmp::linalg::Matrix< Type >::operator-(), gpmp::linalg::Matrix< Type >::operator==(), gpmp::linalg::Matrix< Type >::print_mtx(), gpmp::linalg::Matrix< Type >::print_shape(), gpmp::linalg::Matrix< Type >::scalar_add(), gpmp::linalg::Matrix< Type >::sum(), gpmp::linalg::Matrix< Type >::sum(), and gpmp::linalg::Matrix< Type >::transpose().
The documentation for this class was generated from the following file:
include/linalg/mtx_tmpl.hpp