openGPMP: gpmp::ml::SecondaryMLP< T > Class Template Reference
gpmp::ml::SecondaryMLP< T > Class Template Reference
Secondary Multi-Layer Perceptron Class making use of the Linear Algebra module.
#include <mlp_net.hpp>
Public Member Functions
void log (auto &file, const auto &x, const auto &y, const auto &y_hat)
long double sigmoid_activ (long double x)
Sigmoid activation function.
long double sigmoid_deriv (long double x)
Sigmoid Derivative for backwards propogation.
SecondaryMLP (std::vector< size_t > layer_units, long double lr=.001)
auto prop_forwards (gpmp::linalg::Matrix< T > x)
void prop_backwards (gpmp::linalg::Matrix< T > target)
Public Attributes
std::vector< size_t > layer_units
std::vector< gpmp::linalg::Matrix< T > > bias_vectors
std::vector< gpmp::linalg::Matrix< T > > wt_mtx
std::vector< gpmp::linalg::Matrix< T > > activations
long double lr
Detailed Description
template<typename T>
class gpmp::ml::SecondaryMLP< T >
Secondary Multi-Layer Perceptron Class making use of the Linear Algebra module.
Definition at line 151 of file mlp_net.hpp.
Constructor & Destructor Documentation
SecondaryMLP()
template<typename T > gpmp::ml::SecondaryMLP< T >::SecondaryMLP (std::vector< size_t > layer_units, long double lr = .001) inline explicit
Secondary Multi-Layer Perceptron Constructor Initialize a set of weights + biases for each layer set to random Gaussian Noise related values
Definition at line 194 of file mlp_net.hpp.
        : layer_units(layer_units), wt_mtx(), bias_vectors(), lr(lr) {
        // traverse the elements
        for (size_t i = 0; i < layer_units.size() - 1; ++i) {
            // size of inputs
            size_t inputs{layer_units[i]};
            // size of outputs
            size_t outputs{layer_units[i + 1]};
            // set to random Guassian Noise related values
            // weights
            auto gauss_wt = gpmp::linalg::mtx<T>::randn(outputs, inputs);
            wt_mtx.push_back(gauss_wt);
            // biases
            auto bias_wt = gpmp::linalg::mtx<T>::randn(outputs, 1);
            bias_vectors.push_back(bias_wt);
            // activation function
            activations.resize(layer_units.size());
        }
    }
References gpmp::ml::SecondaryMLP< T >::activations, gpmp::ml::SecondaryMLP< T >::bias_vectors, gpmp::ml::SecondaryMLP< T >::layer_units, gpmp::linalg::mtx< T >::randn(), and gpmp::ml::SecondaryMLP< T >::wt_mtx.
Member Function Documentation
log()
template<typename T > void gpmp::ml::SecondaryMLP< T >::log (auto & file, const auto & x, const auto & y, const auto & y_hat) inline
Logging function for collecting the results
Definition at line 156 of file mlp_net.hpp.
{
        // mean squared error
        auto mse = (y.data[0] - y_hat.data[0]);
        mse = mse * mse;
        file << mse << " " << x.data[0] << " " << y.data[0] << " "
             << y_hat.data[0] << " \n";
    }
prop_backwards()
template<typename T > void gpmp::ml::SecondaryMLP< T >::prop_backwards (gpmp::linalg::Matrix< T > target) inline
Backwards Propagation is utilized to optimize the net's weights. Enabling learning how to correctly map arbitrary inputs to outputs. The goal being to update each weight of the network allowing them to increase the chance of the actual output being closer to the target output. This method takes the target output as an input parameter
Definition at line 245 of file mlp_net.hpp.
{
        assert(get<0>(target.shape) == layer_units.back());
        // calculate the error, target - ouput
        auto y = target;
        auto y_hat = activations.back();
        auto err = target - y_hat;
        // back propagate the error calculated from output to input
        // and step the weights
        for (int64_t i = wt_mtx.size() - 1; i >= 0; --i) {
            // calculate errors for previous layer
            auto wt = wt_mtx[i].T();
            auto prior_errs = wt.mult(err);
            auto outputs_d =
                activations[i + 1].apply_function(&SecondaryMLP::sigmoid_deriv);
            auto gradients = err.hadamard(outputs_d);
            gradients = gradients.scalar_mult(lr);
            auto trans_a = activations[i].T();
            auto gradients_wt = gradients.mult(trans_a);
            // adjust the networks weights based on propagation
            // technique
            bias_vectors[i] = bias_vectors[i].add(gradients);
            wt_mtx[i] = wt_mtx[i].add(gradients_wt);
            err = prior_errs;
        }
    }
References gpmp::ml::SecondaryMLP< T >::activations, gpmp::linalg::Matrix< Type >::add(), gpmp::ml::SecondaryMLP< T >::bias_vectors, gpmp::linalg::Matrix< Type >::hadamard(), gpmp::ml::SecondaryMLP< T >::layer_units, gpmp::ml::SecondaryMLP< T >::lr, gpmp::linalg::Matrix< Type >::mult(), gpmp::linalg::Matrix< Type >::scalar_mult(), gpmp::ml::SecondaryMLP< T >::sigmoid_deriv(), gpmp::linalg::Matrix< Type >::T(), and gpmp::ml::SecondaryMLP< T >::wt_mtx.
prop_forwards()
template<typename T > auto gpmp::ml::SecondaryMLP< T >::prop_forwards (gpmp::linalg::Matrix< T > x) inline
Forward passes compute the activations at a specific layer. This method saves the results to the activations Matrix passing it forwards to use as an input paramater on the next layer
Definition at line 221 of file mlp_net.hpp.
{
        assert(get<0>(x.shape) == layer_units[0] && get<1>(x.shape));
        // input = to previously declared acitvations method
        activations[0] = x;
        gpmp::linalg::Matrix prev(x);
        // traverse layer units
        for (uint64_t i = 0; i < layer_units.size() - 1; ++i) {
            gpmp::linalg::Matrix y = wt_mtx[i].mult(prev);
            y = y + bias_vectors[i];
            y = y.apply_function(&SecondaryMLP::sigmoid_activ);
            activations[i + 1] = y;
            prev = y;
        }
        return prev;
    }
References gpmp::ml::SecondaryMLP< T >::activations, gpmp::ml::SecondaryMLP< T >::bias_vectors, gpmp::ml::SecondaryMLP< T >::layer_units, gpmp::linalg::Matrix< Type >::mult(), gpmp::ml::SecondaryMLP< T >::sigmoid_activ(), and gpmp::ml::SecondaryMLP< T >::wt_mtx.
sigmoid_activ()
template<typename T > long double gpmp::ml::SecondaryMLP< T >::sigmoid_activ (long double x) inline
Sigmoid activation function.
Parameters
[in] x : (float)
Definition at line 169 of file mlp_net.hpp.
{
        return 1.0f / (1 + exp(-x));
    }
Referenced by gpmp::ml::SecondaryMLP< T >::prop_forwards().
sigmoid_deriv()
template<typename T > long double gpmp::ml::SecondaryMLP< T >::sigmoid_deriv (long double x) inline
Sigmoid Derivative for backwards propogation.
Parameters
[in] x : (float)
Definition at line 178 of file mlp_net.hpp.
{
        return (x * (1 - x));
    }
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards().
Member Data Documentation
activations
template<typename T > std::vector<gpmp::linalg::Matrix<T> > gpmp::ml::SecondaryMLP< T >::activations
Definition at line 185 of file mlp_net.hpp.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards(), gpmp::ml::SecondaryMLP< T >::prop_forwards(), and gpmp::ml::SecondaryMLP< T >::SecondaryMLP().
bias_vectors
template<typename T > std::vector<gpmp::linalg::Matrix<T> > gpmp::ml::SecondaryMLP< T >::bias_vectors
Definition at line 183 of file mlp_net.hpp.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards(), gpmp::ml::SecondaryMLP< T >::prop_forwards(), and gpmp::ml::SecondaryMLP< T >::SecondaryMLP().
layer_units
template<typename T > std::vector<size_t> gpmp::ml::SecondaryMLP< T >::layer_units
Definition at line 182 of file mlp_net.hpp.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards(), gpmp::ml::SecondaryMLP< T >::prop_forwards(), and gpmp::ml::SecondaryMLP< T >::SecondaryMLP().
lr
template<typename T > long double gpmp::ml::SecondaryMLP< T >::lr
Definition at line 187 of file mlp_net.hpp.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards().
wt_mtx
template<typename T > std::vector<gpmp::linalg::Matrix<T> > gpmp::ml::SecondaryMLP< T >::wt_mtx
Definition at line 184 of file mlp_net.hpp.
Referenced by gpmp::ml::SecondaryMLP< T >::prop_backwards(), gpmp::ml::SecondaryMLP< T >::prop_forwards(), and gpmp::ml::SecondaryMLP< T >::SecondaryMLP().
The documentation for this class was generated from the following file:
include/ml/mlp_net.hpp