openGPMP: gpmp::ml::BayesGauss Class Reference
gpmp::ml::BayesGauss Class Reference
#include <bayes_clf.hpp>
Public Member Functions
BayesGauss ()=default
Constructor for BayesGauss class.
~BayesGauss ()=default
Destructor for BayesGauss class.
void train (const std::vector< std::vector< double > > &data, const std::vector< std::string > &labels)
Train the classifier with a set of labeled data.
std::string predict (const std::vector< double > &newData) const
Predict the class of a new data point.
void display () const
Display the learned probabilities.
Public Attributes
std::unordered_map< std::string, double > class_probs
Map storing the probabilities of each class.
std::unordered_map< std::string, std::vector< double > > mean
Map storing the mean values for each feature in each class.
std::unordered_map< std::string, std::vector< double > > variance
Map storing the variance values for each feature in each class.
Private Member Functions
void mean_and_var (const std::vector< std::vector< double > > &data, const std::vector< std::string > &labels)
Calculate the mean and variance for each class.
Detailed Description
Classification technique that assumes that each parameter (also called features or predictors) has an independent capacity of predicting the output variable.
Definition at line 172 of file bayes_clf.hpp.
Constructor & Destructor Documentation
BayesGauss()
gpmp::ml::BayesGauss::BayesGauss () default
Constructor for BayesGauss class.
~BayesGauss()
gpmp::ml::BayesGauss::~BayesGauss () default
Destructor for BayesGauss class.
Member Function Documentation
display()
void gpmp::ml::BayesGauss::display () const
Display the learned probabilities.
Note
This method is for debugging purposes
Definition at line 324 of file bayes_clf.cpp.
{
    std::cout << "Class Probabilities:\n";
    for (const auto &entry : class_probs) {
        std::cout << entry.first << ": " << entry.second << "\n";
    }
    std::cout << "\nMean and Variance:\n";
    for (const auto &class_entry : mean) {
        std::cout << class_entry.first << ":\n";
        std::cout << "  Mean: ";
        for (size_t j = 0; j < class_entry.second.size(); ++j) {
            std::cout << class_entry.second[j] << " ";
        }
        std::cout << "\n  Variance: ";
        for (size_t j = 0; j < variance.at(class_entry.first).size(); ++j) {
            std::cout << variance.at(class_entry.first).at(j) << " ";
        }
        std::cout << "\n";
    }
}
Referenced by main().
mean_and_var()
void gpmp::ml::BayesGauss::mean_and_var (const std::vector< std::vector< double > > & data, const std::vector< std::string > & labels) private
Calculate the mean and variance for each class.
Parameters
data A vector of vectors representing the training instances
labels A vector of strings representing the corresponding class labels
Definition at line 246 of file bayes_clf.cpp.
{
    size_t num_features = data[0].size();
    for (size_t i = 0; i < data.size(); ++i) {
        const std::string &label = labels[i];
        const std::vector<double> &features = data[i];
        class_probs[label] += 1.0;
        // initialize mean[label] and variance[label] if not present
        if (mean.find(label) == mean.end()) {
            mean[label] = std::vector<double>(num_features, 0.0);
            variance[label] = std::vector<double>(num_features, 0.0);
        }
        // update mean
        for (size_t j = 0; j < num_features; ++j) {
            mean[label][j] += features[j];
        }
    }
    // calculate mean
    for (auto &entry : mean) {
        const std::string &label = entry.first;
        double class_count = class_probs[label];
        for (size_t j = 0; j < num_features; ++j) {
            entry.second[j] /= class_count;
        }
    }
    // calculate variance
    for (size_t i = 0; i < data.size(); ++i) {
        const std::string &label = labels[i];
        const std::vector<double> &features = data[i];
        for (size_t j = 0; j < num_features; ++j) {
            variance[label][j] += std::pow(features[j] - mean[label][j], 2);
        }
    }
    for (auto &entry : variance) {
        const std::string &label = entry.first;
        double class_count = class_probs[label];
        for (size_t j = 0; j < num_features; ++j) {
            entry.second[j] /= class_count;
        }
    }
}
predict()
std::string gpmp::ml::BayesGauss::predict (const std::vector< double > & newData) const
Predict the class of a new data point.
Parameters
newData A vector of doubles representing the features of the new data point
Returns
The predicted class label as a string
Definition at line 300 of file bayes_clf.cpp.
{
    double max_prob = -std::numeric_limits<double>::infinity();
    std::string predicted_class;
    for (const auto &entry : class_probs) {
        const std::string &label = entry.first;
        double probability = log(entry.second);
        for (size_t j = 0; j < newData.size(); ++j) {
            probability -=
                0.5 * (std::log(2 * M_PI * variance.at(label).at(j)) +
                       std::pow(newData[j] - mean.at(label).at(j), 2) /
                           (2 * variance.at(label).at(j)));
        }
        if (probability > max_prob) {
            max_prob = probability;
            predicted_class = label;
        }
    }
    return predicted_class;
}
Referenced by main().
train()
void gpmp::ml::BayesGauss::train (const std::vector< std::vector< double > > & data, const std::vector< std::string > & labels)
Train the classifier with a set of labeled data.
Parameters
data A vector of vectors representing the training instances
labels A vector of strings representing the corresponding class labels
Definition at line 229 of file bayes_clf.cpp.
{
    // calculate class occurrences
    for (const auto &label : labels) {
        class_probs[label] += 1.0;
    }
    // calculate mean and variance for each feature in each class
    mean_and_var(data, labels);
    // calculate class probabilities
    double total_instances = static_cast<double>(data.size());
    for (auto &entry : class_probs) {
        entry.second /= total_instances;
    }
}
Referenced by main().
Member Data Documentation
class_probs
gpmp::ml::BayesGauss::class_probs
Map storing the probabilities of each class.
The key is the class label (string), and the value is the probability (double)
Definition at line 180 of file bayes_clf.hpp.
mean
gpmp::ml::BayesGauss::mean
Map storing the mean values for each feature in each class.
The key is the class label (string), and the value is a vector of mean values
Definition at line 187 of file bayes_clf.hpp.
variance
gpmp::ml::BayesGauss::variance
Map storing the variance values for each feature in each class.
The key is the class label (string), and the value is a vector of variance values
Definition at line 194 of file bayes_clf.hpp.
The documentation for this class was generated from the following files:
include/ml/bayes_clf.hpp
modules/ml/bayes_clf.cpp