openGPMP: Checkerboard Class Reference
Checkerboard Class Reference
Public Member Functions
Checkerboard (int width, int depth)
double centerx ()
double centerz ()
void create ()
void draw ()
Private Attributes
int displayListId
int width
int depth
Detailed Description
Definition at line 104 of file openGL_bounce.c.
Constructor & Destructor Documentation
Checkerboard()
Checkerboard::Checkerboard (int width, int depth) inline
Definition at line 110 of file openGL_bounce.c.
                                       : width(width), depth(depth) {
    }
Member Function Documentation
centerx()
double Checkerboard::centerx () inline
Definition at line 113 of file openGL_bounce.c.
                     {
        return width / 2;
    }
References width.
Referenced by display().
centerz()
double Checkerboard::centerz () inline
Definition at line 116 of file openGL_bounce.c.
                     {
        return depth / 2;
    }
References depth.
Referenced by display().
create()
void Checkerboard::create () inline
Definition at line 120 of file openGL_bounce.c.
                  {
        displayListId = glGenLists(1);
        glNewList(displayListId, GL_COMPILE);
        GLfloat lightPosition[] = {4, 3, 7, 1};
        glLightfv(GL_LIGHT0, GL_POSITION, lightPosition);
        glBegin(GL_QUADS);
        glNormal3d(0, 1, 0);
        for (int x = 0; x < width - 1; x++) {
            for (int z = 0; z < depth - 1; z++) {
                glMaterialfv(GL_FRONT,
                             GL_AMBIENT_AND_DIFFUSE,
                             (x + z) % 2 == 0 ? RED : WHITE);
                glVertex3d(x, 0, z);
                glVertex3d(x + 1, 0, z);
                glVertex3d(x + 1, 0, z + 1);
                glVertex3d(x, 0, z + 1);
            }
        }
        glEnd();
        glEndList();
    }
References depth, displayListId, RED, WHITE, and width.
Referenced by init().
draw()
void Checkerboard::draw () inline
Definition at line 144 of file openGL_bounce.c.
                {
        glCallList(displayListId);
    }
References displayListId.
Referenced by display().
Member Data Documentation
depth
int Checkerboard::depth private
Definition at line 107 of file openGL_bounce.c.
Referenced by centerz(), and create().
displayListId
int Checkerboard::displayListId private
Definition at line 105 of file openGL_bounce.c.
Referenced by create(), and draw().
width
int Checkerboard::width private
Definition at line 106 of file openGL_bounce.c.
Referenced by centerx(), and create().
The documentation for this class was generated from the following file:
modules/complex/openGL_bounce.c