openGPMP: gpmp::Basics Class Reference
gpmp::Basics Class Reference
Arithmetic Operations
#include <arithmetic.hpp>
Public Member Functions
int64_t greatest_power (int64_t n, int64_t p)
Find greatest power of 2 itegers.
int64_t op_gcd (int64_t x, int64_t y)
Find Greatest Common Divisor of 2 integers.
Detailed Description
Arithmetic Operations
Encompasses Arithmetic related operations
Examples
arithmetic.cpp.
Definition at line 101 of file arithmetic.hpp.
Member Function Documentation
greatest_power()
int64_t gpmp::Basics::greatest_power (int64_t n, int64_t p)
Find greatest power of 2 itegers.
Parameters
[in] n : integer 1
[in] p : integer 2
Returns
result : (int)
Examples
arithmetic.cpp.
Definition at line 40 of file arith.cpp.
{
    int64_t result = 0;
    // Calculate x = n/p + n/(p^2) + n/(p^3) + ....
    while (n) {
        n /= p;
        result += n;
    }
    return result;
}
Referenced by main().
op_gcd()
int64_t gpmp::Basics::op_gcd (int64_t x, int64_t y)
Find Greatest Common Divisor of 2 integers.
Parameters
[in] x : integer 1
[in] y : integer 2
Returns
result : (int)
Examples
arithmetic.cpp.
Definition at line 51 of file arith.cpp.
{
    if (x < y)
        return op_gcd(y, x);
    else if (x % y == 0)
        return y;
    else
        return op_gcd(y, x % y);
}
Referenced by gpmp::PrimalityTest::carmichael_num(), gpmp::PrimalityTest::ETF(), and main().
The documentation for this class was generated from the following files:
include/arithmetic.hpp
modules/arithmetic/arith.cpp