openMTPK: mtpk::Data Class Reference
mtpk::Data Class Reference
#include <utils.hpp>
Public Member Functions
std::tuple< std::vector< std::vector< double > >, std::vector< double > > load ()
std::tuple< std::vector< std::vector< double > >, std::vector< std::vector< double > > > load ()
std::tuple< std::vector< std::vector< double > >, std::vector< double > > load ()
std::tuple< std::vector< double >, std::vector< double > > load ()
void setData (int k, std::string fileName, std::vector< std::vector< double > > &inputSet, std::vector< double > &outputSet)
void printData (std::vector< std::string > inputName, std::vector< std::vector< double > > inputSet)
void printData (std::vector< std::string > inputName, std::string outputName, std::vector< std::vector< double > > inputSet, std::vector< double > outputSet)
void set_input_names (std::string file_name, std::vector< std::string > &input_names)
std::vector< std::vector< double > > feature_scaling (std::vector< std::vector< double > > X)
std::vector< std::vector< double > > one_rep (std::vector< double > temp_output_set, int n_class)
std::vector< double > one_rep_reverse (std::vector< std::vector< double > > temp_output_set)
std::vector< char > split (std::string text)
std::vector< std::string > splitSentences (std::string data)
std::vector< std::string > removeSpaces (std::vector< std::string > data)
std::vector< std::string > removeNullByte (std::vector< std::string > data)
std::vector< std::string > segment (std::string text)
Detailed Description
Definition at line 56 of file utils.hpp.
Member Function Documentation
feature_scaling()
std::vector< std::vector< double > > mtpk::Data::feature_scaling (std::vector< std::vector< double > > X)
load() [1/4]
std::tuple< std::vector< std::vector< double > >, std::vector< double > > Data::load ()
std::vector<std::vector<double>> is a 2D vector which is a Matrix. We could define it with Matrix class
Definition at line 55 of file utils.cpp.
{
    const int SIZE = 1; // k = 30
    std::vector<std::vector<double>> inputSet;
    std::vector<double> outputSet;
    setData(SIZE, "../../data/school_scores.csv",
            //"../../data/BreastCancer.csv",
            inputSet, outputSet);
    return {inputSet, outputSet};
}
References setData().
Referenced by main().
load() [2/4]
std::tuple< std::vector< std::vector< double > >, std::vector< std::vector< double > > > mtpk::Data::load ()
load() [3/4]
std::tuple< std::vector< std::vector< double > >, std::vector< double > > mtpk::Data::load ()
load() [4/4]
std::tuple< std::vector< double >, std::vector< double > > mtpk::Data::load ()
one_rep()
std::vector< std::vector< double > > mtpk::Data::one_rep (std::vector< double > temp_output_set, int n_class)
one_rep_reverse()
std::vector< double > mtpk::Data::one_rep_reverse (std::vector< std::vector< double > > temp_output_set)
printData() [1/2]
void Data::printData (std::vector< std::string > inputName, std::string outputName, std::vector< std::vector< double > > inputSet, std::vector< double > outputSet)
Definition at line 113 of file utils.cpp.
{
    // LinAlg alg;
    // inputSet = alg.transpose(inputSet);
    for (int i = 0; i < inputSet.size(); i++) {
        std::cout << inputName[i] << std::endl;
        for (int j = 0; j < inputSet[i].size(); j++) {
            std::cout << inputSet[i][j] << std::endl;
        }
    }
    std::cout << outputName << std::endl;
    for (int i = 0; i < outputSet.size(); i++) {
        std::cout << outputSet[i] << std::endl;
    }
}
printData() [2/2]
void Data::printData (std::vector< std::string > inputName, std::vector< std::vector< double > > inputSet)
Definition at line 101 of file utils.cpp.
{
    // LinAlg alg;
    // inputSet = alg.transpose(inputSet);
    for (int i = 0; i < inputSet.size(); i++) {
        std::cout << inputName[i] << std::endl;
        for (int j = 0; j < inputSet[i].size(); j++) {
            std::cout << inputSet[i][j] << std::endl;
        }
    }
}
removeNullByte()
std::vector< std::string > mtpk::Data::removeNullByte (std::vector< std::string > data)
removeSpaces()
std::vector< std::string > mtpk::Data::removeSpaces (std::vector< std::string > data)
segment()
std::vector< std::string > mtpk::Data::segment (std::string text)
set_input_names()
void mtpk::Data::set_input_names (std::string file_name, std::vector< std::string > & input_names)
setData()
void Data::setData (int k, std::string fileName, std::vector< std::vector< double > > & inputSet, std::vector< double > & outputSet)
Definition at line 68 of file utils.cpp.
{
    // LinAlg alg;
    std::string inputTemp;
    std::string outputTemp;
    inputSet.resize(k);
    std::ifstream dataFile(fileName);
    if (!dataFile.is_open()) {
        std::cout << fileName << " failed to open." << std::endl;
    }
    std::string line;
    while (std::getline(dataFile, line)) {
        std::stringstream ss(line);
        for (int i = 0; i < k; i++) {
            std::getline(ss, inputTemp, ',');
            inputSet[i].push_back(std::stod(inputTemp));
            // inputSet(i, inputSet.cols) = std::stod(inputTemp);
        }
        std::getline(ss, outputTemp, ',');
        outputSet.push_back(std::stod(outputTemp));
        // outputSet(0, outputSet.cols) = std::stod(outputTemp);
    }
    // Matrix obj
    // inputSet = inputSet.T();
    dataFile.close();
}
Referenced by load().
split()
std::vector< char > mtpk::Data::split (std::string text)
splitSentences()
std::vector< std::string > mtpk::Data::splitSentences (std::string data)
The documentation for this class was generated from the following files:
include/core/utils.hpp
modules/core/utils.cpp