openGPMP: modules/linalg/linsys.f90 File Reference
linsys.f90 File Reference
Functions/Subroutines
subroutine solvelinearsystem (a, b, x, n)
program main
Function/Subroutine Documentation
main()
program main (void)
Definition at line 61 of file linsys.f90.
References reshape(), and solvelinearsystem().
solvelinearsystem()
subroutine solvelinearsystem (real, dimension(n, n), intent(inout) a, real, dimension(n), intent(inout) b, real, dimension(n), intent(out) x, integer, intent(in) n)
Definition at line 35 of file linsys.f90.
    implicit none
    integer, intent(in) :: n
    real, dimension(n, n), intent(inout) :: A
    real, dimension(n), intent(inout) :: b
    real, dimension(n), intent(out) :: x
    real :: factor
    integer :: i, j, k
    ! Forward elimination
    do k = 1, n - 1
        do i = k + 1, n
            factor = a(i, k)/a(k, k)
            a(i, k + 1:n) = a(i, k + 1:n) - factor*a(k, k + 1:n)
            b(i) = b(i) - factor*b(k)
        end do
    end do
    ! Back substitution
    x(n) = b(n)/a(n, n)
    do i = n - 1, 1, -1
        x(i) = (b(i) - dot_product(a(i, i + 1:n), x(i + 1:n)))/a(i, i)
    end do
Referenced by main().