openMTPK: modules/ml/nearest_neighbors.cpp File Reference
nearest_neighbors.cpp File Reference
#include "k-NN.h"
#include <algorithm>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
Classes
class Company
class CSVReader
Functions
bool comparison (Company &lhs, Company &rhs)
long double euclideanDistance (Company &lhs, Company &test)
long double manhattanDistance (Company &lhs, Company &test)
void fillDistances (vector< Company > &data, Company &test, double(*distanceFunction)(Company &, Company &))
bool KNN (vector< Company > &data, Company &test, int k, double(*distanceFunction)(Company &, Company &))
int main ()
Function Documentation
comparison()
bool comparison (Company & lhs, Company & rhs)
Definition at line 138 of file nearest_neighbors.cpp.
{
    return lhs.distance < rhs.distance;
}
References Company::distance.
Referenced by KNN().
euclideanDistance()
long double euclideanDistance (Company & lhs, Company & test)
Definition at line 142 of file nearest_neighbors.cpp.
{
    return sqrt(pow((lhs.turnover - test.turnover), 2) +
                pow((lhs.characteristics - test.characteristics), 2));
}
References Company::characteristics, test(), and Company::turnover.
Referenced by main().
fillDistances()
void fillDistances (vector< Company > & data, Company & test, double(*)(Company &, Company &) distanceFunction)
Definition at line 152 of file nearest_neighbors.cpp.
{
    for (size_t i = 0; i < data.size(); ++i) {
        data[i].distance = distanceFunction(data[i], test);
    }
}
References test().
Referenced by KNN().
KNN()
bool KNN (vector< Company > & data, Company & test, int k, double(*)(Company &, Company &) distanceFunction)
Definition at line 159 of file nearest_neighbors.cpp.
{
    // filling the distances between all points and test
    fillDistances(data, test, distanceFunction);
    // sorting so that we can get the k nearest
    sort(data.begin(), data.end(), comparison);
    int64_t countSuccesful = 0;
    int64_t countUnsuccesful = 0;
    for (int64_t i = 0; i < k; ++i) {
        if (data[i].success) {
            ++countSuccesful;
        } else {
            ++countUnsuccesful;
        }
    }
    /*
     * Based on the count of succesful and unsuccessful examples
     * within those k, we are deciding whether the test example is
     * successful or not.
     */
    if (countSuccesful == countUnsuccesful) {
        test.success = data[0].success;
    } else {
        test.success = countSuccesful > countUnsuccesful ? true : false;
    }
    return test.success;
}
References comparison(), fillDistances(), and test().
Referenced by main().
main()
int main ()
Definition at line 189 of file nearest_neighbors.cpp.
           {
    const string path = "../data/zip.test.gz";
    CSVReader reader(path);
    vector<vector<string>> rawData = reader.getData();
    vector<Company> data;
    for (vector<string> line : rawData) {
        Company comp(stoi(line[0]), line[1],
                     line[2] == "1" ? true : false);
        data.push_back(comp);
    }
    /* Test examples
     * 1256 Weak - should return Successful
     * 725 Weak - should return Unsuccessful
     * 1471 Average - should return Successful
     * 703 Very Strong - should return Unsuccessful
     * 1301 Strong - should return Successful
     */
    Company test(703, "Very Strong", true);
    string answer = KNN(data, test, 12, euclideanDistance)
                        ? "Successful"
                        : "Unsuccessful";
    cout << answer;
}
References euclideanDistance(), CSVReader::getData(), KNN(), and test().
manhattanDistance()
long double manhattanDistance (Company & lhs, Company & test)
Definition at line 147 of file nearest_neighbors.cpp.
{
    return (abs(lhs.turnover - test.turnover) +
            abs(lhs.characteristics - test.characteristics));
}
References Company::characteristics, test(), and Company::turnover.