openGPMP: modules/complex/openGL_astronomy_animated.c File Reference
openGL_astronomy_animated.c File Reference
#include <GL/glut.h>
#include <math.h>
#include <stdio.h>
Macros
#define pi 3.142857
Functions
void myWireSphere (GLfloat radius, int slices, int stacks)
void display ()
void timer (int v)
void reshape (GLint w, GLint h)
int main (int argc, char **argv)
Variables
static bool spinning = true
static const int FPS = 20
static GLfloat current_rot = 0.0
static int year = 0
static int day = 0
static GLfloat u = 0.0
static GLfloat du = 0.1
Macro Definition Documentation
pi
#define pi 3.142857
Definition at line 8 of file openGL_astronomy_animated.c.
Function Documentation
display()
void display (void)
Definition at line 40 of file openGL_astronomy_animated.c.
               {
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    glPushMatrix();
    // Draw sun: a yellow sphere of radius 1 centered at the origin.
    glColor3f(1.0, 1.0, 0.0);
    myWireSphere(1.0, 15, 15);
    // Draw planet: a blue sphere of radius 0.2, 2 units away from
    // sun, with a white "pole" for its axis.
    glRotatef((GLfloat)year, 0.0, 1.0, 0.0);
    glTranslatef(2.0, 0.0, 0.0);
    glRotatef((GLfloat)day, 0.0, 1.0, 0.0);
    glColor3f(0.0, 0.0, 1.0);
    myWireSphere(0.2, 15, 15);
    glColor3f(1, 1, 1);
    glBegin(GL_LINES);
    glVertex3f(0, -0.3, 0);
    glVertex3f(0, 0.3, 0);
    glEnd();
    glPopMatrix();
    glFlush();
    glutSwapBuffers();
}
References day, myWireSphere(), and year.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 112 of file openGL_astronomy_animated.c.
{
    glutInit(&argc, argv);
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH);
    glutInitWindowSize(800, 600);
    glutCreateWindow("Comet, Planet Simulation");
    glutDisplayFunc(display);
    glutReshapeFunc(reshape);
    glutTimerFunc(100, timer, 0);
    glEnable(GL_DEPTH_TEST);
    glutMainLoop();
}
References display(), reshape(), and timer().
myWireSphere()
void myWireSphere (GLfloat radius, int slices, int stacks)
Definition at line 20 of file openGL_astronomy_animated.c.
{
    glPushMatrix();
    glRotatef(-90.0, 1.0, 0.0, 0.0);
    glutWireSphere(radius, slices, stacks);
    glPopMatrix();
}
Referenced by display().
reshape()
void reshape (GLint w, GLint h)
Definition at line 103 of file openGL_astronomy_animated.c.
{
    glViewport(0, 0, w, h);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluPerspective(60.0, (GLfloat)w / (GLfloat)h, 1.0, 40.0);
    glMatrixMode(GL_MODELVIEW);
}
Referenced by main(), and main().
timer()
void timer (int v)
Definition at line 75 of file openGL_astronomy_animated.c.
                  {
    u += du;
    day = (day + 1) % 360;
    year = (year + 2) % 360;
    glLoadIdentity();
    gluLookAt(20 * cos(u / 8.0) + 12,
              5 * sin(u / 8.0) + 1,
              10 * cos(u / 8.0) + 2,
              0,
              0,
              0,
              0,
              1,
              0);
    glutPostRedisplay();
    glutTimerFunc(1000 / 60, timer, v);
}
References day, du, timer(), u, and year.
Referenced by main(), and timer().
Variable Documentation
current_rot
GLfloat current_rot = 0.0 static
Definition at line 14 of file openGL_astronomy_animated.c.
day
int day = 0 static
Definition at line 32 of file openGL_astronomy_animated.c.
Referenced by display(), and timer().
du
GLfloat du = 0.1 static
Definition at line 73 of file openGL_astronomy_animated.c.
Referenced by timer().
FPS
const int FPS = 20 static
Definition at line 11 of file openGL_astronomy_animated.c.
spinning
bool spinning = true static
Definition at line 10 of file openGL_astronomy_animated.c.
u
GLfloat u = 0.0 static
Definition at line 72 of file openGL_astronomy_animated.c.
Referenced by gpmp::Graph::bellman_ford(), gpmp::Graph::chromatic_number(), gpmp::Graph::dfs_connected_components(), gpmp::Graph::dijkstra(), gpmp::Graph::eccentricity(), gpmp::Graph::greedy_coloring(), gpmp::Graph::has_k5(), gpmp::Graph::is_bipartite(), gpmp::Graph::kruskal(), map_file(), gpmp::Graph::match_cardinality(), gpmp::Graph::match_wt(), gpmp::Graph::planar_gen(), timer(), gpmp::Graph::topo_sort_util(), and gpmp::ml::ConcreteAutoEncoder::train().
year
int year = 0 static
Definition at line 32 of file openGL_astronomy_animated.c.
Referenced by gpmp::core::DataTable::datetime(), display(), and timer().