openGPMP: modules/complex/openGL_bounce.c File Reference
openGL_bounce.c File Reference
#include <GL/glut.h>
#include <cmath>
#include <math.h>
#include <stdio.h>
Classes
class Camera
class Ball
class Checkerboard
Macros
#define pi 3.142857
Functions
Checkerboard checkerboard (8, 8)
void init ()
void display ()
void reshape (GLint w, GLint h)
void timer (int v)
void special (int key, int, int)
int main (int argc, char **argv)
Variables
GLfloat WHITE [] = {1, 1, 1}
GLfloat RED [] = {1, 0, 0}
GLfloat GREEN [] = {0, 1, 0}
GLfloat MAGENTA [] = {1, 0, 1}
Camera camera
Ball balls []
Macro Definition Documentation
pi
#define pi 3.142857
Definition at line 9 of file openGL_bounce.c.
Function Documentation
checkerboard()
Checkerboard checkerboard (8 , 8)
Referenced by display(), and init().
display()
void display (void)
Definition at line 171 of file openGL_bounce.c.
               {
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    glLoadIdentity();
    gluLookAt(camera.getX(),
              camera.getY(),
              camera.getZ(),
              checkerboard.centerx(),
              0.0,
              checkerboard.centerz(),
              0.0,
              1.0,
              0.0);
    checkerboard.draw();
    for (int i = 0; i < sizeof balls / sizeof(Ball); i++) {
        balls[i].update();
    }
    glFlush();
    glutSwapBuffers();
}
References balls, camera, Checkerboard::centerx(), Checkerboard::centerz(), checkerboard(), Checkerboard::draw(), Camera::getX(), Camera::getY(), Camera::getZ(), and Ball::update().
Referenced by main().
init()
void init ()
Definition at line 158 of file openGL_bounce.c.
            {
    glEnable(GL_DEPTH_TEST);
    glLightfv(GL_LIGHT0, GL_DIFFUSE, WHITE);
    glLightfv(GL_LIGHT0, GL_SPECULAR, WHITE);
    glMaterialfv(GL_FRONT, GL_SPECULAR, WHITE);
    glMaterialf(GL_FRONT, GL_SHININESS, 30);
    glEnable(GL_LIGHTING);
    glEnable(GL_LIGHT0);
    checkerboard.create();
}
References checkerboard(), Checkerboard::create(), and WHITE.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 227 of file openGL_bounce.c.
{
    glutInit(&argc, argv);
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH);
    glutInitWindowPosition(80, 80);
    glutInitWindowSize(800, 600);
    glutCreateWindow("Bouncing Balls");
    glutDisplayFunc(display);
    glutReshapeFunc(reshape);
    glutSpecialFunc(special);
    glutTimerFunc(100, timer, 0);
    init();
    glutMainLoop();
}
References display(), init(), reshape(), special(), and timer().
reshape()
void reshape (GLint w, GLint h)
Definition at line 192 of file openGL_bounce.c.
{
    glViewport(0, 0, w, h);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluPerspective(40.0, GLfloat(w) / GLfloat(h), 1.0, 150.0);
    glMatrixMode(GL_MODELVIEW);
}
Referenced by main().
special()
void special (int key, int , int)
Definition at line 208 of file openGL_bounce.c.
{
    switch (key) {
    case GLUT_KEY_LEFT:
        camera.moveLeft();
        break;
    case GLUT_KEY_RIGHT:
        camera.moveRight();
        break;
    case GLUT_KEY_UP:
        camera.moveUp();
        break;
    case GLUT_KEY_DOWN:
        camera.moveDown();
        break;
    }
    glutPostRedisplay();
}
References camera, Camera::moveDown(), Camera::moveLeft(), Camera::moveRight(), and Camera::moveUp().
Referenced by main().
timer()
void timer (int v)
Definition at line 201 of file openGL_bounce.c.
                  {
    glutPostRedisplay();
    glutTimerFunc(1000 / 60, timer, v);
}
References timer().
Referenced by main(), and timer().
Variable Documentation
balls
Ball balls[]
Initial value:
= {Ball(1, GREEN, 7, 6, 1),
                Ball(1.5, MAGENTA, 6, 3, 4),
                Ball(0.4, WHITE, 5, 1, 7)}
Definition at line 152 of file openGL_bounce.c.
               {Ball(1, GREEN, 7, 6, 1),
                Ball(1.5, MAGENTA, 6, 3, 4),
                Ball(0.4, WHITE, 5, 1, 7)};
Referenced by display().
camera
Camera camera
Definition at line 151 of file openGL_bounce.c.
Referenced by display(), and special().
GREEN
GLfloat GREEN[] = {0, 1, 0}
Definition at line 14 of file openGL_bounce.c.
{0, 1, 0};
MAGENTA
GLfloat MAGENTA[] = {1, 0, 1}
Definition at line 15 of file openGL_bounce.c.
{1, 0, 1};
RED
GLfloat RED[] = {1, 0, 0}
Definition at line 13 of file openGL_bounce.c.
{1, 0, 0};
Referenced by Checkerboard::create().
WHITE
GLfloat WHITE[] = {1, 1, 1}
Definition at line 12 of file openGL_bounce.c.
{1, 1, 1};
Referenced by Checkerboard::create(), and init().