openGPMP: modules/complex/openGL_torus_animated.c File Reference
openGL_torus_animated.c File Reference
#include <GL/glut.h>
#include <math.h>
#include <stdio.h>
Macros
#define pi 3.142857
Functions
void reshape (GLint w, GLint h)
void display ()
void timer (int v)
void mouse (int button, int state, int x, int y)
void init ()
int main (int argc, char **argv)
Variables
static bool spinning = true
static const int FPS = 20
static GLfloat current_rot = 0.0
Macro Definition Documentation
pi
#define pi 3.142857
Definition at line 8 of file openGL_torus_animated.c.
Function Documentation
display()
void display (void)
Definition at line 38 of file openGL_torus_animated.c.
               {
    // setting every pixel in frame buffer to a clear color
    glClear(GL_COLOR_BUFFER_BIT);
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
    glColor3f(1.0, 1.0, 1.0);
    glRotatef(current_rot, 0.0, 0.0, 1.0);
    glutWireTorus(0.5, 3, 15, 30);
    // being drawing
    glBegin(GL_POLYGON);
    glRotatef(current_rot, 1.0, 0.0, 1.0);
    glColor3f(1, 0, 0);
    glVertex3f(0, 0, 0);
    glVertex3f(10, 0, 0);
    glColor3f(0, 1, 0);
    glVertex3f(0, 0, 0);
    glVertex3f(0, 10, 0);
    glColor3f(0, 0, 1);
    glVertex3f(0, 0, 0);
    glVertex3f(0, 0, 10);
    glEnd();
    glRotatef(current_rot, 1.0, 0.0, 1.0);
    // flush the draw cmd to display image immediately
    glFlush();
    glutSwapBuffers();
}
References current_rot.
Referenced by main().
init()
void init ()
Definition at line 98 of file openGL_torus_animated.c.
            {
    glClearColor(0.0, 0.0, 0.0, 1.0);
    glColor3f(1.0, 1.0, 1.0);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluPerspective(60.0, 4.0 / 3.0, 1, 40);
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
    gluLookAt(4, 6, 5, 0, 0, 0, 0, 1, 0);
}
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 111 of file openGL_torus_animated.c.
{
    glutInit(&argc, argv);
    glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
    // Position window at (80,80)-(480,380) and give it a title.
    glutInitWindowPosition(80, 80);
    glutInitWindowSize(1000, 800);
    glutCreateWindow("A Torus on a Plane");
    glutReshapeFunc(reshape);
    // Tell GLUT that whenever the main window needs to be repainted
    // that it should call the function display().
    glutDisplayFunc(display);
    glutTimerFunc(100, timer, 0);
    glutMouseFunc(mouse);
    init();
    glutMainLoop();
}
References display(), init(), mouse(), reshape(), and timer().
mouse()
void mouse (int button, int state, int x, int y)
Definition at line 90 of file openGL_torus_animated.c.
{
    if (button == GLUT_LEFT_BUTTON && state == GLUT_DOWN) {
        spinning = true;
    } else if (button == GLUT_RIGHT_BUTTON && state == GLUT_DOWN) {
        spinning = false;
    }
}
References spinning.
Referenced by main().
reshape()
void reshape (GLint w, GLint h)
Definition at line 19 of file openGL_torus_animated.c.
{
    glViewport(0, 0, w, h);
    GLfloat aspect = (GLfloat)w / (GLfloat)h;
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    if (w <= h) {
        // width is smaller, go from -50 .. 50 in width
        glOrtho(-50.0, 50.0, -50.0 / aspect, 50.0 / aspect, -1.0, 1.0);
    }
    else {
        // height is smaller, go from -50 .. 50 in height
        // glOrtho(-50.0*aspect, 50.0*aspect, -50.0, 50.0, -1.0, 1.0);
        glOrtho(-10.0 * aspect, 10.0 * aspect, -10.0, 10.0, -1.0, 1.0);
    }
}
Referenced by main().
timer()
void timer (int v)
Definition at line 73 of file openGL_torus_animated.c.
                  {
    if (spinning) {
        current_rot += 1.0;
        if (current_rot > 360.0) {
            current_rot -= 360.0;
        }
        glutPostRedisplay();
    }
    glutTimerFunc(1000 / FPS, timer, v);
}
References current_rot, FPS, spinning, and timer().
Referenced by main(), and timer().
Variable Documentation
current_rot
GLfloat current_rot = 0.0 static
Definition at line 14 of file openGL_torus_animated.c.
Referenced by display(), and timer().
FPS
const int FPS = 20 static
Definition at line 11 of file openGL_torus_animated.c.
Referenced by timer().
spinning
bool spinning = true static
Definition at line 10 of file openGL_torus_animated.c.
Referenced by mouse(), and timer().