openGPMP: modules/core/CTHR/c_threadtest.c File Reference
c_threadtest.c File Reference
#include "c_threadpool.h"
#include "extra.h"
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Functions
int add_memory_access (memaddr_t addr, line_type_e type, pthread_t thread)
void dispatch_to_me (void *arg)
int main (int argc, char **argv)
Variables
int errno
Function Documentation
add_memory_access()
int add_memory_access (memaddr_t addr, line_type_e type, pthread_t thread)
dispatch_to_me()
void dispatch_to_me (void * arg)
Definition at line 17 of file c_threadtest.c.
{
     int seconds = (int)arg;
     fprintf(stdout, "  in dispatch %d\n", seconds);
     fprintf(stdout, "  done dispatch %d\n", seconds);
 }
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 22 of file c_threadtest.c.
{
     threadpool tp;
     int i = 0;
     construct_locksmith(122);
     /*
       locksmith_add_memory_access(pthread_self(),2,3,4,5);
       locksmith_add_lock_to_thread(1);
     */
     tp = create_threadpool(7);
     for (; i < 16; i++) {
         dispatch(tp, dispatch_to_me, (void *)i);
     }
     fprintf(stdout, "**main** done first\n");
     sleep(1);
     fprintf(stdout, "\n\n");
     for (i = 0; i < 12; i++) {
         dispatch(tp, dispatch_to_me, (void *)i);
     }
     fprintf(stdout, "**main done second\n");
     destroy_locksmith();
     destroy_threadpool(tp);
     sleep(5);
     exit(-1);
 }
References construct_locksmith(), create_threadpool(), destroy_locksmith(), destroy_threadpool(), dispatch(), and dispatch_to_me().
Variable Documentation
errno
int errno extern
threadpool_test.c, copyright 2001 Steve Gribble Just a regression test for the threadpool code.