openGPMP: NeuralNetwork Class Reference
NeuralNetwork Class Reference
Public Member Functions
NeuralNetwork ()
std::vector< double > forward (const std::vector< double > &input)
void backward (const std::vector< double > &input, double target)
Private Attributes
std::vector< std::vector< double > > weightsInputHidden
std::vector< std::vector< double > > weightsHiddenOutput
Detailed Description
Definition at line 50 of file TEST.cpp.
Constructor & Destructor Documentation
NeuralNetwork()
NeuralNetwork::NeuralNetwork () inline
Definition at line 56 of file TEST.cpp.
                     {
         // Initialize weights with random values between -1 and 1
         weightsInputHidden = std::vector<std::vector<double>>(
             inputSize,
             std::vector<double>(hiddenSize, 0.0));
         weightsHiddenOutput = std::vector<std::vector<double>>(
             hiddenSize,
             std::vector<double>(outputSize, 0.0));
         for (int i = 0; i < inputSize; i++) {
             for (int j = 0; j < hiddenSize; j++) {
                 weightsInputHidden[i][j] = (double)rand() / RAND_MAX * 2 - 1;
             }
         }
         for (int i = 0; i < hiddenSize; i++) {
             for (int j = 0; j < outputSize; j++) {
                 weightsHiddenOutput[i][j] = (double)rand() / RAND_MAX * 2 - 1;
             }
         }
     }
References hiddenSize, inputSize, outputSize, weightsHiddenOutput, and weightsInputHidden.
Member Function Documentation
backward()
void NeuralNetwork::backward (const std::vector< double > & input, double target) inline
Definition at line 107 of file TEST.cpp.
{
         std::vector<std::vector<double>> hiddenLayer(
             hiddenSize,
             std::vector<double>(1, 0.0));
         std::vector<std::vector<double>> outputLayer(
             outputSize,
             std::vector<double>(1, 0.0));
         // Compute hidden layer activations
         hiddenLayer = multiply(weightsInputHidden, {input});
         // Apply activation function to hidden layer activations
         for (int i = 0; i < hiddenSize; i++) {
             hiddenLayer[i][0] = sigmoid(hiddenLayer[i][0]);
         }
         // Compute output layer activations
         outputLayer = multiply(weightsHiddenOutput, hiddenLayer);
         // Apply activation function to output layer activations
         for (int i = 0; i < outputSize; i++) {
             outputLayer[i][0] = sigmoid(outputLayer[i][0]);
         }
         // Compute the error at the output layer
         std::vector<double> outputError(outputSize, 0.0);
         for (int i = 0; i < outputSize; i++) {
             outputError[i] = (target[i] - outputLayer[i][0]) *
                              sigmoidDerivative(outputLayer[i][0]);
         }
         // Compute the error at the hidden layer
         std::vector<double> hiddenError(hiddenSize, 0.0);
         for (int i = 0; i < hiddenSize; i++) {
             double sum = 0.0;
             for (int j = 0; j < outputSize; j++) {
                 sum += weightsHiddenOutput[i][j] * outputError[j];
             }
             hiddenError[i] = sum * sigmoidDerivative(hiddenLayer[i][0]);
         }
         // Update the weights between the hidden and output layers
         for (int i = 0; i < hiddenSize; i++) {
             for (int j = 0; j < outputSize; j++) {
                 weightsHiddenOutput[i][j] +=
                     learningRate * outputError[j] * hiddenLayer[i][0];
             }
         }
         // Update the weights between the input and hidden layers
         for (int i = 0; i < inputSize; i++) {
             for (int j = 0; j < hiddenSize; j++) {
                 weightsInputHidden[i][j] +=
                     learningRate * hiddenError[j] * input[i];
             }
         }
     }
References hiddenSize, inputSize, learningRate, multiply(), outputSize, sigmoid(), sigmoidDerivative(), weightsHiddenOutput, and weightsInputHidden.
Referenced by main().
forward()
std::vector<double> NeuralNetwork::forward (const std::vector< double > & input) inline
Definition at line 79 of file TEST.cpp.
{
         std::vector<std::vector<double>> hiddenLayer(
             hiddenSize,
             std::vector<double>(1, 0.0));
         std::vector<std::vector<double>> outputLayer(
             outputSize,
             std::vector<double>(1, 0.0));
         // Compute hidden layer activations
         hiddenLayer = multiply(weightsInputHidden, {input});
         // Apply activation function to hidden layer activations
         for (int i = 0; i < hiddenSize; i++) {
             hiddenLayer[i][0] = sigmoid(hiddenLayer[i][0]);
         }
         // Compute output layer activations
         outputLayer = multiply(weightsHiddenOutput, hiddenLayer);
         // Apply activation function to output layer activations
         for (int i = 0; i < outputSize; i++) {
             outputLayer[i][0] = sigmoid(outputLayer[i][0]);
         }
         return outputLayer[0]; // Return the output of the neural network
     }
References hiddenSize, multiply(), outputSize, sigmoid(), weightsHiddenOutput, and weightsInputHidden.
Referenced by main().
Member Data Documentation
weightsHiddenOutput
std::vector<std::vector<double> > NeuralNetwork::weightsHiddenOutput private
Definition at line 53 of file TEST.cpp.
Referenced by backward(), forward(), and NeuralNetwork().
weightsInputHidden
std::vector<std::vector<double> > NeuralNetwork::weightsInputHidden private
Definition at line 52 of file TEST.cpp.
Referenced by backward(), forward(), and NeuralNetwork().
The documentation for this class was generated from the following file:
modules/ml/TEST.cpp