openGPMP: gpmp::linalg::Mtx Class Reference
gpmp::linalg::Mtx Class Reference
Mtx class offers matrix arithmetic operations. Some methods are element-wise while others make use of grouping and unrolling.
#include <mtx.hpp>
Public Member Functions
void mtx_add_f90 (float *A, float *B, float *C, std::size_t matrixSize)
Perform matrix addition using flattened matrices and the designated Fortran subroutine. Accepts type float.
void mtx_add_f90 (int *A, int *B, int *C, std::size_t matrixSize)
Perform matrix addition using flattened matrices and the designated Fortran subroutine. Accepts type int.
template<typename T >
void std_mtx_add (const T *A, const T *B, T *C, int rows, int cols)
Perform matrix addition on two matrices as flat arrays.
template<typename T >
void std_mtx_add (const std::vector< T > &A, const std::vector< T > &B, std::vector< T > &C)
Perform matrix addition on two matrices as flat vectors.
template<typename T >
void std_mtx_add (const std::vector< std::vector< T >> &A, const std::vector< std::vector< T >> &B, std::vector< std::vector< T >> &C)
Perform matrix addition on two matrices as 2D vectors.
template<typename T >
void std_mtx_sub (const std::vector< std::vector< T >> &A, const std::vector< std::vector< T >> &B, std::vector< std::vector< T >> &C)
Perform matrix subtraction on two matrices as 2D vectors.
template<typename T >
void std_mtx_mult (const std::vector< std::vector< T >> &A, const std::vector< std::vector< T >> &B, std::vector< std::vector< T >> &C)
Perform matrix multiplication on two matrices 2D vectors.
void std_mtx_mult_strass (const std::vector< std::vector< int >> &A, const std::vector< std::vector< int >> &B, std::vector< std::vector< int >> &C)
Performs matrix multiplication using the Strassen algorithm.
Detailed Description
Mtx class offers matrix arithmetic operations. Some methods are element-wise while others make use of grouping and unrolling.
Definition at line 48 of file mtx.hpp.
Member Function Documentation
mtx_add_f90() [1/2]
void gpmp::linalg::Mtx::mtx_add_f90 (float * A, float * B, float * C, std::size_t matrixSize)
Perform matrix addition using flattened matrices and the designated Fortran subroutine. Accepts type float.
Definition at line 57 of file mtx.cpp.
{
     mtx_add_routine_float_(A, B, C, &mtx_size);
 }
References mtx_add_routine_float_().
Referenced by mtx_add_f90().
mtx_add_f90() [2/2]
void gpmp::linalg::Mtx::mtx_add_f90 (int * A, int * B, int * C, std::size_t matrixSize)
Perform matrix addition using flattened matrices and the designated Fortran subroutine. Accepts type int.
Definition at line 65 of file mtx.cpp.
{
     mtx_add_routine_int_(A, B, C, &mtx_size);
 }
References mtx_add_routine_int_().
std_mtx_add() [1/3]
template<typename T > void gpmp::linalg::Mtx::std_mtx_add (const std::vector< std::vector< T >> & A, const std::vector< std::vector< T >> & B, std::vector< std::vector< T >> & C)
Perform matrix addition on two matrices as 2D vectors.
Parameters
A Input matrix A
B Input matrix B
C Output matrix C This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1183 of file mtx.cpp.
{
     const int size = A.size();
     for (int i = 0; i < size; ++i) {
         for (int j = 0; j < size; ++j) {
             // perform matrix addition
             C[i][j] = A[i][j] + B[i][j];
         }
     }
 }
std_mtx_add() [2/3]
template<typename T > void gpmp::linalg::Mtx::std_mtx_add (const std::vector< T > & A, const std::vector< T > & B, std::vector< T > & C)
Perform matrix addition on two matrices as flat vectors.
Parameters
A Input matrix A
B Input matrix B
C Output matrix C This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1147 of file mtx.cpp.
{
     // MTX A AND B MUST BE SAME SIZE
     int rows = A.size();
     int cols = rows > 0 ? A.size() / rows : 0;
     for (int i = 0; i < rows; ++i) {
         for (int j = 0; j < cols; ++j) {
             // perform matrix addition
             C[i * cols + j] = A[i * cols + j] + B[i * cols + j];
         }
     }
 }
std_mtx_add() [3/3]
template<typename T > void gpmp::linalg::Mtx::std_mtx_add (const T * A, const T * B, T * C, int rows, int cols)
Perform matrix addition on two matrices as flat arrays.
Parameters
A Input matrix A
B Input matrix B
C Output matrix C
rows Number of rows
cols Number of columns This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1094 of file mtx.cpp.
{
     // MTX A AND B MUST BE SAME SIZE
     for (int i = 0; i < rows; ++i) {
         for (int j = 0; j < cols; ++j) {
             // perform matrix addition
             C[i * cols + j] = A[i * cols + j] + B[i * cols + j];
         }
     }
 }
Referenced by run_mtx_add(), run_mtx_add_arr(), run_mtx_add_doub(), and run_mtx_add_flt().
std_mtx_mult()
template<typename T > template void gpmp::linalg::Mtx::std_mtx_mult (const std::vector< std::vector< T >> & A, const std::vector< std::vector< T >> & B, std::vector< std::vector< T >> & C)
Perform matrix multiplication on two matrices 2D vectors.
Parameters
A Input matrix A
B Input matrix B
C Output matrix C This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1245 of file mtx.cpp.
{
     assert(A.size() == B.size());
     assert(A[0].size() == B[0].size());
     int64_t nrows = A.size();
     int64_t ncols = A[0].size();
     for (int64_t i = 0; i < nrows; ++i) {
         for (int64_t j = 0; j < ncols; ++j) {
             C[i][j] = 0.0;
             for (int64_t k = 0; k < ncols; ++k) {
                 C[i][j] += A[i][k] * B[k][j];
             }
         }
     }
 }
std_mtx_mult_strass()
void gpmp::linalg::Mtx::std_mtx_mult_strass (const std::vector< std::vector< int >> & A, const std::vector< std::vector< int >> & B, std::vector< std::vector< int >> & C)
Performs matrix multiplication using the Strassen algorithm.
Parameters
A Input matrix A
B Input matrix B
C Output matrix C
Note
The input matrices A and B should be square matrices with dimensions that are powers of 2 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
std_mtx_sub()
template<typename T > template void gpmp::linalg::Mtx::std_mtx_sub (const std::vector< std::vector< T >> & A, const std::vector< std::vector< T >> & B, std::vector< std::vector< T >> & C)
Perform matrix subtraction on two matrices as 2D vectors.
Parameters
A Input matrix A
B Input matrix B
C Output matrix C This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1214 of file mtx.cpp.
{
     const int size = A.size();
     for (int i = 0; i < size; ++i) {
         for (int j = 0; j < size; ++j) {
             // Perform matrix subtraction
             C[i][j] = A[i][j] - B[i][j];
         }
     }
 }
The documentation for this class was generated from the following files:
include/linalg/mtx.hpp
modules/linalg/mtx.cpp