openGPMP: gpmp::Cipher Class Reference
gpmp::Cipher Class Reference
#include <cipher.hpp>
Public Member Functions
std::string caesar (std::string plaintext, int64_t key)
std::string keyword_encode (std::string key)
std::string keyword (std::string plaintext, std::string encoded_text)
Detailed Description
Examples
cipher.cpp.
Definition at line 50 of file cipher.hpp.
Member Function Documentation
caesar()
std::string gpmp::Cipher::caesar (std::string plaintext, int64_t key)
Examples
cipher.cpp.
Definition at line 47 of file cipher.cpp.
{
     std::string hashtext = "";
     for (int64_t i = 0; uint64_t(i) < plaintext.length(); i++) {
         // inject transformation
         if (isupper(plaintext[i])) {
             // upper case
             hashtext += char(int64_t(plaintext[i] + key - 65) % 26 + 65);
         } else {
             // lower case
             hashtext += char(int64_t(plaintext[i] + key - 97) % 26 + 97);
         }
     }
     return hashtext;
 }
Referenced by main().
keyword()
std::string gpmp::Cipher::keyword (std::string plaintext, std::string encoded_text)
Examples
cipher.cpp.
Definition at line 100 of file cipher.cpp.
{
     std::string cipher = "";
     /*
      * This loop ciphered the message. Spaces, special characters
      * and numbers remain same.
      */
     for (int64_t i = 0; uint64_t(i) < plaintext.size(); i++) {
         if (plaintext[i] >= 'a' && plaintext[i] <= 'z') {
             int64_t pos = plaintext[i] - 97;
             cipher += encoded_text[pos];
         }
         else if (plaintext[i] >= 'A' && plaintext[i] <= 'Z') {
             int64_t pos = plaintext[i] - 65;
             cipher += encoded_text[pos];
         }
         else {
             cipher += plaintext[i];
         }
     }
     return cipher;
 }
Referenced by main().
keyword_encode()
std::string gpmp::Cipher::keyword_encode (std::string key)
Examples
cipher.cpp.
Definition at line 64 of file cipher.cpp.
{
     std::string encoded = "";
     // This array represents the 26 letters of alphabets
     bool arr[26] = {0};
     // This loop inserts the keyword at the start of the encoded
     // string
     for (int64_t i = 0; uint64_t(i) < key.size(); i++) {
         if (key[i] >= 'A' && key[i] <= 'Z') {
             /*
              * To check whether the character is inserted earlier
              * in the encoded string or not
              */
             if (arr[key[i] - 65] == 0) {
                 encoded += key[i];
                 arr[key[i] - 65] = 1;
             }
         } else if (key[i] >= 'a' && key[i] <= 'z') {
             if (arr[key[i] - 97] == 0) {
                 encoded += key[i] - 32;
                 arr[key[i] - 97] = 1;
             }
         }
     }
     // This loop inserts the remaining characters in the encoded
     // string.
     for (int64_t i = 0; i < 26; i++) {
         if (arr[i] == 0) {
             arr[i] = 1;
             encoded += char(i + 65);
         }
     }
     return encoded;
 }
Referenced by main().
The documentation for this class was generated from the following files:
include/nt/cipher.hpp
modules/nt/cipher.cpp