openMTPK: Function_pool Class Reference
Function_pool Class Reference
#include <test_pool.hpp>
Public Member Functions
Function_pool ()
~Function_pool ()
void push (std::function< void()> func)
void done ()
void infinite_loop_func ()
Private Attributes
std::deque< std::function< void()> > m_function_queue
std::deque< size_t > m_order_queue
std::mutex m_lock
std::condition_variable m_data_condition
std::atomic< bool > m_accept_functions
Detailed Description
Definition at line 10 of file test_pool.hpp.
Constructor & Destructor Documentation
Function_pool()
Function_pool::Function_pool ()
Definition at line 3 of file test_pool.cpp.
     : m_function_queue(), m_lock(), m_data_condition(),
       m_accept_functions(true) {
 }
~Function_pool()
Function_pool::~Function_pool ()
Definition at line 8 of file test_pool.cpp.
{
 }
Member Function Documentation
done()
void Function_pool::done ()
Definition at line 30 of file test_pool.cpp.
{
     std::unique_lock<std::mutex> lock(m_lock);
     m_accept_functions = false;
     lock.unlock();
     // when we send the notification immediately, the consumer will try to
     // get the lock , so unlock asap
     m_data_condition.notify_all();
     // notify all waiting threads.
 }
References m_accept_functions, m_data_condition, and m_lock.
Referenced by main().
infinite_loop_func()
void Function_pool::infinite_loop_func ()
Definition at line 40 of file test_pool.cpp.
{
     std::function<void()> func;
     while (true) {
         {
             std::unique_lock<std::mutex> lock(m_lock);
             m_data_condition.wait(lock, [this]() {
                 return !m_function_queue.empty() || !m_accept_functions;
             });
             if (!m_accept_functions && m_function_queue.empty()) {
                 // lock will be release automatically.
                 // finish the thread loop and let it join in the main
                 // thread.
                 return;
             }
             func = m_function_queue.front();
             m_function_queue.pop_front();
             // release the lock
         }
         func();
     }
 }
References m_accept_functions, m_data_condition, m_function_queue, and m_lock.
Referenced by main().
push()
void Function_pool::push (std::function< void()> func)
Definition at line 11 of file test_pool.cpp.
{
     std::unique_lock<std::mutex> lock(m_lock);
     m_function_queue.push_back(func);
     // when we send the notification immediately, the consumer will try to
     // get the lock , so unlock asap
     lock.unlock();
     m_data_condition.notify_one();
 }
References m_data_condition, m_function_queue, and m_lock.
Referenced by main().
Member Data Documentation
m_accept_functions
std::atomic<bool> Function_pool::m_accept_functions private
Definition at line 16 of file test_pool.hpp.
Referenced by done(), and infinite_loop_func().
m_data_condition
std::condition_variable Function_pool::m_data_condition private
Definition at line 15 of file test_pool.hpp.
Referenced by done(), infinite_loop_func(), and push().
m_function_queue
std::deque<std::function<void()> > Function_pool::m_function_queue private
Definition at line 12 of file test_pool.hpp.
Referenced by infinite_loop_func(), and push().
m_lock
std::mutex Function_pool::m_lock private
Definition at line 14 of file test_pool.hpp.
Referenced by done(), infinite_loop_func(), and push().
m_order_queue
std::deque<size_t> Function_pool::m_order_queue private
Definition at line 13 of file test_pool.hpp.
The documentation for this class was generated from the following files:
include/test_pool.hpp
include/test_pool.cpp