openGPMP: gpmp::stats::ProbDist Class Reference
gpmp::stats::ProbDist Class Reference
#include <probdist.hpp>
Public Member Functions
double quantile_dist (double probability)
Compute the quantile of the standard normal distribution.
double normal_PDF (double x, double mean, double stddev)
Compute the probability density function (PDF) for the normal distribution.
double normal_CDF (double x, double mean, double stddev)
Compute the cumulative distribution function (CDF) for the normal distribution.
double uniform_CDF (size_t k, size_t n)
Compute the cumulative distribution function (CDF) for the uniform distribution.
double exp_PDF (double x, size_t k, double lambda)
Compute the probability density function (PDF) for the exponential distribution.
double emp_CDF (const std::vector< double > &data, double x)
Compute the empirical cumulative distribution function (CDF) for a given value.
double emp_PMF (const std::vector< double > &data, double x)
Compute the empirical probability mass function (PMF) for a given value.
double inverse_emp_CDF (const std::vector< double > &data, double p)
Compute the inverse of the empirical cumulative distribution function (CDF) for a given probability.
double mle (const std::vector< double > &data)
Compute the Maximum Likelihood Estimate (MLE) for the mean of a dataset.
double mom (const std::vector< double > &data)
Compute the method of moments (MOM) estimate for the mean of a dataset.
double mle_est (const std::vector< double > &data)
Placeholder function for M-estimation.
double mumv (const std::vector< double > &data)
Compute the Mean-Unbiased Minimum-Variance (MUMV) estimate for the mean of a dataset.
double median_uniased (const std::vector< double > &data)
Compute the median-unbiased estimate for the median of a dataset.
std::pair< double, double > ConfidenceInterval (const std::vector< double > &data, double alpha)
Compute the confidence interval for the mean of a dataset.
double Pivot (const std::vector< double > &data, double pivotFunction(const std::vector< double > &))
Compute the value of a pivot function for interval estimation.
double PivotFunctionForConfidenceInterval (const std::vector< double > &data)
Example pivot function for computing a confidence interval.
std::pair< double, double > LikelihoodInterval (const std::vector< double > &data, double alpha)
Compute the likelihood interval for a given dataset and significance level.
std::pair< double, double > PredictionInterval (const std::vector< double > &data, double alpha)
Compute the prediction interval for a given dataset and significance level.
std::pair< double, double > ToleranceInterval (const std::vector< double > &data, double alpha)
Compute the tolerance interval for a given dataset and significance level.
std::pair< double, double > BootstrapResampling (const std::vector< double > &data, int numSamples)
Compute the bootstrap resampling confidence interval for a given dataset and number of samples.
std::pair< double, double > JackknifeResampling (const std::vector< double > &data)
Compute the Jackknife resampling confidence interval for a given dataset.
Detailed Description
Definition at line 42 of file probdist.hpp.
Member Function Documentation
BootstrapResampling()
std::pair< double, double > gpmp::stats::ProbDist::BootstrapResampling (const std::vector< double > & data, int numSamples)
Compute the bootstrap resampling confidence interval for a given dataset and number of samples.
Parameters
data The dataset
numSamples The number of bootstrap samples
Returns
A pair representing the lower and upper bounds of the bootstrap resampling confidence interval
Definition at line 335 of file probdist.cpp.
{
     if (data.empty() || numSamples <= 0) {
         return {0.0, 0.0}; // Invalid input, return an empty interval
     }
     std::vector<double> resampledMeans;
     resampledMeans.reserve(numSamples);
     std::mt19937 gen(std::random_device{}());
     std::uniform_int_distribution<size_t> distribution(0, data.size() - 1);
     gpmp::stats::Describe desc;
     for (int i = 0; i < numSamples; ++i) {
         std::vector<double> resampledData;
         resampledData.reserve(data.size());
         for (size_t j = 0; j < data.size(); ++j) {
             resampledData.push_back(data[distribution(gen)]);
         }
         resampledMeans.push_back(desc.mean_arith(resampledData));
     }
     std::sort(resampledMeans.begin(), resampledMeans.end());
     double lowerBound = resampledMeans[numSamples / 20];
     double upperBound = resampledMeans[19 * numSamples / 20];
     return {lowerBound, upperBound};
 }
References gpmp::stats::Describe::mean_arith().
ConfidenceInterval()
std::pair< double, double > gpmp::stats::ProbDist::ConfidenceInterval (const std::vector< double > & data, double alpha)
Compute the confidence interval for the mean of a dataset.
Parameters
data The dataset
alpha The confidence level
Returns
A pair representing the lower and upper bounds of the confidence interval
Definition at line 250 of file probdist.cpp.
{
     if (data.empty() || alpha <= 0.0 || alpha >= 1.0) {
         return {0.0, 0.0}; // Invalid input, return an empty interval
     }
     size_t n = data.size();
     gpmp::stats::Describe desc;
     double mean = desc.mean_arith(data);
     double stddev = desc.stdev(data, mean);
     // Assuming a normal distribution for simplicity
     double z = quantile_dist(1 - alpha / 2.0);
     double margin = z * stddev / std::sqrt(static_cast<double>(n));
     return {mean - margin, mean + margin};
 }
References gpmp::stats::Describe::mean_arith(), and gpmp::stats::Describe::stdev().
emp_CDF()
double gpmp::stats::ProbDist::emp_CDF (const std::vector< double > & data, double x)
Compute the empirical cumulative distribution function (CDF) for a given value.
Parameters
data The dataset
x The value at which to evaluate the empirical CDF
Returns
The empirical CDF value at the given point
Definition at line 165 of file probdist.cpp.
{
     size_t count = 0;
     for (const auto &value : data) {
         if (value <= x) {
             count++;
         }
     }
     return static_cast<double>(count) / data.size();
 }
emp_PMF()
double gpmp::stats::ProbDist::emp_PMF (const std::vector< double > & data, double x)
Compute the empirical probability mass function (PMF) for a given value.
Parameters
data The dataset
x The value at which to evaluate the empirical PMF
Returns
The empirical PMF value at the given point
Definition at line 177 of file probdist.cpp.
{
     size_t count = std::count(data.begin(), data.end(), x);
     return static_cast<double>(count) / data.size();
 }
exp_PDF()
double gpmp::stats::ProbDist::exp_PDF (double x, size_t k, double lambda)
Compute the probability density function (PDF) for the exponential distribution.
Parameters
x The value at which to evaluate the PDF
k The shape parameter of the distribution
lambda The rate parameter of the distribution
Returns
The PDF value at the given point
Definition at line 147 of file probdist.cpp.
{
                 // Check if k is valid (k must be 1 for exponential distribution)
                 if (k != 1) {
                     // Return 0 if k is not 1, as exponential distribution is only defined for k = 1
                     return 0.0;
                 }
                 // Check if lambda is non-positive
                 if (lambda <= 0) {
                     // Return 0 if lambda is non-positive
                     return 0.0;
                 }
                 // Calculate the exponential PDF
                 return (k / lambda) * exp(-k * x);
 }
inverse_emp_CDF()
double gpmp::stats::ProbDist::inverse_emp_CDF (const std::vector< double > & data, double p)
Compute the inverse of the empirical cumulative distribution function (CDF) for a given probability.
Parameters
data The dataset
p The probability value between 0 and 1
Returns
The value at which the empirical CDF is equal to or greater than the given probability
Definition at line 183 of file probdist.cpp.
{
     if (data.empty() || p < 0.0 || p > 1.0) {
         return 0.0; // Invalid input, return 0
     }
     std::vector<double> sortedData = data;
     std::sort(sortedData.begin(), sortedData.end());
     size_t index = static_cast<size_t>(p * (data.size() - 1));
     return sortedData[index];
 }
JackknifeResampling()
std::pair< double, double > gpmp::stats::ProbDist::JackknifeResampling (const std::vector< double > & data)
Compute the Jackknife resampling confidence interval for a given dataset.
Parameters
data The dataset
Returns
A pair representing the lower and upper bounds of the Jackknife resampling confidence interval
Definition at line 366 of file probdist.cpp.
{
     if (data.empty()) {
         return {0.0, 0.0}; // Invalid input, return an empty interval
     }
     size_t n = data.size();
     std::vector<double> resampledMeans;
     resampledMeans.reserve(n);
     gpmp::stats::Describe desc;
     for (size_t i = 0; i < n; ++i) {
         std::vector<double> resampledData;
         resampledData.reserve(n - 1);
         for (size_t j = 0; j < n; ++j) {
             if (j != i) {
                 resampledData.push_back(data[j]);
             }
         }
         resampledMeans.push_back(desc.mean_arith(resampledData));
     }
     std::sort(resampledMeans.begin(), resampledMeans.end());
     double lowerBound = resampledMeans[n / 20];
     double upperBound = resampledMeans[19 * n / 20];
     return {lowerBound, upperBound};
 }
References gpmp::stats::Describe::mean_arith().
LikelihoodInterval()
std::pair< double, double > gpmp::stats::ProbDist::LikelihoodInterval (const std::vector< double > & data, double alpha)
Compute the likelihood interval for a given dataset and significance level.
Parameters
data The dataset
alpha The significance level
Returns
A pair representing the lower and upper bounds of the likelihood interval
Definition at line 291 of file probdist.cpp.
{
     // Example implementation, this needs to be adapted based on the specific
     // likelihood function
     if (data.empty() || alpha <= 0.0 || alpha >= 1.0) {
         return {0.0, 0.0}; // Invalid input, return an empty interval
     }
     // Placeholder, implement likelihood function and find confidence bounds
     double lowerBound = 0.0;
     double upperBound = 1.0;
     return {lowerBound, upperBound};
 }
median_uniased()
double gpmp::stats::ProbDist::median_uniased (const std::vector< double > & data)
Compute the median-unbiased estimate for the median of a dataset.
Parameters
data The dataset
Returns
The median-unbiased estimate for the median
Definition at line 232 of file probdist.cpp.
{
     if (data.empty()) {
         return 0.0; // Invalid input, return 0
     }
     std::vector<double> sortedData = data;
     std::sort(sortedData.begin(), sortedData.end());
     size_t size = sortedData.size();
     if (size % 2 == 0) {
         return (sortedData[size / 2 - 1] + sortedData[size / 2]) / 2.0;
     } else {
         return sortedData[size / 2];
     }
 }
mle()
double gpmp::stats::ProbDist::mle (const std::vector< double > & data)
Compute the Maximum Likelihood Estimate (MLE) for the mean of a dataset.
Parameters
data The dataset
Returns
The MLE estimate for the mean
Definition at line 196 of file probdist.cpp.
{
     if (data.empty()) {
         return 0.0; // Invalid input, return 0
     }
     double sum = std::accumulate(data.begin(), data.end(), 0.0);
     return sum / data.size();
 }
mle_est()
double gpmp::stats::ProbDist::mle_est (const std::vector< double > & data)
Placeholder function for M-estimation.
Parameters
data The dataset
Returns
The M-estimation result
Definition at line 217 of file probdist.cpp.
{
     // This is a placeholder, you can replace it with a specific M-estimation
     // method
     return mle(data);
 }
mom()
double gpmp::stats::ProbDist::mom (const std::vector< double > & data)
Compute the method of moments (MOM) estimate for the mean of a dataset.
Parameters
data The dataset
Returns
The MOM estimate for the mean
Definition at line 205 of file probdist.cpp.
{
     if (data.empty()) {
         return 0.0; // Invalid input, return 0
     }
     gpmp::stats::Describe desc;
     double mean = desc.mean_arith(data);
     double variance = desc.variance(data, mean);
     return mean - variance / 2.0;
 }
References gpmp::stats::Describe::mean_arith(), and gpmp::stats::Describe::variance().
mumv()
double gpmp::stats::ProbDist::mumv (const std::vector< double > & data)
Compute the Mean-Unbiased Minimum-Variance (MUMV) estimate for the mean of a dataset.
Parameters
data The dataset
Returns
The MUMV estimate for the mean
Definition at line 223 of file probdist.cpp.
{
     if (data.empty()) {
         return 0.0; // Invalid input, return 0
     }
     double sum = std::accumulate(data.begin(), data.end(), 0.0);
     return sum / data.size();
 }
normal_CDF()
double gpmp::stats::ProbDist::normal_CDF (double x, double mean, double stddev)
Compute the cumulative distribution function (CDF) for the normal distribution.
Parameters
x The value at which to evaluate the CDF
mean The mean of the distribution
stddev The standard deviation of the distribution
Returns
The CDF value at the given point
Definition at line 132 of file probdist.cpp.
{
     // Implement the cumulative distribution function (CDF) for the normal
     // distribution You can use standard libraries or existing implementations
     // for this calculation Example using C++ standard library:
     return 0.5 * (1.0 + std::erf((x - mean) / (stddev * std::sqrt(2.0))));
 }
normal_PDF()
double gpmp::stats::ProbDist::normal_PDF (double x, double mean, double stddev)
Compute the probability density function (PDF) for the normal distribution.
Parameters
x The value at which to evaluate the PDF
mean The mean of the distribution
stddev The standard deviation of the distribution
Returns
The PDF value at the given point
Definition at line 124 of file probdist.cpp.
{
     // Implement the probability density function (PDF) for the normal
     // distribution You can use standard libraries or existing implementations
     // for this calculation Example using C++ standard library:
     double exponent = -0.5 * std::pow((x - mean) / stddev, 2.0);
     return (1.0 / (stddev * std::sqrt(2.0 * M_PI))) * std::exp(exponent);
 }
Pivot()
double gpmp::stats::ProbDist::Pivot (const std::vector< double > & data, double pivotFunctionconst std::vector< double > &)
Compute the value of a pivot function for interval estimation.
Parameters
data The dataset
pivotFunction The pivot function to evaluate
Returns
The value of the pivot function
Definition at line 268 of file probdist.cpp.
{
     if (data.empty()) {
         return 0.0; // Invalid input, return 0
     }
     return pivotFunction(data);
 }
PivotFunctionForConfidenceInterval()
double gpmp::stats::ProbDist::PivotFunctionForConfidenceInterval (const std::vector< double > & data)
Example pivot function for computing a confidence interval.
Parameters
data The dataset
Returns
The value of the pivot function for a confidence interval
Definition at line 279 of file probdist.cpp.
{
     size_t n = data.size();
     gpmp::stats::Describe desc;
     double mean = desc.mean_arith(data);
     double stddev = desc.stdev(data, mean);
     return mean + 2 * stddev / std::sqrt(static_cast<double>(n));
 }
References gpmp::stats::Describe::mean_arith(), and gpmp::stats::Describe::stdev().
PredictionInterval()
std::pair< double, double > gpmp::stats::ProbDist::PredictionInterval (const std::vector< double > & data, double alpha)
Compute the prediction interval for a given dataset and significance level.
Parameters
data The dataset
alpha The significance level
Returns
A pair representing the lower and upper bounds of the prediction interval
Definition at line 307 of file probdist.cpp.
{
     if (data.empty() || alpha <= 0.0 || alpha >= 1.0) {
         return {0.0, 0.0}; // Invalid input, return an empty interval
     }
     // Placeholder, implement prediction interval calculation
     double lowerBound = 0.0;
     double upperBound = 1.0;
     return {lowerBound, upperBound};
 }
quantile_dist()
double gpmp::stats::ProbDist::quantile_dist (double probability)
Compute the quantile of the standard normal distribution.
Parameters
probability The probability value between 0 and 1
Returns
The quantile corresponding to the given probability
Definition at line 113 of file probdist.cpp.
{
     if (probability <= 0.0 || probability >= 1.0) {
         return 0.0; // Invalid input, return 0
     }
     // Using erfinv for older C++ standards
     double z = std::sqrt(2.0) * erfinv(2.0 * probability - 1.0);
     return z;
 }
References erfinv().
ToleranceInterval()
std::pair< double, double > gpmp::stats::ProbDist::ToleranceInterval (const std::vector< double > & data, double alpha)
Compute the tolerance interval for a given dataset and significance level.
Parameters
data The dataset
alpha The significance level
Returns
A pair representing the lower and upper bounds of the tolerance interval
Definition at line 321 of file probdist.cpp.
{
     if (data.empty() || alpha <= 0.0 || alpha >= 1.0) {
         return {0.0, 0.0}; // Invalid input, return an empty interval
     }
     // Placeholder, implement tolerance interval calculation
     double lowerBound = 0.0;
     double upperBound = 1.0;
     return {lowerBound, upperBound};
 }
uniform_CDF()
double gpmp::stats::ProbDist::uniform_CDF (size_t k, size_t n)
Compute the cumulative distribution function (CDF) for the uniform distribution.
Parameters
k The value at which to evaluate the CDF
n The maximum value in the uniform distribution
Returns
The CDF value at the given point
Definition at line 139 of file probdist.cpp.
{
     if (k == 0 || k > n) {
         return 0.0; // Invalid input, return 0
     }
     return static_cast<double>(k) / (n + 1);
 }
The documentation for this class was generated from the following files:
include/stats/probdist.hpp
modules/stats/probdist.cpp