openGPMP: gpmp::ml::BayesBernoulli Class Reference
gpmp::ml::BayesBernoulli Class Reference
#include <bayes_clf.hpp>
Public Member Functions
BayesBernoulli (double alpha_param=1.0)
Constructor for BayesBernoulli class.
~BayesBernoulli ()
Destructor for BayesBernoulli class.
void train (const std::vector< std::vector< size_t >> &data, const std::vector< std::string > &labels)
Train the classifier with a set of labeled data.
std::string predict (const std::vector< size_t > &newData) const
Predict the class of a new data point.
void display () const
Display the learned probabilities.
Public Attributes
std::unordered_map< std::string, double > class_probs
std::unordered_map< std::string, std::unordered_map< size_t, double > > feat_probs
double alpha
Detailed Description
Bernoulli Naive Bayes is a part of the Naive Bayes family. It is based on the Bernoulli Distribution and accepts only binary values, i.e., 0 or 1. If the features of the dataset are binary, then we can assume that Bernoulli Naive Bayes is the algorithm to be used.
Definition at line 123 of file bayes_clf.hpp.
Constructor & Destructor Documentation
BayesBernoulli()
gpmp::ml::BayesBernoulli::BayesBernoulli (double alpha_param = 1.0) inline
Constructor for BayesBernoulli class.
Parameters
alpha Additive (Laplace/Lidstone) smoothing parameter
Definition at line 134 of file bayes_clf.hpp.
                                              : alpha(alpha_param) {
     }
~BayesBernoulli()
gpmp::ml::BayesBernoulli::~BayesBernoulli () inline
Destructor for BayesBernoulli class.
Definition at line 140 of file bayes_clf.hpp.
                       {
     }
Member Function Documentation
display()
void gpmp::ml::BayesBernoulli::display () const
Display the learned probabilities.
Note
This method is for debugging purposes
Definition at line 212 of file bayes_clf.cpp.
{
     std::cout << "Class Probabilities:\n";
     for (const auto &entry : class_probs) {
         std::cout << entry.first << ": " << entry.second << "\n";
     }
     std::cout << "\nFeature Probabilities:\n";
     for (const auto &class_entry : feat_probs) {
         std::cout << class_entry.first << ":\n";
         for (const auto &feat_entry : class_entry.second) {
             std::cout << "  Feature " << feat_entry.first << ": "
                       << feat_entry.second << "\n";
         }
     }
 }
Referenced by main().
predict()
std::string gpmp::ml::BayesBernoulli::predict (const std::vector< size_t > & newData) const
Predict the class of a new data point.
Parameters
newData A vector of size_t representing the features of the new data point
Returns
The predicted class label as a string
Definition at line 191 of file bayes_clf.cpp.
{
     double max_prob = -std::numeric_limits<double>::infinity();
     std::string predicted_class;
     for (const auto &class_entry : class_probs) {
         double probability = log(class_entry.second);
         for (size_t i = 0; i < new_data.size(); ++i) {
             probability +=
                 new_data[i] * log(feat_probs.at(class_entry.first).at(i));
         }
         if (probability > max_prob) {
             max_prob = probability;
             predicted_class = class_entry.first;
         }
     }
     return predicted_class;
 }
Referenced by main().
train()
void gpmp::ml::BayesBernoulli::train (const std::vector< std::vector< size_t >> & data, const std::vector< std::string > & labels)
Train the classifier with a set of labeled data.
Parameters
data A vector of vectors representing the training instances
labels A vector of strings representing the corresponding class labels
Definition at line 155 of file bayes_clf.cpp.
{
     size_t numInstances = data.size();
     size_t num_feats = data[0].size();
     for (size_t i = 0; i < numInstances; ++i) {
         std::string classLabel = labels[i];
         // update class probabilities
         class_probs[classLabel] += 1.0;
         // update feature probabilities
         for (size_t j = 0; j < num_feats; ++j) {
             feat_probs[classLabel][j] += data[i][j];
         }
     }
     // laplace smoothing
     double smoothing_factor = alpha * 2.0;
     for (auto &entry : class_probs) {
         entry.second =
             (entry.second + alpha) / (numInstances + smoothing_factor);
     }
     for (auto &class_entry : feat_probs) {
         for (auto &feat_entry : class_entry.second) {
             feat_entry.second =
                 (feat_entry.second + alpha) /
                 (class_probs[class_entry.first] + smoothing_factor);
         }
     }
 }
Referenced by main().
Member Data Documentation
alpha
double gpmp::ml::BayesBernoulli::alpha
Definition at line 128 of file bayes_clf.hpp.
class_probs
std::unordered_map<std::string, double> gpmp::ml::BayesBernoulli::class_probs
Definition at line 125 of file bayes_clf.hpp.
feat_probs
std::unordered_map<std::string, std::unordered_map<size_t, double> > gpmp::ml::BayesBernoulli::feat_probs
Definition at line 127 of file bayes_clf.hpp.
The documentation for this class was generated from the following files:
include/openGPMP/ml/bayes_clf.hpp
modules/ml/bayes_clf.cpp