openGPMP: gpmp::stats::CDF Class Reference
gpmp::stats::CDF Class Reference
Class providing methods for computing cumulative distribution functions (CDFs)
#include <cdfs.hpp>
Static Public Member Functions
static double bernoulli (double x, double p)
Compute the cumulative distribution function (CDF) of the Bernoulli distribution.
static double beta (double x, double alpha, double beta)
Compute the cumulative distribution function (CDF) of the beta distribution.
static double binomial (int k, int n, double p)
Compute the cumulative distribution function (CDF) of the binomial distribution.
static double cauchy (double x, double x0, double gamma)
Compute the cumulative distribution function (CDF) of the Cauchy distribution.
static double chi_squared (double x, double k)
Compute the cumulative distribution function (CDF) of the chi-squared distribution.
static double exponential (double x, double lambda)
Compute the cumulative distribution function (CDF) of the exponential distribution.
static double f (double x, double df1, double df2)
Compute the cumulative distribution function (CDF) of the F distribution.
static double gamma (double x, double shape, double scale)
Compute the cumulative distribution function (CDF) of the gamma distribution.
static double inverse_gamma (double x, double shape, double scale)
Compute the cumulative distribution function (CDF) of the inverse-gamma distribution.
static double inverse_gaussian (double x, double mu, double lambda)
Compute the cumulative distribution function (CDF) of the inverse-Gaussian distribution.
static double laplace (double x, double mu, double b)
Compute the cumulative distribution function (CDF) of the Laplace distribution.
static double logistic (double x, double mu, double s)
Compute the cumulative distribution function (CDF) of the logistic distribution.
static double log_normal (double x, double mu, double sigma)
Compute the cumulative distribution function (CDF) of the log-normal distribution.
static double gaussian (double x, double mu, double sigma)
Compute the cumulative distribution function (CDF) of the normal (Gaussian) distribution.
static double poisson (int k, double lambda)
Compute the cumulative distribution function (CDF) of the Poisson distribution.
static double rademacher (double x)
Compute the cumulative distribution function (CDF) of the Rademacher distribution.
static double student_t (double x, double df)
Compute the cumulative distribution function (CDF) of Student's t distribution.
static double uniform (double x, double a, double b)
Compute the cumulative distribution function (CDF) of the uniform distribution.
static double weibull (double x, double shape, double scale)
Compute the cumulative distribution function (CDF) of the Weibull distribution.
static double normal_cdf (double x)
Compute the cumulative distribution function (CDF) of the standard normal distribution.
static double incomplete_beta (double a, double b, double x)
Compute the incomplete beta function.
static double incomplete_gamma (double a, double x)
Compute the incomplete gamma function.
Detailed Description
Class providing methods for computing cumulative distribution functions (CDFs)
Definition at line 43 of file cdfs.hpp.
Member Function Documentation
bernoulli()
double gpmp::stats::CDF::bernoulli (double x, double p) static
Compute the cumulative distribution function (CDF) of the Bernoulli distribution.
Parameters
x The value at which to evaluate the CDF
p The probability parameter of the Bernoulli distribution
Returns
The CDF value at the given point
Definition at line 43 of file cdfs.cpp.
{
     if (x < 0)
         return 0.0;
     else if (x < 1)
         return 1 - (1 - p);
     else
         return 1.0;
 }
Referenced by main().
beta()
double gpmp::stats::CDF::beta (double x, double alpha, double beta) static
Compute the cumulative distribution function (CDF) of the beta distribution.
Parameters
x The value at which to evaluate the CDF
alpha The alpha parameter of the beta distribution
beta The beta parameter of the beta distribution
Returns
The CDF value at the given point
Definition at line 53 of file cdfs.cpp.
{
     if (x <= 0)
         return 0.0;
     else if (x >= 1)
         return 1.0;
     else
         return incomplete_beta(alpha, beta, x);
 }
Referenced by main().
binomial()
double gpmp::stats::CDF::binomial (int k, int n, double p) static
Compute the cumulative distribution function (CDF) of the binomial distribution.
Parameters
k The number of successes
n The number of trials
p The probability of success in each trial
Returns
The CDF value at the given point
Definition at line 63 of file cdfs.cpp.
{
     if (k < 0)
         return 0.0;
     else if (k >= n)
         return 1.0;
     else
         return incomplete_beta(1.0 - p, n - k, k + 1);
 }
Referenced by main().
cauchy()
double gpmp::stats::CDF::cauchy (double x, double x0, double gamma) static
Compute the cumulative distribution function (CDF) of the Cauchy distribution.
Parameters
x The value at which to evaluate the CDF
x0 The location parameter of the Cauchy distribution
gamma The scale parameter of the Cauchy distribution
Returns
The CDF value at the given point
Definition at line 73 of file cdfs.cpp.
{
     return 0.5 + atan((x - x0) / gamma) / M_PI;
 }
Referenced by main().
chi_squared()
double gpmp::stats::CDF::chi_squared (double x, double k) static
Compute the cumulative distribution function (CDF) of the chi-squared distribution.
Parameters
x The value at which to evaluate the CDF
k The degrees of freedom parameter of the chi-squared distribution
Returns
The CDF value at the given point
Definition at line 78 of file cdfs.cpp.
{
     if (x < 0)
         return 0.0;
     else
         return incomplete_gamma(k / 2.0, x / 2.0);
 }
Referenced by main().
exponential()
double gpmp::stats::CDF::exponential (double x, double lambda) static
Compute the cumulative distribution function (CDF) of the exponential distribution.
Parameters
x The value at which to evaluate the CDF
lambda The rate parameter of the exponential distribution
Returns
The CDF value at the given point
Definition at line 86 of file cdfs.cpp.
{
     if (x < 0)
         return 0.0;
     else
         return 1.0 - exp(-lambda * x);
 }
Referenced by main().
f()
double gpmp::stats::CDF::f (double x, double df1, double df2) static
Compute the cumulative distribution function (CDF) of the F distribution.
Parameters
x The value at which to evaluate the CDF
df1 The numerator degrees of freedom parameter of the F distribution
df2 The denominator degrees of freedom parameter of the F distribution
Returns
The CDF value at the given point
Definition at line 94 of file cdfs.cpp.
{
     if (x <= 0)
         return 0.0;
     else
         return incomplete_beta(df1 / 2.0, df2 / 2.0, df1 / (df1 + df2 * x));
 }
Referenced by main().
gamma()
double gpmp::stats::CDF::gamma (double x, double shape, double scale) static
Compute the cumulative distribution function (CDF) of the gamma distribution.
Parameters
x The value at which to evaluate the CDF
shape The shape parameter of the gamma distribution
scale The scale parameter of the gamma distribution
Returns
The CDF value at the given point
Definition at line 102 of file cdfs.cpp.
{
     if (x < 0)
         return 0.0;
     else
         return incomplete_gamma(shape, x / scale);
 }
Referenced by main().
gaussian()
double gpmp::stats::CDF::gaussian (double x, double mu, double sigma) static
Compute the cumulative distribution function (CDF) of the normal (Gaussian) distribution.
Parameters
x The value at which to evaluate the CDF
mu The mean parameter of the normal distribution
sigma The standard deviation parameter of the normal distribution
Returns
The CDF value at the given point
Definition at line 147 of file cdfs.cpp.
{
     return 0.5 * (1 + erf((x - mu) / (sigma * sqrt(2))));
 }
Referenced by main().
incomplete_beta()
double gpmp::stats::CDF::incomplete_beta (double a, double b, double x) static
Compute the incomplete beta function.
Parameters
a The first parameter of the incomplete beta function
b The second parameter of the incomplete beta function
x The value at which to evaluate the incomplete beta function
Returns
The value of the incomplete beta function at the given point
Definition at line 201 of file cdfs.cpp.
{
     const int maxIterations = 1000;
     const double epsilon = 1e-12;
     double result = 0.0;
     double term = 1.0;
     for (int k = 0; k < maxIterations; ++k) {
         term *=
             (k == 0 ? 1.0
                     : (a + k - 1) * (b - k) / (a + b + k - 1) * x / (k + 1));
         result += term;
         if (std::abs(term) < epsilon * std::abs(result))
             break;
     }
     return result * std::pow(x, a) * std::pow(1 - x, b) / (a * std::beta(a, b));
 }
incomplete_gamma()
double gpmp::stats::CDF::incomplete_gamma (double a, double x) static
Compute the incomplete gamma function.
Parameters
a The shape parameter of the incomplete gamma function
x The value at which to evaluate the incomplete gamma function
Returns
The value of the incomplete gamma function at the given point
Definition at line 218 of file cdfs.cpp.
{
     const int maxIterations = 1000;
     const double epsilon = 1e-12;
     double result = 0.0;
     double term = 1.0;
     for (int k = 0; k < maxIterations; ++k) {
         term *= x / (a + k);
         result += term;
         if (std::abs(term) < epsilon * std::abs(result))
             break;
     }
     return exp(-x) * std::pow(x, a) * result / std::tgamma(a);
 }
inverse_gamma()
double gpmp::stats::CDF::inverse_gamma (double x, double shape, double scale) static
Compute the cumulative distribution function (CDF) of the inverse-gamma distribution.
Parameters
x The value at which to evaluate the CDF
shape The shape parameter of the inverse-gamma distribution
scale The scale parameter of the inverse-gamma distribution
Returns
The CDF value at the given point
Definition at line 110 of file cdfs.cpp.
{
     if (x <= 0)
         return 0.0;
     else
         return 1.0 - incomplete_gamma(shape, scale / x);
 }
Referenced by main().
inverse_gaussian()
double gpmp::stats::CDF::inverse_gaussian (double x, double mu, double lambda) static
Compute the cumulative distribution function (CDF) of the inverse-Gaussian distribution.
Parameters
x The value at which to evaluate the CDF
mu The mean parameter of the inverse-Gaussian distribution
lambda The shape parameter of the inverse-Gaussian distribution
Returns
The CDF value at the given point
Definition at line 118 of file cdfs.cpp.
{
     if (x <= 0)
         return 0.0;
     else
         return normal_cdf(sqrt(lambda / x) * (x / mu - 1.0));
 }
Referenced by main().
laplace()
double gpmp::stats::CDF::laplace (double x, double mu, double b) static
Compute the cumulative distribution function (CDF) of the Laplace distribution.
Parameters
x The value at which to evaluate the CDF
mu The location parameter of the Laplace distribution
b The scale parameter of the Laplace distribution
Returns
The CDF value at the given point
Definition at line 126 of file cdfs.cpp.
{
     if (x < mu)
         return 0.5 * exp((x - mu) / b);
     else
         return 1.0 - 0.5 * exp(-(x - mu) / b);
 }
Referenced by main().
log_normal()
double gpmp::stats::CDF::log_normal (double x, double mu, double sigma) static
Compute the cumulative distribution function (CDF) of the log-normal distribution.
Parameters
x The value at which to evaluate the CDF
mu The mean parameter of the log-normal distribution
sigma The standard deviation parameter of the log-normal distribution
Returns
The CDF value at the given point
Definition at line 139 of file cdfs.cpp.
{
     if (x <= 0)
         return 0.0;
     else
         return 0.5 + 0.5 * erf((log(x) - mu) / (sqrt(2.0) * sigma));
 }
Referenced by main().
logistic()
double gpmp::stats::CDF::logistic (double x, double mu, double s) static
Compute the cumulative distribution function (CDF) of the logistic distribution.
Parameters
x The value at which to evaluate the CDF
mu The location parameter of the logistic distribution
s The scale parameter of the logistic distribution
Returns
The CDF value at the given point
Definition at line 134 of file cdfs.cpp.
{
     return 1.0 / (1.0 + exp(-(x - mu) / s));
 }
Referenced by main().
normal_cdf()
double gpmp::stats::CDF::normal_cdf (double x) static
Compute the cumulative distribution function (CDF) of the standard normal distribution.
Parameters
x The value at which to evaluate the CDF
Returns
The CDF value at the given point
Definition at line 196 of file cdfs.cpp.
{
     return 0.5 * (1 + erf(x / sqrt(2.0)));
 }
poisson()
double gpmp::stats::CDF::poisson (int k, double lambda) static
Compute the cumulative distribution function (CDF) of the Poisson distribution.
Parameters
k The number of occurrences
lambda The rate parameter of the Poisson distribution
Returns
The CDF value at the given point
Definition at line 152 of file cdfs.cpp.
{
     if (k < 0)
         return 0.0;
     else
         return incomplete_gamma(k + 1, lambda);
 }
Referenced by main().
rademacher()
double gpmp::stats::CDF::rademacher (double x) static
Compute the cumulative distribution function (CDF) of the Rademacher distribution.
Parameters
x The value at which to evaluate the CDF
Returns
The CDF value at the given point
Definition at line 160 of file cdfs.cpp.
{
     if (x < 0)
         return 0.0;
     else if (x < 0.5)
         return 0.0;
     else
         return 1.0;
 }
Referenced by main().
student_t()
double gpmp::stats::CDF::student_t (double x, double df) static
Compute the cumulative distribution function (CDF) of Student's t distribution.
Parameters
x The value at which to evaluate the CDF
df The degrees of freedom parameter of Student's t distribution
Returns
The CDF value at the given point
Definition at line 170 of file cdfs.cpp.
{
     if (df <= 0)
         return NAN;
     return 0.5 + 0.5 * std::tgamma((df + 1) / 2) * std::hypot(1, x / sqrt(df)) /
                      (sqrt(df) * std::tgamma(df / 2));
 }
Referenced by main().
uniform()
double gpmp::stats::CDF::uniform (double x, double a, double b) static
Compute the cumulative distribution function (CDF) of the uniform distribution.
Parameters
x The value at which to evaluate the CDF
a The minimum value of the uniform distribution
b The maximum value of the uniform distribution
Returns
The CDF value at the given point
Definition at line 178 of file cdfs.cpp.
{
     if (x < a)
         return 0.0;
     else if (x < b)
         return (x - a) / (b - a);
     else
         return 1.0;
 }
Referenced by main().
weibull()
double gpmp::stats::CDF::weibull (double x, double shape, double scale) static
Compute the cumulative distribution function (CDF) of the Weibull distribution.
Parameters
x The value at which to evaluate the CDF
shape The shape parameter of the Weibull distribution
scale The scale parameter of the Weibull distribution
Returns
The CDF value at the given point
Definition at line 188 of file cdfs.cpp.
{
     if (x < 0)
         return 0.0;
     else
         return 1.0 - exp(-pow(x / scale, shape));
 }
Referenced by main().
The documentation for this class was generated from the following files:
include/openGPMP/stats/cdfs.hpp
modules/stats/cdfs.cpp