openMTPK: Cipher Class Reference
Cipher Class Reference
#include <cipher.hpp>
Public Member Functions
std::string C_cipher (std::string plaintext, int key)
std::string KC_encode (std::string key)
std::string KC_cipher (std::string plaintext, std::string encoded_text)
Detailed Description
Definition at line 14 of file cipher.hpp.
Member Function Documentation
C_cipher()
std::string Cipher::C_cipher (std::string plaintext, int key)
Definition at line 13 of file cipher.cpp.
{
     std::string hashtext = "";
     for (int i = 0; unsigned(i) < plaintext.length(); i++) {
         // inject transformation
         if (isupper(plaintext[i])) {
             // upper case
             hashtext += char(int(plaintext[i] + key - 65) % 26 + 65);
         }
         else {
             // lower case
             hashtext += char(int(plaintext[i] + key - 97) % 26 + 97);
         }
     }
     return hashtext;
 }
References Python.examples.cipher_ex::hashtext.
Referenced by main(), and anonymous_namespace{t_cipher.cpp}::TEST().
KC_cipher()
std::string Cipher::KC_cipher (std::string plaintext, std::string encoded_text)
Definition at line 66 of file cipher.cpp.
{
     std::string cipher = "";
     /*
      * This loop ciphered the message. Spaces, special characters
      * and numbers remain same.
      */
     for (int i = 0; unsigned(i) < plaintext.size(); i++) {
         if (plaintext[i] >= 'a' && plaintext[i] <= 'z') {
             int pos = plaintext[i] - 97;
             cipher += encoded_text[pos];
         }
         else if (plaintext[i] >= 'A' && plaintext[i] <= 'Z') {
             int pos = plaintext[i] - 65;
             cipher += encoded_text[pos];
         }
         else {
             cipher += plaintext[i];
         }
     }
     return cipher;
 }
References Python.examples.cipher_ex::encoded_text.
Referenced by main(), and anonymous_namespace{t_cipher.cpp}::TEST().
KC_encode()
std::string Cipher::KC_encode (std::string key)
Definition at line 31 of file cipher.cpp.
{
     std::string encoded = "";
     // This array represents the 26 letters of alphabets
     bool arr[26] = {0};
     // This loop inserts the keyword at the start of the encoded string
     for (int i = 0; unsigned(i) < key.size(); i++) {
         if(key[i] >= 'A' && key[i] <= 'Z') {
             /*
              * To check whether the character is inserted earlier
              * in the encoded string or not
              */
             if (arr[key[i]-65] == 0) {
                 encoded += key[i];
                 arr[key[i]-65] = 1;
             }
         }
         else if (key[i] >= 'a' && key[i] <= 'z') {
             if (arr[key[i] - 97] == 0) {
                 encoded += key[i] - 32;
                 arr[key[i] - 97] = 1;
             }
         }
     }
     // This loop inserts the remaining characters in the encoded string.
     for (int i = 0; i < 26; i++) {
         if(arr[i] == 0) {
             arr[i]=1;
             encoded += char(i + 65);
         }
     }
     return encoded;
 }
Referenced by main(), and anonymous_namespace{t_cipher.cpp}::TEST().
The documentation for this class was generated from the following files:
include/number_theory/cipher.hpp
modules/number_theory/cipher.cpp