openMTPK: Arith Class Reference
Arith Class Reference
Arithmetic Template Class. Each method is variadic taking 'n' params.
#include <arith.hpp>
Public Member Functions
template<typename T >
T add (T t)
Addition method.
template<typename T , typename... Ts>
auto add (T t, Ts... ts)
template<typename X >
X sub (X x)
Subtraction method.
template<typename X , typename... Xy>
auto sub (X x, Xy... xy)
template<typename W >
W mult (W w)
Multiplication method.
template<typename W , typename... Wv>
auto mult (W w, Wv... wv)
template<typename Z >
Z exp (Z z)
Exponentiation method.
template<typename Z , typename... Zy>
auto exp (Z z, Zy... zy)
Detailed Description
Arithmetic Template Class. Each method is variadic taking 'n' params.
Definition at line 18 of file arith.hpp.
Member Function Documentation
add() [1/2]
template<typename T > T Arith::add (T t) inline
Addition method.
Parameters
'n' addends
Returns
sum
Definition at line 27 of file arith.hpp.
{
             return t;
         }
Referenced by add().
add() [2/2]
template<typename T , typename... Ts> auto Arith::add (T t, Ts... ts) inline
Definition at line 31 of file arith.hpp.
{
             return t + add(ts...);
         }
References add().
exp() [1/2]
template<typename Z > Z Arith::exp (Z z) inline
Exponentiation method.
Parameters
base
'n' powers
Returns
product
Definition at line 71 of file arith.hpp.
{
             return z;
         }
Referenced by exp().
exp() [2/2]
template<typename Z , typename... Zy> auto Arith::exp (Z z, Zy... zy) inline
Definition at line 75 of file arith.hpp.
{
             return z *= exp(zy...);
         }
References exp().
mult() [1/2]
template<typename W > W Arith::mult (W w) inline
Multiplication method.
Parameters
'n' factors
Returns
product
Definition at line 56 of file arith.hpp.
{
             return w;
         }
Referenced by mult().
mult() [2/2]
template<typename W , typename... Wv> auto Arith::mult (W w, Wv... wv) inline
Definition at line 60 of file arith.hpp.
{
             return w * mult(wv...);
         }
References mult().
sub() [1/2]
template<typename X > X Arith::sub (X x) inline
Subtraction method.
Parameters
minuend
'n' subtrahends
Returns
difference
Definition at line 42 of file arith.hpp.
{
             return x;
         }
Referenced by sub().
sub() [2/2]
template<typename X , typename... Xy> auto Arith::sub (X x, Xy... xy) inline
Definition at line 46 of file arith.hpp.
{
             return x - sub(xy...);
         }
References sub().
The documentation for this class was generated from the following file:
include/arithmetic/arith.hpp