openMTPK: Primality Class Reference
Primality Class Reference
#include <primes.hpp>
Public Member Functions
bool is_prime (int n)
bool compute_miller_rabin (int d, int n)
bool miller_rabin_prime (int n, int iters)
void miller_rabin (int inters, int min_val, int max_val)
int jacobian_number (long long a, long long n)
bool solovoy_strassen (long long p, int iters)
long long int mod_pow (long long int base, long long int exponent, long long int mod)
bool carmichael_num (int n)
void sieve_of_eratosthenes (int n)
long long int pollard_rho (long long int n)
int ETF (unsigned int n)
Detailed Description
Definition at line 11 of file primes.hpp.
Member Function Documentation
carmichael_num()
bool Primality::carmichael_num (int n)
Definition at line 202 of file primes.cpp.
{
     for (int b = 2; b < n; b++) {
         // If "b" is relatively prime to n
         if (basics.rm_gcd(b, n) == 1)
             // And pow(b, n-1)%n is not 1, return false.
             if (mod_pow(b, n - 1, n) != 1)
                 return false;
     }
     return true;
 }
References Python.examples.arithmetic::b, basics, mod_pow(), and Basics::rm_gcd().
Referenced by R_swig_Primality_carmichael_num(), and anonymous_namespace{t_primes.cpp}::TEST().
compute_miller_rabin()
bool Primality::compute_miller_rabin (int d, int n)
Definition at line 54 of file primes.cpp.
{
     // Pick a random number in [2..n-2] Corner cases make sure that n > 4
     int a = 2 + rand() % (n - 4);
     // Compute a^d % n
     int x = mod_pow(a, d, n);
     if (x == 1  || x == n-1)
        return true;
     // Keep squaring x while one of the following doesn't
     // happen
     // (i)   d does not reach n-1
     // (ii)  (x^2) % n is not 1
     // (iii) (x^2) % n is not n-1
     while (d != n - 1) {
         x = (x * x) % n;
         d *= 2;
         if (x == 1)
             return false;
         if (x == n - 1)
             return true;
     }
     // Return composite
     return false;
 }
References mod_pow().
Referenced by miller_rabin_prime(), R_swig_Primality_compute_miller_rabin(), and anonymous_namespace{t_primes.cpp}::TEST().
ETF()
int Primality::ETF (unsigned int n)
Definition at line 319 of file primes.cpp.
{
     unsigned int result = 1;
     for (int index = 2; unsigned(index) < n; index++) {
         if (basics.rm_gcd(index, n) == 1) {
             result++;
         }
     }
     return result;
 }
References basics, and Basics::rm_gcd().
is_prime()
bool Primality::is_prime (int n)
Definition at line 39 of file primes.cpp.
{
     if (n <= 1)
         return false;
     // Check from 2 to n-1
     for (int iter = 2; iter < n; iter++)
         if (n % iter == 0)
             return false;
     return true;
 }
Referenced by R_swig_Primality_is_prime(), and anonymous_namespace{t_primes.cpp}::TEST().
jacobian_number()
int Primality::jacobian_number (long long a, long long n)
Definition at line 130 of file primes.cpp.
{
     if (!a)
         return 0;// (0/n) = 0
     int ans = 1;
     if (a < 0) {
         a = -a; // (a/n) = (-a/n)*(-1/n)
         if (n % 4 == 3)
             ans = -ans; // (-1/n) = -1 if n = 3 (mod 4)
     }
     if (a == 1)
         return ans;// (1/n) = 1
     while (a) {
         if (a < 0) {
             a = -a;// (a/n) = (-a/n)*(-1/n)
             if (n % 4 == 3)
                 ans = -ans;// (-1/n) = -1 if n = 3 (mod 4)
         }
         while (a % 2 == 0) {
             a = a / 2;
             if (n % 8 == 3 || n % 8 == 5)
                 ans = -ans;
         }
         std::swap(a, n);
         if (a % 4 == 3 && n % 4 == 3)
             ans = -ans;
         a = a % n;
         if (a > n / 2)
             a = a - n;
     }
     if (n == 1)
         return ans;
     return 0;
 }
Referenced by solovoy_strassen().
miller_rabin()
void Primality::miller_rabin (int inters, int min_val, int max_val)
Definition at line 110 of file primes.cpp.
{
     std::cout << "Primes between " << min_val <<
                 " and " << max_val << std::endl;
     //int d = iters - 1;
     //int min_val = minimum;
     //int max_val = maximum;
     // traverse from the min to max
     for (; min_val < max_val; min_val++) {
     //while (min_val < max_val) {
         if (miller_rabin_prime(min_val, iters)) {
             std::cout << min_val << " ";
         }
     }
     std::cout << "\n";
 }
References miller_rabin_prime().
miller_rabin_prime()
bool Primality::miller_rabin_prime (int n, int iters)
Definition at line 83 of file primes.cpp.
{
     /*
      * this method will return true if n is prime, iters will determine
      * accuracy
      */
     // these are corner cases
     if (n <= 1 || n == 4)
         return false;
     if (n <= 3)
         return true;
     // odd will represent an odd number
     int odd = n - 1;
     while (odd % 2 == 0) {
         odd /= 2;
     }
     // iterate given the iters paramater
     for (int i = 0; i < iters; i ++) {
         // compute using the Miller-Rabin method
         if (!compute_miller_rabin(odd, n)) {
             return false;
         }
     }
     return true;
 }
References compute_miller_rabin().
Referenced by miller_rabin(), R_swig_Primality_miller_rabin_prime(), and anonymous_namespace{t_primes.cpp}::TEST().
mod_pow()
long long int Primality::mod_pow (long long int base, long long int exponent, long long int mod)
Definition at line 21 of file primes.cpp.
{
     long long x = 1;
     long long y = base;
     while (exponent > 0) {
         if (exponent & 1) {
             x = (x * y) % mod;
         }
         exponent = exponent >> 1;
         y = (y * y) % mod;
     }
     return x;
 }
Referenced by carmichael_num(), compute_miller_rabin(), pollard_rho(), solovoy_strassen(), and anonymous_namespace{t_primes.cpp}::TEST().
pollard_rho()
long long int Primality::pollard_rho (long long int n)
Definition at line 258 of file primes.cpp.
{
     /* initialize random seed */
     srand (time(NULL));
     /* no prime divisor for 1 */
     if (n == 1)
         return n;
     /* even number means one of the divisors is 2 */
     if (n % 2 == 0)
         return 2;
     /* we will pick from the range [2, N) */
     long long int x = (rand() % (n - 2)) + 2;
     long long int y = x;
     /* the constant in f(x).
      * Algorithm can be re-run with a different c
      * if it throws failure for a composite. */
     long long int c = (rand() % (n - 1)) + 1;
     /* Initialize candidate divisor (or result) */
     long long int divisor = 1;
     /* until the prime factor isn't obtained.
        If n is prime, return n */
     while (divisor == 1) {
         /* Tortoise Move: x(i+1) = f(x(i)) */
         // take power
         // calculate modulus
         x = (mod_pow(x, 2, n) + c + n) % n;
         /* Hare Move: y(i+1) = f(f(y(i))) */
         y = (mod_pow(y, 2, n) + c + n) % n;
         y = (mod_pow(y, 2, n) + c + n) % n;
         /* check gcd of |x-y| and n */
         divisor = basics.rm_gcd(abs(x - y), n);
         //divisor = std::__gcd(abs(x - y), n);
         /* retry if the algorithm fails to find prime factor
          * with chosen x and c */
         if (divisor == n)
             return pollard_rho(n);
     }
     return divisor;
 }
References basics, Python.examples.cipher_ex::c, mod_pow(), and Basics::rm_gcd().
sieve_of_eratosthenes()
void Primality::sieve_of_eratosthenes (int n)
Definition at line 218 of file primes.cpp.
{
     // Create a boolean array "prime[0..n]" and initialize
     // all entries it as true. A value in prime[i] will
     // finally be false if i is Not a prime, else true.
     bool prime[n + 1];
     memset(prime, true, sizeof(prime));
     for (int p = 2; p * p <= n; p++) {
         // If prime[p] is not changed, then it is a prime
         if (prime[p] == true) {
             // Update all multiples of p greater than or
             // equal to the square of it numbers which are
             // multiple of p and are less than p^2 are
             // already been marked.
             for (int i = p * p; i <= n; i += p)
                 prime[i] = false;
         }
     }
     // Print all prime numbers
     for (int p = 2; p <= n; p++)
         if (prime[p])
             std::cout << p << " " << std::endl;
 }
References Python.examples.primes_ex::p.
solovoy_strassen()
bool Primality::solovoy_strassen (long long p, int iters)
Definition at line 178 of file primes.cpp.
{
     if (p < 2)
         return false;
     if (p != 2 && p % 2 == 0)
         return false;
     for (int i = 0; i < iters; i++) {
         // Generate a random number a
         long long a = rand() % (p - 1) + 1;
         long long jacobian = (p + jacobian_number(a, p)) % p;
         long long mod = mod_pow(a, (p - 1) / 2, p);
         if (!jacobian || mod != jacobian)
             return false;
     }
     return true;
 }
References jacobian_number(), mod_pow(), and Python.examples.primes_ex::p.
Referenced by anonymous_namespace{t_primes.cpp}::TEST().
The documentation for this class was generated from the following files:
include/number_theory/primes.hpp
modules/number_theory/primes.cpp