openGPMP: SigProc Class Reference
SigProc Class Reference
#include <sigproc.hpp>
Public Member Functions
SigProc (const std::vector< double > &signal)
Constructor Initializes the SigProc object with a signal.
double mean () const
Compute the mean value of the signal.
double stdev () const
Compute the standard deviation of the signal.
void lpf (double alpha)
Apply a simple low-pass filter to the signal.
void normalize ()
Normalize the signal to have zero mean and unit variance.
std::vector< double > get_sig () const
Get the processed signal.
std::complex< double > z_tform (const std::complex< double > &z) const
Compute the Z-transform of the signal.
std::complex< double > z_adv_tform (const std::complex< double > &z, int delay) const
Compute the Advanced Z-transform of the signal.
std::complex< double > z_matched_tform (const std::complex< double > &z, const std::vector< double > &referenceSignal) const
Compute the Matched Z-transform of the signal.
std::vector< double > bilinear_tform (double Ts) const
Compute the Bilinear Transform of the signal.
std::vector< double > bilinear_adv_tform (double Ts, int delay) const
Compute the Advanced Bilinear Transform of the signal.
std::vector< double > bilinear_matched_tform (double Ts, const std::vector< double > &referenceSignal) const
Compute the Matched Bilinear Transform of the signal.
std::vector< double > compute_constant_q_transform (double Q, double Ts) const
Compute the constant-Q transform of the signal.
std::vector< double > compute_inverse_constant_q_transform (double Q, double Ts) const
Compute the inverse constant-Q transform of the signal.
std::vector< double > compute_dct (size_t M) const
Compute the Discrete Cosine Transform (DCT) of the signal.
std::vector< double > compute_inverse_dct (size_t M) const
Compute the Inverse Discrete Cosine Transform (IDCT) of the signal.
std::vector< std::complex< double > > compute_dft () const
Compute the Discrete Fourier Transform (DFT) of the signal.
std::vector< double > compute_inverse_dft () const
Compute the Inverse Discrete Fourier Transform (IDFT) of the signal.
std::vector< double > compute_magnitude_spectrum () const
Compute the magnitude spectrum of the signal.
std::vector< double > compute_phase_spectrum () const
Compute the phase spectrum of the signal.
std::vector< std::complex< double > > compute_dtft (const std::vector< double > &omega) const
Compute the Discrete-time Fourier Transform (DTFT) of the signal.
std::vector< double > compute_inverse_dtft (const std::vector< double > &omega) const
Compute the Inverse Discrete-time Fourier Transform (IDTFT) of the signal.
std::vector< double > compute_dtft_magnitude_spectrum (const std::vector< double > &omega) const
Compute the magnitude spectrum of the DTFT of the signal.
std::vector< double > compute_dtft_phase_spectrum (const std::vector< double > &omega) const
Compute the phase spectrum of the DTFT of the signal.
std::vector< double > design_discrete_system (const std::vector< double > &analog_system_coefficients, double sampling_rate)
Design a discrete-time system using the impulse invariance method.
std::vector< double > impulse_invariance_transform (const std::vector< double > &analog_signal, double analog_sampling_rate, double discrete_sampling_rate)
Apply the impulse invariance method to transform an analog signal to discrete time.
Private Attributes
std::vector< double > signal_
Detailed Description
Definition at line 41 of file sigproc.hpp.
Constructor & Destructor Documentation
SigProc()
SigProc::SigProc (const std::vector< double > & signal) explicit
Constructor Initializes the SigProc object with a signal.
Parameters
signal The input signal
Definition at line 39 of file sigproc.cpp.
                                                 : signal_(signal) {
 }
Member Function Documentation
bilinear_adv_tform()
std::vector< double > SigProc::bilinear_adv_tform (double Ts, int delay) const
Compute the Advanced Bilinear Transform of the signal.
Parameters
Ts Sampling period
delay Delay parameter for the Advanced Bilinear Transform
Returns
The Advanced Bilinear Transform of the signal
Definition at line 131 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(N);
     for (size_t n = 0; n < N; ++n) {
         double t = static_cast<double>(n - delay) * Ts;
         result[n] = signal_[n] / (1.0 + t);
     }
     return result;
 }
References N, and signal_.
bilinear_matched_tform()
std::vector< double > SigProc::bilinear_matched_tform (double Ts, const std::vector< double > & referenceSignal) const
Compute the Matched Bilinear Transform of the signal.
Parameters
Ts Sampling period
referenceSignal Reference signal for the Matched Bilinear Transform
Returns
The Matched Bilinear Transform of the signal
Definition at line 143 of file sigproc.cpp.
{
     if (signal_.size() != referenceSignal.size()) {
         throw std::invalid_argument(
             "Error: Signal and reference signal must have the same size.");
     }
     size_t N = signal_.size();
     std::vector<double> result(N);
     for (size_t n = 0; n < N; ++n) {
         double t = static_cast<double>(n) * Ts;
         result[n] = signal_[n] * referenceSignal[n] / (1.0 + t);
     }
     return result;
 }
References N, and signal_.
bilinear_tform()
std::vector< double > SigProc::bilinear_tform (double Ts) const
Compute the Bilinear Transform of the signal.
Parameters
Ts Sampling period
Returns
The Bilinear Transform of the signal
Definition at line 119 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(N);
     for (size_t n = 0; n < N; ++n) {
         double t = static_cast<double>(n) * Ts;
         result[n] = signal_[n] / (1.0 + t);
     }
     return result;
 }
References N, and signal_.
compute_constant_q_transform()
std::vector< double > SigProc::compute_constant_q_transform (double Q, double Ts) const
Compute the constant-Q transform of the signal.
Parameters
Q Quality factor
Ts Sampling period
Returns
The constant-Q transform of the signal
Definition at line 162 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(N);
     for (size_t n = 0; n < N; ++n) {
         double t = static_cast<double>(n) * Ts;
         result[n] = signal_[n] * std::exp(-2.0 * M_PI * Q * t);
     }
     return result;
 }
References N, and signal_.
compute_dct()
std::vector< double > SigProc::compute_dct (size_t M) const
Compute the Discrete Cosine Transform (DCT) of the signal.
Parameters
M Number of coefficients (non-negative integer)
Returns
The DCT of the signal
Definition at line 188 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(M, 0.0);
     for (size_t m = 0; m < M; ++m) {
         double sum = 0.0;
         double coef = (m == 0) ? 1.0 / std::sqrt(2.0) : 1.0;
         for (size_t n = 0; n < N; ++n) {
             double theta = (M_PI * m * (2.0 * n + 1)) / (2.0 * N);
             sum += signal_[n] * std::cos(theta);
         }
         result[m] = coef * sum;
     }
     return result;
 }
References N, and signal_.
compute_dft()
std::vector< std::complex< double > > SigProc::compute_dft () const
Compute the Discrete Fourier Transform (DFT) of the signal.
Returns
The DFT of the signal
Definition at line 226 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<std::complex<double>> result(N, 0.0);
     for (size_t k = 0; k < N; ++k) {
         for (size_t n = 0; n < N; ++n) {
             double theta = -2.0 * M_PI * k * n / N;
             result[k] += signal_[n] * std::polar(1.0, theta);
         }
     }
     return result;
 }
References N, and signal_.
Referenced by compute_magnitude_spectrum(), and compute_phase_spectrum().
compute_dtft()
std::vector< std::complex< double > > SigProc::compute_dtft (const std::vector< double > & omega) const
Compute the Discrete-time Fourier Transform (DTFT) of the signal.
Parameters
omega Frequency values at which to compute the DTFT
Returns
The DTFT of the signal at the specified frequencies
Definition at line 279 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<std::complex<double>> result(omega.size(), 0.0);
     for (size_t w = 0; w < omega.size(); ++w) {
         for (size_t n = 0; n < N; ++n) {
             double theta = -omega[w] * n;
             result[w] += signal_[n] * std::polar(1.0, theta);
         }
     }
     return result;
 }
References N, and signal_.
Referenced by compute_dtft_magnitude_spectrum(), and compute_dtft_phase_spectrum().
compute_dtft_magnitude_spectrum()
std::vector< double > SigProc::compute_dtft_magnitude_spectrum (const std::vector< double > & omega) const
Compute the magnitude spectrum of the DTFT of the signal.
Parameters
omega Frequency values at which to compute the DTFT
Returns
The magnitude spectrum of the DTFT
Definition at line 308 of file sigproc.cpp.
{
     auto dtft_result = compute_dtft(omega);
     std::vector<double> magnitude_spectrum(dtft_result.size(), 0.0);
     for (size_t w = 0; w < dtft_result.size(); ++w) {
         magnitude_spectrum[w] = std::abs(dtft_result[w]);
     }
     return magnitude_spectrum;
 }
References compute_dtft().
compute_dtft_phase_spectrum()
std::vector< double > SigProc::compute_dtft_phase_spectrum (const std::vector< double > & omega) const
Compute the phase spectrum of the DTFT of the signal.
Parameters
omega Frequency values at which to compute the DTFT
Returns
The phase spectrum of the DTFT
Definition at line 321 of file sigproc.cpp.
{
     auto dtft_result = compute_dtft(omega);
     std::vector<double> phase_spectrum(dtft_result.size(), 0.0);
     for (size_t w = 0; w < dtft_result.size(); ++w) {
         phase_spectrum[w] = std::arg(dtft_result[w]);
     }
     return phase_spectrum;
 }
References compute_dtft().
compute_inverse_constant_q_transform()
std::vector< double > SigProc::compute_inverse_constant_q_transform (double Q, double Ts) const
Compute the inverse constant-Q transform of the signal.
Parameters
Q Quality factor
Ts Sampling period
Returns
The inverse constant-Q transform of the signal
Definition at line 176 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(N);
     for (size_t n = 0; n < N; ++n) {
         double t = static_cast<double>(n) * Ts;
         result[n] = signal_[n] * std::exp(2.0 * M_PI * Q * t);
     }
     return result;
 }
References N, and signal_.
compute_inverse_dct()
std::vector< double > SigProc::compute_inverse_dct (size_t M) const
Compute the Inverse Discrete Cosine Transform (IDCT) of the signal.
Parameters
M Number of coefficients (non-negative integer)
Returns
The IDCT of the signal
Definition at line 207 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(N, 0.0);
     for (size_t n = 0; n < N; ++n) {
         double sum = 0.0;
         for (size_t m = 0; m < M; ++m) {
             double coef = (m == 0) ? 1.0 / std::sqrt(2.0) : 1.0;
             double theta = (M_PI * m * (2.0 * n + 1)) / (2.0 * N);
             sum += coef * signal_[m] * std::cos(theta);
         }
         result[n] = sum;
     }
     return result;
 }
References N, and signal_.
compute_inverse_dft()
std::vector< double > SigProc::compute_inverse_dft () const
Compute the Inverse Discrete Fourier Transform (IDFT) of the signal.
Returns
The IDFT of the signal
Definition at line 240 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(N, 0.0);
     for (size_t n = 0; n < N; ++n) {
         for (size_t k = 0; k < N; ++k) {
             double theta = 2.0 * M_PI * k * n / N;
             result[n] += std::real(signal_[k] * std::polar(1.0, theta));
         }
         result[n] /= N;
     }
     return result;
 }
References N, and signal_.
compute_inverse_dtft()
std::vector< double > SigProc::compute_inverse_dtft (const std::vector< double > & omega) const
Compute the Inverse Discrete-time Fourier Transform (IDTFT) of the signal.
Parameters
omega Frequency values at which to compute the IDTFT
Returns
The IDTFT of the signal at the specified frequencies
Definition at line 294 of file sigproc.cpp.
{
     size_t N = signal_.size();
     std::vector<double> result(omega.size(), 0.0);
     for (size_t w = 0; w < omega.size(); ++w) {
         for (size_t n = 0; n < N; ++n) {
             double theta = omega[w] * n;
             result[w] += std::real(signal_[n] * std::polar(1.0, theta));
         }
     }
     return result;
 }
References N, and signal_.
compute_magnitude_spectrum()
std::vector< double > SigProc::compute_magnitude_spectrum () const
Compute the magnitude spectrum of the signal.
Returns
The magnitude spectrum
Definition at line 256 of file sigproc.cpp.
{
     auto dft_result = compute_dft();
     std::vector<double> magnitude_spectrum(dft_result.size(), 0.0);
     for (size_t k = 0; k < dft_result.size(); ++k) {
         magnitude_spectrum[k] = std::abs(dft_result[k]);
     }
     return magnitude_spectrum;
 }
References compute_dft().
compute_phase_spectrum()
std::vector< double > SigProc::compute_phase_spectrum () const
Compute the phase spectrum of the signal.
Returns
The phase spectrum
Definition at line 267 of file sigproc.cpp.
{
     auto dft_result = compute_dft();
     std::vector<double> phase_spectrum(dft_result.size(), 0.0);
     for (size_t k = 0; k < dft_result.size(); ++k) {
         phase_spectrum[k] = std::arg(dft_result[k]);
     }
     return phase_spectrum;
 }
References compute_dft().
design_discrete_system()
std::vector< double > SigProc::design_discrete_system (const std::vector< double > & analog_system_coefficients, double sampling_rate)
Design a discrete-time system using the impulse invariance method.
Parameters
analog_system_coefficients Coefficients of the analog system
sampling_rate Sampling rate of the discrete-time system
Returns
Coefficients of the discrete-time system
Definition at line 332 of file sigproc.cpp.
{
     // Design a discrete-time system using impulse invariance method
     size_t order = analog_system_coefficients.size() - 1;
     std::vector<double> discrete_system_coefficients(order + 1, 0.0);
     // Impulse invariance transformation
     for (size_t k = 0; k <= order; ++k) {
         double ak = analog_system_coefficients[k];
         for (size_t n = 0; n <= order; ++n) {
             discrete_system_coefficients[n] +=
                 ak * std::sin(2 * M_PI * n * sampling_rate / 2.0) / (M_PI * n);
         }
     }
     return discrete_system_coefficients;
 }
get_sig()
std::vector< double > SigProc::get_sig () const
Get the processed signal.
Returns
The processed signal
Definition at line 82 of file sigproc.cpp.
{
     return signal_;
 }
References signal_.
impulse_invariance_transform()
std::vector< double > SigProc::impulse_invariance_transform (const std::vector< double > & analog_signal, double analog_sampling_rate, double discrete_sampling_rate)
Apply the impulse invariance method to transform an analog signal to discrete time.
Parameters
analog_signal Analog signal to be transformed
analog_sampling_rate Sampling rate of the analog signal
discrete_sampling_rate Sampling rate of the discrete-time system
Returns
Discrete-time signal after transformation
Definition at line 352 of file sigproc.cpp.
{
     size_t M = analog_signal.size();
     std::vector<double> discrete_signal(M, 0.0);
     // Impulse invariance transformation
     for (size_t m = 0; m < M; ++m) {
         double t = m / analog_sampling_rate;
         double sum = 0.0;
         for (size_t n = 0; n < M; ++n) {
             sum += analog_signal[n] *
                    std::sin(M_PI * discrete_sampling_rate *
                             (t - n / discrete_sampling_rate)) /
                    (M_PI * (t - n / discrete_sampling_rate));
         }
         discrete_signal[m] = sum;
     }
     return discrete_signal;
 }
lpf()
void SigProc::lpf (double alpha)
Apply a simple low-pass filter to the signal.
Parameters
alpha Filter coefficient (0 < alpha < 1)
Definition at line 62 of file sigproc.cpp.
{
     if (alpha <= 0.0 || alpha >= 1.0) {
         throw std::invalid_argument(
             "Error: Alpha must be in the range (0, 1).");
     }
     for (size_t i = 1; i < signal_.size(); ++i) {
         signal_[i] = alpha * signal_[i] + (1 - alpha) * signal_[i - 1];
     }
 }
References signal_.
mean()
double SigProc::mean () const
Compute the mean value of the signal.
Returns
The mean value
Definition at line 42 of file sigproc.cpp.
{
     double sum = 0.0;
     for (const auto &value : signal_) {
         sum += value;
     }
     return sum / static_cast<double>(signal_.size());
 }
References signal_.
Referenced by normalize(), and stdev().
normalize()
void SigProc::normalize ()
Normalize the signal to have zero mean and unit variance.
Definition at line 73 of file sigproc.cpp.
{
     double mn = mean();
     double stdDev = stdev();
     for (auto &value : signal_) {
         value = (value - mn) / stdDev;
     }
 }
References mean(), signal_, and stdev().
stdev()
double SigProc::stdev () const
Compute the standard deviation of the signal.
Returns
The standard deviation
Definition at line 50 of file sigproc.cpp.
{
     double mn = mean();
     double sumSquaredDiff = 0.0;
     for (const auto &value : signal_) {
         double diff = value - mn;
         sumSquaredDiff += diff * diff;
     }
     return std::sqrt(sumSquaredDiff / static_cast<double>(signal_.size()));
 }
References mean(), and signal_.
Referenced by normalize().
z_adv_tform()
std::complex< double > SigProc::z_adv_tform (const std::complex< double > & z, int delay) const
Compute the Advanced Z-transform of the signal.
Parameters
z Complex number representing the Z-transform variable
delay Delay parameter for the Advanced Z-transform
Returns
The Advanced Z-transform of the signal
Definition at line 94 of file sigproc.cpp.
{
     std::complex<double> result = 0.0;
     for (size_t n = 0; n < signal_.size(); ++n) {
         result += signal_[n] * std::pow(z, -static_cast<double>(n - delay));
     }
     return result;
 }
References signal_.
z_matched_tform()
std::complex< double > SigProc::z_matched_tform (const std::complex< double > & z, const std::vector< double > & referenceSignal) const
Compute the Matched Z-transform of the signal.
Parameters
z Complex number representing the Z-transform variable
referenceSignal Reference signal for the Matched Z-transform
Returns
The Matched Z-transform of the signal
Definition at line 104 of file sigproc.cpp.
{
     if (signal_.size() != referenceSignal.size()) {
         throw std::invalid_argument(
             "Error: Signal and reference signal must have the same size.");
     }
     std::complex<double> result = 0.0;
     for (size_t n = 0; n < signal_.size(); ++n) {
         result += signal_[n] * referenceSignal[n] *
                   std::pow(z, -static_cast<double>(n));
     }
     return result;
 }
References signal_.
z_tform()
std::complex< double > SigProc::z_tform (const std::complex< double > & z) const
Compute the Z-transform of the signal.
Parameters
z Complex number representing the Z-transform variable
Returns
The Z-transform of the signal
Definition at line 86 of file sigproc.cpp.
{
     std::complex<double> result = 0.0;
     for (size_t n = 0; n < signal_.size(); ++n) {
         result += signal_[n] * std::pow(z, -static_cast<double>(n));
     }
     return result;
 }
References signal_.
Member Data Documentation
signal_
std::vector<double> SigProc::signal_ private
Definition at line 243 of file sigproc.hpp.
Referenced by bilinear_adv_tform(), bilinear_matched_tform(), bilinear_tform(), compute_constant_q_transform(), compute_dct(), compute_dft(), compute_dtft(), compute_inverse_constant_q_transform(), compute_inverse_dct(), compute_inverse_dft(), compute_inverse_dtft(), get_sig(), lpf(), mean(), normalize(), stdev(), z_adv_tform(), z_matched_tform(), and z_tform().
The documentation for this class was generated from the following files:
include/linalg/sigproc.hpp
modules/linalg/sigproc.cpp