openGPMP: gpmp::PrimalityTest Class Reference
gpmp::PrimalityTest Class Reference
#include <prime_test.hpp>
Public Member Functions
bool is_prime (uint64_t n)
Determine if an integer is prime.
bool compute_miller_rabin (uint64_t d, uint64_t n)
Algorithm determining liklihood a number is prime.
bool miller_rabin_prime (uint64_t n, uint64_t iters)
Modified primes algorithm.
void miller_rabin (uint64_t iters, uint64_t min_val, uint64_t max_val)
Miller-Rabin driver, prints values that satisfy conditions.
bool witness (uint64_t n, uint64_t d, uint64_t a, uint64_t s)
bool AKS (uint64_t n)
uint64_t jacobian_number (uint64_t a, uint64_t n)
bool solovoy_strassen (uint64_t p, uint64_t iters)
uint64_t mod_mul (uint64_t a, uint64_t b, uint64_t m)
uint64_t mod_pow (uint64_t a, uint64_t b, uint64_t m)
bool carmichael_num (uint64_t n)
uint64_t ETF (uint64_t n)
Detailed Description
Primality Class dealing with prime number manipulations
Examples
primes.cpp.
Definition at line 50 of file prime_test.hpp.
Member Function Documentation
AKS()
bool gpmp::PrimalityTest::AKS (uint64_t n)
Definition at line 228 of file prime_test.cpp.
{
     // Check if n is a perfect power
     for (uint64_t b = 2; b <= std::sqrt(n); b++) {
         uint64_t a = std::round(std::pow(n, 1.0 / b));
         if (std::pow(a, b) == n) {
             return false;
         }
     }
     // Find the smallest r such that ord_r(n) > log2(n)^2
     uint64_t r = 2;
     while (r < n) {
         bool is_coprime = true;
         for (uint64_t i = 2; i <= std::sqrt(r); i++) {
             if (r % i == 0 && n % i == 0) {
                 is_coprime = false;
                 break;
             }
         }
         if (is_coprime) {
             uint64_t t = 1;
             for (uint64_t i = 0; i < std::floor(2 * std::log2(n)); i++) {
                 t = (t * r) % n;
             }
             if (t == 1) {
                 r++;
                 continue;
             }
             bool is_prime = true;
             for (uint64_t i = 0; i < std::floor(std::log2(n)); i++) {
                 t = (t * t) % n;
                 if (t == 1) {
                     is_prime = false;
                     break;
                 }
             }
             if (is_prime) {
                 return true;
             }
         }
         r++;
     }
     return false;
 }
carmichael_num()
bool gpmp::PrimalityTest::carmichael_num (uint64_t n)
Examples
primes.cpp.
Definition at line 349 of file prime_test.cpp.
{
     for (uint64_t b = 2; b < n; b++) {
         // If "b" is relatively prime to n
         if (ba.op_gcd(b, n) == 1)
             // And pow(b, n-1)%n is not 1, return false.
             if (mod_pow(b, n - 1, n) != 1)
                 return false;
     }
     return true;
 }
References ba, and gpmp::Basics::op_gcd().
Referenced by main().
compute_miller_rabin()
bool gpmp::PrimalityTest::compute_miller_rabin (uint64_t d, uint64_t n)
Algorithm determining liklihood a number is prime.
Parameters
[in] d : target number (uint64_t)
[in] n : target - 1 (uint64_t)
Precondition
miller_rabin_prime()
Returns
true/false (bool)
Definition at line 121 of file prime_test.cpp.
{
     // Pick a random number in [2..n-2] Corner cases make sure that n
     // > 4
 #ifdef __APPLE__
     std::random_device rd;
     std::mt19937 gen(rd());
     std::uniform_int_distribution<uint64_t> dist(2, n - 3);
     uint64_t a = dist(gen);
 #else
     uint64_t a = 2 + rand() % (n - 4);
 #endif
     /*
     std::random_device rd;
     std::mt19937_64 gen(rd());
     std::uniform_int_distribution<uint64_t> dis(2, n - 4);
     uint64_t a = dis(gen);
     */
     // Compute a^d % n
     uint64_t x = mod_pow(a, d, n);
     if (x == 1 || x == n - 1) {
         return true;
     }
     // Keep squaring x while one of the following doesn't
     // happen
     // (I)   d does not reach n-1
     // (II)  (x^2) % n is not 1
     // (III) (x^2) % n is not n-1
     while (d != n - 1) {
         x = (x * x) % n;
         d *= 2;
         if (x == 1) {
             return false;
         }
         if (x == n - 1) {
             return true;
         }
     }
     // Return composite
     return false;
 }
ETF()
uint64_t gpmp::PrimalityTest::ETF (uint64_t n)
Definition at line 408 of file prime_test.cpp.
{
     uint64_t result = 1;
     for (uint64_t index = 2; uint64_t(index) < n; index++) {
         if (ba.op_gcd(index, n) == 1) {
             result++;
         }
     }
     return result;
 }
References ba, and gpmp::Basics::op_gcd().
is_prime()
bool gpmp::PrimalityTest::is_prime (uint64_t n)
Determine if an integer is prime.
Parameters
[in] n : any number (uint64_t)
Returns
: true/false (bool)
Examples
primes.cpp.
Definition at line 104 of file prime_test.cpp.
{
     if (n <= 1) {
         return false;
     }
     // Check from 2 to n-1
     for (uint64_t iter = 2; iter < n; iter++) {
         if (n % iter == 0) {
             return false;
         }
     }
     return true;
 }
Referenced by main().
jacobian_number()
uint64_t gpmp::PrimalityTest::jacobian_number (uint64_t a, uint64_t n)
Definition at line 276 of file prime_test.cpp.
{
     if (!a)
         return 0; // (0/n) = 0
     uint64_t ans = 1;
     if (a < 0) {
         a = -a; // (a/n) = (-a/n)*(-1/n)
         if (n % 4 == 3)
             ans = -ans; // (-1/n) = -1 if n = 3 (mod 4)
     }
     if (a == 1)
         return ans; // (1/n) = 1
     while (a) {
         if (a < 0) {
             a = -a; // (a/n) = (-a/n)*(-1/n)
             if (n % 4 == 3)
                 ans = -ans; // (-1/n) = -1 if n = 3 (mod 4)
         }
         while (a % 2 == 0) {
             a = a / 2;
             if (n % 8 == 3 || n % 8 == 5)
                 ans = -ans;
         }
         std::swap(a, n);
         if (a % 4 == 3 && n % 4 == 3)
             ans = -ans;
         a = a % n;
         if (a > n / 2)
             a = a - n;
     }
     if (n == 1)
         return ans;
     return 0;
 }
miller_rabin()
void gpmp::PrimalityTest::miller_rabin (uint64_t iters, uint64_t min_val, uint64_t max_val)
Miller-Rabin driver, prints values that satisfy conditions.
Note
Finds the primes in a given range
Parameters
[in] iters : iterations determine accuracy (uint64_t)
[in] min_val : bottom end of range (uint64_t)
[in] max_val : top end of range (uint64_t)
[out] result : values within range that satisfy
Returns
Void
Examples
primes.cpp.
Definition at line 209 of file prime_test.cpp.
{
     std::cout << "Primes between " << min_val << " and " << max_val
               << std::endl;
     // int d = iters - 1;
     // int min_val = minimum;
     // int max_val = maximum;
     // traverse from the min to max
     for (; min_val < max_val; min_val++) {
         // while (min_val < max_val) {
         if (miller_rabin_prime(min_val, iters)) {
             std::cout << min_val << " ";
         }
     }
     std::cout << "\n";
 }
Referenced by main().
miller_rabin_prime()
bool gpmp::PrimalityTest::miller_rabin_prime (uint64_t n, uint64_t iters = 10)
Modified primes algorithm.
Parameters
[in] n : target number (uint64_t)
[in] iters : iterations determine accuracy (uint64_t)
Precondition
miller_rabin()
return true/false (bool)
Examples
primes.cpp.
Definition at line 185 of file prime_test.cpp.
{
     if (n < 2) {
         return false;
     }
     if (n == 2 || n == 3) {
         return true;
     }
     if (n % 2 == 0) {
         return false;
     }
     uint64_t d = n - 1, s = 0;
     while (d % 2 == 0) {
         d /= 2;
         s++;
     }
     for (uint64_t i = 0; i < iters; i++) {
         uint64_t a = rand() % (n - 3) + 2;
         if (witness(n, d, a, s)) {
             return false;
         }
     }
     return true;
 }
Referenced by main(), testing_miller(), and testing_new_miller().
mod_mul()
uint64_t gpmp::PrimalityTest::mod_mul (uint64_t a, uint64_t b, uint64_t m)
Definition at line 61 of file prime_test.cpp.
{
     uint64_t res = 0;
     while (b > 0) {
         if (b & 1) {
             res = (res + a) % m;
         }
         a = (2 * a) % m;
         b >>= 1;
     }
     return res;
 }
References python.linalg::res.
mod_pow()
uint64_t gpmp::PrimalityTest::mod_pow (uint64_t a, uint64_t b, uint64_t m)
Examples
primes.cpp.
Definition at line 74 of file prime_test.cpp.
{
     uint64_t res = 1;
     a %= m;
     while (b > 0) {
         if (b & 1) {
             res = mod_mul(res, a, m);
         }
         a = mod_mul(a, a, m);
         b >>= 1;
     }
     return res;
 }
References python.linalg::res.
Referenced by gpmp::Logarithms::BSGS(), main(), and gpmp::Factorization::pollard_rho().
solovoy_strassen()
bool gpmp::PrimalityTest::solovoy_strassen (uint64_t p, uint64_t iters)
Examples
primes.cpp.
Definition at line 325 of file prime_test.cpp.
{
     if (p < 2)
         return false;
     if (p != 2 && p % 2 == 0)
         return false;
     for (uint64_t i = 0; i < iters; i++) {
         // Generate a random number a
         uint64_t a = rand() % (p - 1) + 1;
         uint64_t jacobian = (p + jacobian_number(a, p)) % p;
         uint64_t mod = mod_pow(a, (p - 1) / 2, p);
         if (!jacobian || mod != jacobian)
             return false;
     }
     return true;
 }
Referenced by main().
witness()
bool gpmp::PrimalityTest::witness (uint64_t n, uint64_t d, uint64_t a, uint64_t s)
Definition at line 168 of file prime_test.cpp.
{
     uint64_t x = mod_pow(a, d, n);
     if (x == 1 || x == n - 1) {
         return false;
     }
     for (uint64_t r = 1; r < s; r++) {
         x = mod_mul(x, x, n);
         if (x == n - 1) {
             return false;
         }
     }
     return true;
 }
The documentation for this class was generated from the following files:
include/nt/prime_test.hpp
modules/nt/prime_test.cpp