openGPMP: gpmp::core::Logger Class Reference
gpmp::core::Logger Class Reference
#include <utils.hpp>
Public Member Functions
Logger (LogLevel level=INFO, bool useTimestamp=true)
Constructs a Logger instance.
~Logger ()
Logger destructor, destroys the Logger instance.
void setLogLevel (LogLevel level)
Sets the minimum log level.
void enableTimestamps (bool enable)
Enables or disables timestamps in log messages.
void setLogDestination (LogDestination destination)
Sets the log destination.
void setLogFile (const std::string &logFile)
Sets the log file name for FILE_ONLY or CONSOLE_AND_FILE destinations.
void log (LogLevel level, const std::string &message)
Logs a message with the specified log level.
Private Member Functions
std::string getLogPrefix (LogLevel level)
Gets the log prefix based on the log level.
std::string getCurrentTimestamp ()
Gets the current timestamp as a string.
std::string formatLogMessage (const std::string &prefix, const std::string &message)
Formats a log message with a specified prefix.
Private Attributes
LogLevel logLevel
The minimum log level to record.
bool enableTimestamp
Flag indicating whether to include timestamps in log messages.
LogDestination logDestination
The log destination, which can be CONSOLE, FILE_ONLY, or CONSOLE_AND_FILE.
bool logToFile
Flag indicating whether to log messages to a file.
std::ofstream logFileStream
The output stream for logging to a file.
Detailed Description
Definition at line 97 of file utils.hpp.
Constructor & Destructor Documentation
Logger()
gpmp::core::Logger::Logger (LogLevel level = INFO, bool useTimestamp = true)
Constructs a Logger instance.
Parameters
level The minimum log level to record.
useTimestamp Whether to include timestamps in log messages (default: true).
destination The log destination, which can be CONSOLE, FILE_ONLY, or CONSOLE_AND_FILE (default: CONSOLE).
logFile The name of the log file (if destination is FILE_ONLY or CONSOLE_AND_FILE).
Definition at line 47 of file utils.cpp.
     : logLevel(level), enableTimestamp(useTimestamp), logDestination(CONSOLE),
       logToFile(false) {
 }
~Logger()
gpmp::core::Logger::~Logger ()
Logger destructor, destroys the Logger instance.
Definition at line 52 of file utils.cpp.
{
     if (logToFile) {
         logFileStream.close();
     }
 }
Member Function Documentation
enableTimestamps()
void gpmp::core::Logger::enableTimestamps (bool enable)
Enables or disables timestamps in log messages.
Parameters
enable True to enable timestamps, false to disable.
Definition at line 62 of file utils.cpp.
{
     enableTimestamp = enable;
 }
formatLogMessage()
std::string gpmp::core::Logger::formatLogMessage (const std::string & prefix, const std::string & message) private
Formats a log message with a specified prefix.
Parameters
prefix The log message prefix.
message The log message content.
Returns
The formatted log message as a string.
Definition at line 126 of file utils.cpp.
{
     std::string logMessage = prefix + " " + message;
     if (enableTimestamp) {
         logMessage = getCurrentTimestamp() + " " + logMessage;
     }
     return logMessage;
 }
getCurrentTimestamp()
std::string gpmp::core::Logger::getCurrentTimestamp () private
Gets the current timestamp as a string.
Returns
A string representing the current timestamp.
Definition at line 111 of file utils.cpp.
{
     auto now = std::chrono::system_clock::now();
     auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                   now.time_since_epoch()) %
               1000;
     std::time_t nowTime = std::chrono::system_clock::to_time_t(now);
     std::tm tm = *std::localtime(&nowTime);
     std::ostringstream oss;
     oss << std::put_time(&tm, "%H:%M:%S") << '.' << std::setfill('0')
         << std::setw(3) << ms.count();
     return oss.str();
 }
getLogPrefix()
std::string gpmp::core::Logger::getLogPrefix (LogLevel level) private
Gets the log prefix based on the log level.
Parameters
level The log level.
Returns
A string representing the log prefix.
Definition at line 96 of file utils.cpp.
{
     switch (level) {
     case DEBUG:
         return "[DEBUG]";
     case INFO:
         return "[INFO]";
     case WARNING:
         return "[WARN]";
     case ERROR:
         return "[ERR]";
     default:
         return "[UNKN]";
     }
 }
References DEBUG, ERROR, INFO, and WARNING.
log()
void gpmp::core::Logger::log (LogLevel level, const std::string & message)
Logs a message with the specified log level.
Parameters
level The log level of the message.
message The message to log.
Definition at line 78 of file utils.cpp.
{
     if (level >= logLevel) {
         std::string prefix = getLogPrefix(level);
         std::string logMessage = formatLogMessage(prefix, message);
         if (logDestination == CONSOLE || logDestination == CONSOLE_AND_FILE) {
             if (level == ERROR) {
                 std::cerr << logMessage << std::endl;
             } else {
                 std::cout << logMessage << std::endl;
             }
         }
         if (logDestination != CONSOLE && logToFile && logFileStream.is_open()) {
             logFileStream << logMessage << std::endl;
         }
     }
 }
References CONSOLE, CONSOLE_AND_FILE, and ERROR.
Referenced by gpmp::ml::LinearRegression::best_fit(), gpmp::core::DataTable::csv_read(), gpmp::core::DataTable::datetime(), gpmp::ml::LinearRegression::get_input(), gpmp::core::DataTable::group_by(), gpmp::core::DataTable::inferType(), gpmp::core::DataTable::native_type(), gpmp::ml::LinearRegression::r_sqrd(), gpmp::ml::LinearRegression::split_data(), and test_train().
setLogDestination()
void gpmp::core::Logger::setLogDestination (LogDestination destination)
Sets the log destination.
Parameters
destination The log destination, which can be CONSOLE, FILE_ONLY, or CONSOLE_AND_FILE.
Definition at line 66 of file utils.cpp.
{
     logDestination = destination;
 }
setLogFile()
void gpmp::core::Logger::setLogFile (const std::string & logFile)
Sets the log file name for FILE_ONLY or CONSOLE_AND_FILE destinations.
Parameters
logFile The name of the log file.
Definition at line 70 of file utils.cpp.
{
     logToFile = true;
     logFileStream.open(logFile, std::ios::out | std::ios::app);
     if (!logFileStream.is_open()) {
         std::cerr << "Error: Could not open log file " << logFile << std::endl;
     }
 }
setLogLevel()
void gpmp::core::Logger::setLogLevel (LogLevel level)
Sets the minimum log level.
Parameters
level The minimum log level to record.
Definition at line 58 of file utils.cpp.
{
     logLevel = level;
 }
Member Data Documentation
enableTimestamp
bool gpmp::core::Logger::enableTimestamp private
Flag indicating whether to include timestamps in log messages.
Definition at line 158 of file utils.hpp.
logDestination
LogDestination gpmp::core::Logger::logDestination private
The log destination, which can be CONSOLE, FILE_ONLY, or CONSOLE_AND_FILE.
Definition at line 164 of file utils.hpp.
logFileStream
std::ofstream gpmp::core::Logger::logFileStream private
The output stream for logging to a file.
Definition at line 174 of file utils.hpp.
logLevel
LogLevel gpmp::core::Logger::logLevel private
The minimum log level to record.
Definition at line 153 of file utils.hpp.
logToFile
bool gpmp::core::Logger::logToFile private
Flag indicating whether to log messages to a file.
Definition at line 169 of file utils.hpp.
The documentation for this class was generated from the following files:
include/core/utils.hpp
modules/core/utils.cpp