openGPMP: QuasiNewton Class Reference
QuasiNewton Class Reference
Class implementing Quasi-Newton optimization methods.
#include <quasi.hpp>
Public Member Functions
std::vector< double > bhhh_optimize (const std::function< double(const std::vector< double > &)> &func, const std::vector< double > &initial_point, double tolerance, size_t max_iterations)
Optimize a function using the Berndt–Hall–Hall–Hausman (BHHH) algorithm.
std::vector< double > calculate_gradient (const std::function< double(const std::vector< double > &)> &func, const std::vector< double > &point, double epsilon)
Calculate the gradient of a function at a given point.
std::vector< std::vector< double > > calculate_bhhh_matrix (const std::vector< double > &gradient)
Calculate the BHHH matrix from the gradient.
std::vector< double > update_point (const std::vector< double > &current_point, const std::vector< double > &gradient, const std::vector< std::vector< double >> &bhhh_matrix)
Update the current point using the BHHH matrix.
std::vector< double > bfgs_optimize (const std::function< double(const std::vector< double > &)> &func, const std::vector< double > &initial_point, double tolerance, size_t max_iterations)
Optimize a function using the Broyden–Fletcher–Goldfarb–Shanno (BFGS) algorithm.
std::vector< double > calculate_search_direction (const std::vector< double > &gradient, const std::vector< std::vector< double >> &hessian_inverse)
Calculate the search direction using the BFGS method.
double line_search (const std::function< double(const std::vector< double > &)> &func, const std::vector< double > &current_point, const std::vector< double > &search_direction)
Perform line search to find an appropriate step size.
std::vector< double > update_point (const std::vector< double > &current_point, const std::vector< double > &search_direction, double step_size)
Update the current point using the line search and step size.
std::vector< double > calculate_gradient_difference (const std::vector< double > &next_point, const std::vector< double > &current_point, const std::vector< double > &gradient)
Calculate the gradient difference between two points.
std::vector< std::vector< double > > update_hessian_inverse (const std::vector< std::vector< double >> &hessian_inverse, const std::vector< double > &gradient_difference, const std::vector< double > &search_direction)
Update the inverse of the Hessian matrix using the BFGS method.
double dot_product (const std::vector< double > &a, const std::vector< double > &b)
Calculate the dot product of two vectors.
std::vector< double > vector_subtraction (const std::vector< double > &a, const std::vector< double > &b) const
Subtract two vectors element-wise.
std::vector< double > lbfgs_optimize (const std::function< double(const std::vector< double > &)> &func, const std::vector< double > &initial_point, double tolerance, size_t max_iterations, size_t memory_size)
Optimize a function using the Limited-Memory Broyden-Fletcher-Goldfarb-Shanno (L-BFGS) algorithm.
Detailed Description
Class implementing Quasi-Newton optimization methods.
Definition at line 44 of file quasi.hpp.
Member Function Documentation
bfgs_optimize()
std::vector< double > QuasiNewton::bfgs_optimize (const std::function< double(const std::vector< double > &)> & func, const std::vector< double > & initial_point, double tolerance, size_t max_iterations)
Optimize a function using the Broyden–Fletcher–Goldfarb–Shanno (BFGS) algorithm.
Parameters
func The objective function to minimize
initial_point The initial guess for the optimal parameters
tolerance The tolerance for stopping criterion
max_iterations The maximum number of iterations
Returns
The vector of optimal parameters
Definition at line 144 of file quasi.cpp.
{
     std::vector<double> current_point = initial_point;
     size_t n = initial_point.size();
     // Initialize Hessian approximation as the identity matrix
     std::vector<std::vector<double>> hessian_inverse(
         n,
         std::vector<double>(n, 0.0));
     for (size_t i = 0; i < n; ++i) {
         hessian_inverse[i][i] = 1.0;
     }
     for (size_t iteration = 0; iteration < max_iterations; ++iteration) {
         // Calculate the gradient
         std::vector<double> gradient =
             calculate_gradient(func, current_point, 1e-6);
         // Check convergence
         double gradient_norm = 0.0;
         for (size_t i = 0; i < n; ++i) {
             gradient_norm += gradient[i] * gradient[i];
         }
         gradient_norm = std::sqrt(gradient_norm);
         if (gradient_norm < tolerance) {
             std::cout << "Converged after " << iteration << " iterations."
                       << std::endl;
             return current_point;
         }
         // Calculate search direction
         std::vector<double> search_direction =
             calculate_search_direction(gradient, hessian_inverse);
         // Perform line search to find the step size
         double step_size = line_search(func, current_point, search_direction);
         // Update the current point
         std::vector<double> next_point =
             update_point(current_point, search_direction, step_size);
         // Update the Hessian approximation
         std::vector<double> gradient_difference =
             calculate_gradient_difference(next_point, current_point, gradient);
         hessian_inverse = update_hessian_inverse(hessian_inverse,
                                                  gradient_difference,
                                                  search_direction);
         // Move to the next iteration
         current_point = next_point;
     }
     std::cout << "Reached maximum iterations without convergence." << std::endl;
     return current_point;
 }
References calculate_gradient(), calculate_gradient_difference(), calculate_search_direction(), line_search(), update_hessian_inverse(), and update_point().
bhhh_optimize()
std::vector< double > QuasiNewton::bhhh_optimize (const std::function< double(const std::vector< double > &)> & func, const std::vector< double > & initial_point, double tolerance, size_t max_iterations)
Optimize a function using the Berndt–Hall–Hall–Hausman (BHHH) algorithm.
Parameters
func The objective function to minimize
initial_point The initial guess for the optimal parameters
tolerance The tolerance for stopping criterion
max_iterations The maximum number of iterations
Returns
The vector of optimal parameters
Definition at line 58 of file quasi.cpp.
{
     std::vector<double> current_point = initial_point;
     size_t n = initial_point.size();
     for (size_t iteration = 0; iteration < max_iterations; ++iteration) {
         // Calculate the gradient
         std::vector<double> gradient =
             calculate_gradient(func, current_point, 1e-6);
         // Check convergence
         double gradient_norm = 0.0;
         for (size_t i = 0; i < n; ++i) {
             gradient_norm += gradient[i] * gradient[i];
         }
         gradient_norm = std::sqrt(gradient_norm);
         if (gradient_norm < tolerance) {
             std::cout << "Converged after " << iteration << " iterations."
                       << std::endl;
             return current_point;
         }
         // Calculate the BHHH matrix
         std::vector<std::vector<double>> bhhh_matrix =
             calculate_bhhh_matrix(gradient);
         // Update the current point
         current_point = update_point(current_point, gradient, bhhh_matrix);
     }
     std::cout << "Reached maximum iterations without convergence." << std::endl;
     return current_point;
 }
References calculate_bhhh_matrix(), calculate_gradient(), and update_point().
calculate_bhhh_matrix()
std::vector< std::vector< double > > QuasiNewton::calculate_bhhh_matrix (const std::vector< double > & gradient)
Calculate the BHHH matrix from the gradient.
Parameters
gradient The gradient vector
Returns
The BHHH matrix
Definition at line 117 of file quasi.cpp.
{
     size_t n = gradient.size();
     std::vector<std::vector<double>> bhhh_matrix(n, std::vector<double>(n));
     for (size_t i = 0; i < n; ++i) {
         for (size_t j = 0; j < n; ++j) {
             bhhh_matrix[i][j] = gradient[i] * gradient[j];
         }
     }
     return bhhh_matrix;
 }
Referenced by bhhh_optimize().
calculate_gradient()
std::vector< double > QuasiNewton::calculate_gradient (const std::function< double(const std::vector< double > &)> & func, const std::vector< double > & point, double epsilon)
Calculate the gradient of a function at a given point.
Parameters
func The objective function
point The point at which to calculate the gradient
epsilon The perturbation for finite differences
Returns
The gradient vector
Definition at line 96 of file quasi.cpp.
                     {
     size_t n = point.size();
     std::vector<double> gradient(n);
     for (size_t i = 0; i < n; ++i) {
         std::vector<double> perturbed_point = point;
         perturbed_point[i] += epsilon;
         double perturbed_value = func(perturbed_point);
         double original_value = func(point);
         gradient[i] = (perturbed_value - original_value) / epsilon;
     }
     return gradient;
 }
Referenced by bfgs_optimize(), bhhh_optimize(), lbfgs_optimize(), and line_search().
calculate_gradient_difference()
std::vector< double > QuasiNewton::calculate_gradient_difference (const std::vector< double > & next_point, const std::vector< double > & current_point, const std::vector< double > & gradient)
Calculate the gradient difference between two points.
Parameters
next_point The next point
current_point The current point
gradient The gradient vector
Returns
The gradient difference vector
Definition at line 260 of file quasi.cpp.
{
     size_t n = next_point.size();
     std::vector<double> gradient_difference(n);
     for (size_t i = 0; i < n; ++i) {
         gradient_difference[i] =
             gradient[i] * (next_point[i] - current_point[i]);
     }
     return gradient_difference;
 }
Referenced by bfgs_optimize().
calculate_search_direction()
std::vector< double > QuasiNewton::calculate_search_direction (const std::vector< double > & gradient, const std::vector< std::vector< double >> & hessian_inverse)
Calculate the search direction using the BFGS method.
Parameters
gradient The gradient vector
hessian_inverse The inverse of the Hessian matrix
Returns
The search direction vector
Definition at line 204 of file quasi.cpp.
{
     size_t n = gradient.size();
     std::vector<double> search_direction(n);
     for (size_t i = 0; i < n; ++i) {
         search_direction[i] = 0.0;
         for (size_t j = 0; j < n; ++j) {
             search_direction[i] -= hessian_inverse[i][j] * gradient[j];
         }
     }
     return search_direction;
 }
Referenced by bfgs_optimize().
dot_product()
double QuasiNewton::dot_product (const std::vector< double > & a, const std::vector< double > & b)
Calculate the dot product of two vectors.
Parameters
a The first vector
b The second vector
Returns
The dot product value
Definition at line 298 of file quasi.cpp.
{
     size_t n = a.size();
     double result = 0.0;
     for (size_t i = 0; i < n; ++i) {
         result += a[i] * b[i];
     }
     return result;
 }
Referenced by lbfgs_optimize(), line_search(), and update_hessian_inverse().
lbfgs_optimize()
std::vector< double > QuasiNewton::lbfgs_optimize (const std::function< double(const std::vector< double > &)> & func, const std::vector< double > & initial_point, double tolerance, size_t max_iterations, size_t memory_size)
Optimize a function using the Limited-Memory Broyden-Fletcher-Goldfarb-Shanno (L-BFGS) algorithm.
Parameters
func The objective function to optimize
initial_point The initial guess for the optimal point
tolerance The tolerance for stopping criterion
max_iterations The maximum number of iterations
memory_size The size of the limited-memory history (s and y vectors)
Returns
The optimized point that minimizes the given objective function
Definition at line 310 of file quasi.cpp.
{
     // Validate memory_size
     if (memory_size == 0) {
         throw std::invalid_argument(
             "Error: Memory size for L-BFGS must be greater than zero.");
     }
     size_t n = initial_point.size();
     size_t m = std::min(memory_size, n);
     // Initialize vectors and matrices
     std::vector<std::vector<double>> s;
     std::vector<std::vector<double>> y;
     std::vector<double> rho;
     std::vector<double> alpha;
     std::vector<double> q;
     std::vector<double> gradient =
         calculate_gradient(func, initial_point, 1e-8);
     std::vector<double> x = initial_point;
     // Main optimization loop
     for (size_t iteration = 0; iteration < max_iterations; ++iteration) {
         // Check convergence
         if (dot_product(gradient, gradient) < tolerance * tolerance) {
             return x; // Converged
         }
         // Compute search direction using L-BFGS update
         q = gradient;
         for (size_t i = m - 1; i != static_cast<size_t>(-1); --i) {
             rho[i] = 1.0 / dot_product(s[i], y[i]);
             alpha[i] = rho[i] * dot_product(s[i], q);
             for (size_t j = 0; j < n; ++j) {
                 q[j] -= alpha[i] * y[i][j];
             }
         }
         // Scale the initial Hessian approximation
         double gamma =
             dot_product(s[m - 1], y[m - 1]) / dot_product(y[m - 1], y[m - 1]);
         for (size_t i = 0; i < n; ++i) {
             q[i] *= gamma;
         }
         // Perform forward recursion
         for (size_t i = 0; i < m; ++i) {
             double beta = rho[i] * dot_product(y[i], q);
             for (size_t j = 0; j < n; ++j) {
                 q[j] += (alpha[i] - beta) * s[i][j];
             }
         }
         // Perform L-BFGS update
         std::vector<double> direction = q;
         double step_size = line_search(func, x, direction);
         // Update vectors and matrices
         std::vector<double> new_point = update_point(x, direction, step_size);
         std::vector<double> new_gradient =
             calculate_gradient(func, new_point, 1e-8);
         // Update s and y
         s.push_back(vector_subtraction(new_point, x));
         y.push_back(vector_subtraction(new_gradient, gradient));
         // Ensure s and y do not exceed memory_size
         if (s.size() > m) {
             s.erase(s.begin());
             y.erase(y.begin());
         }
         x = new_point;
         gradient = new_gradient;
     }
     return x; // Return the result after the maximum number of iterations
 }
References calculate_gradient(), dot_product(), line_search(), update_point(), and vector_subtraction().
line_search()
double QuasiNewton::line_search (const std::function< double(const std::vector< double > &)> & func, const std::vector< double > & current_point, const std::vector< double > & search_direction)
Perform line search to find an appropriate step size.
Parameters
func The objective function
current_point The current point
search_direction The search direction vector
Returns
The optimal step size
Definition at line 220 of file quasi.cpp.
{
     const double alpha = 0.001; // Step size multiplier
     const double beta = 0.5;    // Factor for reducing the step size
     double step_size = 1.0; // Initial step size
     // Evaluate the objective function at the current point
     double f_current = func(current_point);
     // Calculate the directional derivative (gradient dot search_direction)
     double directional_derivative =
         dot_product(calculate_gradient(func, current_point, 1e-6),
                     search_direction);
     // Armijo condition for line search
     while (func(update_point(current_point, search_direction, step_size)) >
            f_current + alpha * step_size * directional_derivative) {
         step_size *= beta; // Reduce the step size
     }
     return step_size;
 }
References calculate_gradient(), dot_product(), and update_point().
Referenced by bfgs_optimize(), and lbfgs_optimize().
update_hessian_inverse()
std::vector< std::vector< double > > QuasiNewton::update_hessian_inverse (const std::vector< std::vector< double >> & hessian_inverse, const std::vector< double > & gradient_difference, const std::vector< double > & search_direction)
Update the inverse of the Hessian matrix using the BFGS method.
Parameters
hessian_inverse The current inverse of the Hessian matrix
gradient_difference The gradient difference vector
search_direction The search direction vector
Returns
The updated inverse of the Hessian matrix
Definition at line 275 of file quasi.cpp.
{
     size_t n = hessian_inverse.size();
     std::vector<std::vector<double>> updated_hessian_inverse(
         n,
         std::vector<double>(n));
     // Update Hessian using BFGS update formula
     double rho = 1.0 / dot_product(gradient_difference, search_direction);
     for (size_t i = 0; i < n; ++i) {
         for (size_t j = 0; j < n; ++j) {
             updated_hessian_inverse[i][j] =
                 hessian_inverse[i][j] +
                 rho * gradient_difference[i] * gradient_difference[j];
         }
     }
     return updated_hessian_inverse;
 }
References dot_product().
Referenced by bfgs_optimize().
update_point() [1/2]
std::vector< double > QuasiNewton::update_point (const std::vector< double > & current_point, const std::vector< double > & gradient, const std::vector< std::vector< double >> & bhhh_matrix)
Update the current point using the BHHH matrix.
Parameters
current_point The current point
gradient The gradient vector
bhhh_matrix The BHHH matrix
Returns
The updated point
Definition at line 131 of file quasi.cpp.
{
     size_t n = current_point.size();
     std::vector<double> updated_point(n);
     for (size_t i = 0; i < n; ++i) {
         updated_point[i] = current_point[i] - gradient[i] / bhhh_matrix[i][i];
     }
     return updated_point;
 }
Referenced by bfgs_optimize(), bhhh_optimize(), lbfgs_optimize(), and line_search().
update_point() [2/2]
std::vector< double > QuasiNewton::update_point (const std::vector< double > & current_point, const std::vector< double > & search_direction, double step_size)
Update the current point using the line search and step size.
Parameters
current_point The current point
search_direction The search direction vector
step_size The step size from the line search
Returns
The updated point
Definition at line 247 of file quasi.cpp.
{
     size_t n = current_point.size();
     std::vector<double> updated_point(n);
     for (size_t i = 0; i < n; ++i) {
         updated_point[i] = current_point[i] + step_size * search_direction[i];
     }
     return updated_point;
 }
vector_subtraction()
std::vector< double > QuasiNewton::vector_subtraction (const std::vector< double > & a, const std::vector< double > & b) const
Subtract two vectors element-wise.
Parameters
a The first vector
b The second vector
Returns
The result of subtracting each element of vector b from vector a
Definition at line 41 of file quasi.cpp.
{
     if (a.size() != b.size()) {
         throw std::invalid_argument(
             "Error: Vector dimensions do not match for subtraction.");
     }
     std::vector<double> result;
     result.reserve(a.size());
     for (size_t i = 0; i < a.size(); ++i) {
         result.push_back(a[i] - b[i]);
     }
     return result;
 }
Referenced by lbfgs_optimize().
The documentation for this class was generated from the following files:
include/optim/quasi.hpp
modules/optim/quasi.cpp