openMTPK: mtpk::Arith Class Reference
mtpk::Arith Class Reference
Arithmetic Template Class. Each method is variadic taking 'n' params.
#include <arith_base.hpp>
Public Member Functions
template<typename T >
T add (T t)
Addition method.
template<typename T , typename... Ts>
auto add (T t, Ts... ts)
template<typename X >
X sub (X x)
Subtraction method.
template<typename X , typename... Xy>
auto sub (X x, Xy... xy)
template<typename W >
W mult (W w)
Multiplication method.
template<typename W , typename... Wv>
auto mult (W w, Wv... wv)
template<typename Z >
Z exp (Z z)
Exponentiation method.
template<typename Z , typename... Zy>
auto exp (Z z, Zy... zy)
Detailed Description
Arithmetic Template Class. Each method is variadic taking 'n' params.
Definition at line 31 of file arith_base.hpp.
Member Function Documentation
add() [1/2]
template<typename T > T mtpk::Arith::add (T t) inline
Addition method.
Template Parameters
'n' addends
Returns
sum
Definition at line 40 of file arith_base.hpp.
{
         return t;
     }
Referenced by add().
add() [2/2]
template<typename T , typename... Ts> auto mtpk::Arith::add (T t, Ts... ts) inline
Definition at line 44 of file arith_base.hpp.
{
         return t + add(ts...);
     }
References add().
exp() [1/2]
template<typename Z > Z mtpk::Arith::exp (Z z) inline
Exponentiation method.
Template Parameters
base
'n' powers
Returns
product
Definition at line 85 of file arith_base.hpp.
{
         return z;
     }
Referenced by exp().
exp() [2/2]
template<typename Z , typename... Zy> auto mtpk::Arith::exp (Z z, Zy... zy) inline
Definition at line 88 of file arith_base.hpp.
{
         return z *= exp(zy...);
     }
References exp().
mult() [1/2]
template<typename W > W mtpk::Arith::mult (W w) inline
Multiplication method.
Template Parameters
'n' factors
Returns
product
Definition at line 70 of file arith_base.hpp.
{
         return w;
     }
Referenced by mult().
mult() [2/2]
template<typename W , typename... Wv> auto mtpk::Arith::mult (W w, Wv... wv) inline
Definition at line 73 of file arith_base.hpp.
{
         return w * mult(wv...);
     }
References mult().
sub() [1/2]
template<typename X > X mtpk::Arith::sub (X x) inline
Subtraction method.
Template Parameters
minuend
'n' subtrahends
Returns
difference
Definition at line 56 of file arith_base.hpp.
{
         return x;
     }
Referenced by sub().
sub() [2/2]
template<typename X , typename... Xy> auto mtpk::Arith::sub (X x, Xy... xy) inline
Definition at line 59 of file arith_base.hpp.
{
         return x - sub(xy...);
     }
References sub().
The documentation for this class was generated from the following file:
include/arithmetic/arith_base.hpp