openGPMP: gpmp::stats::PDF Class Reference
gpmp::stats::PDF Class Reference
Class representing Probability Distribution Functions (PDFs)
#include <pdfs.hpp>
Static Public Member Functions
static double bernoulli (double x, double p)
Calculates the probability of success in a Bernoulli trial.
static double beta (double x, double alpha, double beta)
Calculates the probability density function (PDF) of the Beta distribution.
static double binomial (int k, int n, double p)
Calculates the probability of observing k successes in n independent Bernoulli trials.
static double cauchy (double x, double x0, double gamma)
Calculates the probability density function (PDF) of the Cauchy distribution.
static double chi_squared (double x, int k)
Calculates the probability density function (PDF) of the chi-squared distribution.
static double exponential (double x, double lambda)
Calculates the probability density function (PDF) of the exponential distribution.
static double f_dist (double x, int df1, int df2)
Calculates the probability density function (PDF) of the F distribution.
static double gamma (double x, double alpha, double beta)
Calculates the probability density function (PDF) of the gamma distribution.
static double inverse_gamma (double x, double alpha, double beta)
Calculates the probability density function (PDF) of the inverse gamma distribution.
static double inverse_gaussian (double x, double mu, double lambda)
Calculates the probability density function (PDF) of the inverse Gaussian distribution.
static double laplace (double x, double mu, double b)
Calculates the probability density function (PDF) of the Laplace distribution.
static double logistic (double x, double mu, double s)
Calculates the probability density function (PDF) of the logistic distribution.
static double log_normal (double x, double mu, double sigma)
Calculates the probability density function (PDF) of the log-normal distribution.
static double gaussian (double x, double mu, double sigma)
Calculates the probability density function (PDF) of the Gaussian (normal) distribution.
static double poisson (int k, double lambda)
Calculates the probability density function (PDF) of the Poisson distribution.
static double rademacher (int k)
Calculates the probability density function (PDF) of the Rademacher distribution.
static double student_t (double x, int df)
Calculates the probability density function (PDF) of Student's t distribution.
static double uniform (double x, double a, double b)
Calculates the probability density function (PDF) of the uniform distribution.
static double weibull (double x, double k, double lambda)
Calculates the probability density function (PDF) of the Weibull distribution.
static double binomial_coefficient (int n, int k)
Calculates the binomial coefficient "n choose k".
static double beta_function (double alpha, double beta)
Calculates the beta function.
static double factorial (int n)
Calculates the factorial of an integer.
Detailed Description
Class representing Probability Distribution Functions (PDFs)
Definition at line 41 of file pdfs.hpp.
Member Function Documentation
bernoulli()
double gpmp::stats::PDF::bernoulli (double x, double p) static
Calculates the probability of success in a Bernoulli trial.
Parameters
x The outcome (0 or 1)
p The probability of success
Returns
The probability of observing the outcome
Definition at line 44 of file pdfs.cpp.
{
     if (std::abs(x - 0) < std::numeric_limits<double>::epsilon())
         return 1 - p;
     else if (std::abs(x - 1) < std::numeric_limits<double>::epsilon())
         return p;
     else
         return 0;
 }
Referenced by main().
beta()
double gpmp::stats::PDF::beta (double x, double alpha, double beta) static
Calculates the probability density function (PDF) of the Beta distribution.
Parameters
x The value at which to evaluate the PDF
alpha The shape parameter alpha (> 0)
beta The shape parameter beta (> 0)
Returns
The value of the PDF at x
Definition at line 54 of file pdfs.cpp.
{
     if (x < 0 || x > 1)
         return 0;
     else
         return (std::pow(x, alpha - 1) * std::pow(1 - x, beta - 1)) /
                beta_function(alpha, beta);
 }
Referenced by main().
beta_function()
double gpmp::stats::PDF::beta_function (double alpha, double beta) static
Calculates the beta function.
Parameters
alpha The first shape parameter (> 0)
beta The second shape parameter (> 0)
Returns
The value of the beta function
Definition at line 212 of file pdfs.cpp.
{
     return std::tgamma(alpha) * std::tgamma(beta) / std::tgamma(alpha + beta);
 }
binomial()
double gpmp::stats::PDF::binomial (int k, int n, double p) static
Calculates the probability of observing k successes in n independent Bernoulli trials.
Parameters
k The number of successes
n The number of trials
p The probability of success in each trial
Returns
The probability of observing k successes
Definition at line 63 of file pdfs.cpp.
{
     if (k < 0 || k > n)
         return 0;
     else
         return binomial_coefficient(n, k) * std::pow(p, k) *
                std::pow(1 - p, n - k);
 }
Referenced by main().
binomial_coefficient()
double gpmp::stats::PDF::binomial_coefficient (int n, int k) static
Calculates the binomial coefficient "n choose k".
Parameters
n The total number of items
k The number of items to choose
Returns
The binomial coefficient
Definition at line 203 of file pdfs.cpp.
{
     double result = 1.0;
     for (int i = 1; i <= k; ++i) {
         result *= static_cast<double>(n - (k - i)) / i;
     }
     return result;
 }
cauchy()
double gpmp::stats::PDF::cauchy (double x, double x0, double gamma) static
Calculates the probability density function (PDF) of the Cauchy distribution.
Parameters
x The value at which to evaluate the PDF
x0 The location parameter
gamma The scale parameter (> 0)
Returns
The value of the PDF at x
Definition at line 72 of file pdfs.cpp.
{
     return (1 / (M_PI * gamma)) *
            (gamma * gamma / ((x - x0) * (x - x0) + gamma * gamma));
 }
Referenced by main().
chi_squared()
double gpmp::stats::PDF::chi_squared (double x, int k) static
Calculates the probability density function (PDF) of the chi-squared distribution.
Parameters
x The value at which to evaluate the PDF
k The degrees of freedom (> 0)
Returns
The value of the PDF at x
Definition at line 78 of file pdfs.cpp.
{
     if (x < 0)
         return 0;
     else
         return (std::pow(x, k / 2.0 - 1) * std::exp(-x / 2.0)) /
                (std::pow(2, k / 2.0) * std::tgamma(k / 2.0));
 }
Referenced by main().
exponential()
double gpmp::stats::PDF::exponential (double x, double lambda) static
Calculates the probability density function (PDF) of the exponential distribution.
Parameters
x The value at which to evaluate the PDF
lambda The rate parameter (> 0)
Returns
The value of the PDF at x
Definition at line 87 of file pdfs.cpp.
{
     if (x < 0)
         return 0;
     else
         return lambda * std::exp(-lambda * x);
 }
Referenced by main().
f_dist()
double gpmp::stats::PDF::f_dist (double x, int df1, int df2) static
Calculates the probability density function (PDF) of the F distribution.
Parameters
x The value at which to evaluate the PDF
df1 The degrees of freedom of the numerator (> 0)
df2 The degrees of freedom of the denominator (> 0)
Returns
The value of the PDF at x
Definition at line 95 of file pdfs.cpp.
{
     if (x < 0)
         return 0;
     else
         return std::pow(df1, df1 / 2.0) * std::pow(df2, df2 / 2.0) *
                std::pow(x, df1 / 2.0 - 1) /
                (std::pow(df2 + df1 * x, (df1 + df2) / 2.0) *
                 std::tgamma(df1 / 2.0) * std::tgamma(df2 / 2.0));
 }
Referenced by main().
factorial()
static double gpmp::stats::PDF::factorial (int n) static
Calculates the factorial of an integer.
Parameters
n The integer
Returns
The factorial of n
gamma()
double gpmp::stats::PDF::gamma (double x, double alpha, double beta) static
Calculates the probability density function (PDF) of the gamma distribution.
Parameters
x The value at which to evaluate the PDF
alpha The shape parameter (> 0)
beta The scale parameter (> 0)
Returns
The value of the PDF at x
Definition at line 106 of file pdfs.cpp.
{
     if (x < 0)
         return 0;
     else
         return (std::pow(x, alpha - 1) * std::exp(-x / beta)) /
                (std::pow(beta, alpha) * std::tgamma(alpha));
 }
Referenced by main().
gaussian()
double gpmp::stats::PDF::gaussian (double x, double mu, double sigma) static
Calculates the probability density function (PDF) of the Gaussian (normal) distribution.
Parameters
x The value at which to evaluate the PDF
mu The mean of the distribution
sigma The standard deviation of the distribution (> 0)
Returns
The value of the PDF at x
Definition at line 154 of file pdfs.cpp.
{
     return (1 / (sigma * std::sqrt(2 * M_PI))) *
            std::exp(-0.5 * std::pow((x - mu) / sigma, 2));
 }
Referenced by main().
inverse_gamma()
double gpmp::stats::PDF::inverse_gamma (double x, double alpha, double beta) static
Calculates the probability density function (PDF) of the inverse gamma distribution.
Parameters
x The value at which to evaluate the PDF
alpha The shape parameter (> 0)
beta The scale parameter (> 0)
Returns
The value of the PDF at x
Definition at line 115 of file pdfs.cpp.
{
     if (x <= 0)
         return 0;
     else
         return (std::pow(beta, alpha) * std::pow(x, -alpha - 1) *
                 std::exp(-beta / x)) /
                std::tgamma(alpha);
 }
Referenced by main().
inverse_gaussian()
double gpmp::stats::PDF::inverse_gaussian (double x, double mu, double lambda) static
Calculates the probability density function (PDF) of the inverse Gaussian distribution.
Parameters
x The value at which to evaluate the PDF
mu The mean parameter (> 0)
lambda The shape parameter (> 0)
Returns
The value of the PDF at x
Definition at line 125 of file pdfs.cpp.
{
     if (x <= 0)
         return 0;
     else
         return std::sqrt(lambda / (2 * M_PI * x * x * x)) *
                std::exp(-lambda * (x - mu) * (x - mu) / (2 * mu * mu * x));
 }
Referenced by main().
laplace()
double gpmp::stats::PDF::laplace (double x, double mu, double b) static
Calculates the probability density function (PDF) of the Laplace distribution.
Parameters
x The value at which to evaluate the PDF
mu The location parameter
b The scale parameter (> 0)
Returns
The value of the PDF at x
Definition at line 134 of file pdfs.cpp.
{
     return 0.5 * std::exp(-std::abs(x - mu) / b) / b;
 }
Referenced by main().
log_normal()
double gpmp::stats::PDF::log_normal (double x, double mu, double sigma) static
Calculates the probability density function (PDF) of the log-normal distribution.
Parameters
x The value at which to evaluate the PDF
mu The mean of the underlying normal distribution
sigma The standard deviation of the underlying normal distribution (> 0)
Returns
The value of the PDF at x
Definition at line 145 of file pdfs.cpp.
{
     if (x <= 0)
         return 0;
     else
         return (1 / (x * sigma * std::sqrt(2 * M_PI))) *
                std::exp(-0.5 * std::pow((std::log(x) - mu) / sigma, 2));
 }
Referenced by main().
logistic()
double gpmp::stats::PDF::logistic (double x, double mu, double s) static
Calculates the probability density function (PDF) of the logistic distribution.
Parameters
x The value at which to evaluate the PDF
mu The location parameter
s The scale parameter (> 0)
Returns
The value of the PDF at x
Definition at line 139 of file pdfs.cpp.
{
     double z = (x - mu) / s;
     return std::exp(-z) / (s * std::pow(1 + std::exp(-z), 2));
 }
Referenced by main().
poisson()
double gpmp::stats::PDF::poisson (int k, double lambda) static
Calculates the probability density function (PDF) of the Poisson distribution.
Parameters
k The number of events
lambda The rate parameter (> 0)
Returns
The value of the PDF at k
Definition at line 160 of file pdfs.cpp.
{
     if (k < 0)
         return 0;
     else
         return std::exp(-lambda) * std::pow(lambda, k) /
                gpmp::core::Misc::factorial(k);
 }
References gpmp::core::Misc::factorial().
Referenced by main().
rademacher()
double gpmp::stats::PDF::rademacher (int k) static
Calculates the probability density function (PDF) of the Rademacher distribution.
Parameters
k The value (1 or -1)
Returns
The value of the PDF at k
Definition at line 169 of file pdfs.cpp.
{
     if (k == -1)
         return 0.5;
     else if (k == 1)
         return 0.5;
     else
         return 0;
 }
Referenced by main().
student_t()
double gpmp::stats::PDF::student_t (double x, int df) static
Calculates the probability density function (PDF) of Student's t distribution.
Parameters
x The value at which to evaluate the PDF
df The degrees of freedom (> 0)
Returns
The value of the PDF at x
Definition at line 179 of file pdfs.cpp.
{
     double numerator = std::tgamma((df + 1) / 2.0);
     double denominator = std::sqrt(df * M_PI) * std::tgamma(df / 2.0);
     return std::pow(1 + x * x / df, -(df + 1) / 2.0) * numerator / denominator;
 }
Referenced by main().
uniform()
double gpmp::stats::PDF::uniform (double x, double a, double b) static
Calculates the probability density function (PDF) of the uniform distribution.
Parameters
x The value at which to evaluate the PDF
a The minimum value of the interval
b The maximum value of the interval
Returns
The value of the PDF at x
Definition at line 186 of file pdfs.cpp.
{
     if (x >= a && x <= b)
         return 1 / (b - a);
     else
         return 0;
 }
Referenced by main().
weibull()
double gpmp::stats::PDF::weibull (double x, double k, double lambda) static
Calculates the probability density function (PDF) of the Weibull distribution.
Parameters
x The value at which to evaluate the PDF
k The shape parameter (> 0)
lambda The scale parameter (> 0)
Returns
The value of the PDF at x
Definition at line 194 of file pdfs.cpp.
{
     if (x < 0)
         return 0;
     else
         return (k / lambda) * std::pow(x / lambda, k - 1) *
                std::exp(-std::pow(x / lambda, k));
 }
Referenced by main().
The documentation for this class was generated from the following files:
include/openGPMP/stats/pdfs.hpp
modules/stats/pdfs.cpp