openGPMP: Quantile Class Reference
Quantile Class Reference
Static Public Member Functions
static double bernoulli (double p, double q)
static double beta (double alpha, double beta, double q)
static int binomial (int n, double p, double q)
static double cauchy (double median, double scale, double q)
static double chiSquared (int df, double q)
static double exponential (double lambda, double q)
static double f (int df1, int df2, double q)
static double gamma (double shape, double scale, double q)
static double inverseGamma (double shape, double q)
Static Private Member Functions
static double incompleteBeta (double a, double b, double x)
static double gammaLn (double xx)
static double betaContinuedFraction (double a, double b, double x)
static double inverseBeta (double a, double b, double q)
static int binomialCoefficient (int n, int k)
Detailed Description
Definition at line 42 of file quantiles.cpp.
Member Function Documentation
bernoulli()
static double Quantile::bernoulli (double p, double q) inline static
Definition at line 45 of file quantiles.cpp.
{
         return (q < p) ? 0.0 : 1.0;
     }
beta()
static double Quantile::beta (double alpha, double beta, double q) inline static
Definition at line 50 of file quantiles.cpp.
{
         if (q <= 0.0)
             return 0.0;
         if (q >= 1.0)
             return 1.0;
         double result = 0.0;
         if (q > 0.5)
             result = 1.0 - incompleteBeta(beta, alpha, 1.0 - q);
         else
             result = incompleteBeta(alpha, beta, q);
         return result;
     }
References incompleteBeta().
betaContinuedFraction()
static double Quantile::betaContinuedFraction (double a, double b, double x) inline static private
Definition at line 154 of file quantiles.cpp.
{
         const int maxIterations = 200;
         const double epsilon = 1.0e-15;
         double am = 1.0;
         double bm = 1.0;
         double az = 1.0;
         double qab = a + b;
         double qap = a + 1.0;
         double qam = a - 1.0;
         double bz = 1.0 - qab * x / qap;
         double aold = 0.0;
         double em, tem, d, ap, bp, app, bpp;
         int m;
         for (m = 1; m <= maxIterations; m++) {
             em = m;
             tem = em + em;
             d = em * (b - m) * x / ((qam + tem) * (a + tem));
             ap = az + d * am;
             bp = bz + d * bm;
             d = -(a + em) * (qab + em) * x / ((a + tem) * (qap + tem));
             app = ap + d * az;
             bpp = bp + d * bz;
             aold = az;
             am = ap / bpp;
             bm = bp / bpp;
             az = app / bpp;
             bz = 1.0;
             if (fabs(az - aold) < (epsilon * fabs(az)))
                 return az;
         }
         return az;
     }
Referenced by incompleteBeta().
binomial()
static int Quantile::binomial (int n, double p, double q) inline static
Definition at line 66 of file quantiles.cpp.
{
         int x = 0;
         double cdf = 0.0;
         while (x <= n) {
             cdf += binomialCoefficient(n, x) * pow(p, x) * pow(1.0 - p, n - x);
             if (cdf >= q)
                 return x;
             x++;
         }
         return n;
     }
References binomialCoefficient().
binomialCoefficient()
static int Quantile::binomialCoefficient (int n, int k) inline static private
Definition at line 194 of file quantiles.cpp.
{
         if (k < 0 || k > n)
             return 0;
         if (k == 0 || k == n)
             return 1;
         int result = 1;
         if (k > n - k)
             k = n - k;
         for (int i = 0; i < k; ++i) {
             result *= (n - i);
             result /= (i + 1);
         }
         return result;
     }
Referenced by binomial().
cauchy()
static double Quantile::cauchy (double median, double scale, double q) inline static
Definition at line 79 of file quantiles.cpp.
{
         return median + scale * tan(M_PI * (q - 0.5));
     }
chiSquared()
static double Quantile::chiSquared (int df, double q) inline static
Definition at line 84 of file quantiles.cpp.
{
         if (q < 0.0 || q > 1.0 || df < 1)
             return NAN;
         return df * inverseGamma(0.5 * df, q);
     }
References inverseGamma().
exponential()
static double Quantile::exponential (double lambda, double q) inline static
Definition at line 91 of file quantiles.cpp.
{
         if (q < 0.0 || q > 1.0 || lambda <= 0.0)
             return NAN;
         return -log(1.0 - q) / lambda;
     }
f()
static double Quantile::f (int df1, int df2, double q) inline static
Definition at line 98 of file quantiles.cpp.
{
         if (q <= 0.0 || q >= 1.0 || df1 <= 0 || df2 <= 0)
             return NAN;
         return (inverseBeta(0.5 * df2, 0.5 * df1, q) * df2) /
                (inverseBeta(0.5 * df2, 0.5 * df1, 1.0 - q) * df1);
     }
References inverseBeta().
gamma()
static double Quantile::gamma (double shape, double scale, double q) inline static
Definition at line 106 of file quantiles.cpp.
{
         if (q < 0.0 || q > 1.0 || shape <= 0.0 || scale <= 0.0)
             return NAN;
         return shape * scale * inverseGamma(shape, q);
     }
References inverseGamma().
Referenced by inverseGamma().
gammaLn()
static double Quantile::gammaLn (double xx) inline static private
Definition at line 135 of file quantiles.cpp.
{
         double x, y, tmp, ser;
         static const double cof[6] = {76.18009172947146,
                                       -86.50532032941677,
                                       24.01409824083091,
                                       -1.231739572450155,
                                       0.1208650973866179e-2,
                                       -0.5395239384953e-5};
         int j;
         y = x = xx;
         tmp = x + 5.5;
         tmp -= (x + 0.5) * log(tmp);
         ser = 1.000000000190015;
         for (j = 0; j < 6; j++)
             ser += cof[j] / ++y;
         return -tmp + log(2.5066282746310005 * ser / x);
     }
Referenced by incompleteBeta().
incompleteBeta()
static double Quantile::incompleteBeta (double a, double b, double x) inline static private
Definition at line 120 of file quantiles.cpp.
{
         const int maxIterations = 200;
         const double epsilon = 1.0e-15;
         double bt = (x == 0.0 || x == 1.0)
                         ? 0.0
                         : exp(gammaLn(a + b) - gammaLn(a) - gammaLn(b) +
                               a * log(x) + b * log(1.0 - x));
         if (x < (a + 1.0) / (a + b + 2.0))
             return bt * betaContinuedFraction(a, b, x) / a;
         else
             return 1.0 - bt * betaContinuedFraction(b, a, 1.0 - x) / b;
     }
References betaContinuedFraction(), and gammaLn().
Referenced by beta(), and inverseBeta().
inverseBeta()
static double Quantile::inverseBeta (double a, double b, double q) inline static private
Definition at line 190 of file quantiles.cpp.
{
         return 1.0 - incompleteBeta(b, a, q);
     }
References incompleteBeta().
Referenced by f().
inverseGamma()
static double Quantile::inverseGamma (double shape, double q) inline static
Definition at line 113 of file quantiles.cpp.
{
         if (q < 0.0 || q > 1.0 || shape <= 0.0)
             return NAN;
         return 1.0 / gamma(shape, 1.0 / shape, 1.0 - q);
     }
References gamma().
Referenced by chiSquared(), and gamma().
The documentation for this class was generated from the following file:
modules/stats/quantiles.cpp