openMTPK: Basics Class Reference
Basics Class Reference
#include <arith.hpp>
Public Member Functions
int greatest_power (int n, int p)
int rm_gcd (int x, int y)
Detailed Description
Definition at line 80 of file arith.hpp.
Member Function Documentation
greatest_power()
int Basics::greatest_power (int n, int p)
Definition at line 7 of file arith.cpp.
{
     int x = 0;
     // Calculate x = n/p + n/(p^2) + n/(p^3) + ....
     while (n) {
         n /= p;
         x += n;
     }
     return x;
 }
References Python.examples.primes_ex::p.
Referenced by main(), R_swig_Basics_greatest_power(), and anonymous_namespace{t_arith.cpp}::TEST().
rm_gcd()
int Basics::rm_gcd (int x, int y)
Definition at line 18 of file arith.cpp.
{
     if(x < y)
         return rm_gcd(y, x);
     else if(x % y == 0)
         return y;
     else
         return rm_gcd(y, x % y);
 }
Referenced by Primality::carmichael_num(), Primality::ETF(), main(), Primality::pollard_rho(), R_swig_Basics_rm_gcd(), and anonymous_namespace{t_arith.cpp}::TEST().
The documentation for this class was generated from the following files:
include/arithmetic/arith.hpp
modules/arithmetic/arith.cpp