openGPMP: gpmp::stats::Describe Class Reference
gpmp::stats::Describe Class Reference
A class providing methods for descriptive statistics.
#include <describe.hpp>
Public Member Functions
double mean_arith (const std::vector< double > &data)
Calculates the arithmetic mean of a given dataset.
double mean_geo (const std::vector< double > &data)
Calculates the geometric mean of a given dataset.
double mean_cubic (const std::vector< double > &data, double p)
Calculates the cubic generalized mean of a given dataset with a specified power.
double mean_geo_pow (const std::vector< double > &data, double p)
Calculates the power geometric mean of a given dataset with a specified power.
double mean_harmonic (const std::vector< double > &data)
Calculates the harmonic mean of a given dataset.
double mean_heronian (const std::vector< double > &data)
Calculates the Heronian mean of a given dataset.
double mean_heinz (const std::vector< double > &data)
Calculates the Heinz mean of a given dataset.
double mean_lehmer (const std::vector< double > &data, double p)
Calculates the Lehmer mean of a given dataset with a specified power.
double Median (std::vector< double > data)
Calculates the median of a given dataset.
double avg_abs_dev (const std::vector< double > &data)
Calculates the average absolute deviation of a given dataset.
double var_coeff (const std::vector< double > &data)
Calculates the coefficient of variation of a given dataset.
double iq_range (const std::vector< double > &data)
Calculates the interquartile range of a given dataset.
double percentile (const std::vector< double > &data, double percentile)
Calculates the specified percentile of a given dataset.
double range (const std::vector< double > &data)
Calculates the range of a given dataset.
double stdev (const std::vector< double > &data, double mean)
Calculates the standard deviation of a given dataset, given the mean.
double variance (const std::vector< double > &data, double mean)
Calculates the variance of a given dataset, given the mean.
double clt (const std::vector< double > &data, int numSamples)
Calculates the standard error of the mean using the Central Limit Theorem.
double kurtosis (const std::vector< double > &data, double mean)
Calculates the kurtosis of a given dataset.
double lmoment1 (const std::vector< double > &data, double mean)
Calculates the first L-moment of a given dataset.
double lmoment2 (const std::vector< double > &data, double mean)
Calculates the second L-moment of a given dataset.
double skewness (const std::vector< double > &data, double mean, double stddev)
Calculates the skewness of a given dataset.
std::vector< size_t > rank_data (const std::vector< double > &data)
Ranks the data in ascending order.
double partial_corr (const std::vector< double > &x, const std::vector< double > &y, const std::vector< double > &z)
Calculates the partial correlation coefficient between two variables, controlling for a third variable.
double ppmc (const std::vector< double > &x, const std::vector< double > &y)
Calculates the Pearson Product-Moment Correlation between two variables.
double kendalls_tau (const std::vector< double > &x, const std::vector< double > &y)
Calculates Kendall's Tau Rank Correlation between two variables.
double spearmans_rho (const std::vector< double > &x, const std::vector< double > &y)
Calculates Spearman's Rank Correlation between two variables.
Detailed Description
A class providing methods for descriptive statistics.
Definition at line 44 of file describe.hpp.
Member Function Documentation
avg_abs_dev()
double gpmp::stats::Describe::avg_abs_dev (const std::vector< double > & data)
Calculates the average absolute deviation of a given dataset.
Parameters
data The input dataset
Returns
The average absolute deviation
Definition at line 125 of file describe.cpp.
{
     double mean = mean_arith(data);
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::abs(value - mean);
     }
     return sum / static_cast<double>(data.size());
 }
clt()
double gpmp::stats::Describe::clt (const std::vector< double > & data, int numSamples)
Calculates the standard error of the mean using the Central Limit Theorem.
This method estimates the standard error of the mean based on the Central Limit Theorem
Parameters
data The input dataset
numSamples The number of samples for the Central Limit Theorem
Returns
The estimated standard error of the mean
Definition at line 191 of file describe.cpp.
{
     double mean = mean_arith(data);
     double stddev = stdev(data, mean);
     return stddev / std::sqrt(static_cast<double>(numSamples));
 }
iq_range()
double gpmp::stats::Describe::iq_range (const std::vector< double > & data)
Calculates the interquartile range of a given dataset.
Parameters
data The input dataset
Returns
The interquartile range
Definition at line 142 of file describe.cpp.
{
     std::vector<double> sortedData = data;
     std::sort(sortedData.begin(), sortedData.end());
     size_t size = sortedData.size();
     size_t lowerIndex = size / 4;
     size_t upperIndex = 3 * size / 4;
     return sortedData[upperIndex] - sortedData[lowerIndex];
 }
kendalls_tau()
double gpmp::stats::Describe::kendalls_tau (const std::vector< double > & x, const std::vector< double > & y)
Calculates Kendall's Tau Rank Correlation between two variables.
This method measures the strength and direction of monotonic relationships between variables X and Y
Parameters
x The values of variable X
y The values of variable Y
Returns
Kendall's Tau Rank Correlation coefficient
Definition at line 287 of file describe.cpp.
{
     size_t concordant = 0;
     size_t discordant = 0;
     for (size_t i = 0; i < x.size() - 1; ++i) {
         for (size_t j = i + 1; j < x.size(); ++j) {
             if ((x[i] < x[j] && y[i] < y[j]) || (x[i] > x[j] && y[i] > y[j])) {
                 concordant++;
             } else if ((x[i] < x[j] && y[i] > y[j]) ||
                        (x[i] > x[j] && y[i] < y[j])) {
                 discordant++;
             }
         }
     }
     return static_cast<double>(concordant - discordant) /
            std::sqrt(static_cast<double>((concordant + discordant) *
                                          (x.size() * (x.size() - 1)) / 2));
 }
kurtosis()
double gpmp::stats::Describe::kurtosis (const std::vector< double > & data, double mean)
Calculates the kurtosis of a given dataset.
This method measures the "tailedness" or sharpness of the dataset's peak
Parameters
data The input dataset
mean The mean of the dataset
Returns
The kurtosis value
Definition at line 199 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value - mean, 4.0);
     }
     double var = variance(data, mean);
     return sum / (data.size() * std::pow(var, 2.0)) - 3.0;
 }
lmoment1()
double gpmp::stats::Describe::lmoment1 (const std::vector< double > & data, double mean)
Calculates the first L-moment of a given dataset.
L-moments are used to estimate the parameters of a probability distribution
Parameters
data The input dataset
mean The mean of the dataset
Returns
The first L-moment
Definition at line 210 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value - mean, 3.0);
     }
     return sum / data.size();
 }
lmoment2()
double gpmp::stats::Describe::lmoment2 (const std::vector< double > & data, double mean)
Calculates the second L-moment of a given dataset.
L-moments are used to estimate the parameters of a probability distribution
Parameters
data The input dataset
mean The mean of the dataset
Returns
The second L-moment
Definition at line 219 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value - mean, 4.0);
     }
     return sum / data.size();
 }
mean_arith()
double gpmp::stats::Describe::mean_arith (const std::vector< double > & data)
Calculates the arithmetic mean of a given dataset.
Parameters
data The input dataset
Returns
The arithmetic mean
Definition at line 39 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += value;
     }
     return sum / static_cast<double>(data.size());
 }
Referenced by gpmp::stats::ProbDist::BootstrapResampling(), gpmp::stats::ProbDist::ConfidenceInterval(), gpmp::stats::ProbDist::JackknifeResampling(), gpmp::stats::ProbDist::mom(), and gpmp::stats::ProbDist::PivotFunctionForConfidenceInterval().
mean_cubic()
double gpmp::stats::Describe::mean_cubic (const std::vector< double > & data, double p)
Calculates the cubic generalized mean of a given dataset with a specified power.
Parameters
data The input dataset
p The power parameter
Returns
The cubic generalized mean
Definition at line 57 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value, p);
     }
     return std::pow(sum / static_cast<double>(data.size()), 1.0 / p);
 }
mean_geo()
double gpmp::stats::Describe::mean_geo (const std::vector< double > & data)
Calculates the geometric mean of a given dataset.
Parameters
data The input dataset
Returns
The geometric mean
Definition at line 48 of file describe.cpp.
{
     double product = 1.0;
     for (const auto &value : data) {
         product *= value;
     }
     return std::pow(product, 1.0 / static_cast<double>(data.size()));
 }
mean_geo_pow()
double gpmp::stats::Describe::mean_geo_pow (const std::vector< double > & data, double p)
Calculates the power geometric mean of a given dataset with a specified power.
Parameters
data The input dataset
p The power parameter
Returns
The power geometric mean
Definition at line 67 of file describe.cpp.
{
     double product = 1.0;
     for (const auto &value : data) {
         product *= std::pow(value, p);
     }
     return std::pow(product, 1.0 / static_cast<double>(data.size()));
 }
mean_harmonic()
double gpmp::stats::Describe::mean_harmonic (const std::vector< double > & data)
Calculates the harmonic mean of a given dataset.
Parameters
data The input dataset
Returns
The harmonic mean
Definition at line 77 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += 1.0 / value;
     }
     return static_cast<double>(data.size()) / sum;
 }
mean_heinz()
double gpmp::stats::Describe::mean_heinz (const std::vector< double > & data)
Calculates the Heinz mean of a given dataset.
Parameters
data The input dataset
Returns
The Heinz mean
Definition at line 95 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += value * std::log(value);
     }
     return std::exp(sum / static_cast<double>(data.size()));
 }
mean_heronian()
double gpmp::stats::Describe::mean_heronian (const std::vector< double > & data)
Calculates the Heronian mean of a given dataset.
Parameters
data The input dataset
Returns
The Heronian mean
Definition at line 86 of file describe.cpp.
{
     double product = 1.0;
     for (const auto &value : data) {
         product *= std::sqrt(value);
     }
     return std::pow(product, 2.0 / static_cast<double>(data.size()));
 }
mean_lehmer()
double gpmp::stats::Describe::mean_lehmer (const std::vector< double > & data, double p)
Calculates the Lehmer mean of a given dataset with a specified power.
Parameters
data The input dataset
p The power parameter
Returns
The Lehmer mean
Definition at line 104 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value, p);
     }
     return sum / static_cast<double>(data.size());
 }
Median()
double gpmp::stats::Describe::Median (std::vector< double > data)
Calculates the median of a given dataset.
Parameters
data The input dataset
Returns
The median
Definition at line 114 of file describe.cpp.
{
     std::sort(data.begin(), data.end());
     size_t size = data.size();
     if (size % 2 == 0) {
         return (data[size / 2 - 1] + data[size / 2]) / 2.0;
     } else {
         return data[size / 2];
     }
 }
partial_corr()
double gpmp::stats::Describe::partial_corr (const std::vector< double > & x, const std::vector< double > & y, const std::vector< double > & z)
Calculates the partial correlation coefficient between two variables, controlling for a third variable.
This method computes the partial correlation between variables X and Y, controlling for variable Z
Parameters
x The values of variable X
y The values of variable Y
z The values of control variable Z
Returns
The partial correlation coefficient
Definition at line 256 of file describe.cpp.
{
     double r_xy = ppmc(x, y);
     double r_xz = ppmc(x, z);
     double r_yz = ppmc(y, z);
     return (r_xy - (r_xz * r_yz)) /
            std::sqrt((1.0 - std::pow(r_xz, 2.0)) * (1.0 - std::pow(r_yz, 2.0)));
 }
percentile()
double gpmp::stats::Describe::percentile (const std::vector< double > & data, double percentile)
Calculates the specified percentile of a given dataset.
Parameters
data The input dataset
percentile The desired percentile (00 to 10)
Returns
The value at the specified percentile
Definition at line 154 of file describe.cpp.
{
     std::vector<double> sortedData = data;
     std::sort(sortedData.begin(), sortedData.end());
     size_t size = sortedData.size();
     size_t index = static_cast<size_t>(percentile * (size - 1));
     return sortedData[index];
 }
ppmc()
double gpmp::stats::Describe::ppmc (const std::vector< double > & x, const std::vector< double > & y)
Calculates the Pearson Product-Moment Correlation between two variables.
This method measures the linear relationship between variables X and Y
Parameters
x The values of variable X
y The values of variable Y
Returns
The Pearson Product-Moment Correlation coefficient
Definition at line 268 of file describe.cpp.
{
     double mean_x = mean_arith(x);
     double mean_y = mean_arith(y);
     double numerator = 0.0;
     double denominator_x = 0.0;
     double denominator_y = 0.0;
     for (size_t i = 0; i < x.size(); ++i) {
         numerator += (x[i] - mean_x) * (y[i] - mean_y);
         denominator_x += std::pow(x[i] - mean_x, 2.0);
         denominator_y += std::pow(y[i] - mean_y, 2.0);
     }
     return numerator / std::sqrt(denominator_x * denominator_y);
 }
range()
double gpmp::stats::Describe::range (const std::vector< double > & data)
Calculates the range of a given dataset.
Parameters
data The input dataset
Returns
The range
Definition at line 165 of file describe.cpp.
{
     auto result = std::minmax_element(data.begin(), data.end());
     return *result.second - *result.first;
 }
rank_data()
std::vector< size_t > gpmp::stats::Describe::rank_data (const std::vector< double > & data)
Ranks the data in ascending order.
This method assigns ranks to the data, where the smallest value gets rank 1, the second smallest gets rank 2, and so on
Parameters
data The input dataset
Returns
A vector containing the ranks of the input data
Definition at line 240 of file describe.cpp.
{
     std::vector<size_t> ranks(data.size());
     for (size_t i = 0; i < data.size(); ++i) {
         size_t rank = 1;
         for (size_t j = 0; j < data.size(); ++j) {
             if (j != i && data[j] < data[i]) {
                 rank++;
             }
         }
         ranks[i] = rank;
     }
     return ranks;
 }
skewness()
double gpmp::stats::Describe::skewness (const std::vector< double > & data, double mean, double stddev)
Calculates the skewness of a given dataset.
This method measures the asymmetry of the dataset's distribution
Parameters
data The input dataset
mean The mean of the dataset
stddev The standard deviation of the dataset
Returns
The skewness value
Definition at line 229 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow((value - mean) / stddev, 3.0);
     }
     return sum / static_cast<double>(data.size());
 }
spearmans_rho()
double gpmp::stats::Describe::spearmans_rho (const std::vector< double > & x, const std::vector< double > & y)
Calculates Spearman's Rank Correlation between two variables.
This method measures the strength and direction of monotonic relationships between variables X and Y
Parameters
x The values of variable X
y The values of variable Y
Returns
Spearman's Rank Correlation coefficient
Definition at line 309 of file describe.cpp.
{
     std::vector<size_t> ranks_x = rank_data(x);
     std::vector<size_t> ranks_y = rank_data(y);
     double d_squared = 0.0;
     for (size_t i = 0; i < x.size(); ++i) {
         d_squared += std::pow(ranks_x[i] - ranks_y[i], 2.0);
     }
     return 1.0 -
            (6.0 * d_squared) / (x.size() * (std::pow(x.size(), 2.0) - 1.0));
 }
stdev()
double gpmp::stats::Describe::stdev (const std::vector< double > & data, double mean)
Calculates the standard deviation of a given dataset, given the mean.
Parameters
data The input dataset
mean The mean of the dataset
Returns
The standard deviation
Definition at line 171 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value - mean, 2.0);
     }
     return std::sqrt(sum / static_cast<double>(data.size()));
 }
Referenced by gpmp::stats::ProbDist::ConfidenceInterval(), and gpmp::stats::ProbDist::PivotFunctionForConfidenceInterval().
var_coeff()
double gpmp::stats::Describe::var_coeff (const std::vector< double > & data)
Calculates the coefficient of variation of a given dataset.
Parameters
data The input dataset
Returns
The coefficient of variation (in percentage)
Definition at line 135 of file describe.cpp.
{
     double mean = mean_arith(data);
     double stddev = stdev(data, mean);
     return (stddev / mean) * 100.0; // Multiply by 100 for percentage
 }
variance()
double gpmp::stats::Describe::variance (const std::vector< double > & data, double mean)
Calculates the variance of a given dataset, given the mean.
Parameters
data The input dataset
mean The mean of the dataset
Returns
The variance
Definition at line 181 of file describe.cpp.
{
     double sum = 0.0;
     for (const auto &value : data) {
         sum += std::pow(value - mean, 2.0);
     }
     return sum / static_cast<double>(data.size());
 }
Referenced by gpmp::stats::ProbDist::mom().
The documentation for this class was generated from the following files:
include/stats/describe.hpp
modules/stats/describe.cpp