openGPMP: modules/linalg/dgemm_nn.c File Reference
dgemm_nn.c File Reference
#include <stdio.h>
#include <time.h>
#include <emmintrin.h>
#include <immintrin.h>
#include <assert.h>
#include "dgemm_asm.h"
Macros
#define MC 384
#define KC 384
#define NC 4096
#define MR 4
#define NR 4
#define N 128
Functions
static double _A[MC *KC] __attribute__ ((aligned(16)))
void dgemm_kernel_asm (const double *A, const double *B, double *C, const double *nextA, const double *nextB, long kl, long kb, long incRowC, long incColC, double alpha, double beta)
static void pack_MRxk (int k, const double *A, int incRowA, int incColA, double *buffer)
static void pack_A (int mc, int kc, const double *A, int incRowA, int incColA, double *buffer)
static void pack_kxNR (int k, const double *B, int incRowB, int incColB, double *buffer)
static void pack_B (int kc, int nc, const double *B, int incRowB, int incColB, double *buffer)
static void dgemm_micro_kernel (long kc, double alpha, const double *A, const double *B, double beta, double *C, long incRowC, long incColC, const double *nextA, const double *nextB)
static void dgeaxpy (int m, int n, double alpha, const double *X, int incRowX, int incColX, double *Y, int incRowY, int incColY)
static void dgescal (int m, int n, double alpha, double *X, int incRowX, int incColX)
static void dgemm_macro_kernel (int mc, int nc, int kc, double alpha, double beta, double *C, int incRowC, int incColC)
void dgemm_nn (int m, int n, int k, double alpha, const double *A, int incRowA, int incColA, const double *B, int incRowB, int incColB, double beta, double *C, int incRowC, int incColC)
void fill_matrix (double *mat, int rows, int cols)
void print_matrix (double *mat, int rows, int cols)
void naive_matrix_multiply (double *A, double *B, double *C, int size)
int compare_matrices (double *mat1, double *mat2, int rows, int cols)
int main ()
Macro Definition Documentation
KC
#define KC 384
Definition at line 11 of file dgemm_nn.c.
MC
#define MC 384
Definition at line 10 of file dgemm_nn.c.
MR
#define MR 4
Definition at line 14 of file dgemm_nn.c.
N
#define N 128
Definition at line 728 of file dgemm_nn.c.
NC
#define NC 4096
Definition at line 12 of file dgemm_nn.c.
NR
#define NR 4
Definition at line 15 of file dgemm_nn.c.
Function Documentation
__attribute__()
static double _A [MC*KC] __attribute__ ((aligned(16))) static
compare_matrices()
int compare_matrices (double * mat1, double * mat2, int rows, int cols)
Definition at line 757 of file dgemm_nn.c.
{
     int count = 0;
     int matches = 0;
     int i;
     for (i = 0; i < rows * cols; ++i) {
         printf("Comparing element at index %d: %.2f vs %.2f\n", i, mat1[i], mat2[i]);
         if (mat1[i] != mat2[i]) {
             //return 0; // Matrices are not equal
             count++;
         }
         else {
             matches++;
         }
     }
     printf("MISMATCHES  / TOTAL : %d/%d\n", count, i);
     printf("MATCHES     / TOTAL : %d/%d\n", matches, i);
     return 1; // Matrices are equal
 }
References test_linalg::cols, and test_linalg::rows.
Referenced by main().
dgeaxpy()
static void dgeaxpy (int m, int n, double alpha, const double * X, int incRowX, int incColX, double * Y, int incRowY, int incColY) static
Definition at line 547 of file dgemm_nn.c.
 {
     int i, j;
     if (alpha!=1.0) {
         for (j=0; j<n; ++j) {
             for (i=0; i<m; ++i) {
                 Y[i*incRowY+j*incColY] += alpha*X[i*incRowX+j*incColX];
             }
         }
     } else {
         for (j=0; j<n; ++j) {
             for (i=0; i<m; ++i) {
                 Y[i*incRowY+j*incColY] += X[i*incRowX+j*incColX];
             }
         }
     }
 }
Referenced by gpmp::linalg::DGEMM::dgemm_macro_kernel(), and dgemm_macro_kernel().
dgemm_kernel_asm()
void dgemm_kernel_asm (const double * A, const double * B, double * C, const double * nextA, const double * nextB, long kl, long kb, long incRowC, long incColC, double alpha, double beta)
Referenced by dgemm_micro_kernel().
dgemm_macro_kernel()
static void dgemm_macro_kernel (int mc, int nc, int kc, double alpha, double beta, double * C, int incRowC, int incColC) static
Definition at line 608 of file dgemm_nn.c.
 {
     int mp = (mc+MR-1) / MR;
     int np = (nc+NR-1) / NR;
     int _mr = mc % MR;
     int _nr = nc % NR;
     int mr, nr;
     int i, j;
     const double *nextA;
     const double *nextB;
     for (j=0; j<np; ++j) {
         nr    = (j!=np-1 || _nr==0) ? NR : _nr;
         nextB = &_B[j*kc*NR];
         for (i=0; i<mp; ++i) {
             mr    = (i!=mp-1 || _mr==0) ? MR : _mr;
             nextA = &_A[(i+1)*kc*MR];
             if (i==mp-1) {
                 nextA = _A;
                 nextB = &_B[(j+1)*kc*NR];
                 if (j==np-1) {
                     nextB = _B;
                 }
             }
             if (mr==MR && nr==NR) {
                 dgemm_micro_kernel(kc, alpha, &_A[i*kc*MR], &_B[j*kc*NR],
                                    beta,
                                    &C[i*MR*incRowC+j*NR*incColC],
                                    incRowC, incColC,
                                    nextA, nextB);
             } else {
                 dgemm_micro_kernel(kc, alpha, &_A[i*kc*MR], &_B[j*kc*NR],
                                    0.0,
                                    _C, 1, MR,
                                    nextA, nextB);
                 dgescal(mr, nr, beta,
                         &C[i*MR*incRowC+j*NR*incColC], incRowC, incColC);
                 dgeaxpy(mr, nr, 1.0, _C, 1, MR,
                         &C[i*MR*incRowC+j*NR*incColC], incRowC, incColC);
             }
         }
     }
 }
References python.linalg::C, dgeaxpy(), dgemm_micro_kernel(), dgescal(), MR, and NR.
Referenced by gpmp::linalg::DGEMM::dgemm_nn(), and dgemm_nn().
dgemm_micro_kernel()
static void dgemm_micro_kernel (long kc, double alpha, const double * A, const double * B, double beta, double * C, long incRowC, long incColC, const double * nextA, const double * nextB) static
Definition at line 136 of file dgemm_nn.c.
 {
     long kb = kc / 4;
     long kl = kc % 4;
     /*
     printf("kb = %ld kl = %ld\n", kb, kl);
     printf("A[0] = %f B[0] = %f\n", A[0], B[0]);
     printf("nextA[0] = %f nextB[0] = %f\n", nextA[0], nextB[0]);
     printf("alpha = %f beta = %f\n", alpha, beta);
     printf("incRowC = %ld incColC = %ld\n", incRowC, incColC);
     */
     // maybe make the variables that are arrays go in thru the parameter
     // registers and the rest can be referenced via the stack
     // A, B, C, nextA, nextB all thru arg registers
     // kl, kb, alpha, beta, incRowC, incColC
     //dgemm_kernel_asm(kl, kb, A, B, nextA, nextB, alpha, beta, C, incRowC, incColC);
     dgemm_kernel_asm(A, B, C, nextA, nextB, kl, kb, incRowC, incColC, alpha, beta);
     //printf("populated C[0]=%f\n",C[0]);
 }
References python.linalg::A, python.linalg::B, python.linalg::C, and dgemm_kernel_asm().
Referenced by gpmp::linalg::DGEMM::dgemm_macro_kernel(), and dgemm_macro_kernel().
dgemm_nn()
void dgemm_nn (int m, int n, int k, double alpha, const double * A, int incRowA, int incColA, const double * B, int incRowB, int incColB, double beta, double * C, int incRowC, int incColC)
Definition at line 668 of file dgemm_nn.c.
 {
     int mb = (m+MC-1) / MC;
     int nb = (n+NC-1) / NC;
     int kb = (k+KC-1) / KC;
     int _mc = m % MC;
     int _nc = n % NC;
     int _kc = k % KC;
     int mc, nc, kc;
     int i, j, l;
     double _beta;
     if (alpha==0.0 || k==0) {
         dgescal(m, n, beta, C, incRowC, incColC);
         return;
     }
     for (j=0; j<nb; ++j) {
         nc = (j!=nb-1 || _nc==0) ? NC : _nc;
         for (l=0; l<kb; ++l) {
             kc    = (l!=kb-1 || _kc==0) ? KC   : _kc;
             _beta = (l==0) ? beta : 1.0;
             pack_B(kc, nc,
                    &B[l*KC*incRowB+j*NC*incColB], incRowB, incColB,
                    _B);
             for (i=0; i<mb; ++i) {
                 mc = (i!=mb-1 || _mc==0) ? MC : _mc;
                 pack_A(mc, kc,
                        &A[i*MC*incRowA+l*KC*incColA], incRowA, incColA,
                        _A);
                 dgemm_macro_kernel(mc, nc, kc, alpha, _beta,
                                    &C[i*MC*incRowC+j*NC*incColC],
                                    incRowC, incColC);
             }
         }
     }
 }
References python.linalg::A, python.linalg::B, python.linalg::C, dgemm_macro_kernel(), dgescal(), KC, MC, NC, pack_A(), and pack_B().
Referenced by main().
dgescal()
static void dgescal (int m, int n, double alpha, double * X, int incRowX, int incColX) static
Definition at line 579 of file dgemm_nn.c.
 {
     int i, j;
     if (alpha!=0.0) {
         for (j=0; j<n; ++j) {
             for (i=0; i<m; ++i) {
                 X[i*incRowX+j*incColX] *= alpha;
             }
         }
     } else {
         for (j=0; j<n; ++j) {
             for (i=0; i<m; ++i) {
                 X[i*incRowX+j*incColX] = 0.0;
             }
         }
     }
 }
Referenced by gpmp::linalg::DGEMM::dgemm_macro_kernel(), dgemm_macro_kernel(), gpmp::linalg::DGEMM::dgemm_nn(), and dgemm_nn().
fill_matrix()
void fill_matrix (double * mat, int rows, int cols)
Definition at line 730 of file dgemm_nn.c.
{
     for (int i = 0; i < rows * cols; ++i) {
         mat[i] = (double)rand() / RAND_MAX;
     }
 }
References test_linalg::cols, and test_linalg::rows.
Referenced by main().
main()
int main (void)
Definition at line 776 of file dgemm_nn.c.
            {
     double *A = (double *)malloc(N * N * sizeof(double));
     double *B = (double *)malloc(N * N * sizeof(double));
     double *C_naive = (double *)calloc(N * N, sizeof(double));
     double *C_optimized = (double *)calloc(N * N, sizeof(double));
     srand(time(NULL)); // Seed for random number generation
     printf("generating values for mtx\n");
     fill_matrix(A, N, N);
     fill_matrix(B, N, N);
     // Start timing for naive implementation
     clock_t start_naive = clock();
     naive_matrix_multiply(A, B, C_naive, N);
     clock_t end_naive = clock();
     double time_naive = (double)(end_naive - start_naive) / CLOCKS_PER_SEC;
     // Start timing for optimized implementation
     clock_t start_optimized = clock();
     dgemm_nn(N, N, N, 1.0, A, N, 1, B, N, 1, 0.0, C_optimized, N, 1);
     clock_t end_optimized = clock();
     double time_optimized = (double)(end_optimized - start_optimized) / CLOCKS_PER_SEC;
     printf("Naive implementation took %.6f seconds\n", time_naive);
     printf("Optimized implementation took %.6f seconds\n", time_optimized);
     //printf("\nMatrix C (Result of A * B):\n");
     //print_matrix(C_naive, N, N);
     //printf("\nOpt. Matrix C (Result of A * B):\n");
     //print_matrix(C_optimized, N, N);
     // Assert that the results are the same
     assert(compare_matrices(C_naive, C_optimized, N, N));
     // Free allocated memory
     free(A);
     free(B);
     free(C_naive);
     free(C_optimized);
     return 0;
 }
References python.linalg::A, python.linalg::B, compare_matrices(), dgemm_nn(), fill_matrix(), N, and naive_matrix_multiply().
naive_matrix_multiply()
void naive_matrix_multiply (double * A, double * B, double * C, int size)
Definition at line 745 of file dgemm_nn.c.
{
     for (int i = 0; i < size; ++i) {
         for (int j = 0; j < size; ++j) {
             double sum = 0.0;
             for (int k = 0; k < size; ++k) {
                 sum += A[i * size + k] * B[k * size + j];
             }
             C[i * size + j] = sum;
         }
     }
 }
References python.linalg::A, python.linalg::B, and python.linalg::C.
Referenced by main().
pack_A()
static void pack_A (int mc, int kc, const double * A, int incRowA, int incColA, double * buffer) static
Definition at line 56 of file dgemm_nn.c.
 {
     int mp  = mc / MR;
     int _mr = mc % MR;
     int i, j;
     for (i=0; i<mp; ++i) {
         pack_MRxk(kc, A, incRowA, incColA, buffer);
         buffer += kc*MR;
         A      += MR*incRowA;
     }
     if (_mr>0) {
         for (j=0; j<kc; ++j) {
             for (i=0; i<_mr; ++i) {
                 buffer[i] = A[i*incRowA];
             }
             for (i=_mr; i<MR; ++i) {
                 buffer[i] = 0.0;
             }
             buffer += MR;
             A      += incColA;
         }
     }
 }
References python.linalg::A, MR, and pack_MRxk().
Referenced by dgemm_nn().
pack_B()
static void pack_B (int kc, int nc, const double * B, int incRowB, int incColB, double * buffer) static
Definition at line 105 of file dgemm_nn.c.
 {
     int np  = nc / NR;
     int _nr = nc % NR;
     int i, j;
     for (j=0; j<np; ++j) {
         pack_kxNR(kc, B, incRowB, incColB, buffer);
         buffer += kc*NR;
         B      += NR*incColB;
     }
     if (_nr>0) {
         for (i=0; i<kc; ++i) {
             for (j=0; j<_nr; ++j) {
                 buffer[j] = B[j*incColB];
             }
             for (j=_nr; j<NR; ++j) {
                 buffer[j] = 0.0;
             }
             buffer += NR;
             B      += incRowB;
         }
     }
 }
References python.linalg::B, NR, and pack_kxNR().
Referenced by dgemm_nn().
pack_kxNR()
static void pack_kxNR (int k, const double * B, int incRowB, int incColB, double * buffer) static
Definition at line 87 of file dgemm_nn.c.
 {
     int i, j;
     for (i=0; i<k; ++i) {
         for (j=0; j<NR; ++j) {
             buffer[j] = B[j*incColB];
         }
         buffer += NR;
         B      += incRowB;
     }
 }
References python.linalg::B, and NR.
Referenced by pack_B().
pack_MRxk()
static void pack_MRxk (int k, const double * A, int incRowA, int incColA, double * buffer) static
Definition at line 38 of file dgemm_nn.c.
 {
     int i, j;
     for (j=0; j<k; ++j) {
         for (i=0; i<MR; ++i) {
             buffer[i] = A[i*incRowA];
         }
         buffer += MR;
         A      += incColA;
     }
 }
References python.linalg::A, and MR.
Referenced by pack_A().
print_matrix()
void print_matrix (double * mat, int rows, int cols)
Definition at line 736 of file dgemm_nn.c.
{
     for (int i = 0; i < rows; ++i) {
         for (int j = 0; j < cols; ++j) {
             printf("%.2f ", mat[i * cols + j]);
         }
         printf("\n");
     }
 }
References test_linalg::cols, and test_linalg::rows.