openMTPK: Fortran/lib/openMTPK_wrap.cxx File Reference
openMTPK_wrap.cxx File Reference
#include <stdexcept>
#include <string>
#include "../../include/number_theory/primes.hpp"
#include "../../include/number_theory/rc4.hpp"
#include "../../include/number_theory/cipher.hpp"
#include <stdlib.h>
#include <string.h>
Classes
struct SwigClassWrapper
struct swig::DestructorPolicy< T, A >
struct swig::DestructorPolicy< T, ASSIGNMENT_NODESTRUCT >
struct swig::AssignmentPolicy< T, A >
struct swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >
struct SwigArrayWrapper
Namespaces
swig
Macros
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIGEXTERN
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) { throw std::logic_error("In " DECL ": " MSG); }
#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL)
#define SWIG_VERSION 0x040101
#define SWIGFORTRAN
#define SWIGPOLICY_Primality swig::ASSIGNMENT_DEFAULT
#define SWIGPOLICY_RC4 swig::ASSIGNMENT_DEFAULT
#define SWIGPOLICY_Cipher swig::ASSIGNMENT_DEFAULT
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); }
#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a))
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a))
Enumerations
enum SwigMemFlags { SWIG_MEM_OWN = 0x01 , SWIG_MEM_RVALUE = 0x02 }
enum swig::AssignmentType { swig::ASSIGNMENT_DEFAULT , swig::ASSIGNMENT_NODESTRUCT , swig::ASSIGNMENT_SMARTPTR }
Functions
SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized ()
SWIGINTERN SwigClassWrapper swig::capture (SwigClassWrapper other)
template<class T , swig::AssignmentType A>
SWIGINTERN void SWIG_assign (SwigClassWrapper *self, SwigClassWrapper other)
template<class T , swig::AssignmentType A>
SWIGINTERN void SWIG_free_rvalue (SwigClassWrapper other)
SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized ()
SWIGEXPORT int _wrap_Primality_is_prime (SwigClassWrapper *farg1, int const *farg2)
SWIGEXPORT int _wrap_Primality_compute_miller_rabin (SwigClassWrapper *farg1, int const *farg2, int const *farg3)
SWIGEXPORT int _wrap_Primality_miller_rabin_prime (SwigClassWrapper *farg1, int const *farg2, int const *farg3)
SWIGEXPORT void _wrap_Primality_miller_rabin (SwigClassWrapper *farg1, int const *farg2, int const *farg3, int const *farg4)
SWIGEXPORT int _wrap_Primality_jacobian_number (SwigClassWrapper *farg1, long long const *farg2, long long const *farg3)
SWIGEXPORT int _wrap_Primality_solovoy_strassen (SwigClassWrapper *farg1, long long const *farg2, int const *farg3)
SWIGEXPORT long long _wrap_Primality_mod_pow (SwigClassWrapper *farg1, long long const *farg2, long long const *farg3, long long const *farg4)
SWIGEXPORT int _wrap_Primality_carmichael_num (SwigClassWrapper *farg1, int const *farg2)
SWIGEXPORT void _wrap_Primality_sieve_of_eratosthenes (SwigClassWrapper *farg1, int const *farg2)
SWIGEXPORT long long _wrap_Primality_pollard_rho (SwigClassWrapper *farg1, long long const *farg2)
SWIGEXPORT int _wrap_Primality_ETF (SwigClassWrapper *farg1, int const *farg2)
SWIGEXPORT SwigClassWrapper _wrap_new_Primality ()
SWIGEXPORT void _wrap_delete_Primality (SwigClassWrapper *farg1)
SWIGEXPORT void _wrap_Primality_op_assign__ (SwigClassWrapper *farg1, SwigClassWrapper *farg2)
SWIGEXPORT int _wrap_BITS_get ()
SWIGEXPORT int _wrap_BYTE_LIMIT_get ()
SWIGEXPORT void _wrap_RC4_byte_swap (SwigClassWrapper *farg1, SwigClassWrapper *farg2, SwigClassWrapper *farg3)
SWIGEXPORT void _wrap_RC4_trad_swap (SwigClassWrapper *farg1, SwigClassWrapper *farg2, SwigClassWrapper *farg3)
SWIGEXPORT void _wrap_RC4_XOR_swap (SwigClassWrapper *farg1, SwigClassWrapper *farg2, SwigClassWrapper *farg3)
SWIGEXPORT void _wrap_RC4_KSA (SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigClassWrapper *farg3, int const *farg4)
SWIGEXPORT void _wrap_RC4_PRGA (SwigClassWrapper *farg1, SwigClassWrapper *farg2, SwigArrayWrapper *farg3, SwigClassWrapper *farg4, int const *farg5)
SWIGEXPORT SwigArrayWrapper _wrap_RC4_store_hash (SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigClassWrapper *farg3, int const *farg4)
SWIGEXPORT SwigClassWrapper _wrap_RC4_compute (SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3, SwigClassWrapper *farg4, int const *farg5)
SWIGEXPORT SwigClassWrapper _wrap_new_RC4 ()
SWIGEXPORT void _wrap_delete_RC4 (SwigClassWrapper *farg1)
SWIGEXPORT void _wrap_RC4_op_assign__ (SwigClassWrapper *farg1, SwigClassWrapper *farg2)
SWIGEXPORT SwigArrayWrapper _wrap_Cipher_C_cipher (SwigClassWrapper *farg1, SwigArrayWrapper *farg2, int const *farg3)
SWIGEXPORT SwigArrayWrapper _wrap_Cipher_KC_encode (SwigClassWrapper *farg1, SwigArrayWrapper *farg2)
SWIGEXPORT SwigArrayWrapper _wrap_Cipher_KC_cipher (SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3)
SWIGEXPORT SwigClassWrapper _wrap_new_Cipher ()
SWIGEXPORT void _wrap_delete_Cipher (SwigClassWrapper *farg1)
SWIGEXPORT void _wrap_Cipher_op_assign__ (SwigClassWrapper *farg1, SwigClassWrapper *farg2)
Macro Definition Documentation
SWIG_as_voidptr
#define SWIG_as_voidptr (a) const_cast< void * >(static_cast< const void * >(a))
Definition at line 236 of file openMTPK_wrap.cxx.
SWIG_as_voidptrptr
#define SWIG_as_voidptrptr (a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a))
Definition at line 237 of file openMTPK_wrap.cxx.
SWIG_check_nonnull
#define SWIG_check_nonnull (PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL)
Value:
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }
Definition at line 152 of file openMTPK_wrap.cxx.
SWIG_contract_assert
#define SWIG_contract_assert (RETURNNULL, EXPR, MSG) if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); }
Definition at line 232 of file openMTPK_wrap.cxx.
SWIG_exception_impl
#define SWIG_exception_impl (DECL, CODE, MSG, RETURNNULL) { throw std::logic_error("In " DECL ": " MSG); }
Definition at line 142 of file openMTPK_wrap.cxx.
SWIG_VERSION
#define SWIG_VERSION 0x040101
Definition at line 170 of file openMTPK_wrap.cxx.
SWIGEXPORT
#define SWIGEXPORT
Definition at line 94 of file openMTPK_wrap.cxx.
SWIGEXTERN
#define SWIGEXTERN
Definition at line 137 of file openMTPK_wrap.cxx.
SWIGFORTRAN
#define SWIGFORTRAN
Definition at line 171 of file openMTPK_wrap.cxx.
SWIGINLINE
#define SWIGINLINE
Definition at line 31 of file openMTPK_wrap.cxx.
SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
Definition at line 66 of file openMTPK_wrap.cxx.
SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
Definition at line 71 of file openMTPK_wrap.cxx.
SWIGPOLICY_Cipher
#define SWIGPOLICY_Cipher swig::ASSIGNMENT_DEFAULT
Definition at line 174 of file openMTPK_wrap.cxx.
SWIGPOLICY_Primality
#define SWIGPOLICY_Primality swig::ASSIGNMENT_DEFAULT
Definition at line 172 of file openMTPK_wrap.cxx.
SWIGPOLICY_RC4
#define SWIGPOLICY_RC4 swig::ASSIGNMENT_DEFAULT
Definition at line 173 of file openMTPK_wrap.cxx.
SWIGSTDCALL
#define SWIGSTDCALL
Definition at line 104 of file openMTPK_wrap.cxx.
SWIGTEMPLATEDISAMBIGUATOR
#define SWIGTEMPLATEDISAMBIGUATOR
Definition at line 22 of file openMTPK_wrap.cxx.
SWIGUNUSED
#define SWIGUNUSED
Definition at line 46 of file openMTPK_wrap.cxx.
SWIGUNUSEDPARM
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
Definition at line 60 of file openMTPK_wrap.cxx.
Enumeration Type Documentation
SwigMemFlags
enum SwigMemFlags
Enumerator
SWIG_MEM_OWN
SWIG_MEM_RVALUE
Definition at line 146 of file openMTPK_wrap.cxx.
                   {
     SWIG_MEM_OWN = 0x01,
     SWIG_MEM_RVALUE = 0x02,
 };
Function Documentation
_wrap_BITS_get()
SWIGEXPORT int _wrap_BITS_get ()
Definition at line 612 of file openMTPK_wrap.cxx.
{
   int fresult ;
   int result;
   result = (int)(255);
   fresult = (int)(result);
   return fresult;
 }
_wrap_BYTE_LIMIT_get()
SWIGEXPORT int _wrap_BYTE_LIMIT_get ()
Definition at line 622 of file openMTPK_wrap.cxx.
{
   int fresult ;
   int result;
   result = (int)(256);
   fresult = (int)(result);
   return fresult;
 }
_wrap_Cipher_C_cipher()
SWIGEXPORT SwigArrayWrapper _wrap_Cipher_C_cipher (SwigClassWrapper * farg1, SwigArrayWrapper * farg2, int const * farg3)
Definition at line 780 of file openMTPK_wrap.cxx.
{
   SwigArrayWrapper fresult ;
   Cipher *arg1 = (Cipher *) 0 ;
   std::string arg2 ;
   int arg3 ;
   std::string result;
   SWIG_check_nonnull(farg1->cptr, "Cipher *", "Cipher", "Cipher::C_cipher(std::string,int)", return SwigArrayWrapper_uninitialized());
   arg1 = (Cipher *)farg1->cptr;
   (&arg2)->assign(static_cast<char *>(farg2->data), farg2->size);
   arg3 = (int)(*farg3);
   result = (arg1)->C_cipher(arg2,arg3);
   fresult.size = (&result)->size();
   if (fresult.size > 0) {
     fresult.data = malloc(fresult.size);
     memcpy(fresult.data, (&result)->c_str(), fresult.size);
   } else {
     fresult.data = NULL;
   }
   return fresult;
 }
References SwigClassWrapper::cptr, SwigArrayWrapper::data, SwigArrayWrapper::size, SWIG_check_nonnull, and SwigArrayWrapper_uninitialized().
_wrap_Cipher_KC_cipher()
SWIGEXPORT SwigArrayWrapper _wrap_Cipher_KC_cipher (SwigClassWrapper * farg1, SwigArrayWrapper * farg2, SwigArrayWrapper * farg3)
Definition at line 824 of file openMTPK_wrap.cxx.
{
   SwigArrayWrapper fresult ;
   Cipher *arg1 = (Cipher *) 0 ;
   std::string arg2 ;
   std::string arg3 ;
   std::string result;
   SWIG_check_nonnull(farg1->cptr, "Cipher *", "Cipher", "Cipher::KC_cipher(std::string,std::string)", return SwigArrayWrapper_uninitialized());
   arg1 = (Cipher *)farg1->cptr;
   (&arg2)->assign(static_cast<char *>(farg2->data), farg2->size);
   (&arg3)->assign(static_cast<char *>(farg3->data), farg3->size);
   result = (arg1)->KC_cipher(arg2,arg3);
   fresult.size = (&result)->size();
   if (fresult.size > 0) {
     fresult.data = malloc(fresult.size);
     memcpy(fresult.data, (&result)->c_str(), fresult.size);
   } else {
     fresult.data = NULL;
   }
   return fresult;
 }
References SwigClassWrapper::cptr, SwigArrayWrapper::data, SwigArrayWrapper::size, SWIG_check_nonnull, and SwigArrayWrapper_uninitialized().
_wrap_Cipher_KC_encode()
SWIGEXPORT SwigArrayWrapper _wrap_Cipher_KC_encode (SwigClassWrapper * farg1, SwigArrayWrapper * farg2)
Definition at line 803 of file openMTPK_wrap.cxx.
{
   SwigArrayWrapper fresult ;
   Cipher *arg1 = (Cipher *) 0 ;
   std::string arg2 ;
   std::string result;
   SWIG_check_nonnull(farg1->cptr, "Cipher *", "Cipher", "Cipher::KC_encode(std::string)", return SwigArrayWrapper_uninitialized());
   arg1 = (Cipher *)farg1->cptr;
   (&arg2)->assign(static_cast<char *>(farg2->data), farg2->size);
   result = (arg1)->KC_encode(arg2);
   fresult.size = (&result)->size();
   if (fresult.size > 0) {
     fresult.data = malloc(fresult.size);
     memcpy(fresult.data, (&result)->c_str(), fresult.size);
   } else {
     fresult.data = NULL;
   }
   return fresult;
 }
References SwigClassWrapper::cptr, SwigArrayWrapper::data, SwigArrayWrapper::size, SWIG_check_nonnull, and SwigArrayWrapper_uninitialized().
_wrap_Cipher_op_assign__()
SWIGEXPORT void _wrap_Cipher_op_assign__ (SwigClassWrapper * farg1, SwigClassWrapper * farg2)
Definition at line 866 of file openMTPK_wrap.cxx.
{
   Cipher *arg1 = (Cipher *) 0 ;
   Cipher *arg2 = 0 ;
   (void)sizeof(arg1);
   (void)sizeof(arg2);
   SWIG_assign<Cipher, SWIGPOLICY_Cipher>(farg1, *farg2);
 }
_wrap_delete_Cipher()
SWIGEXPORT void _wrap_delete_Cipher (SwigClassWrapper * farg1)
Definition at line 858 of file openMTPK_wrap.cxx.
{
   Cipher *arg1 = (Cipher *) 0 ;
   arg1 = (Cipher *)farg1->cptr;
   delete arg1;
 }
References SwigClassWrapper::cptr.
_wrap_delete_Primality()
SWIGEXPORT void _wrap_delete_Primality (SwigClassWrapper * farg1)
Definition at line 593 of file openMTPK_wrap.cxx.
{
   Primality *arg1 = (Primality *) 0 ;
   arg1 = (Primality *)farg1->cptr;
   delete arg1;
 }
References SwigClassWrapper::cptr.
_wrap_delete_RC4()
SWIGEXPORT void _wrap_delete_RC4 (SwigClassWrapper * farg1)
Definition at line 761 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   arg1 = (RC4 *)farg1->cptr;
   delete arg1;
 }
References SwigClassWrapper::cptr.
_wrap_new_Cipher()
SWIGEXPORT SwigClassWrapper _wrap_new_Cipher ()
Definition at line 847 of file openMTPK_wrap.cxx.
{
   SwigClassWrapper fresult ;
   Cipher *result = 0 ;
   result = (Cipher *)new Cipher();
   fresult.cptr = (void*)result;
   fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
   return fresult;
 }
References SwigClassWrapper::cmemflags, SwigClassWrapper::cptr, SWIG_MEM_OWN, and SWIG_MEM_RVALUE.
_wrap_new_Primality()
SWIGEXPORT SwigClassWrapper _wrap_new_Primality ()
Definition at line 582 of file openMTPK_wrap.cxx.
{
   SwigClassWrapper fresult ;
   Primality *result = 0 ;
   result = (Primality *)new Primality();
   fresult.cptr = (void*)result;
   fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
   return fresult;
 }
References SwigClassWrapper::cmemflags, SwigClassWrapper::cptr, SWIG_MEM_OWN, and SWIG_MEM_RVALUE.
_wrap_new_RC4()
SWIGEXPORT SwigClassWrapper _wrap_new_RC4 ()
Definition at line 750 of file openMTPK_wrap.cxx.
{
   SwigClassWrapper fresult ;
   RC4 *result = 0 ;
   result = (RC4 *)new RC4();
   fresult.cptr = (void*)result;
   fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
   return fresult;
 }
References SwigClassWrapper::cmemflags, SwigClassWrapper::cptr, SWIG_MEM_OWN, and SWIG_MEM_RVALUE.
_wrap_Primality_carmichael_num()
SWIGEXPORT int _wrap_Primality_carmichael_num (SwigClassWrapper * farg1, int const * farg2)
Definition at line 526 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   bool result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::carmichael_num(int)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (int)(*farg2);
   result = (bool)(arg1)->carmichael_num(arg2);
   fresult = (result ? 1 : 0);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_compute_miller_rabin()
SWIGEXPORT int _wrap_Primality_compute_miller_rabin (SwigClassWrapper * farg1, int const * farg2, int const * farg3)
Definition at line 424 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   int arg3 ;
   bool result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::compute_miller_rabin(int,int)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (int)(*farg2);
   arg3 = (int)(*farg3);
   result = (bool)(arg1)->compute_miller_rabin(arg2,arg3);
   fresult = (result ? 1 : 0);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_ETF()
SWIGEXPORT int _wrap_Primality_ETF (SwigClassWrapper * farg1, int const * farg2)
Definition at line 567 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   unsigned int arg2 ;
   int result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::ETF(unsigned int)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (unsigned int)(*farg2);
   result = (int)(arg1)->ETF(arg2);
   fresult = (int)(result);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_is_prime()
SWIGEXPORT int _wrap_Primality_is_prime (SwigClassWrapper * farg1, int const * farg2)
Definition at line 409 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   bool result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::is_prime(int)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (int)(*farg2);
   result = (bool)(arg1)->is_prime(arg2);
   fresult = (result ? 1 : 0);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_jacobian_number()
SWIGEXPORT int _wrap_Primality_jacobian_number (SwigClassWrapper * farg1, long long const * farg2, long long const * farg3)
Definition at line 473 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   long long arg3 ;
   int result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::jacobian_number(long long,long long)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (long long)(*farg2);
   arg3 = (long long)(*farg3);
   result = (int)(arg1)->jacobian_number(arg2,arg3);
   fresult = (int)(result);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_miller_rabin()
SWIGEXPORT void _wrap_Primality_miller_rabin (SwigClassWrapper * farg1, int const * farg2, int const * farg3, int const * farg4)
Definition at line 458 of file openMTPK_wrap.cxx.
{
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   int arg3 ;
   int arg4 ;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::miller_rabin(int,int,int)", return );
   arg1 = (Primality *)farg1->cptr;
   arg2 = (int)(*farg2);
   arg3 = (int)(*farg3);
   arg4 = (int)(*farg4);
   (arg1)->miller_rabin(arg2,arg3,arg4);
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_miller_rabin_prime()
SWIGEXPORT int _wrap_Primality_miller_rabin_prime (SwigClassWrapper * farg1, int const * farg2, int const * farg3)
Definition at line 441 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   int arg3 ;
   bool result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::miller_rabin_prime(int,int)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (int)(*farg2);
   arg3 = (int)(*farg3);
   result = (bool)(arg1)->miller_rabin_prime(arg2,arg3);
   fresult = (result ? 1 : 0);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_mod_pow()
SWIGEXPORT long long _wrap_Primality_mod_pow (SwigClassWrapper * farg1, long long const * farg2, long long const * farg3, long long const * farg4)
Definition at line 507 of file openMTPK_wrap.cxx.
{
   long long fresult ;
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   long long arg3 ;
   long long arg4 ;
   long long result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::mod_pow(long long,long long,long long)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (long long)(*farg2);
   arg3 = (long long)(*farg3);
   arg4 = (long long)(*farg4);
   result = (long long)(arg1)->mod_pow(arg2,arg3,arg4);
   fresult = (long long)(result);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_op_assign__()
SWIGEXPORT void _wrap_Primality_op_assign__ (SwigClassWrapper * farg1, SwigClassWrapper * farg2)
Definition at line 601 of file openMTPK_wrap.cxx.
{
   Primality *arg1 = (Primality *) 0 ;
   Primality *arg2 = 0 ;
   (void)sizeof(arg1);
   (void)sizeof(arg2);
   SWIG_assign<Primality, SWIGPOLICY_Primality>(farg1, *farg2);
 }
_wrap_Primality_pollard_rho()
SWIGEXPORT long long _wrap_Primality_pollard_rho (SwigClassWrapper * farg1, long long const * farg2)
Definition at line 552 of file openMTPK_wrap.cxx.
{
   long long fresult ;
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   long long result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::pollard_rho(long long)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (long long)(*farg2);
   result = (long long)(arg1)->pollard_rho(arg2);
   fresult = (long long)(result);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_sieve_of_eratosthenes()
SWIGEXPORT void _wrap_Primality_sieve_of_eratosthenes (SwigClassWrapper * farg1, int const * farg2)
Definition at line 541 of file openMTPK_wrap.cxx.
{
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::sieve_of_eratosthenes(int)", return );
   arg1 = (Primality *)farg1->cptr;
   arg2 = (int)(*farg2);
   (arg1)->sieve_of_eratosthenes(arg2);
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_Primality_solovoy_strassen()
SWIGEXPORT int _wrap_Primality_solovoy_strassen (SwigClassWrapper * farg1, long long const * farg2, int const * farg3)
Definition at line 490 of file openMTPK_wrap.cxx.
{
   int fresult ;
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   int arg3 ;
   bool result;
   SWIG_check_nonnull(farg1->cptr, "Primality *", "Primality", "Primality::solovoy_strassen(long long,int)", return 0);
   arg1 = (Primality *)farg1->cptr;
   arg2 = (long long)(*farg2);
   arg3 = (int)(*farg3);
   result = (bool)(arg1)->solovoy_strassen(arg2,arg3);
   fresult = (result ? 1 : 0);
   return fresult;
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_RC4_byte_swap()
SWIGEXPORT void _wrap_RC4_byte_swap (SwigClassWrapper * farg1, SwigClassWrapper * farg2, SwigClassWrapper * farg3)
Definition at line 632 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   uint8_t *arg2 = (uint8_t *) 0 ;
   uint8_t *arg3 = (uint8_t *) 0 ;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::byte_swap(uint8_t *,uint8_t *)", return );
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (uint8_t *)farg2->cptr;
   arg3 = (uint8_t *)farg3->cptr;
   (arg1)->byte_swap(arg2,arg3);
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_RC4_compute()
SWIGEXPORT SwigClassWrapper _wrap_RC4_compute (SwigClassWrapper * farg1, SwigArrayWrapper * farg2, SwigArrayWrapper * farg3, SwigClassWrapper * farg4, int const * farg5)
Definition at line 728 of file openMTPK_wrap.cxx.
{
   SwigClassWrapper fresult ;
   RC4 *arg1 = (RC4 *) 0 ;
   char *arg2 = (char *) 0 ;
   char *arg3 = (char *) 0 ;
   unsigned char *arg4 = (unsigned char *) 0 ;
   int arg5 ;
   unsigned char *result = 0 ;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::compute(char *,char *,unsigned char *,int)", return SwigClassWrapper_uninitialized());
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (char *)(farg2->data);
   arg3 = (char *)(farg3->data);
   arg4 = (unsigned char *)farg4->cptr;
   arg5 = (int)(*farg5);
   result = (unsigned char *)(arg1)->compute(arg2,arg3,arg4,arg5);
   fresult.cptr = (void*)result;
   fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
   return fresult;
 }
References SwigClassWrapper::cmemflags, SwigClassWrapper::cptr, SwigArrayWrapper::data, SWIG_check_nonnull, SWIG_MEM_OWN, SWIG_MEM_RVALUE, and SwigClassWrapper_uninitialized().
_wrap_RC4_KSA()
SWIGEXPORT void _wrap_RC4_KSA (SwigClassWrapper * farg1, SwigArrayWrapper * farg2, SwigClassWrapper * farg3, int const * farg4)
Definition at line 671 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   char *arg2 = (char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   int arg4 ;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::KSA(char *,unsigned char *,int)", return );
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (char *)(farg2->data);
   arg3 = (unsigned char *)farg3->cptr;
   arg4 = (int)(*farg4);
   (arg1)->KSA(arg2,arg3,arg4);
 }
References SwigClassWrapper::cptr, SwigArrayWrapper::data, and SWIG_check_nonnull.
_wrap_RC4_op_assign__()
SWIGEXPORT void _wrap_RC4_op_assign__ (SwigClassWrapper * farg1, SwigClassWrapper * farg2)
Definition at line 769 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   RC4 *arg2 = 0 ;
   (void)sizeof(arg1);
   (void)sizeof(arg2);
   SWIG_assign<RC4, SWIGPOLICY_RC4>(farg1, *farg2);
 }
_wrap_RC4_PRGA()
SWIGEXPORT void _wrap_RC4_PRGA (SwigClassWrapper * farg1, SwigClassWrapper * farg2, SwigArrayWrapper * farg3, SwigClassWrapper * farg4, int const * farg5)
Definition at line 686 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   unsigned char *arg2 = (unsigned char *) 0 ;
   char *arg3 = (char *) 0 ;
   unsigned char *arg4 = (unsigned char *) 0 ;
   int arg5 ;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::PRGA(unsigned char *,char *,unsigned char *,int)", return );
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (unsigned char *)farg2->cptr;
   arg3 = (char *)(farg3->data);
   arg4 = (unsigned char *)farg4->cptr;
   arg5 = (int)(*farg5);
   (arg1)->PRGA(arg2,arg3,arg4,arg5);
 }
References SwigClassWrapper::cptr, SwigArrayWrapper::data, and SWIG_check_nonnull.
_wrap_RC4_store_hash()
SWIGEXPORT SwigArrayWrapper _wrap_RC4_store_hash (SwigClassWrapper * farg1, SwigArrayWrapper * farg2, SwigClassWrapper * farg3, int const * farg4)
Definition at line 703 of file openMTPK_wrap.cxx.
{
   SwigArrayWrapper fresult ;
   RC4 *arg1 = (RC4 *) 0 ;
   char *arg2 = (char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   int arg4 ;
   std::string result;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::store_hash(char *,unsigned char *,int)", return SwigArrayWrapper_uninitialized());
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (char *)(farg2->data);
   arg3 = (unsigned char *)farg3->cptr;
   arg4 = (int)(*farg4);
   result = (arg1)->store_hash(arg2,arg3,arg4);
   fresult.size = (&result)->size();
   if (fresult.size > 0) {
     fresult.data = malloc(fresult.size);
     memcpy(fresult.data, (&result)->c_str(), fresult.size);
   } else {
     fresult.data = NULL;
   }
   return fresult;
 }
References SwigClassWrapper::cptr, SwigArrayWrapper::data, SwigArrayWrapper::size, SWIG_check_nonnull, and SwigArrayWrapper_uninitialized().
_wrap_RC4_trad_swap()
SWIGEXPORT void _wrap_RC4_trad_swap (SwigClassWrapper * farg1, SwigClassWrapper * farg2, SwigClassWrapper * farg3)
Definition at line 645 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   unsigned char *arg2 = (unsigned char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::trad_swap(unsigned char *,unsigned char *)", return );
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (unsigned char *)farg2->cptr;
   arg3 = (unsigned char *)farg3->cptr;
   (arg1)->trad_swap(arg2,arg3);
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
_wrap_RC4_XOR_swap()
SWIGEXPORT void _wrap_RC4_XOR_swap (SwigClassWrapper * farg1, SwigClassWrapper * farg2, SwigClassWrapper * farg3)
Definition at line 658 of file openMTPK_wrap.cxx.
{
   RC4 *arg1 = (RC4 *) 0 ;
   unsigned char *arg2 = (unsigned char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   SWIG_check_nonnull(farg1->cptr, "RC4 *", "RC4", "RC4::XOR_swap(unsigned char *,unsigned char *)", return );
   arg1 = (RC4 *)farg1->cptr;
   arg2 = (unsigned char *)farg2->cptr;
   arg3 = (unsigned char *)farg3->cptr;
   (arg1)->XOR_swap(arg2,arg3);
 }
References SwigClassWrapper::cptr, and SWIG_check_nonnull.
SWIG_assign()
template<class T , swig::AssignmentType A> SWIGINTERN void SWIG_assign (SwigClassWrapper * self, SwigClassWrapper other)
Definition at line 342 of file openMTPK_wrap.cxx.
{
   typedef swig::AssignmentPolicy<T, A> Policy_t;
   if (self->cptr == NULL) {
     /* LHS is unassigned */
     if (other.cmemflags & SWIG_MEM_RVALUE) {
       /* Capture pointer from RHS, clear 'moving' flag */
       *self = swig::capture(other);
     } else {
       /* Aliasing another class; clear ownership or copy smart pointer */
       *self = Policy_t::alias(other);
     }
   } else if (other.cptr == NULL) {
     /* Replace LHS with a null pointer */
     *self = Policy_t::destroy(*self);
   } else if (self->cptr == other.cptr) {
     /* Self-assignment: ignore */
   } else if (other.cmemflags & SWIG_MEM_RVALUE) {
     /* Transferred ownership from a variable that's about to be lost.
      * Move-assign and delete the transient data */
     *self = Policy_t::move_alias(*self, other);
   } else {
     /* RHS shouldn't be deleted, alias to LHS */
     *self = Policy_t::copy_alias(*self, other);
   }
 }
References swig::capture(), SwigClassWrapper::cmemflags, SwigClassWrapper::cptr, and SWIG_MEM_RVALUE.
SWIG_free_rvalue()
template<class T , swig::AssignmentType A> SWIGINTERN void SWIG_free_rvalue (SwigClassWrapper other)
Definition at line 370 of file openMTPK_wrap.cxx.
{
   typedef swig::AssignmentPolicy<T, A> Policy_t;
   if (other.cmemflags & SWIG_MEM_RVALUE
       && other.cmemflags & SWIG_MEM_OWN) {
     /* We own *and* are being passed an expiring value */
     Policy_t::destroy(other);
   }
 }
References SwigClassWrapper::cmemflags, SWIG_MEM_OWN, and SWIG_MEM_RVALUE.
SwigArrayWrapper_uninitialized()
SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized ()
Definition at line 398 of file openMTPK_wrap.cxx.
{
   SwigArrayWrapper result;
   result.data = NULL;
   result.size = 0;
   return result;
 }
References SwigArrayWrapper::data, and SwigArrayWrapper::size.
Referenced by _wrap_Cipher_C_cipher(), _wrap_Cipher_KC_cipher(), _wrap_Cipher_KC_encode(), and _wrap_RC4_store_hash().
SwigClassWrapper_uninitialized()
SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized ()
Definition at line 256 of file openMTPK_wrap.cxx.
{
     SwigClassWrapper result;
     result.cptr = NULL;
     result.cmemflags = 0;
     return result;
 }
References SwigClassWrapper::cmemflags, and SwigClassWrapper::cptr.
Referenced by _wrap_RC4_compute(), swig::DestructorPolicy< T, A >::destroy(), and swig::DestructorPolicy< T, ASSIGNMENT_NODESTRUCT >::destroy().