To do the homeworks you need to use python; it is recommended to
install/use [[https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html][anaconda/miniconda]], with either
- one of the [[https://docs.anaconda.com/anaconda/user-guide/tasks/integration/index.html][IDEs described on the anaconda docs]]

** Instructions for conda

After [[https://docs.conda.io/en/latest/miniconda.html][downloading conda]] you can install all packages for this class,
same versions that my professor used, via:

#+begin_src shell-script
conda env create -f https://raw.githubusercontent.com/tdhock/cs499-599-fall-2022/master/environment.yml
#+end_src

OR (less memory usage):

#+begin_src shell-script
conda env create -f https://raw.githubusercontent.com/tdhock/cs499-599-fall-2022/master/environment-p39only.yml
pip install torchtext plotnine numpy pandas pillow scikit-image
#+end_src

That should create a new "cs499f22" python environment with the
required packages. Before you activate an environment, you need to
setup your shell for the first time.

#+begin_src shell-script
conda init bash
#+end_src

That should put some code in your ~/.bash_profile, After restarting 
your shell you should see a (base) prefix in your prompt, which 
indicates the name of the currently activated conda environment.  
You can activate another environment via

#+begin_src shell-script
conda activate cs499f22
#+end_src

After activation, that environment will be used for new python
processes, looking for python modules, etc.

