openMTPK: modules/nt/logarithms.cpp File Reference
logarithms.cpp File Reference
#include "../../include/nt/logarithms.hpp"
#include "../../include/arithmetic.hpp"
#include "../../include/nt/primes.hpp"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <unordered_map>
Functions
int64_t pollard_rho_log (int g, int y, int p)
int main ()
Variables
mtpk::Primality log_primes
Function Documentation
main()
int main ()
Definition at line 126 of file logarithms.cpp.
            {
     mtpk::Logarithms logs;
     int64_t g = 3;
     int64_t y = 7;
     int64_t p = 11;
     int64_t x = pollard_rho_log(g, y, p);
     std::cout << "The discrete logarithm of " << y
               << " with respect to the base " << g
               << " in the group of order " << p << " is " << x
               << std::endl;
     int64_t a = 2, b = 3, m = 5;
     std::cout << logs.BSGS(a, b, m) << std::endl;
     a = 3, b = 7, m = 11;
     std::cout << logs.BSGS(a, b, m) << std::endl;
 }
References mtpk::Logarithms::BSGS(), and pollard_rho_log().
pollard_rho_log()
int64_t pollard_rho_log (int g, int y, int p)
Definition at line 60 of file logarithms.cpp.
{
     int64_t x = rand() % (p - 1) + 1;
 #ifdef USE_SRAND
     srand(time(NULL));
     x = rand() % (p - 1) + 1;
 #endif
     int64_t y1 = y;
     int64_t y2 = y;
     int64_t d = 1;
     std::unordered_map<int64_t, int64_t> values;
     // Compute the iterated values of the sequence x_n = g^x_n-1 mod p
     // until a collision is found
     while (d == 1) {
         x = (x * x + 1) % p;
         y1 = (y1 * g) % p;
         y2 = (y2 * g) % p;
         y2 = (y2 * g) % p;
         d = std::__gcd(abs(y2 - y1), p);
         values[x] = y1;
     }
     // Compute the discrete logarithm using the collision point
     if (d == p) {
         return -1;
     } else {
         int64_t x0 = abs(y2 - y1) / d;
         int64_t y0 = values[x0];
         int64_t k = 1;
         while (y0 != y) {
             y0 = (y0 * g) % p;
             k++;
         }
         return k * x0 % (p - 1);
     }
 }
Referenced by main().
Variable Documentation
log_primes
mtpk::Primality log_primes
Definition at line 51 of file logarithms.cpp.
Referenced by mtpk::Logarithms::BSGS().