openGPMP: modules/nt/random.cpp File Reference
random.cpp File Reference
#include "../../include/nt/random.hpp"
#include <chrono>
#include <cstdint>
#include <iostream>
Functions
uint32_t rotr32 (uint32_t x, unsigned r)
uint32_t pcg32 (void)
void pcg32_init (uint64_t seed)
Function Documentation
pcg32()
uint32_t pcg32 (void)
Definition at line 86 of file random.cpp.
                      {
     uint64_t x = __PCG_STATE;
     unsigned count = (unsigned)(x >> 59);       // 59 = 64 - 5
     __PCG_STATE = x * __PCG_MULTPLR + __PCG_INCR;
     x ^= x >> 18;                               // 18 = (64 - 27)/2
     return rotr32((uint32_t)(x >> 27), count);  // 27 = 32 - 5
 }
References __PCG_INCR, __PCG_MULTPLR, __PCG_STATE, and rotr32().
Referenced by pcg32_init().
pcg32_init()
void pcg32_init (uint64_t seed)
Definition at line 95 of file random.cpp.
{
     __PCG_STATE = seed + __PCG_INCR;
     (void)pcg32();
 }
References __PCG_INCR, __PCG_STATE, and pcg32().
rotr32()
uint32_t rotr32 (uint32_t x, unsigned r)
Definition at line 82 of file random.cpp.
{
     return x >> r | x << (-r & 31);
 }
Referenced by pcg32().