openMTPK: modules/complex/torus.cpp File Reference
torus.cpp File Reference
#include <GL/glut.h>
#include <math.h>
#include <stdio.h>
Macros
#define pi 3.142857
Functions
void display ()
void init ()
int main (int argc, char **argv)
Macro Definition Documentation
pi
#define pi 3.142857
Definition at line 42 of file torus.cpp.
Function Documentation
display()
void display ()
Definition at line 44 of file torus.cpp.
                {
     // setting every pixel in frame buffer to a clear color
     glClear(GL_COLOR_BUFFER_BIT);
     glColor3f(1.0, 1.0, 1.0);
     glutWireTorus(0.5, 3, 15, 30);
     // being drawing
     glBegin(GL_POLYGON);
     glColor3f(1, 0, 0);
     glVertex3f(0, 0, 0);
     glVertex3f(10, 0, 0);
     glColor3f(0, 1, 0);
     glVertex3f(0, 0, 0);
     glVertex3f(0, 10, 0);
     glColor3f(0, 0, 1);
     glVertex3f(0, 0, 0);
     glVertex3f(0, 0, 10);
     glEnd();
     // flush the draw cmd to display image immediately
     glFlush();
 }
Referenced by main().
init()
void init ()
Definition at line 68 of file torus.cpp.
             {
     glClearColor(0.0, 0.0, 0.0, 1.0);
     glColor3f(1.0, 1.0, 1.0);
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluPerspective(60.0, 4.0 / 3.0, 1, 40);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     gluLookAt(4, 6, 5, 0, 0, 0, 0, 1, 0);
 }
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 81 of file torus.cpp.
{
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
     // Position window at (80,80)-(480,380) and give it a title.
     glutInitWindowPosition(80, 80);
     glutInitWindowSize(1000, 800);
     glutCreateWindow("A Torus on a Plane");
     // Tell GLUT that whenever the main window needs to be repainted
     // that it should call the function display().
     glutDisplayFunc(display);
     init();
     glutMainLoop();
 }
References display(), and init().