openMTPK: anonymous_namespace{t_arith.cpp} Namespace Reference
anonymous_namespace{t_arith.cpp} Namespace Reference
Functions
TEST (arith_test, add_positive)
TEST (arith_test, mult_positive)
TEST (arith_test, sub_positive)
TEST (basics, greatest_pow)
TEST (basics, greatest_common_divisor)
Variables
Arith ar
Basics ba
Function Documentation
TEST() [1/5]
anonymous_namespace{t_arith.cpp}::TEST (arith_test , add_positive)
Definition at line 17 of file t_arith.cpp.
{
         EXPECT_EQ(46094, ar.add(93, 106, 3551, 42344));
         EXPECT_EQ(21, ar.add(10, 8, 3));
         EXPECT_EQ(6.85, ar.add(1.25, 1.85, 2.75, 1));
     }
References Arith::add(), and ar.
TEST() [2/5]
anonymous_namespace{t_arith.cpp}::TEST (arith_test , mult_positive)
Definition at line 25 of file t_arith.cpp.
{
         EXPECT_EQ(240, ar.mult(10, 8, 3));
         EXPECT_EQ(6.359375, ar.mult(1.25, 1.85, 2.75, 1));
     }
References ar, and Arith::mult().
TEST() [3/5]
anonymous_namespace{t_arith.cpp}::TEST (arith_test , sub_positive)
Definition at line 31 of file t_arith.cpp.
{
         EXPECT_EQ(5, ar.sub(10, 8, 3));
         EXPECT_EQ(2.15, ar.sub(1.25, 1.85, 2.75));
         EXPECT_EQ(7, ar.sub(3, 3, 7));
     }
References ar, and Arith::sub().
TEST() [4/5]
anonymous_namespace{t_arith.cpp}::TEST (basics , greatest_common_divisor)
Definition at line 48 of file t_arith.cpp.
{
         EXPECT_EQ(2, ba.rm_gcd(2, 4));
         EXPECT_EQ(6, ba.rm_gcd(2198466, 96096));
         EXPECT_EQ(11, ba.rm_gcd(66, 11));
         EXPECT_EQ(8, ba.rm_gcd(232, 96));
         EXPECT_EQ(10, ba.rm_gcd(1703210, 20320));
     }
References ba, and Basics::rm_gcd().
TEST() [5/5]
anonymous_namespace{t_arith.cpp}::TEST (basics , greatest_pow)
Definition at line 42 of file t_arith.cpp.
{
         EXPECT_EQ(4, ba.greatest_power(10, 3));
         EXPECT_EQ(2, ba.greatest_power(7, 3));
     }
References ba, and Basics::greatest_power().
Variable Documentation
ar
Arith anonymous_namespace{t_arith.cpp}::ar
Definition at line 14 of file t_arith.cpp.
Referenced by main(), and TEST().
ba
Basics anonymous_namespace{t_arith.cpp}::ba
Definition at line 39 of file t_arith.cpp.
Referenced by main(), and TEST().