openMTPK: openmtpk Module Reference
openmtpk Module Reference
Data Types
type swigclasswrapper
interface primality
type swigtype_p_uint8_t
type swigtype_p_unsigned_char
type swigarraywrapper
interface rc4
interface cipher
interface swigc_Primality_is_prime
interface swigc_Primality_compute_miller_rabin
interface swigc_Primality_miller_rabin_prime
interface swigc_Primality_miller_rabin
interface swigc_Primality_jacobian_number
interface swigc_Primality_solovoy_strassen
interface swigc_Primality_mod_pow
interface swigc_Primality_carmichael_num
interface swigc_Primality_sieve_of_eratosthenes
interface swigc_Primality_pollard_rho
interface swigc_Primality_ETF
interface swigc_new_Primality
interface swigc_delete_Primality
interface swigc_Primality_op_assign__
interface swigc_BITS_get
interface swigc_BYTE_LIMIT_get
interface swigc_RC4_byte_swap
interface swigc_RC4_trad_swap
interface swigc_RC4_XOR_swap
interface swigc_RC4_KSA
interface swigc_RC4_PRGA
interface SWIG_free
interface swigc_RC4_store_hash
interface swigc_RC4_compute
interface swigc_new_RC4
interface swigc_delete_RC4
interface swigc_RC4_op_assign__
interface swigc_Cipher_C_cipher
interface swigc_Cipher_KC_encode
interface swigc_Cipher_KC_cipher
interface swigc_new_Cipher
interface swigc_delete_Cipher
interface swigc_Cipher_op_assign__
Functions/Subroutines
subroutine swigtm_fout_bool (imout, fout)
logical function swigf_primality_is_prime (self, n)
logical function swigf_primality_compute_miller_rabin (self, d, n)
logical function swigf_primality_miller_rabin_prime (self, n, iters)
subroutine swigf_primality_miller_rabin (self, inters, min_val, max_val)
integer(c_int) function swigf_primality_jacobian_number (self, a, n)
logical function swigf_primality_solovoy_strassen (self, p, iters)
integer(c_long_long) function swigf_primality_mod_pow (self, base, exponent, mod)
logical function swigf_primality_carmichael_num (self, n)
subroutine swigf_primality_sieve_of_eratosthenes (self, n)
integer(c_long_long) function swigf_primality_pollard_rho (self, n)
integer(c_int) function swigf_primality_etf (self, n)
type(primality) function swigf_new_primality ()
subroutine swigf_primality_release (self)
subroutine swigf_primality_op_assign__ (self, other)
integer(c_int) function, public get_bits ()
integer(c_int) function, public get_byte_limit ()
subroutine swigf_rc4_byte_swap (self, a, b)
subroutine swigf_rc4_trad_swap (self, a, b)
subroutine swigf_rc4_xor_swap (self, a, b)
subroutine swigtm_fin_char_sm_ (finp, iminp, temp)
subroutine swigf_rc4_ksa (self, key, s, swap_type)
subroutine swigf_rc4_prga (self, s, plaintext, ciphertext, swap_type)
subroutine swigtm_fout_char_sm_ (imout, fout)
character(len=:) function, allocatable swigf_rc4_store_hash (self, plaintext, hashtext, swap_type)
type(swigtype_p_unsigned_char) function swigf_rc4_compute (self, key, plaintext, hashtext, swap_type)
type(rc4) function swigf_new_rc4 ()
subroutine swigf_rc4_release (self)
subroutine swigf_rc4_op_assign__ (self, other)
character(len=:) function, allocatable swigf_cipher_c_cipher (self, plaintext, key)
character(len=:) function, allocatable swigf_cipher_kc_encode (self, key)
character(len=:) function, allocatable swigf_cipher_kc_cipher (self, plaintext, encoded_text)
type(cipher) function swigf_new_cipher ()
subroutine swigf_cipher_release (self)
subroutine swigf_cipher_op_assign__ (self, other)
Variables
integer, parameter swig_cmem_own_bit = 0
integer, parameter swig_cmem_rvalue_bit = 1
Function/Subroutine Documentation
get_bits()
integer(c_int) function, public openmtpk::get_bits
Definition at line 644 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 integer(C_INT) :: swig_result
 integer(C_INT) :: fresult
 fresult = swigc_bits_get()
 swig_result = fresult
Referenced by openmtpk::primality::assignment().
get_byte_limit()
integer(c_int) function, public openmtpk::get_byte_limit
Definition at line 654 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 integer(C_INT) :: swig_result
 integer(C_INT) :: fresult
 fresult = swigc_byte_limit_get()
 swig_result = fresult
Referenced by openmtpk::primality::assignment().
swigf_cipher_c_cipher()
character(len=:) function, allocatable openmtpk::swigf_cipher_c_cipher (class(cipher), intent(in) self, character(len=*), target plaintext, integer(c_int), intent(in) key) private
Definition at line 870 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 character(len=:), allocatable :: swig_result
 class(Cipher), intent(in) :: self
 character(len=*), target :: plaintext
 integer(C_INT), intent(in) :: key
 type(SwigArrayWrapper) :: fresult
 type(SwigClassWrapper) :: farg1
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp
 type(SwigArrayWrapper) :: farg2
 integer(C_INT) :: farg3
 farg1 = self%swigdata
 call swigtm_fin_char_sm_(plaintext, farg2, farg2_temp)
 farg3 = key
 fresult = swigc_cipher_c_cipher(farg1, farg2, farg3)
 call swigtm_fout_char_sm_(fresult, swig_result)
 call swig_free(fresult%data)
References swigtm_fin_char_sm_(), and swigtm_fout_char_sm_().
swigf_cipher_kc_cipher()
character(len=:) function, allocatable openmtpk::swigf_cipher_kc_cipher (class(cipher), intent(in) self, character(len=*), target plaintext, character(len=*), target encoded_text) private
Definition at line 909 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 character(len=:), allocatable :: swig_result
 class(Cipher), intent(in) :: self
 character(len=*), target :: plaintext
 character(len=*), target :: encoded_text
 type(SwigArrayWrapper) :: fresult
 type(SwigClassWrapper) :: farg1
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp
 type(SwigArrayWrapper) :: farg2
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp
 type(SwigArrayWrapper) :: farg3
 farg1 = self%swigdata
 call swigtm_fin_char_sm_(plaintext, farg2, farg2_temp)
 call swigtm_fin_char_sm_(encoded_text, farg3, farg3_temp)
 fresult = swigc_cipher_kc_cipher(farg1, farg2, farg3)
 call swigtm_fout_char_sm_(fresult, swig_result)
 call swig_free(fresult%data)
References swigtm_fin_char_sm_(), and swigtm_fout_char_sm_().
swigf_cipher_kc_encode()
character(len=:) function, allocatable openmtpk::swigf_cipher_kc_encode (class(cipher), intent(in) self, character(len=*), target key) private
Definition at line 891 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 character(len=:), allocatable :: swig_result
 class(Cipher), intent(in) :: self
 character(len=*), target :: key
 type(SwigArrayWrapper) :: fresult
 type(SwigClassWrapper) :: farg1
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp
 type(SwigArrayWrapper) :: farg2
 farg1 = self%swigdata
 call swigtm_fin_char_sm_(key, farg2, farg2_temp)
 fresult = swigc_cipher_kc_encode(farg1, farg2)
 call swigtm_fout_char_sm_(fresult, swig_result)
 call swig_free(fresult%data)
References swigtm_fin_char_sm_(), and swigtm_fout_char_sm_().
swigf_cipher_op_assign__()
subroutine openmtpk::swigf_cipher_op_assign__ (class(cipher), intent(inout) self, type(cipher), intent(in) other) private
Definition at line 955 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(Cipher), intent(inout) :: self
 type(Cipher), intent(in) :: other
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 farg1 = self%swigdata
 farg2 = other%swigdata
 call swigc_cipher_op_assign__(farg1, farg2)
 self%swigdata = farg1
Referenced by openmtpk::cipher::assignment().
swigf_cipher_release()
subroutine openmtpk::swigf_cipher_release (class(cipher), intent(inout) self) private
Definition at line 941 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(Cipher), intent(inout) :: self
 type(SwigClassWrapper) :: farg1
 farg1 = self%swigdata
 if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
 call swigc_delete_cipher(farg1)
 endif
 farg1%cptr = c_null_ptr
 farg1%cmemflags = 0
 self%swigdata = farg1
References swig_cmem_own_bit.
swigf_new_cipher()
type(cipher) function openmtpk::swigf_new_cipher private
Definition at line 931 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 type(Cipher) :: self
 type(SwigClassWrapper) :: fresult
 fresult = swigc_new_cipher()
 self%swigdata = fresult
Referenced by openmtpk::cipher::assignment().
swigf_new_primality()
type(primality) function openmtpk::swigf_new_primality private
Definition at line 607 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 type(Primality) :: self
 type(SwigClassWrapper) :: fresult
 fresult = swigc_new_primality()
 self%swigdata = fresult
Referenced by openmtpk::cipher::assignment().
swigf_new_rc4()
type(rc4) function openmtpk::swigf_new_rc4 private
Definition at line 833 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 type(RC4) :: self
 type(SwigClassWrapper) :: fresult
 fresult = swigc_new_rc4()
 self%swigdata = fresult
Referenced by openmtpk::cipher::assignment().
swigf_primality_carmichael_num()
logical function openmtpk::swigf_primality_carmichael_num (class(primality), intent(in) self, integer(c_int), intent(in) n) private
Definition at line 547 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 logical :: swig_result
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: n
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 farg1 = self%swigdata
 farg2 = n
 fresult = swigc_primality_carmichael_num(farg1, farg2)
 call swigtm_fout_bool(fresult, swig_result)
References swigtm_fout_bool().
swigf_primality_compute_miller_rabin()
logical function openmtpk::swigf_primality_compute_miller_rabin (class(primality), intent(in) self, integer(c_int), intent(in) d, integer(c_int), intent(in) n) private
Definition at line 431 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 logical :: swig_result
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: d
 integer(C_INT), intent(in) :: n
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 integer(C_INT) :: farg3
 farg1 = self%swigdata
 farg2 = d
 farg3 = n
 fresult = swigc_primality_compute_miller_rabin(farg1, farg2, farg3)
 call swigtm_fout_bool(fresult, swig_result)
References swigtm_fout_bool().
swigf_primality_etf()
integer(c_int) function openmtpk::swigf_primality_etf (class(primality), intent(in) self, integer(c_int), intent(in) n) private
Definition at line 591 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 integer(C_INT) :: swig_result
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: n
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 farg1 = self%swigdata
 farg2 = n
 fresult = swigc_primality_etf(farg1, farg2)
 swig_result = fresult
swigf_primality_is_prime()
logical function openmtpk::swigf_primality_is_prime (class(primality), intent(in) self, integer(c_int), intent(in) n) private
Definition at line 415 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 logical :: swig_result
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: n
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 farg1 = self%swigdata
 farg2 = n
 fresult = swigc_primality_is_prime(farg1, farg2)
 call swigtm_fout_bool(fresult, swig_result)
References swigtm_fout_bool().
swigf_primality_jacobian_number()
integer(c_int) function openmtpk::swigf_primality_jacobian_number (class(primality), intent(in) self, integer(c_long_long), intent(in) a, integer(c_long_long), intent(in) n) private
Definition at line 487 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 integer(C_INT) :: swig_result
 class(Primality), intent(in) :: self
 integer(C_LONG_LONG), intent(in) :: a
 integer(C_LONG_LONG), intent(in) :: n
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_LONG_LONG) :: farg2
 integer(C_LONG_LONG) :: farg3
 farg1 = self%swigdata
 farg2 = a
 farg3 = n
 fresult = swigc_primality_jacobian_number(farg1, farg2, farg3)
 swig_result = fresult
swigf_primality_miller_rabin()
subroutine openmtpk::swigf_primality_miller_rabin (class(primality), intent(in) self, integer(c_int), intent(in) inters, integer(c_int), intent(in) min_val, integer(c_int), intent(in) max_val) private
Definition at line 469 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: inters
 integer(C_INT), intent(in) :: min_val
 integer(C_INT), intent(in) :: max_val
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 integer(C_INT) :: farg3
 integer(C_INT) :: farg4
 farg1 = self%swigdata
 farg2 = inters
 farg3 = min_val
 farg4 = max_val
 call swigc_primality_miller_rabin(farg1, farg2, farg3, farg4)
swigf_primality_miller_rabin_prime()
logical function openmtpk::swigf_primality_miller_rabin_prime (class(primality), intent(in) self, integer(c_int), intent(in) n, integer(c_int), intent(in) iters) private
Definition at line 450 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 logical :: swig_result
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: n
 integer(C_INT), intent(in) :: iters
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 integer(C_INT) :: farg3
 farg1 = self%swigdata
 farg2 = n
 farg3 = iters
 fresult = swigc_primality_miller_rabin_prime(farg1, farg2, farg3)
 call swigtm_fout_bool(fresult, swig_result)
References swigtm_fout_bool().
swigf_primality_mod_pow()
integer(c_long_long) function openmtpk::swigf_primality_mod_pow (class(primality), intent(in) self, integer(c_long_long), intent(in) base, integer(c_long_long), intent(in) exponent, integer(c_long_long), intent(in) mod) private
Definition at line 525 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 integer(C_LONG_LONG) :: swig_result
 class(Primality), intent(in) :: self
 integer(C_LONG_LONG), intent(in) :: base
 integer(C_LONG_LONG), intent(in) :: exponent
 integer(C_LONG_LONG), intent(in) :: mod
 integer(C_LONG_LONG) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_LONG_LONG) :: farg2
 integer(C_LONG_LONG) :: farg3
 integer(C_LONG_LONG) :: farg4
 farg1 = self%swigdata
 farg2 = base
 farg3 = exponent
 farg4 = mod
 fresult = swigc_primality_mod_pow(farg1, farg2, farg3, farg4)
 swig_result = fresult
swigf_primality_op_assign__()
subroutine openmtpk::swigf_primality_op_assign__ (class(primality), intent(inout) self, type(primality), intent(in) other) private
Definition at line 631 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(Primality), intent(inout) :: self
 type(Primality), intent(in) :: other
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 farg1 = self%swigdata
 farg2 = other%swigdata
 call swigc_primality_op_assign__(farg1, farg2)
 self%swigdata = farg1
Referenced by openmtpk::primality::assignment().
swigf_primality_pollard_rho()
integer(c_long_long) function openmtpk::swigf_primality_pollard_rho (class(primality), intent(in) self, integer(c_long_long), intent(in) n) private
Definition at line 575 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 integer(C_LONG_LONG) :: swig_result
 class(Primality), intent(in) :: self
 integer(C_LONG_LONG), intent(in) :: n
 integer(C_LONG_LONG) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_LONG_LONG) :: farg2
 farg1 = self%swigdata
 farg2 = n
 fresult = swigc_primality_pollard_rho(farg1, farg2)
 swig_result = fresult
swigf_primality_release()
subroutine openmtpk::swigf_primality_release (class(primality), intent(inout) self) private
Definition at line 617 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(Primality), intent(inout) :: self
 type(SwigClassWrapper) :: farg1
 farg1 = self%swigdata
 if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
 call swigc_delete_primality(farg1)
 endif
 farg1%cptr = c_null_ptr
 farg1%cmemflags = 0
 self%swigdata = farg1
References swig_cmem_own_bit.
swigf_primality_sieve_of_eratosthenes()
subroutine openmtpk::swigf_primality_sieve_of_eratosthenes (class(primality), intent(in) self, integer(c_int), intent(in) n) private
Definition at line 563 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(Primality), intent(in) :: self
 integer(C_INT), intent(in) :: n
 type(SwigClassWrapper) :: farg1
 integer(C_INT) :: farg2
 farg1 = self%swigdata
 farg2 = n
 call swigc_primality_sieve_of_eratosthenes(farg1, farg2)
swigf_primality_solovoy_strassen()
logical function openmtpk::swigf_primality_solovoy_strassen (class(primality), intent(in) self, integer(c_long_long), intent(in) p, integer(c_int), intent(in) iters) private
Definition at line 506 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 logical :: swig_result
 class(Primality), intent(in) :: self
 integer(C_LONG_LONG), intent(in) :: p
 integer(C_INT), intent(in) :: iters
 integer(C_INT) :: fresult
 type(SwigClassWrapper) :: farg1
 integer(C_LONG_LONG) :: farg2
 integer(C_INT) :: farg3
 farg1 = self%swigdata
 farg2 = p
 farg3 = iters
 fresult = swigc_primality_solovoy_strassen(farg1, farg2, farg3)
 call swigtm_fout_bool(fresult, swig_result)
References swigtm_fout_bool().
swigf_rc4_byte_swap()
subroutine openmtpk::swigf_rc4_byte_swap (class(rc4), intent(in) self, class(swigtype_p_uint8_t), intent(in) a, class(swigtype_p_uint8_t), intent(in) b) private
Definition at line 664 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(in) :: self
 class(SWIGTYPE_p_uint8_t), intent(in) :: a
 class(SWIGTYPE_p_uint8_t), intent(in) :: b
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 type(SwigClassWrapper) :: farg3
 farg1 = self%swigdata
 farg2 = a%swigdata
 farg3 = b%swigdata
 call swigc_rc4_byte_swap(farg1, farg2, farg3)
swigf_rc4_compute()
type(swigtype_p_unsigned_char) function openmtpk::swigf_rc4_compute (class(rc4), intent(in) self, character(len=*), target key, character(len=*), target plaintext, class(swigtype_p_unsigned_char), intent(in) hashtext, integer(c_int), intent(in) swap_type) private
Definition at line 806 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 type(SWIGTYPE_p_unsigned_char) :: swig_result
 class(RC4), intent(in) :: self
 character(len=*), target :: key
 character(len=*), target :: plaintext
 class(SWIGTYPE_p_unsigned_char), intent(in) :: hashtext
 integer(C_INT), intent(in) :: swap_type
 type(SwigClassWrapper) :: fresult
 type(SwigClassWrapper) :: farg1
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp
 type(SwigArrayWrapper) :: farg2
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp
 type(SwigArrayWrapper) :: farg3
 type(SwigClassWrapper) :: farg4
 integer(C_INT) :: farg5
 farg1 = self%swigdata
 call swigtm_fin_char_sm_(key, farg2, farg2_temp)
 call swigtm_fin_char_sm_(plaintext, farg3, farg3_temp)
 farg4 = hashtext%swigdata
 farg5 = swap_type
 fresult = swigc_rc4_compute(farg1, farg2, farg3, farg4, farg5)
 swig_result%swigdata = fresult
References swigtm_fin_char_sm_().
swigf_rc4_ksa()
subroutine openmtpk::swigf_rc4_ksa (class(rc4), intent(in) self, character(len=*), target key, class(swigtype_p_unsigned_char), intent(in) s, integer(c_int), intent(in) swap_type) private
Definition at line 727 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(in) :: self
 character(len=*), target :: key
 class(SWIGTYPE_p_unsigned_char), intent(in) :: s
 integer(C_INT), intent(in) :: swap_type
 type(SwigClassWrapper) :: farg1
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp
 type(SwigArrayWrapper) :: farg2
 type(SwigClassWrapper) :: farg3
 integer(C_INT) :: farg4
 farg1 = self%swigdata
 call swigtm_fin_char_sm_(key, farg2, farg2_temp)
 farg3 = s%swigdata
 farg4 = swap_type
 call swigc_rc4_ksa(farg1, farg2, farg3, farg4)
References swigtm_fin_char_sm_().
swigf_rc4_op_assign__()
subroutine openmtpk::swigf_rc4_op_assign__ (class(rc4), intent(inout) self, type(rc4), intent(in) other) private
Definition at line 857 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(inout) :: self
 type(RC4), intent(in) :: other
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 farg1 = self%swigdata
 farg2 = other%swigdata
 call swigc_rc4_op_assign__(farg1, farg2)
 self%swigdata = farg1
Referenced by openmtpk::rc4::assignment().
swigf_rc4_prga()
subroutine openmtpk::swigf_rc4_prga (class(rc4), intent(in) self, class(swigtype_p_unsigned_char), intent(in) s, character(len=*), target plaintext, class(swigtype_p_unsigned_char), intent(in) ciphertext, integer(c_int), intent(in) swap_type) private
Definition at line 746 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(in) :: self
 class(SWIGTYPE_p_unsigned_char), intent(in) :: s
 character(len=*), target :: plaintext
 class(SWIGTYPE_p_unsigned_char), intent(in) :: ciphertext
 integer(C_INT), intent(in) :: swap_type
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp
 type(SwigArrayWrapper) :: farg3
 type(SwigClassWrapper) :: farg4
 integer(C_INT) :: farg5
 farg1 = self%swigdata
 farg2 = s%swigdata
 call swigtm_fin_char_sm_(plaintext, farg3, farg3_temp)
 farg4 = ciphertext%swigdata
 farg5 = swap_type
 call swigc_rc4_prga(farg1, farg2, farg3, farg4, farg5)
References swigtm_fin_char_sm_().
swigf_rc4_release()
subroutine openmtpk::swigf_rc4_release (class(rc4), intent(inout) self) private
Definition at line 843 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(inout) :: self
 type(SwigClassWrapper) :: farg1
 farg1 = self%swigdata
 if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
 call swigc_delete_rc4(farg1)
 endif
 farg1%cptr = c_null_ptr
 farg1%cmemflags = 0
 self%swigdata = farg1
References swig_cmem_own_bit.
swigf_rc4_store_hash()
character(len=:) function, allocatable openmtpk::swigf_rc4_store_hash (class(rc4), intent(in) self, character(len=*), target plaintext, class(swigtype_p_unsigned_char), intent(in) hashtext, integer(c_int), intent(in) swap_type) private
Definition at line 782 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 character(len=:), allocatable :: swig_result
 class(RC4), intent(in) :: self
 character(len=*), target :: plaintext
 class(SWIGTYPE_p_unsigned_char), intent(in) :: hashtext
 integer(C_INT), intent(in) :: swap_type
 type(SwigArrayWrapper) :: fresult
 type(SwigClassWrapper) :: farg1
 character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp
 type(SwigArrayWrapper) :: farg2
 type(SwigClassWrapper) :: farg3
 integer(C_INT) :: farg4
 farg1 = self%swigdata
 call swigtm_fin_char_sm_(plaintext, farg2, farg2_temp)
 farg3 = hashtext%swigdata
 farg4 = swap_type
 fresult = swigc_rc4_store_hash(farg1, farg2, farg3, farg4)
 call swigtm_fout_char_sm_(fresult, swig_result)
 call swig_free(fresult%data)
References swigtm_fin_char_sm_(), and swigtm_fout_char_sm_().
swigf_rc4_trad_swap()
subroutine openmtpk::swigf_rc4_trad_swap (class(rc4), intent(in) self, class(swigtype_p_unsigned_char), intent(in) a, class(swigtype_p_unsigned_char), intent(in) b) private
Definition at line 679 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(in) :: self
 class(SWIGTYPE_p_unsigned_char), intent(in) :: a
 class(SWIGTYPE_p_unsigned_char), intent(in) :: b
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 type(SwigClassWrapper) :: farg3
 farg1 = self%swigdata
 farg2 = a%swigdata
 farg3 = b%swigdata
 call swigc_rc4_trad_swap(farg1, farg2, farg3)
swigf_rc4_xor_swap()
subroutine openmtpk::swigf_rc4_xor_swap (class(rc4), intent(in) self, class(swigtype_p_unsigned_char), intent(in) a, class(swigtype_p_unsigned_char), intent(in) b) private
Definition at line 694 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 class(RC4), intent(in) :: self
 class(SWIGTYPE_p_unsigned_char), intent(in) :: a
 class(SWIGTYPE_p_unsigned_char), intent(in) :: b
 type(SwigClassWrapper) :: farg1
 type(SwigClassWrapper) :: farg2
 type(SwigClassWrapper) :: farg3
 farg1 = self%swigdata
 farg2 = a%swigdata
 farg3 = b%swigdata
 call swigc_rc4_xor_swap(farg1, farg2, farg3)
swigtm_fin_char_sm_()
subroutine openmtpk::swigtm_fin_char_sm_ (character(len=*), intent(in) finp, type(swigarraywrapper), intent(out) iminp, character(kind=c_char), dimension(:), intent(out), allocatable, target temp) private
Definition at line 710 of file openMTPK.f90.
   use, intrinsic :: iso_c_binding
   character(len=*), intent(in) :: finp
   type(SwigArrayWrapper), intent(out) :: iminp
   character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
   integer :: i
   allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
   do i=1,len(finp)
     temp(i) = char(ichar(finp(i:i)), kind=c_char)
   end do
   i = len(finp) + 1
   temp(i) = c_null_char ! C finp compatibility
   iminp%data = c_loc(temp)
   iminp%size = len(finp, kind=c_size_t)
Referenced by swigf_cipher_c_cipher(), swigf_cipher_kc_cipher(), swigf_cipher_kc_encode(), swigf_rc4_compute(), swigf_rc4_ksa(), swigf_rc4_prga(), and swigf_rc4_store_hash().
swigtm_fout_bool()
subroutine openmtpk::swigtm_fout_bool (integer(kind=c_int), intent(in) imout, logical, intent(out) fout) private
Definition at line 408 of file openMTPK.f90.
   use, intrinsic :: iso_c_binding
   integer(kind=C_INT), intent(in) :: imout
   logical, intent(out) :: fout
   fout = (imout /= 0)
Referenced by swigf_primality_carmichael_num(), swigf_primality_compute_miller_rabin(), swigf_primality_is_prime(), swigf_primality_miller_rabin_prime(), and swigf_primality_solovoy_strassen().
swigtm_fout_char_sm_()
subroutine openmtpk::swigtm_fout_char_sm_ (type(swigarraywrapper), intent(in) imout, character(len=:), intent(out), allocatable fout) private
Definition at line 769 of file openMTPK.f90.
   use, intrinsic :: iso_c_binding
   type(SwigArrayWrapper), intent(in) :: imout
   character(len=:), allocatable, intent(out) :: fout
   character(kind=C_CHAR), dimension(:), pointer :: chars
   integer(kind=C_SIZE_T) :: i
   call c_f_pointer(imout%data, chars, [imout%size])
   allocate(character(len=imout%size) :: fout)
   do i=1, imout%size
     fout(i:i) = char(ichar(chars(i)))
   end do
Referenced by swigf_cipher_c_cipher(), swigf_cipher_kc_cipher(), swigf_cipher_kc_encode(), and swigf_rc4_store_hash().
Variable Documentation
swig_cmem_own_bit
integer, parameter openmtpk::swig_cmem_own_bit = 0 private
Definition at line 13 of file openMTPK.f90.
  integer, parameter :: swig_cmem_own_bit = 0
Referenced by swigf_cipher_release(), swigf_primality_release(), and swigf_rc4_release().
swig_cmem_rvalue_bit
integer, parameter openmtpk::swig_cmem_rvalue_bit = 1 private
Definition at line 14 of file openMTPK.f90.
  integer, parameter :: swig_cmem_rvalue_bit = 1