openMTPK: mtpk::core::rndm Namespace Reference
mtpk::core::rndm Namespace Reference
Functions
uint32_t LCG (uint32_t lower=0, uint32_t upper=__32BIT_1)
Linear Congruential Generator m = modulus : 32-bits a = multiplier : 1664525 (from Knuth) c = increment : 1013904223 (from Knuth)
uint64_t LCGl (uint64_t lower=0, uint64_t upper=__64BIT_1)
Linear Congruential Generator (64-bit) m = modulus : 64-bits a = multiplier : 6364136223846793005 (from Knuth) c = increment : 1442695040888963407 (from Knuth)
Function Documentation
LCG()
uint32_t mtpk::core::rndm::LCG (uint32_t lower = 0, uint32_t upper = __32BIT_1)
Linear Congruential Generator m = modulus : 32-bits a = multiplier : 1664525 (from Knuth) c = increment : 1013904223 (from Knuth)
Definition at line 39 of file random.cpp.
{
     uint32_t mod = __32BIT_1;
     uint32_t mult = 1664525;
     uint32_t incr = 1013904223;
     // set seed = current time
     uint32_t seed =
         std::chrono::system_clock::now().time_since_epoch().count();
     // Linear Congruential Generator algorithm
     uint32_t res = (mult * seed + incr) % mod;
     return res;
 }
References __32BIT_1, and mult().
Referenced by main().
LCGl()
uint64_t mtpk::core::rndm::LCGl (uint64_t lower = 0, uint64_t upper = __64BIT_1)
Linear Congruential Generator (64-bit) m = modulus : 64-bits a = multiplier : 6364136223846793005 (from Knuth) c = increment : 1442695040888963407 (from Knuth)
Definition at line 53 of file random.cpp.
{
     uint64_t mod = __64BIT_1;
     uint64_t mult = 6364136223846793005;
     uint64_t incr = 1442695040888963407;
     // set seed = current time
     uint64_t seed =
         std::chrono::system_clock::now().time_since_epoch().count();
     // Linear Congruential Generator algorithm
     uint64_t res = (mult * seed + incr) % mod;
     return res;
 }
References __64BIT_1, and mult().
Referenced by main().