openGPMP: gpmp::linalg::sigproc Namespace Reference
gpmp::linalg::sigproc Namespace Reference
Functions
std::map< int, double > z_tform (const std::map< int, double > &signal)
Compute the Z-transform of the signal.
double gaussian (double x, double mu, double sigma)
std::vector< std::pair< int, double > > gaussian_filter (const std::vector< std::pair< int, double >> &signal, double sigma)
std::vector< std::pair< int, double > > butterworth_lpf (const std::vector< std::pair< int, double >> &signal, double cutoff_frequency, double sampling_frequency, int order)
std::vector< std::pair< int, double > > chebyshev_lpf (const std::vector< std::pair< int, double >> &signal, double cutoff_frequency, double sampling_frequency, int order, double ripple)
std::vector< std::pair< int, double > > bessel_lpf (const std::vector< std::pair< int, double >> &signal, double cutoff_frequency, double sampling_frequency, int order)
std::vector< std::pair< int, double > > z_tform (const std::vector< std::pair< int, double >> &signal)
std::complex< double > z_adv_tform (const std::complex< double > &z, int delay)
Compute the Advanced Z-transform of the signal.
std::complex< double > z_matched_tform (const std::complex< double > &z, const std::vector< double > &referenceSignal)
Compute the Matched Z-transform of the signal.
std::vector< double > bilinear_tform (double Ts)
Compute the Bilinear Transform of the signal.
std::vector< double > bilinear_adv_tform (double Ts, int delay)
Compute the Advanced Bilinear Transform of the signal.
std::vector< double > bilinear_matched_tform (double Ts, const std::vector< double > &referenceSignal)
Compute the Matched Bilinear Transform of the signal.
std::vector< double > compute_constant_q_transform (double Q, double Ts)
Compute the constant-Q transform of the signal.
std::vector< double > compute_inverse_constant_q_transform (double Q, double Ts)
Compute the inverse constant-Q transform of the signal.
std::vector< double > compute_dct (size_t M)
Compute the Discrete Cosine Transform (DCT) of the signal.
std::vector< double > compute_inverse_dct (size_t M)
Compute the Inverse Discrete Cosine Transform (IDCT) of the signal.
std::vector< std::complex< double > > compute_dft ()
Compute the Discrete Fourier Transform (DFT) of the signal.
std::vector< double > compute_inverse_dft ()
Compute the Inverse Discrete Fourier Transform (IDFT) of the signal.
std::vector< double > compute_magnitude_spectrum ()
Compute the magnitude spectrum of the signal.
std::vector< double > compute_phase_spectrum ()
Compute the phase spectrum of the signal.
std::vector< std::complex< double > > compute_dtft (const std::vector< double > &omega)
Compute the Discrete-time Fourier Transform (DTFT) of the signal.
std::vector< double > compute_inverse_dtft (const std::vector< double > &omega)
Compute the Inverse Discrete-time Fourier Transform (IDTFT) of the signal.
std::vector< double > compute_dtft_magnitude_spectrum (const std::vector< double > &omega)
Compute the magnitude spectrum of the DTFT of the signal.
std::vector< double > compute_dtft_phase_spectrum (const std::vector< double > &omega)
Compute the phase spectrum of the DTFT of the signal.
std::vector< double > design_discrete_system (const std::vector< double > &analog_system_coefficients, double sampling_rate)
Design a discrete-time system using the impulse invariance method.
std::vector< double > impulse_invariance_transform (const std::vector< double > &analog_signal, double analog_sampling_rate, double discrete_sampling_rate)
Apply the impulse invariance method to transform an analog signal to discrete time.
std::vector< double > zak_transform (const std::vector< double > &time_domain_signal, double frequency, double period)
Perform the Zak transform on a given time domain signal.
std::vector< double > inverse_zak_transform (const std::vector< double > &zak_domain_signal, double frequency, double period)
Perform the inverse Zak transform on a given Zak domain signal.
std::vector< double > zak_transform_modulation (const std::vector< double > &time_domain_signal, double frequency, double period, double modulation_index)
Perform Zak transform modulation on a given time domain signal.
std::vector< double > inverse_zak_transform_modulation (const std::vector< double > &zak_domain_signal, double frequency, double period, double modulation_index)
Perform the inverse Zak transform modulation on a given modulated Zak domain signal.
std::vector< double > apply_aliasing_filter (const std::vector< double > &input_signal, double sampling_rate, double aliasing_frequency)
Apply an aliasing filter to a given signal.
std::vector< double > apply_anti_aliasing_filter (const std::vector< double > &input_signal, double sampling_rate, double cutoff_frequency)
Apply an anti-aliasing filter to remove high-frequency components from a signal.
std::vector< double > generate_aliased_sinusoid (double sampling_rate, double aliasing_frequency, double duration)
Generate a sinusoidal signal with a frequency beyond the Nyquist limit, leading to aliasing when sampled.
std::vector< double > decimate (const std::vector< double > &signal, size_t factor)
std::vector< double > average_downsample (const std::vector< double > &signal, size_t factor)
std::vector< double > max_pool_downsample (const std::vector< double > &signal, size_t factor)
std::vector< double > strided_downsample (const std::vector< double > &signal, size_t factor)
std::vector< double > linear_interpolation_downsample (const std::vector< double > &signal, size_t factor)
std::vector< double > median_downsample (const std::vector< double > &signal, size_t factor)
std::vector< double > nearest_neighbor_upsample (const std::vector< double > &signal, size_t factor)
std::vector< double > linear_interpolation_upsample (const std::vector< double > &signal, size_t factor)
std::vector< double > zero_order_hold_upsample (const std::vector< double > &signal, size_t factor)
double mean () const
Constructor Initializes the SigProc object with a signal.
double stdev () const
Compute the standard deviation of the signal.
void lpf (double alpha)
Apply a simple low-pass filter to the signal.
void normalize ()
Normalize the signal to have zero mean and unit variance.
std::vector< double > get_sig () const
Get the processed signal.
Function Documentation
apply_aliasing_filter()
std::vector< double > gpmp::linalg::sigproc::apply_aliasing_filter (const std::vector< double > & input_signal, double sampling_rate, double aliasing_frequency)
Apply an aliasing filter to a given signal.
Parameters
input_signal The input signal
sampling_rate The sampling rate of the signal
aliasing_frequency The aliasing frequency to introduce
Returns
The signal after aliasing
apply_anti_aliasing_filter()
std::vector< double > gpmp::linalg::sigproc::apply_anti_aliasing_filter (const std::vector< double > & input_signal, double sampling_rate, double cutoff_frequency)
Apply an anti-aliasing filter to remove high-frequency components from a signal.
Parameters
input_signal The input signal with potential high-frequency components
sampling_rate The sampling rate of the signal
cutoff_frequency The cutoff frequency of the anti-aliasing filter
Returns
The signal after anti-aliasing
average_downsample()
std::vector< double > gpmp::linalg::sigproc::average_downsample (const std::vector< double > & signal, size_t factor)
Downsample a signal by averaging blocks of samples
Parameters
signal The input signal
factor The downsampling factor
Returns
The downsampled signal
bessel_lpf()
std::vector< std::pair< int, double > > gpmp::linalg::sigproc::bessel_lpf (const std::vector< std::pair< int, double >> & signal, double cutoff_frequency, double sampling_frequency, int order)
Definition at line 192 of file sigproc.cpp.
                {
     // Calculate the normalized cutoff frequency
     double omega_c = 2.0 * M_PI * cutoff_frequency / sampling_frequency;
     // Calculate the poles of the Bessel filter
     std::vector<std::complex<double>> poles;
     for (int k = 1; k <= order; ++k) {
         double real_part =
             -sin(M_PI * (2 * k + 1) / (2 * order)) * sinh(log(2) / (2 * order));
         double imag_part =
             cos(M_PI * (2 * k + 1) / (2 * order)) * cosh(log(2) / (2 * order));
         poles.push_back(std::complex<double>(real_part, imag_part));
     }
     // Filter the signal using the Bessel filter
     std::vector<std::pair<int, double>> filtered_signal;
     for (size_t i = 0; i < signal.size(); ++i) {
         double t = signal[i].first;  // Time index
         double x = signal[i].second; // Signal value
         // Compute the filtered value at time t
         double filtered_value = 0.0;
         for (const auto &pole : poles) {
             std::complex<double> z(cos(omega_c), sin(omega_c));
             std::complex<double> num = 1.0;
             std::complex<double> denom = z - pole;
             for (const auto &p : poles) {
                 if (p != pole) {
                     num *= (z - p);
                     denom *= (pole - p);
                 }
             }
             filtered_value += std::real(num / denom);
         }
         filtered_value *= x;
         // Add the filtered value to the filtered signal
         filtered_signal.push_back({t, filtered_value});
     }
     return filtered_signal;
 }
bilinear_adv_tform()
std::vector< double > gpmp::linalg::sigproc::bilinear_adv_tform (double Ts, int delay)
Compute the Advanced Bilinear Transform of the signal.
Parameters
Ts Sampling period
delay Delay parameter for the Advanced Bilinear Transform
Returns
The Advanced Bilinear Transform of the signal
bilinear_matched_tform()
std::vector< double > gpmp::linalg::sigproc::bilinear_matched_tform (double Ts, const std::vector< double > & referenceSignal)
Compute the Matched Bilinear Transform of the signal.
Parameters
Ts Sampling period
referenceSignal Reference signal for the Matched Bilinear Transform
Returns
The Matched Bilinear Transform of the signal
bilinear_tform()
std::vector< double > gpmp::linalg::sigproc::bilinear_tform (double Ts)
Compute the Bilinear Transform of the signal.
Parameters
Ts Sampling period
Returns
The Bilinear Transform of the signal
butterworth_lpf()
std::vector< std::pair< int, double > > gpmp::linalg::sigproc::butterworth_lpf (const std::vector< std::pair< int, double >> & signal, double cutoff_frequency, double sampling_frequency, int order)
Definition at line 97 of file sigproc.cpp.
                {
     // Calculate the normalized cutoff frequency
     double omega_c = 2.0 * M_PI * cutoff_frequency / sampling_frequency;
     // Calculate the poles of the Butterworth filter
     std::vector<std::complex<double>> poles;
     for (int k = 0; k < order; ++k) {
         double real_part = -sin((2 * k + 1) * M_PI / (2 * order));
         double imag_part = cos((2 * k + 1) * M_PI / (2 * order));
         poles.push_back(std::complex<double>(real_part, imag_part));
     }
     // Filter the signal using the Butterworth filter
     std::vector<std::pair<int, double>> filtered_signal;
     for (size_t i = 0; i < signal.size(); ++i) {
         double t = signal[i].first;  // Time index
         double x = signal[i].second; // Signal value
         // Compute the filtered value at time t
         double filtered_value = 0.0;
         for (const auto &pole : poles) {
             std::complex<double> z(cos(omega_c), sin(omega_c));
             std::complex<double> num = 1.0;
             std::complex<double> denom = z - pole;
             for (int j = 1; j < order; ++j) {
                 num *= z;
                 denom *= (z - poles[j]);
             }
             filtered_value += std::real(num / denom);
         }
         filtered_value *= x;
         // Add the filtered value to the filtered signal
         filtered_signal.push_back({t, filtered_value});
     }
     return filtered_signal;
 }
chebyshev_lpf()
std::vector< std::pair< int, double > > gpmp::linalg::sigproc::chebyshev_lpf (const std::vector< std::pair< int, double >> & signal, double cutoff_frequency, double sampling_frequency, int order, double ripple)
Definition at line 140 of file sigproc.cpp.
                    {
     // Calculate the normalized cutoff frequency
     double omega_c = 2.0 * M_PI * cutoff_frequency / sampling_frequency;
     // Calculate the ripple factor (epsilon)
     double epsilon = sqrt(pow(10, ripple / 10) - 1);
     // Calculate the poles of the Chebyshev filter
     std::vector<std::complex<double>> poles;
     for (int k = 0; k < order; ++k) {
         double real_part = -sinh(asinh(1 / epsilon) / order) *
                            sin((2 * k + 1) * M_PI / (2 * order));
         double imag_part = cosh(asinh(1 / epsilon) / order) *
                            cos((2 * k + 1) * M_PI / (2 * order));
         poles.push_back(std::complex<double>(real_part, imag_part));
     }
     // Filter the signal using the Chebyshev filter
     std::vector<std::pair<int, double>> filtered_signal;
     for (size_t i = 0; i < signal.size(); ++i) {
         double t = signal[i].first;  // Time index
         double x = signal[i].second; // Signal value
         // Compute the filtered value at time t
         double filtered_value = 0.0;
         for (const auto &pole : poles) {
             std::complex<double> z(cos(omega_c), sin(omega_c));
             std::complex<double> num = 1.0;
             std::complex<double> denom = z - pole;
             for (int j = 0; j < order; ++j) {
                 if (j != i) {
                     num *= z;
                     denom *= (z - poles[j]);
                 }
             }
             filtered_value += std::real(num / denom);
         }
         filtered_value *= x;
         // Add the filtered value to the filtered signal
         filtered_signal.push_back({t, filtered_value});
     }
     return filtered_signal;
 }
compute_constant_q_transform()
std::vector< double > gpmp::linalg::sigproc::compute_constant_q_transform (double Q, double Ts)
Compute the constant-Q transform of the signal.
Parameters
Q Quality factor
Ts Sampling period
Returns
The constant-Q transform of the signal
compute_dct()
std::vector< double > gpmp::linalg::sigproc::compute_dct (size_t M)
Compute the Discrete Cosine Transform (DCT) of the signal.
Parameters
M Number of coefficients (non-negative integer)
Returns
The DCT of the signal
compute_dft()
std::vector< std::complex< double > > gpmp::linalg::sigproc::compute_dft ()
Compute the Discrete Fourier Transform (DFT) of the signal.
Returns
The DFT of the signal
compute_dtft()
std::vector< std::complex< double > > gpmp::linalg::sigproc::compute_dtft (const std::vector< double > & omega)
Compute the Discrete-time Fourier Transform (DTFT) of the signal.
Parameters
omega Frequency values at which to compute the DTFT
Returns
The DTFT of the signal at the specified frequencies
compute_dtft_magnitude_spectrum()
std::vector< double > gpmp::linalg::sigproc::compute_dtft_magnitude_spectrum (const std::vector< double > & omega)
Compute the magnitude spectrum of the DTFT of the signal.
Parameters
omega Frequency values at which to compute the DTFT
Returns
The magnitude spectrum of the DTFT
compute_dtft_phase_spectrum()
std::vector< double > gpmp::linalg::sigproc::compute_dtft_phase_spectrum (const std::vector< double > & omega)
Compute the phase spectrum of the DTFT of the signal.
Parameters
omega Frequency values at which to compute the DTFT
Returns
The phase spectrum of the DTFT
compute_inverse_constant_q_transform()
std::vector< double > gpmp::linalg::sigproc::compute_inverse_constant_q_transform (double Q, double Ts)
Compute the inverse constant-Q transform of the signal.
Parameters
Q Quality factor
Ts Sampling period
Returns
The inverse constant-Q transform of the signal
compute_inverse_dct()
std::vector< double > gpmp::linalg::sigproc::compute_inverse_dct (size_t M)
Compute the Inverse Discrete Cosine Transform (IDCT) of the signal.
Parameters
M Number of coefficients (non-negative integer)
Returns
The IDCT of the signal
compute_inverse_dft()
std::vector< double > gpmp::linalg::sigproc::compute_inverse_dft ()
Compute the Inverse Discrete Fourier Transform (IDFT) of the signal.
Returns
The IDFT of the signal
compute_inverse_dtft()
std::vector< double > gpmp::linalg::sigproc::compute_inverse_dtft (const std::vector< double > & omega)
Compute the Inverse Discrete-time Fourier Transform (IDTFT) of the signal.
Parameters
omega Frequency values at which to compute the IDTFT
Returns
The IDTFT of the signal at the specified frequencies
compute_magnitude_spectrum()
std::vector< double > gpmp::linalg::sigproc::compute_magnitude_spectrum ()
Compute the magnitude spectrum of the signal.
Returns
The magnitude spectrum
compute_phase_spectrum()
std::vector< double > gpmp::linalg::sigproc::compute_phase_spectrum ()
Compute the phase spectrum of the signal.
Returns
The phase spectrum
decimate()
std::vector< double > gpmp::linalg::sigproc::decimate (const std::vector< double > & signal, size_t factor)
Downsample a signal by a given factor using the Decimation method
Parameters
signal The input signal
factor The downsampling factor
Returns
The downsampled signal
design_discrete_system()
std::vector< double > gpmp::linalg::sigproc::design_discrete_system (const std::vector< double > & analog_system_coefficients, double sampling_rate)
Design a discrete-time system using the impulse invariance method.
Parameters
analog_system_coefficients Coefficients of the analog system
sampling_rate Sampling rate of the discrete-time system
Returns
Coefficients of the discrete-time system
gaussian()
double gpmp::linalg::sigproc::gaussian (double x, double mu, double sigma)
Definition at line 63 of file sigproc.cpp.
{
     return exp(-(x - mu) * (x - mu) / (2 * sigma * sigma)) /
            (sigma * sqrt(2 * M_PI));
 }
Referenced by gaussian_filter().
gaussian_filter()
std::vector< std::pair< int, double > > gpmp::linalg::sigproc::gaussian_filter (const std::vector< std::pair< int, double >> & signal, double sigma)
Definition at line 69 of file sigproc.cpp.
                   {
     std::vector<std::pair<int, double>> filtered_signal;
     // Iterate over each element in the signal
     for (size_t i = 0; i < signal.size(); ++i) {
         double filtered_value = 0.0;
         double sum_weights = 0.0;
         // Compute weighted average of neighboring values
         for (size_t j = 0; j < signal.size(); ++j) {
             double distance = abs(signal[i].first - signal[j].first);
             double weight = gaussian(distance, 0, sigma);
             filtered_value += weight * signal[j].second;
             sum_weights += weight;
         }
         // Normalize filtered value
         filtered_value /= sum_weights;
         // Add filtered value to filtered signal
         filtered_signal.push_back({signal[i].first, filtered_value});
     }
     return filtered_signal;
 }
References gaussian().
generate_aliased_sinusoid()
std::vector< double > gpmp::linalg::sigproc::generate_aliased_sinusoid (double sampling_rate, double aliasing_frequency, double duration)
Generate a sinusoidal signal with a frequency beyond the Nyquist limit, leading to aliasing when sampled.
Parameters
sampling_rate The sampling rate of the signal
aliasing_frequency The aliasing frequency to introduce
duration The duration of the signal in seconds
Returns
The aliased sinusoidal signal
get_sig()
std::vector<double> gpmp::linalg::sigproc::get_sig () const
Get the processed signal.
Returns
The processed signal
impulse_invariance_transform()
std::vector< double > gpmp::linalg::sigproc::impulse_invariance_transform (const std::vector< double > & analog_signal, double analog_sampling_rate, double discrete_sampling_rate)
Apply the impulse invariance method to transform an analog signal to discrete time.
Parameters
analog_signal Analog signal to be transformed
analog_sampling_rate Sampling rate of the analog signal
discrete_sampling_rate Sampling rate of the discrete-time system
Returns
Discrete-time signal after transformation
inverse_zak_transform()
std::vector< double > gpmp::linalg::sigproc::inverse_zak_transform (const std::vector< double > & zak_domain_signal, double frequency, double period)
Perform the inverse Zak transform on a given Zak domain signal.
Parameters
zak_domain_signal The input Zak domain signal
frequency The frequency of the Zak transform
period The period of the Zak transform
Returns
The reconstructed time domain signal
inverse_zak_transform_modulation()
std::vector< double > gpmp::linalg::sigproc::inverse_zak_transform_modulation (const std::vector< double > & zak_domain_signal, double frequency, double period, double modulation_index)
Perform the inverse Zak transform modulation on a given modulated Zak domain signal.
Parameters
zak_domain_signal The input modulated Zak domain signal
frequency The frequency of the Zak transform
period The period of the Zak transform
modulation_index The modulation index for Zak transform modulation
Returns
The reconstructed time domain signal after modulation
linear_interpolation_downsample()
std::vector< double > gpmp::linalg::sigproc::linear_interpolation_downsample (const std::vector< double > & signal, size_t factor)
Downsample a signal by interpolating between samples using Linear Interpolation
Parameters
signal The input signal
factor The downsampling factor
Returns
The downsampled signal
linear_interpolation_upsample()
std::vector< double > gpmp::linalg::sigproc::linear_interpolation_upsample (const std::vector< double > & signal, size_t factor)
Upsample a signal using Linear Interpolation
Parameters
signal The input signal
factor The upsampling factor
Returns
The upsampled signal
lpf()
void gpmp::linalg::sigproc::lpf (double alpha)
Apply a simple low-pass filter to the signal.
Parameters
alpha Filter coefficient (0 < alpha < 1)
max_pool_downsample()
std::vector< double > gpmp::linalg::sigproc::max_pool_downsample (const std::vector< double > & signal, size_t factor)
Downsample a signal using the Max-Pooling method
Parameters
signal The input signal
factor The downsampling factor
Returns
The downsampled signal
mean()
double gpmp::linalg::sigproc::mean () const
Constructor Initializes the SigProc object with a signal.
Parameters
signal The input signal
Compute the mean value of the signal
Returns
The mean value
Referenced by gpmp::stats::Describe::avg_abs_dev(), gpmp::ml::Regularize::batch_normalization(), gpmp::stats::Describe::clt(), gpmp::stats::ProbDist::ConfidenceInterval(), gpmp::ml::BayesGauss::display(), gpmp::stats::Describe::kurtosis(), gpmp::stats::Describe::lmoment1(), gpmp::stats::Describe::lmoment2(), gpmp::ml::BayesGauss::mean_and_var(), gpmp::stats::ProbDist::mom(), gpmp::stats::ProbDist::normal_CDF(), gpmp::stats::ProbDist::normal_PDF(), gpmp::stats::ProbDist::PivotFunctionForConfidenceInterval(), gpmp::ml::BayesGauss::predict(), gpmp::ml::VariationalAutoEncoder::reparameterize(), gpmp::stats::Describe::skewness(), gpmp::stats::Describe::stdev(), gpmp::stats::Describe::var_coeff(), and gpmp::stats::Describe::variance().
median_downsample()
std::vector< double > gpmp::linalg::sigproc::median_downsample (const std::vector< double > & signal, size_t factor)
Downsample a signal by selecting the median value in each block
Parameters
signal The input signal
factor The downsampling factor
Returns
The downsampled signal
nearest_neighbor_upsample()
std::vector< double > gpmp::linalg::sigproc::nearest_neighbor_upsample (const std::vector< double > & signal, size_t factor)
Upsample a signal using the Nearest Neighbor method
Parameters
signal The input signal
factor The upsampling factor
Returns
The upsampled signal
normalize()
void gpmp::linalg::sigproc::normalize ()
Normalize the signal to have zero mean and unit variance.
stdev()
double gpmp::linalg::sigproc::stdev () const
Compute the standard deviation of the signal.
Returns
The standard deviation
Referenced by gpmp::stats::Describe::clt(), gpmp::linalg::mtx< T >::randn(), and gpmp::stats::Describe::var_coeff().
strided_downsample()
std::vector< double > gpmp::linalg::sigproc::strided_downsample (const std::vector< double > & signal, size_t factor)
Downsample a signal by selecting every Nth sample using the Strided method
Parameters
signal The input signal
factor The downsampling factor
Returns
The downsampled signal
z_adv_tform()
std::complex< double > gpmp::linalg::sigproc::z_adv_tform (const std::complex< double > & z, int delay)
Compute the Advanced Z-transform of the signal.
Parameters
z Complex number representing the Z-transform variable
delay Delay parameter for the Advanced Z-transform
Returns
The Advanced Z-transform of the signal
z_matched_tform()
std::complex< double > gpmp::linalg::sigproc::z_matched_tform (const std::complex< double > & z, const std::vector< double > & referenceSignal)
Compute the Matched Z-transform of the signal.
Parameters
z Complex number representing the Z-transform variable
referenceSignal Reference signal for the Matched Z-transform
Returns
The Matched Z-transform of the signal
z_tform() [1/2]
std::map< int, double > gpmp::linalg::sigproc::z_tform (const std::map< int, double > & signal)
Compute the Z-transform of the signal.
Parameters
z Complex number representing the Z-transform variable
Returns
The Z-transform of the signal
z_tform() [2/2]
std::vector< std::pair< int, double > > gpmp::linalg::sigproc::z_tform (const std::vector< std::pair< int, double >> & signal)
Definition at line 43 of file sigproc.cpp.
{
     std::vector<std::pair<int, double>> result;
     for (const auto &entry : signal) {
         int index = entry.first;
         // exponent, negate this for meeting formula requirement
         int exp = index * (-1);
         // coefficient
         double coeff = entry.second;
         // populate result vector
         result.push_back({exp, coeff});
     }
     return result;
 }
zak_transform()
std::vector< double > gpmp::linalg::sigproc::zak_transform (const std::vector< double > & time_domain_signal, double frequency, double period)
Perform the Zak transform on a given time domain signal.
Parameters
time_domain_signal The input time domain signal
frequency The frequency of the Zak transform
period The period of the Zak transform
Returns
The Zak domain signal
zak_transform_modulation()
std::vector< double > gpmp::linalg::sigproc::zak_transform_modulation (const std::vector< double > & time_domain_signal, double frequency, double period, double modulation_index)
Perform Zak transform modulation on a given time domain signal.
Parameters
time_domain_signal The input time domain signal
frequency The frequency of the Zak transform
period The period of the Zak transform
modulation_index The modulation index for Zak transform modulation
Returns
The modulated Zak domain signal
zero_order_hold_upsample()
std::vector< double > gpmp::linalg::sigproc::zero_order_hold_upsample (const std::vector< double > & signal, size_t factor)
Upsample a signal using Zero-Order Hold
Parameters
signal The input signal
factor The upsampling factor
Returns
The upsampled signal