openMTPK: Python.examples.primes_ex Namespace Reference
Python.examples.primes_ex Namespace Reference
Variables
p = Primality()
prime_0 = p.is_prime(2999)
prime_1 = p.carmichael_num(561)
mod_0 = p.mod_pow(3, 2, 2)
mod_1 = p.mod_pow(5, 2, 7)
ss_0 = p.solovoy_strassen(15, 50)
ss_1 = p.solovoy_strassen(1049, 50)
Variable Documentation
mod_0
Python.examples.primes_ex.mod_0 = p.mod_pow(3, 2, 2)
Definition at line 25 of file primes_ex.py.
mod_1
Python.examples.primes_ex.mod_1 = p.mod_pow(5, 2, 7)
Definition at line 26 of file primes_ex.py.
p
Python.examples.primes_ex.p = Primality()
Definition at line 18 of file primes_ex.py.
Referenced by caml_val_ptr(), caml_val_string(), caml_val_string_len(), Basics.greatest_power(), main(), R_swig_Basics_greatest_power(), R_SWIG_debug_getCallbackFunctionData(), R_swig_Primality_solovoy_strassen(), Primality.sieve_of_eratosthenes(), and Primality.solovoy_strassen().
prime_0
Python.examples.primes_ex.prime_0 = p.is_prime(2999)
Definition at line 20 of file primes_ex.py.
prime_1
Python.examples.primes_ex.prime_1 = p.carmichael_num(561)
Definition at line 21 of file primes_ex.py.
ss_0
Python.examples.primes_ex.ss_0 = p.solovoy_strassen(15, 50)
Definition at line 32 of file primes_ex.py.
Referenced by main().
ss_1
Python.examples.primes_ex.ss_1 = p.solovoy_strassen(1049, 50)
Definition at line 33 of file primes_ex.py.