openMTPK: swig Namespace Reference
swig Namespace Reference
Classes
struct DestructorPolicy
struct DestructorPolicy< T, ASSIGNMENT_NODESTRUCT >
struct AssignmentPolicy
struct AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >
Enumerations
enum AssignmentType { ASSIGNMENT_DEFAULT , ASSIGNMENT_NODESTRUCT , ASSIGNMENT_SMARTPTR }
Functions
SWIGINTERN SwigClassWrapper capture (SwigClassWrapper other)
Enumeration Type Documentation
AssignmentType
enum swig::AssignmentType
Enumerator
ASSIGNMENT_DEFAULT
ASSIGNMENT_NODESTRUCT
ASSIGNMENT_SMARTPTR
Definition at line 161 of file openMTPK_wrap.cxx.
                     {
   ASSIGNMENT_DEFAULT,
   ASSIGNMENT_NODESTRUCT,
   ASSIGNMENT_SMARTPTR
 };
Function Documentation
capture()
SWIGINTERN SwigClassWrapper swig::capture (SwigClassWrapper other)
Definition at line 284 of file openMTPK_wrap.cxx.
{
   other.cmemflags &= ~SWIG_MEM_RVALUE;
   return other;
 }
References SwigClassWrapper::cmemflags, and SWIG_MEM_RVALUE.
Referenced by swig::AssignmentPolicy< T, A >::copy_alias(), swig::AssignmentPolicy< T, A >::move_alias(), and SWIG_assign().