openGPMP: gpmp::core::rndm Namespace Reference
gpmp::core::rndm Namespace Reference
Functions
uint32_t LCG (uint32_t lower=0, uint32_t upper=std::numeric_limits< uint32_t >::max(), uint32_t seed=0)
Linear Congruential Generator.
uint64_t LCG_64 (uint64_t lower=0, uint64_t upper=std::numeric_limits< uint64_t >::max(), uint64_t seed=0)
Linear Congruential Generator (64-bit)
uint32_t rotr32 (uint32_t x, unsigned r)
uint32_t pcg32 (void)
void pcg32_init (uint64_t seed)
Function Documentation
LCG()
uint32_t gpmp::core::rndm::LCG (uint32_t lower = 0, uint32_t upper = std::numeric_limits<uint32_t>::max(), uint32_t seed = 0)
Linear Congruential Generator.
Parameters
lower lower bound of range
upper upper bound of range
seed
m = modulus : 32-bit int max
a = multiplier : 1664525 (from Knuth & H.W. Lewis)
c = increment : 1013904223 (from Knuth & H.W. Lewis)
Definition at line 39 of file random.cpp.
{
     uint32_t mod = __32MAX;
     uint32_t mult = 1664525;
     uint32_t incr = 1013904223;
     // set seed = current time
     uint32_t time_seed = std::chrono::system_clock::now().time_since_epoch().count();
     uint32_t final_seed = (seed == 0) ? time_seed : seed;
     // Linear Congruential Generator algorithm
     uint32_t res = (mult * final_seed + incr) % mod;
     // trim to range
     res = lower + (res % (upper - lower + 1));
     return res;
 }
References __32MAX, and mult().
Referenced by main().
LCG_64()
uint64_t gpmp::core::rndm::LCG_64 (uint64_t lower = 0, uint64_t upper = std::numeric_limits<uint64_t>::max(), uint64_t seed = 0)
Linear Congruential Generator (64-bit)
Parameters
lower lower bound of range
upper upper bound of range
seed
m = modulus : 64-bits
a = multiplier : 6364136223846793005 (from Knuth MMIX)
c = increment : 1442695040888963407 (from Knuth MMIX)
Definition at line 58 of file random.cpp.
{
     uint64_t mod = __64MAX;
     uint64_t mult = 1103515245;
     uint64_t incr = 12345;
     // set seed = current time
     uint64_t time_seed = std::chrono::system_clock::now().time_since_epoch().count();
     uint64_t final_seed = (seed == 0) ? time_seed : seed;
     // Linear Congruential Generator algorithm
     uint64_t res = (mult * final_seed + incr) % mod;
     // trim to range
     res = lower + (res % (upper - lower + 1));
     return res;
 }
References __64MAX, and mult().
pcg32()
uint32_t gpmp::core::rndm::pcg32 (void)
Definition at line 86 of file random.cpp.
{
     uint64_t x = __PCG_STATE;
     unsigned count = (unsigned)(x >> 59);       // 59 = 64 - 5
     __PCG_STATE = x * __PCG_MULTPLR + __PCG_INCR;
     x ^= x >> 18;                               // 18 = (64 - 27)/2
     return rotr32((uint32_t)(x >> 27), count);  // 27 = 32 - 5
 }
References __PCG_INCR, __PCG_MULTPLR, __PCG_STATE, and rotr32().
Referenced by pcg32_init().
pcg32_init()
void gpmp::core::rndm::pcg32_init (uint64_t seed)
Definition at line 95 of file random.cpp.
{
     __PCG_STATE = seed + __PCG_INCR;
     (void)pcg32();
 }
References __PCG_INCR, __PCG_STATE, and pcg32().
rotr32()
uint32_t gpmp::core::rndm::rotr32 (uint32_t x, unsigned r)
Definition at line 82 of file random.cpp.
{
     return x >> r | x << (-r & 31);
 }
Referenced by pcg32().