openMTPK: Python.examples.arithmetic Namespace Reference
Python.examples.arithmetic Namespace Reference
Variables
b = Basics()
r1 = b.rm_gcd(1703210, 20320)
r2 = b.rm_gcd(2198466, 96096)
r3 = b.greatest_power(232, 96)
r4 = b.greatest_power(10, 3)
Variable Documentation
b
Python.examples.arithmetic.b = Basics()
Definition at line 5 of file arithmetic.py.
Referenced by mtpk::Vectors.add(), RC4.byte_swap(), caml_val_bool(), Primality.carmichael_num(), main(), R_swig_RC4_byte_swap(), R_swig_RC4_trad_swap(), R_swig_RC4_XOR_swap(), run(), RC4.trad_swap(), and RC4.XOR_swap().
r1
Python.examples.arithmetic.r1 = b.rm_gcd(1703210, 20320)
Definition at line 7 of file arithmetic.py.
Referenced by main().
r2
Python.examples.arithmetic.r2 = b.rm_gcd(2198466, 96096)
Definition at line 8 of file arithmetic.py.
Referenced by main().
r3
Python.examples.arithmetic.r3 = b.greatest_power(232, 96)
Definition at line 9 of file arithmetic.py.
Referenced by main().
r4
Python.examples.arithmetic.r4 = b.greatest_power(10, 3)
Definition at line 10 of file arithmetic.py.
Referenced by main().