openMTPK: anonymous_namespace{t_cipher.cpp} Namespace Reference
anonymous_namespace{t_cipher.cpp} Namespace Reference
Functions
TEST (ccipher_test, caesar_0)
TEST (ccipher_test, caesar_1)
TEST (ccipher_test, caesar_2)
TEST (kcipher_test, keyword_0)
TEST (kcipher_test, keyword_1)
TEST (kcipher_test, error_cipher_text)
Variables
Cipher cc
Function Documentation
TEST() [1/6]
anonymous_namespace{t_cipher.cpp}::TEST (ccipher_test , caesar_0)
Definition at line 16 of file t_cipher.cpp.
{
         std::string text_0 = "Plaintext";
         int key_shift_0 = 5;
         std::string hashtext_0 = cc.C_cipher(text_0, key_shift_0);
         std::string expected_0 = "Uqfnsyjcy";
         EXPECT_EQ(expected_0, hashtext_0);
     }
References Cipher::C_cipher(), cc, and anonymous_namespace{t_rc4.cpp}::text_0.
TEST() [2/6]
anonymous_namespace{t_cipher.cpp}::TEST (ccipher_test , caesar_1)
Definition at line 25 of file t_cipher.cpp.
{
         std::string text_1 = "ATTACKATONCE";
         int key_shift_1 = 4;
         std::string hashtext_1 = cc.C_cipher(text_1, key_shift_1);
         std::string expected_1 = "EXXEGOEXSRGI";
         EXPECT_EQ(expected_1, hashtext_1);
     }
References Cipher::C_cipher(), cc, and anonymous_namespace{t_rc4.cpp}::text_1.
TEST() [3/6]
anonymous_namespace{t_cipher.cpp}::TEST (ccipher_test , caesar_2)
Definition at line 34 of file t_cipher.cpp.
{
         std::string text_2 = "EaSyPASsWorD";
         int key_shift_2 = 14;
         std::string hashtext_2 = cc.C_cipher(text_2, key_shift_2);
         std::string expected_2 = "SoGmDOGgKcfR";
         EXPECT_EQ(expected_2, hashtext_2);
     }
References Cipher::C_cipher(), cc, and anonymous_namespace{t_rc4.cpp}::text_2.
TEST() [4/6]
anonymous_namespace{t_cipher.cpp}::TEST (kcipher_test , error_cipher_text)
Definition at line 71 of file t_cipher.cpp.
{
         std::string text_4 = "P455W0RD";
         std::string key_shift_4 = "IN1T_d";
         // encode
         std::string encoded_text_1 = cc.KC_encode(key_shift_4);
         // cipher
         std::string hashtext_4 = cc.KC_cipher(text_4, encoded_text_1);
         std::string expected_4 = "O455W0QD";
         EXPECT_EQ(expected_4, hashtext_4);
     }
References cc, Cipher::KC_cipher(), and Cipher::KC_encode().
TEST() [5/6]
anonymous_namespace{t_cipher.cpp}::TEST (kcipher_test , keyword_0)
Definition at line 43 of file t_cipher.cpp.
{
         std::string text_3 = "Password";
         std::string key_shift_3 = "Computer";
         // encode
         std::string encoded_text_0 = cc.KC_encode(key_shift_3);
         // cipher
         std::string hashtext_3 = cc.KC_cipher(text_3, encoded_text_0);
         std::string expected_3 = "JCNNWILP";
         EXPECT_EQ(expected_3, hashtext_3);
     }
References cc, Cipher::KC_cipher(), and Cipher::KC_encode().
TEST() [6/6]
anonymous_namespace{t_cipher.cpp}::TEST (kcipher_test , keyword_1)
Definition at line 57 of file t_cipher.cpp.
{
         std::string text_4 = "Password";
         std::string key_shift_4 = "Password";
         // encode
         std::string encoded_text_1 = cc.KC_encode(key_shift_4);
         // cipher
         std::string hashtext_4 = cc.KC_cipher(text_4, encoded_text_1);
         std::string expected_4 = "KPNNVJMW";
         EXPECT_EQ(expected_4, hashtext_4);
     }
References cc, Cipher::KC_cipher(), and Cipher::KC_encode().
Variable Documentation
cc
Cipher anonymous_namespace{t_cipher.cpp}::cc
Definition at line 14 of file t_cipher.cpp.
Referenced by main(), and TEST().