openMTPK: OCaml/lib/openMTPK_wrap.cxx File Reference
openMTPK_wrap.cxx File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <caml/alloc.h>
#include <caml/custom.h>
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/misc.h>
#include <assert.h>
#include <typeinfo>
#include <stdexcept>
#include <string>
#include <vector>
#include <algorithm>
#include "../../include/arithmetic/arith.hpp"
#include "../../include/number_theory/primes.hpp"
#include "../../include/number_theory/rc4.hpp"
#include "../../include/number_theory/cipher.hpp"
#include <map>
#include <utility>
Classes
struct swig_type_info
struct swig_cast_info
struct swig_module_info
Macros
#define SWIG_VERSION 0x040100
#define SWIGOCAML
#define SWIG_MODULE "openMTPK"
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_TYPE_TABLE_NAME
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIG_BUFFER_SIZE 1024
#define SWIG_POINTER_DISOWN 0x1
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_POINTER_NO_NULL 0x4
#define SWIG_POINTER_CLEAR 0x8
#define SWIG_POINTER_RELEASE (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)
#define SWIG_POINTER_OWN 0x1
#define SWIG_OK (0)
#define SWIG_ERROR (-1)
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)
#define SWIG_IsOK(r) (r >= 0)
#define SWIG_ArgError(r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_AddNewMask(r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_AddCast(r) (r)
#define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#define SWIGEXT
#define value caml_value_t
#define CAML_VALUE caml_value_t
#define CAML_NAME_SPACE
#define OCAML_VERSION 0 /* Unknown, but < 40200 */
#define caml_array_set swig_caml_array_set
#define SWIG_CAMLlocal1(x)
#define SWIG_CAMLlocal2(x, y)
#define SWIG_CAMLlocal3(x, y, z)
#define SWIG_CAMLlocal4(x, y, z, t)
#define SWIG_CAMLlocal5(x, y, z, t, u)
#define SWIG_CAMLlocalN(x, size)
#define SWIG_Field(x, i) (((caml_value_t *)(x)) [i]) /* Also an l-value. */
#define SWIG_Store_field(block, offset, val)
#define SWIG_Data_custom_val(v) ((void *) &SWIG_Field((v), 1))
#define SWIG_Tag_val(val) (((unsigned char *) (val)) [-sizeof(caml_value_t)])
#define SWIG_Tag_hp(hp) (((unsigned char *) (hp)) [0])
#define CAMLreturn0
#define CAMLreturn(result)
#define CAMLreturn_type(result)
#define CAMLnoreturn ((void) caml__frame)
#define SWIG_Int64_val(v) (*((int64 *) SWIG_Data_custom_val(v)))
#define SWIG_NewPointerObj(p, type, flags) caml_val_ptr(p,type)
#define SWIG_GetModule(clientdata) SWIG_Ocaml_GetModule(clientdata)
#define SWIG_SetModule(clientdata, pointer) SWIG_Ocaml_SetModule(pointer)
#define SWIG_contract_assert(expr, msg) do { if(!(expr)) {SWIG_OCamlThrowException(SWIG_OCamlRuntimeException, msg);} } while (0)
#define C_bool 0
#define C_char 1
#define C_uchar 2
#define C_short 3
#define C_ushort 4
#define C_int 5
#define C_uint 6
#define C_int32 7
#define C_int64 8
#define C_float 9
#define C_double 10
#define C_ptr 11
#define C_array 12
#define C_list 13
#define C_obj 14
#define C_string 15
#define C_enum 16
#define C_director_core 17
#define caml_val_obj(v, name) caml_val_obj_helper(v, SWIG_TypeQuery((name)), name)
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define SWIGTYPE_p_Basics swig_types[0]
#define SWIGTYPE_p_Cipher swig_types[1]
#define SWIGTYPE_p_Primality swig_types[2]
#define SWIGTYPE_p_RC4 swig_types[3]
#define SWIGTYPE_p_uint8_t swig_types[4]
#define SWIGTYPE_p_unsigned_char swig_types[5]
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_exception(code, msg) SWIG_OCamlException(code, msg)
#define SWIG_init f_openMTPK_init
#define SWIG_INIT_CLIENT_DATA_TYPE void *
Typedefs
typedef void *(* swig_converter_func) (void *, int *)
typedef struct swig_type_info *(* swig_dycast_func) (void **)
typedef struct swig_type_info swig_type_info
typedef struct swig_cast_info swig_cast_info
typedef struct swig_module_info swig_module_info
Enumerations
enum SWIG_OCamlExceptionCodes {
SWIG_OCamlArithmeticException , SWIG_OCamlDirectorPureVirtual , SWIG_OCamlOutOfMemoryError , SWIG_OCamlOverflowException ,
SWIG_OCamlIllegalArgumentException , SWIG_OCamlIndexOutOfBoundsException , SWIG_OCamlRuntimeException , SWIG_OCamlSystemException ,
SWIG_OCamlUnknownError , SWIG_OCamlArithmeticException , SWIG_OCamlDirectorPureVirtual , SWIG_OCamlOutOfMemoryError ,
SWIG_OCamlOverflowException , SWIG_OCamlIllegalArgumentException , SWIG_OCamlIndexOutOfBoundsException , SWIG_OCamlRuntimeException ,
SWIG_OCamlSystemException , SWIG_OCamlUnknownError
}
Functions
SWIGRUNTIME int SWIG_TypeNameComp (const char *f1, const char *l1, const char *f2, const char *l2)
SWIGRUNTIME int SWIG_TypeCmp (const char *nb, const char *tb)
SWIGRUNTIME int SWIG_TypeEquiv (const char *nb, const char *tb)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (const swig_type_info *from, swig_type_info *ty)
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info *ty, void *ptr, int *newmemory)
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info *ty, void **ptr)
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info *ty)
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info *type)
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME char * SWIG_PackData (char *c, void *ptr, size_t sz)
SWIGRUNTIME const char * SWIG_UnpackData (const char *c, void *ptr, size_t sz)
SWIGRUNTIME char * SWIG_PackVoidPtr (char *buff, void *ptr, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char *c, void **ptr, const char *name)
SWIGRUNTIME char * SWIG_PackDataName (char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackDataName (const char *c, void *ptr, size_t sz, const char *name)
SWIGINTERN void SWIG_OCamlThrowException (SWIG_OCamlExceptionCodes code, const char *msg)
SWIGINTERN int SWIG_GetPtr (void *source, void **result, swig_type_info *type, swig_type_info *result_type)
SWIGINTERN CAML_VALUE caml_list_nth (CAML_VALUE lst, int n)
SWIGINTERN CAML_VALUE caml_list_append (CAML_VALUE lst, CAML_VALUE elt)
SWIGINTERN int caml_list_length (CAML_VALUE lst)
SWIGINTERN CAML_VALUE caml_array_new (int n)
SWIGINTERN void caml_array_set (CAML_VALUE arr, int n, CAML_VALUE item)
SWIGINTERN CAML_VALUE caml_array_nth (CAML_VALUE arr, int n)
SWIGINTERN int caml_array_len (CAML_VALUE arr)
SWIGINTERN CAML_VALUE caml_val_char (char c)
SWIGINTERN CAML_VALUE caml_val_uchar (unsigned char c)
SWIGINTERN CAML_VALUE caml_val_short (short s)
SWIGINTERN CAML_VALUE caml_val_ushort (unsigned short s)
SWIGINTERN CAML_VALUE caml_val_int (int x)
SWIGINTERN CAML_VALUE caml_val_uint (unsigned int x)
SWIGINTERN CAML_VALUE caml_val_long (long x)
SWIGINTERN CAML_VALUE caml_val_ulong (unsigned long x)
SWIGINTERN CAML_VALUE caml_val_float (float f)
SWIGINTERN CAML_VALUE caml_val_double (double d)
SWIGINTERN CAML_VALUE caml_val_ptr (void *p, swig_type_info *descriptor)
SWIGINTERN CAML_VALUE caml_val_string (const char *str)
SWIGINTERN CAML_VALUE caml_val_string_len (const char *str, int len)
SWIGINTERN long caml_long_val (CAML_VALUE v)
SWIGINTERN double caml_double_val (CAML_VALUE v)
SWIGINTERN int caml_ptr_val_internal (CAML_VALUE v, void **out, swig_type_info *descriptor)
SWIGINTERN void * caml_ptr_val (CAML_VALUE v, swig_type_info *descriptor)
SWIGINTERN char * caml_string_val (CAML_VALUE v)
SWIGINTERN int caml_string_len (CAML_VALUE v)
SWIGINTERN int SWIG_Cast (void *source, swig_type_info *source_type, void **ptr, swig_type_info *dest_type)
SWIGINTERN void caml_print_list (CAML_VALUE v)
SWIGINTERN void caml_print_val (CAML_VALUE v)
SWIGINTERN CAML_VALUE caml_swig_alloc (int x, int y)
SWIGINTERN CAML_VALUE caml_val_bool (int b)
SWIGINTERN CAML_VALUE caml_val_obj_helper (void *v, swig_type_info *type, char *name)
SWIGINTERN long caml_long_val_full (CAML_VALUE v, const char *name)
SWIGINTERN int caml_bool_check (CAML_VALUE v)
SWIGINTERN int caml_int_check (CAML_VALUE v)
SWIGINTERN int caml_float_check (CAML_VALUE v)
SWIGINTERN int caml_ptr_check (CAML_VALUE v)
SWIGINTERN CAML_VALUE SWIG_Ocaml_ptr_to_val (const char *name, void *ptr, swig_type_info *descriptor)
static swig_module_info * SWIG_Ocaml_GetModule (void *SWIGUNUSEDPARM(clientdata))
static void SWIG_Ocaml_SetModule (swig_module_info *pointer)
SWIGINTERN void SWIG_OCamlException (int code, const char *msg)
SWIGINTERNINLINE CAML_VALUE SwigString_FromString (const std::string &s)
SWIGINTERNINLINE std::string SwigString_AsString (CAML_VALUE o)
SWIGEXT CAML_VALUE _wrap_Basics_greatest_poweropenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Basics_rm_gcdopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_new_BasicsopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_delete_BasicsopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_is_primeopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_compute_miller_rabinopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_miller_rabin_primeopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_miller_rabinopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_jacobian_numberopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_solovoy_strassenopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_mod_powopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_carmichael_numopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_sieve_of_eratosthenesopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_pollard_rhoopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Primality_ETFopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_new_PrimalityopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_delete_PrimalityopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_BITS (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_BYTE_LIMIT (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_byte_swapopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_trad_swapopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_XOR_swapopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_KSAopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_PRGAopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_store_hashopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_RC4_computeopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_new_RC4openMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_delete_RC4openMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Cipher_C_cipheropenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Cipher_KC_encodeopenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_Cipher_KC_cipheropenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_new_CipheropenMTPK (CAML_VALUE args)
SWIGEXT CAML_VALUE _wrap_delete_CipheropenMTPK (CAML_VALUE args)
SWIGRUNTIME void SWIG_InitializeModule (SWIG_INIT_CLIENT_DATA_TYPE clientdata)
SWIGRUNTIME void SWIG_PropagateClientData (void)
Variables
static swig_type_info * swig_types [7]
static swig_module_info swig_module = {swig_types, 6, 0, 0, 0, 0}
static int _swig_wrap_BITS = 255
static int _swig_wrap_BYTE_LIMIT = 256
static swig_type_info _swigt__p_Basics = {"_p_Basics", "Basics *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_Cipher = {"_p_Cipher", "Cipher *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_Primality = {"_p_Primality", "Primality *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_RC4 = {"_p_RC4", "RC4 *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_uint8_t = {"_p_uint8_t", "uint8_t *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "unsigned char *", 0, 0, (void*)0, 0}
static swig_type_info * swig_type_initial []
static swig_cast_info _swigc__p_Basics [] = { {&_swigt__p_Basics, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_Cipher [] = { {&_swigt__p_Cipher, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_Primality [] = { {&_swigt__p_Primality, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_RC4 [] = { {&_swigt__p_RC4, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_uint8_t [] = { {&_swigt__p_uint8_t, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_unsigned_char [] = { {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info * swig_cast_initial []
Macro Definition Documentation
C_array
#define C_array 12
Definition at line 956 of file openMTPK_wrap.cxx.
C_bool
#define C_bool 0
Definition at line 944 of file openMTPK_wrap.cxx.
C_char
#define C_char 1
Definition at line 945 of file openMTPK_wrap.cxx.
C_director_core
#define C_director_core 17
Definition at line 961 of file openMTPK_wrap.cxx.
C_double
#define C_double 10
Definition at line 954 of file openMTPK_wrap.cxx.
C_enum
#define C_enum 16
Definition at line 960 of file openMTPK_wrap.cxx.
C_float
#define C_float 9
Definition at line 953 of file openMTPK_wrap.cxx.
C_int
#define C_int 5
Definition at line 949 of file openMTPK_wrap.cxx.
C_int32
#define C_int32 7
Definition at line 951 of file openMTPK_wrap.cxx.
C_int64
#define C_int64 8
Definition at line 952 of file openMTPK_wrap.cxx.
C_list
#define C_list 13
Definition at line 957 of file openMTPK_wrap.cxx.
C_obj
#define C_obj 14
Definition at line 958 of file openMTPK_wrap.cxx.
C_ptr
#define C_ptr 11
Definition at line 955 of file openMTPK_wrap.cxx.
C_short
#define C_short 3
Definition at line 947 of file openMTPK_wrap.cxx.
C_string
#define C_string 15
Definition at line 959 of file openMTPK_wrap.cxx.
C_uchar
#define C_uchar 2
Definition at line 946 of file openMTPK_wrap.cxx.
C_uint
#define C_uint 6
Definition at line 950 of file openMTPK_wrap.cxx.
C_ushort
#define C_ushort 4
Definition at line 948 of file openMTPK_wrap.cxx.
caml_array_set
#define caml_array_set swig_caml_array_set
Definition at line 754 of file openMTPK_wrap.cxx.
CAML_NAME_SPACE
#define CAML_NAME_SPACE
Definition at line 738 of file openMTPK_wrap.cxx.
caml_val_obj
#define caml_val_obj (v, name) caml_val_obj_helper(v, SWIG_TypeQuery((name)), name)
Definition at line 1308 of file openMTPK_wrap.cxx.
CAML_VALUE
#define CAML_VALUE caml_value_t
Definition at line 737 of file openMTPK_wrap.cxx.
CAMLnoreturn
#define CAMLnoreturn ((void) caml__frame)
Definition at line 827 of file openMTPK_wrap.cxx.
CAMLreturn
#define CAMLreturn (result)
Value:
  do{ \
  caml_value_t caml__temp_result = (result); \
  caml_local_roots = caml__frame; \
  return (caml__temp_result); \
}while(0)
Definition at line 813 of file openMTPK_wrap.cxx.
CAMLreturn0
#define CAMLreturn0
Value:
  do{ \
  caml_local_roots = caml__frame; \
  return; \
}while (0)
Definition at line 805 of file openMTPK_wrap.cxx.
CAMLreturn_type
#define CAMLreturn_type (result)
Value:
  do{ \
  caml_local_roots = caml__frame; \
  return result; \
}while(0)
Definition at line 819 of file openMTPK_wrap.cxx.
OCAML_VERSION
#define OCAML_VERSION 0 /* Unknown, but < 40200 */
Definition at line 751 of file openMTPK_wrap.cxx.
SWIG_AddCast
#define SWIG_AddCast (r) (r)
Definition at line 317 of file openMTPK_wrap.cxx.
SWIG_AddNewMask
#define SWIG_AddNewMask (r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
Definition at line 293 of file openMTPK_wrap.cxx.
SWIG_AddTmpMask
#define SWIG_AddTmpMask (r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
Definition at line 296 of file openMTPK_wrap.cxx.
SWIG_ArgError
#define SWIG_ArgError (r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
Definition at line 279 of file openMTPK_wrap.cxx.
SWIG_AttributeError
#define SWIG_AttributeError -11
Definition at line 1552 of file openMTPK_wrap.cxx.
SWIG_BADOBJ
#define SWIG_BADOBJ (SWIG_ERROR)
Definition at line 288 of file openMTPK_wrap.cxx.
SWIG_BUFFER_SIZE
#define SWIG_BUFFER_SIZE 1024
Definition at line 177 of file openMTPK_wrap.cxx.
SWIG_CAMLlocal1
#define SWIG_CAMLlocal1 (x)
Value:
  caml_value_t x = 0; \
  CAMLxparam1 (x)
Definition at line 758 of file openMTPK_wrap.cxx.
SWIG_CAMLlocal2
#define SWIG_CAMLlocal2 (x, y)
Value:
  caml_value_t x = 0, y = 0; \
  CAMLxparam2 (x, y)
Definition at line 762 of file openMTPK_wrap.cxx.
SWIG_CAMLlocal3
#define SWIG_CAMLlocal3 (x, y, z)
Value:
  caml_value_t x = 0, y = 0, z = 0; \
  CAMLxparam3 (x, y, z)
Definition at line 766 of file openMTPK_wrap.cxx.
SWIG_CAMLlocal4
#define SWIG_CAMLlocal4 (x, y, z, t)
Value:
  caml_value_t x = 0, y = 0, z = 0, t = 0; \
  CAMLxparam4 (x, y, z, t)
Definition at line 770 of file openMTPK_wrap.cxx.
SWIG_CAMLlocal5
#define SWIG_CAMLlocal5 (x, y, z, t, u)
Value:
  caml_value_t x = 0, y = 0, z = 0, t = 0, u = 0; \
  CAMLxparam5 (x, y, z, t, u)
Definition at line 774 of file openMTPK_wrap.cxx.
SWIG_CAMLlocalN
#define SWIG_CAMLlocalN (x, size)
Value:
  caml_value_t x [(size)] = { 0, /* 0, 0, ... */ }; \
  CAMLxparamN (x, (size))
Definition at line 778 of file openMTPK_wrap.cxx.
SWIG_CAST_NEW_MEMORY
#define SWIG_CAST_NEW_MEMORY 0x2
Definition at line 182 of file openMTPK_wrap.cxx.
SWIG_CASTRANKLIMIT
#define SWIG_CASTRANKLIMIT (1 << 8)
Definition at line 282 of file openMTPK_wrap.cxx.
SWIG_CheckState
#define SWIG_CheckState (r) (SWIG_IsOK(r) ? 1 : 0)
Definition at line 318 of file openMTPK_wrap.cxx.
SWIG_contract_assert
#define SWIG_contract_assert (expr, msg) do { if(!(expr)) {SWIG_OCamlThrowException(SWIG_OCamlRuntimeException, msg);} } while (0)
Definition at line 886 of file openMTPK_wrap.cxx.
SWIG_Data_custom_val
#define SWIG_Data_custom_val (v) ((void *) &SWIG_Field((v), 1))
Definition at line 789 of file openMTPK_wrap.cxx.
SWIG_DelNewMask
#define SWIG_DelNewMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
Definition at line 294 of file openMTPK_wrap.cxx.
SWIG_DelTmpMask
#define SWIG_DelTmpMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
Definition at line 297 of file openMTPK_wrap.cxx.
SWIG_DivisionByZero
#define SWIG_DivisionByZero -6
Definition at line 1547 of file openMTPK_wrap.cxx.
SWIG_ERROR
#define SWIG_ERROR (-1)
Definition at line 272 of file openMTPK_wrap.cxx.
SWIG_ERROR_RELEASE_NOT_OWNED
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)
Definition at line 276 of file openMTPK_wrap.cxx.
SWIG_exception
#define SWIG_exception (code, msg) SWIG_OCamlException(code, msg)
Definition at line 1659 of file openMTPK_wrap.cxx.
SWIG_Field
#define SWIG_Field (x, i) (((caml_value_t *)(x)) [i]) /* Also an l-value. */
Definition at line 782 of file openMTPK_wrap.cxx.
SWIG_GetModule
#define SWIG_GetModule (clientdata) SWIG_Ocaml_GetModule(clientdata)
Definition at line 846 of file openMTPK_wrap.cxx.
SWIG_IndexError
#define SWIG_IndexError -4
Definition at line 1545 of file openMTPK_wrap.cxx.
SWIG_init
#define SWIG_init (void) f_openMTPK_init
Definition at line 2630 of file openMTPK_wrap.cxx.
SWIG_INIT_CLIENT_DATA_TYPE
#define SWIG_INIT_CLIENT_DATA_TYPE void *
Definition at line 2684 of file openMTPK_wrap.cxx.
SWIG_Int64_val
#define SWIG_Int64_val (v) (*((int64 *) SWIG_Data_custom_val(v)))
Definition at line 834 of file openMTPK_wrap.cxx.
SWIG_IOError
#define SWIG_IOError -2
Definition at line 1543 of file openMTPK_wrap.cxx.
SWIG_IsNewObj
#define SWIG_IsNewObj (r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
Definition at line 295 of file openMTPK_wrap.cxx.
SWIG_IsOK
#define SWIG_IsOK (r) (r >= 0)
Definition at line 278 of file openMTPK_wrap.cxx.
SWIG_IsTmpObj
#define SWIG_IsTmpObj (r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
Definition at line 298 of file openMTPK_wrap.cxx.
SWIG_MangledTypeQuery
#define SWIG_MangledTypeQuery (name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)
Definition at line 1569 of file openMTPK_wrap.cxx.
SWIG_MemoryError
#define SWIG_MemoryError -12
Definition at line 1553 of file openMTPK_wrap.cxx.
SWIG_MODULE
#define SWIG_MODULE "openMTPK"
Definition at line 12 of file openMTPK_wrap.cxx.
SWIG_NEWOBJ
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
Definition at line 290 of file openMTPK_wrap.cxx.
SWIG_NEWOBJMASK
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
Definition at line 284 of file openMTPK_wrap.cxx.
SWIG_NewPointerObj
#define SWIG_NewPointerObj (p, type, flags) caml_val_ptr(p,type)
Definition at line 845 of file openMTPK_wrap.cxx.
SWIG_NullReferenceError
#define SWIG_NullReferenceError -13
Definition at line 1554 of file openMTPK_wrap.cxx.
SWIG_OK
#define SWIG_OK (0)
Definition at line 270 of file openMTPK_wrap.cxx.
SWIG_OLDOBJ
#define SWIG_OLDOBJ (SWIG_OK)
Definition at line 289 of file openMTPK_wrap.cxx.
SWIG_OverflowError
#define SWIG_OverflowError -7
Definition at line 1548 of file openMTPK_wrap.cxx.
SWIG_POINTER_CLEAR
#define SWIG_POINTER_CLEAR 0x8
Definition at line 184 of file openMTPK_wrap.cxx.
SWIG_POINTER_DISOWN
#define SWIG_POINTER_DISOWN 0x1
Definition at line 181 of file openMTPK_wrap.cxx.
SWIG_POINTER_NO_NULL
#define SWIG_POINTER_NO_NULL 0x4
Definition at line 183 of file openMTPK_wrap.cxx.
SWIG_POINTER_OWN
#define SWIG_POINTER_OWN 0x1
Definition at line 188 of file openMTPK_wrap.cxx.
SWIG_POINTER_RELEASE
#define SWIG_POINTER_RELEASE (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)
Definition at line 185 of file openMTPK_wrap.cxx.
SWIG_RUNTIME_VERSION
#define SWIG_RUNTIME_VERSION "4"
Definition at line 147 of file openMTPK_wrap.cxx.
SWIG_RuntimeError
#define SWIG_RuntimeError -3
Definition at line 1544 of file openMTPK_wrap.cxx.
SWIG_SetModule
#define SWIG_SetModule (clientdata, pointer) SWIG_Ocaml_SetModule(pointer)
Definition at line 847 of file openMTPK_wrap.cxx.
SWIG_Store_field
#define SWIG_Store_field (block, offset, val)
Value:
  do{ \
  mlsize_t caml__temp_offset = (offset); \
  caml_value_t caml__temp_val = (val); \
  caml_modify (&SWIG_Field ((block), caml__temp_offset), caml__temp_val); \
}while(0)
Definition at line 783 of file openMTPK_wrap.cxx.
SWIG_SyntaxError
#define SWIG_SyntaxError -8
Definition at line 1549 of file openMTPK_wrap.cxx.
SWIG_SystemError
#define SWIG_SystemError -10
Definition at line 1551 of file openMTPK_wrap.cxx.
SWIG_Tag_hp
#define SWIG_Tag_hp (hp) (((unsigned char *) (hp)) [0])
Definition at line 798 of file openMTPK_wrap.cxx.
SWIG_Tag_val
#define SWIG_Tag_val (val) (((unsigned char *) (val)) [-sizeof(caml_value_t)])
Definition at line 796 of file openMTPK_wrap.cxx.
SWIG_TMPOBJ
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
Definition at line 291 of file openMTPK_wrap.cxx.
SWIG_TMPOBJMASK
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
Definition at line 286 of file openMTPK_wrap.cxx.
SWIG_TYPE_TABLE_NAME
#define SWIG_TYPE_TABLE_NAME
Definition at line 155 of file openMTPK_wrap.cxx.
SWIG_TypeError
#define SWIG_TypeError -5
Definition at line 1546 of file openMTPK_wrap.cxx.
SWIG_TypeQuery
#define SWIG_TypeQuery (name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
Definition at line 1568 of file openMTPK_wrap.cxx.
SWIG_UnknownError
#define SWIG_UnknownError -1
Definition at line 1542 of file openMTPK_wrap.cxx.
SWIG_ValueError
#define SWIG_ValueError -9
Definition at line 1550 of file openMTPK_wrap.cxx.
SWIG_VERSION
#define SWIG_VERSION 0x040100
Definition at line 10 of file openMTPK_wrap.cxx.
SWIGEXPORT
#define SWIGEXPORT
Definition at line 100 of file openMTPK_wrap.cxx.
SWIGEXT
#define SWIGEXT
Definition at line 734 of file openMTPK_wrap.cxx.
SWIGINLINE
#define SWIGINLINE
Definition at line 37 of file openMTPK_wrap.cxx.
SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
Definition at line 72 of file openMTPK_wrap.cxx.
SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
Definition at line 77 of file openMTPK_wrap.cxx.
SWIGOCAML
#define SWIGOCAML
Definition at line 11 of file openMTPK_wrap.cxx.
SWIGRUNTIME
#define SWIGRUNTIME SWIGINTERN
Definition at line 168 of file openMTPK_wrap.cxx.
SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
Definition at line 172 of file openMTPK_wrap.cxx.
SWIGSTDCALL
#define SWIGSTDCALL
Definition at line 110 of file openMTPK_wrap.cxx.
SWIGTEMPLATEDISAMBIGUATOR
#define SWIGTEMPLATEDISAMBIGUATOR
Definition at line 28 of file openMTPK_wrap.cxx.
SWIGTYPE_p_Basics
#define SWIGTYPE_p_Basics swig_types[0]
Definition at line 1560 of file openMTPK_wrap.cxx.
SWIGTYPE_p_Cipher
#define SWIGTYPE_p_Cipher swig_types[1]
Definition at line 1561 of file openMTPK_wrap.cxx.
SWIGTYPE_p_Primality
#define SWIGTYPE_p_Primality swig_types[2]
Definition at line 1562 of file openMTPK_wrap.cxx.
SWIGTYPE_p_RC4
#define SWIGTYPE_p_RC4 swig_types[3]
Definition at line 1563 of file openMTPK_wrap.cxx.
SWIGTYPE_p_uint8_t
#define SWIGTYPE_p_uint8_t swig_types[4]
Definition at line 1564 of file openMTPK_wrap.cxx.
SWIGTYPE_p_unsigned_char
#define SWIGTYPE_p_unsigned_char swig_types[5]
Definition at line 1565 of file openMTPK_wrap.cxx.
SWIGUNUSED
#define SWIGUNUSED
Definition at line 52 of file openMTPK_wrap.cxx.
SWIGUNUSEDPARM
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
Definition at line 66 of file openMTPK_wrap.cxx.
value
#define value caml_value_t
Definition at line 736 of file openMTPK_wrap.cxx.
Typedef Documentation
swig_cast_info
typedef struct swig_cast_info swig_cast_info
swig_converter_func
typedef void*(* swig_converter_func) (void *, int *)
Definition at line 328 of file openMTPK_wrap.cxx.
swig_dycast_func
typedef struct swig_type_info*(* swig_dycast_func) (void **)
Definition at line 328 of file openMTPK_wrap.cxx.
swig_module_info
typedef struct swig_module_info swig_module_info
swig_type_info
typedef struct swig_type_info swig_type_info
Enumeration Type Documentation
SWIG_OCamlExceptionCodes
enum SWIG_OCamlExceptionCodes
Enumerator
SWIG_OCamlArithmeticException
SWIG_OCamlDirectorPureVirtual
SWIG_OCamlOutOfMemoryError
SWIG_OCamlOverflowException
SWIG_OCamlIllegalArgumentException
SWIG_OCamlIndexOutOfBoundsException
SWIG_OCamlRuntimeException
SWIG_OCamlSystemException
SWIG_OCamlUnknownError
SWIG_OCamlArithmeticException
SWIG_OCamlDirectorPureVirtual
SWIG_OCamlOutOfMemoryError
SWIG_OCamlOverflowException
SWIG_OCamlIllegalArgumentException
SWIG_OCamlIndexOutOfBoundsException
SWIG_OCamlRuntimeException
SWIG_OCamlSystemException
SWIG_OCamlUnknownError
Definition at line 849 of file openMTPK_wrap.cxx.
              {
   SWIG_OCamlArithmeticException,
   SWIG_OCamlDirectorPureVirtual,
   SWIG_OCamlOutOfMemoryError,
   SWIG_OCamlOverflowException,
   SWIG_OCamlIllegalArgumentException,
   SWIG_OCamlIndexOutOfBoundsException,
   SWIG_OCamlRuntimeException,
   SWIG_OCamlSystemException,
   SWIG_OCamlUnknownError
 } SWIG_OCamlExceptionCodes;
Function Documentation
_wrap_Basics_greatest_poweropenMTPK()
SWIGEXT CAML_VALUE _wrap_Basics_greatest_poweropenMTPK (CAML_VALUE args)
Definition at line 1706 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Basics *arg1 = (Basics *) 0 ;
   int arg2 ;
   int arg3 ;
   int result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Basics_greatest_power'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Basics *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Basics);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (int)(arg1)->greatest_power(arg2,arg3);
   {
     rv = caml_val_int(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_int(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Basics.
_wrap_Basics_rm_gcdopenMTPK()
SWIGEXT CAML_VALUE _wrap_Basics_rm_gcdopenMTPK (CAML_VALUE args)
Definition at line 1737 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Basics *arg1 = (Basics *) 0 ;
   int arg2 ;
   int arg3 ;
   int result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Basics_rm_gcd'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Basics *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Basics);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (int)(arg1)->rm_gcd(arg2,arg3);
   {
     rv = caml_val_int(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_int(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Basics.
_wrap_BITS()
SWIGEXT CAML_VALUE _wrap_BITS (CAML_VALUE args)
Definition at line 2165 of file openMTPK_wrap.cxx.
{
   CAMLparam1(args);
   SWIG_CAMLlocal1(swig_result);
   swig_result = Val_unit;
   {
     swig_result = caml_val_int(_swig_wrap_BITS);
   }
   CAMLreturn(swig_result);
 }
References _swig_wrap_BITS, caml_val_int(), CAMLreturn, and SWIG_CAMLlocal1.
_wrap_BYTE_LIMIT()
SWIGEXT CAML_VALUE _wrap_BYTE_LIMIT (CAML_VALUE args)
Definition at line 2178 of file openMTPK_wrap.cxx.
{
   CAMLparam1(args);
   SWIG_CAMLlocal1(swig_result);
   swig_result = Val_unit;
   {
     swig_result = caml_val_int(_swig_wrap_BYTE_LIMIT);
   }
   CAMLreturn(swig_result);
 }
References _swig_wrap_BYTE_LIMIT, caml_val_int(), CAMLreturn, and SWIG_CAMLlocal1.
_wrap_Cipher_C_cipheropenMTPK()
SWIGEXT CAML_VALUE _wrap_Cipher_C_cipheropenMTPK (CAML_VALUE args)
Definition at line 2454 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Cipher *arg1 = (Cipher *) 0 ;
   std::string arg2 ;
   int arg3 ;
   std::string result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Cipher_C_cipher'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Cipher *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Cipher);
   }
   {
     if (caml_ptr_check(caml_list_nth(args,1)))
     (&arg2)->assign((char *)caml_ptr_val(caml_list_nth(args,1),0), caml_string_len(caml_list_nth(args,1)));
     else
     SWIG_exception(SWIG_TypeError, "string expected");
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (arg1)->C_cipher(arg2,arg3);
   {
     rv = caml_val_string_len((&result)->c_str(),(&result)->size());
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_check(), caml_ptr_val(), caml_string_len(), caml_val_string_len(), CAMLreturn, SWIG_CAMLlocal2, SWIG_exception, SWIG_TypeError, and SWIGTYPE_p_Cipher.
_wrap_Cipher_KC_cipheropenMTPK()
SWIGEXT CAML_VALUE _wrap_Cipher_KC_cipheropenMTPK (CAML_VALUE args)
Definition at line 2518 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Cipher *arg1 = (Cipher *) 0 ;
   std::string arg2 ;
   std::string arg3 ;
   std::string result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Cipher_KC_cipher'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Cipher *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Cipher);
   }
   {
     if (caml_ptr_check(caml_list_nth(args,1)))
     (&arg2)->assign((char *)caml_ptr_val(caml_list_nth(args,1),0), caml_string_len(caml_list_nth(args,1)));
     else
     SWIG_exception(SWIG_TypeError, "string expected");
   }
   {
     if (caml_ptr_check(caml_list_nth(args,2)))
     (&arg3)->assign((char *)caml_ptr_val(caml_list_nth(args,2),0), caml_string_len(caml_list_nth(args,2)));
     else
     SWIG_exception(SWIG_TypeError, "string expected");
   }
   result = (arg1)->KC_cipher(arg2,arg3);
   {
     rv = caml_val_string_len((&result)->c_str(),(&result)->size());
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_check(), caml_ptr_val(), caml_string_len(), caml_val_string_len(), CAMLreturn, SWIG_CAMLlocal2, SWIG_exception, SWIG_TypeError, and SWIGTYPE_p_Cipher.
_wrap_Cipher_KC_encodeopenMTPK()
SWIGEXT CAML_VALUE _wrap_Cipher_KC_encodeopenMTPK (CAML_VALUE args)
Definition at line 2488 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Cipher *arg1 = (Cipher *) 0 ;
   std::string arg2 ;
   std::string result;
   if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Cipher_KC_encode'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Cipher *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Cipher);
   }
   {
     if (caml_ptr_check(caml_list_nth(args,1)))
     (&arg2)->assign((char *)caml_ptr_val(caml_list_nth(args,1),0), caml_string_len(caml_list_nth(args,1)));
     else
     SWIG_exception(SWIG_TypeError, "string expected");
   }
   result = (arg1)->KC_encode(arg2);
   {
     rv = caml_val_string_len((&result)->c_str(),(&result)->size());
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_check(), caml_ptr_val(), caml_string_len(), caml_val_string_len(), CAMLreturn, SWIG_CAMLlocal2, SWIG_exception, SWIG_TypeError, and SWIGTYPE_p_Cipher.
_wrap_delete_BasicsopenMTPK()
SWIGEXT CAML_VALUE _wrap_delete_BasicsopenMTPK (CAML_VALUE args)
Definition at line 1785 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Basics *arg1 = (Basics *) 0 ;
   if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
     caml_invalid_argument("Incorrect number of arguments passed to 'delete_Basics'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Basics *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Basics);
   }
   delete arg1;
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Basics.
_wrap_delete_CipheropenMTPK()
SWIGEXT CAML_VALUE _wrap_delete_CipheropenMTPK (CAML_VALUE args)
Definition at line 2572 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Cipher *arg1 = (Cipher *) 0 ;
   if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
     caml_invalid_argument("Incorrect number of arguments passed to 'delete_Cipher'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Cipher *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Cipher);
   }
   delete arg1;
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Cipher.
_wrap_delete_PrimalityopenMTPK()
SWIGEXT CAML_VALUE _wrap_delete_PrimalityopenMTPK (CAML_VALUE args)
Definition at line 2145 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
     caml_invalid_argument("Incorrect number of arguments passed to 'delete_Primality'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   delete arg1;
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_delete_RC4openMTPK()
SWIGEXT CAML_VALUE _wrap_delete_RC4openMTPK (CAML_VALUE args)
Definition at line 2434 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
     caml_invalid_argument("Incorrect number of arguments passed to 'delete_RC4'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   delete arg1;
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
_wrap_new_BasicsopenMTPK()
SWIGEXT CAML_VALUE _wrap_new_BasicsopenMTPK (CAML_VALUE args)
Definition at line 1768 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Basics *result = 0 ;
   if (caml_list_length(args) > 0) caml_invalid_argument("'new_Basics' takes no arguments");
   swig_result = Val_unit;
   result = (Basics *)new Basics();
   {
     rv = SWIG_Ocaml_ptr_to_val("create_Basics_from_ptr", (void *)result, SWIGTYPE_p_Basics);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), CAMLreturn, SWIG_CAMLlocal2, SWIG_Ocaml_ptr_to_val(), and SWIGTYPE_p_Basics.
_wrap_new_CipheropenMTPK()
SWIGEXT CAML_VALUE _wrap_new_CipheropenMTPK (CAML_VALUE args)
Definition at line 2555 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Cipher *result = 0 ;
   if (caml_list_length(args) > 0) caml_invalid_argument("'new_Cipher' takes no arguments");
   swig_result = Val_unit;
   result = (Cipher *)new Cipher();
   {
     rv = SWIG_Ocaml_ptr_to_val("create_Cipher_from_ptr", (void *)result, SWIGTYPE_p_Cipher);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), CAMLreturn, SWIG_CAMLlocal2, SWIG_Ocaml_ptr_to_val(), and SWIGTYPE_p_Cipher.
_wrap_new_PrimalityopenMTPK()
SWIGEXT CAML_VALUE _wrap_new_PrimalityopenMTPK (CAML_VALUE args)
Definition at line 2128 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *result = 0 ;
   if (caml_list_length(args) > 0) caml_invalid_argument("'new_Primality' takes no arguments");
   swig_result = Val_unit;
   result = (Primality *)new Primality();
   {
     rv = SWIG_Ocaml_ptr_to_val("create_Primality_from_ptr", (void *)result, SWIGTYPE_p_Primality);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), CAMLreturn, SWIG_CAMLlocal2, SWIG_Ocaml_ptr_to_val(), and SWIGTYPE_p_Primality.
_wrap_new_RC4openMTPK()
SWIGEXT CAML_VALUE _wrap_new_RC4openMTPK (CAML_VALUE args)
Definition at line 2417 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *result = 0 ;
   if (caml_list_length(args) > 0) caml_invalid_argument("'new_RC4' takes no arguments");
   swig_result = Val_unit;
   result = (RC4 *)new RC4();
   {
     rv = SWIG_Ocaml_ptr_to_val("create_RC4_from_ptr", (void *)result, SWIGTYPE_p_RC4);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), CAMLreturn, SWIG_CAMLlocal2, SWIG_Ocaml_ptr_to_val(), and SWIGTYPE_p_RC4.
_wrap_Primality_carmichael_numopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_carmichael_numopenMTPK (CAML_VALUE args)
Definition at line 2023 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   bool result;
   if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_carmichael_num'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   result = (bool)(arg1)->carmichael_num(arg2);
   {
     rv = caml_val_bool(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_bool(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_compute_miller_rabinopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_compute_miller_rabinopenMTPK (CAML_VALUE args)
Definition at line 1832 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   int arg3 ;
   bool result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_compute_miller_rabin'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (bool)(arg1)->compute_miller_rabin(arg2,arg3);
   {
     rv = caml_val_bool(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_bool(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_ETFopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_ETFopenMTPK (CAML_VALUE args)
Definition at line 2101 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   unsigned int arg2 ;
   int result;
   if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_ETF'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   result = (int)(arg1)->ETF(arg2);
   {
     rv = caml_val_int(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_int(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_is_primeopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_is_primeopenMTPK (CAML_VALUE args)
Definition at line 1805 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   bool result;
   if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_is_prime'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   result = (bool)(arg1)->is_prime(arg2);
   {
     rv = caml_val_bool(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_bool(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_jacobian_numberopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_jacobian_numberopenMTPK (CAML_VALUE args)
Definition at line 1926 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   long long arg3 ;
   int result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_jacobian_number'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (int)(arg1)->jacobian_number(arg2,arg3);
   {
     rv = caml_val_int(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_int(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_miller_rabin_primeopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_miller_rabin_primeopenMTPK (CAML_VALUE args)
Definition at line 1863 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   int arg3 ;
   bool result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_miller_rabin_prime'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (bool)(arg1)->miller_rabin_prime(arg2,arg3);
   {
     rv = caml_val_bool(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_bool(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_miller_rabinopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_miller_rabinopenMTPK (CAML_VALUE args)
Definition at line 1894 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   int arg3 ;
   int arg4 ;
   if (caml_list_length(args) < 4 || caml_list_length(args) > 4) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_miller_rabin'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   {
     arg4 = caml_long_val(caml_list_nth(args,3));
   }
   (arg1)->miller_rabin(arg2,arg3,arg4);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_mod_powopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_mod_powopenMTPK (CAML_VALUE args)
Definition at line 1988 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   long long arg3 ;
   long long arg4 ;
   long long result;
   if (caml_list_length(args) < 4 || caml_list_length(args) > 4) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_mod_pow'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   {
     arg4 = caml_long_val(caml_list_nth(args,3));
   }
   result = (long long)(arg1)->mod_pow(arg2,arg3,arg4);
   {
     rv = caml_val_ulong(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_ulong(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_pollard_rhoopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_pollard_rhoopenMTPK (CAML_VALUE args)
Definition at line 2074 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   long long result;
   if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_pollard_rho'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   result = (long long)(arg1)->pollard_rho(arg2);
   {
     rv = caml_val_ulong(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_ulong(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_sieve_of_eratosthenesopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_sieve_of_eratosthenesopenMTPK (CAML_VALUE args)
Definition at line 2050 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   int arg2 ;
   if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_sieve_of_eratosthenes'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   (arg1)->sieve_of_eratosthenes(arg2);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_Primality_solovoy_strassenopenMTPK()
SWIGEXT CAML_VALUE _wrap_Primality_solovoy_strassenopenMTPK (CAML_VALUE args)
Definition at line 1957 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   Primality *arg1 = (Primality *) 0 ;
   long long arg2 ;
   int arg3 ;
   bool result;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'Primality_solovoy_strassen'");
   }
   swig_result = Val_unit;
   {
     arg1 = (Primality *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_Primality);
   }
   {
     arg2 = caml_long_val(caml_list_nth(args,1));
   }
   {
     arg3 = caml_long_val(caml_list_nth(args,2));
   }
   result = (bool)(arg1)->solovoy_strassen(arg2,arg3);
   {
     rv = caml_val_bool(result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_val_bool(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_Primality.
_wrap_RC4_byte_swapopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_byte_swapopenMTPK (CAML_VALUE args)
Definition at line 2191 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   uint8_t *arg2 = (uint8_t *) 0 ;
   uint8_t *arg3 = (uint8_t *) 0 ;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_byte_swap'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (uint8_t *)caml_ptr_val(caml_list_nth(args,1),SWIGTYPE_p_uint8_t);
   }
   {
     arg3 = (uint8_t *)caml_ptr_val(caml_list_nth(args,2),SWIGTYPE_p_uint8_t);
   }
   (arg1)->byte_swap(arg2,arg3);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), CAMLreturn, SWIG_CAMLlocal2, SWIGTYPE_p_RC4, and SWIGTYPE_p_uint8_t.
_wrap_RC4_computeopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_computeopenMTPK (CAML_VALUE args)
Definition at line 2378 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   char *arg2 = (char *) 0 ;
   char *arg3 = (char *) 0 ;
   unsigned char *arg4 = (unsigned char *) 0 ;
   int arg5 ;
   unsigned char *result = 0 ;
   if (caml_list_length(args) < 5 || caml_list_length(args) > 5) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_compute'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (char *)caml_string_val(caml_list_nth(args,1));
   }
   {
     arg3 = (char *)caml_string_val(caml_list_nth(args,2));
   }
   {
     arg4 = (unsigned char *)caml_string_val(caml_list_nth(args,3));
   }
   {
     arg5 = caml_long_val(caml_list_nth(args,4));
   }
   result = (unsigned char *)(arg1)->compute(arg2,arg3,arg4,arg5);
   {
     rv = caml_val_string((char *)result);
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_string_val(), caml_val_string(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
_wrap_RC4_KSAopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_KSAopenMTPK (CAML_VALUE args)
Definition at line 2275 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   char *arg2 = (char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   int arg4 ;
   if (caml_list_length(args) < 4 || caml_list_length(args) > 4) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_KSA'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (char *)caml_string_val(caml_list_nth(args,1));
   }
   {
     arg3 = (unsigned char *)caml_string_val(caml_list_nth(args,2));
   }
   {
     arg4 = caml_long_val(caml_list_nth(args,3));
   }
   (arg1)->KSA(arg2,arg3,arg4);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_string_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
_wrap_RC4_PRGAopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_PRGAopenMTPK (CAML_VALUE args)
Definition at line 2307 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   unsigned char *arg2 = (unsigned char *) 0 ;
   char *arg3 = (char *) 0 ;
   unsigned char *arg4 = (unsigned char *) 0 ;
   int arg5 ;
   if (caml_list_length(args) < 5 || caml_list_length(args) > 5) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_PRGA'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (unsigned char *)caml_string_val(caml_list_nth(args,1));
   }
   {
     arg3 = (char *)caml_string_val(caml_list_nth(args,2));
   }
   {
     arg4 = (unsigned char *)caml_string_val(caml_list_nth(args,3));
   }
   {
     arg5 = caml_long_val(caml_list_nth(args,4));
   }
   (arg1)->PRGA(arg2,arg3,arg4,arg5);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_string_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
_wrap_RC4_store_hashopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_store_hashopenMTPK (CAML_VALUE args)
Definition at line 2343 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   char *arg2 = (char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   int arg4 ;
   std::string result;
   if (caml_list_length(args) < 4 || caml_list_length(args) > 4) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_store_hash'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (char *)caml_string_val(caml_list_nth(args,1));
   }
   {
     arg3 = (unsigned char *)caml_string_val(caml_list_nth(args,2));
   }
   {
     arg4 = caml_long_val(caml_list_nth(args,3));
   }
   result = (arg1)->store_hash(arg2,arg3,arg4);
   {
     rv = caml_val_string_len((&result)->c_str(),(&result)->size());
   }
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_long_val(), caml_ptr_val(), caml_string_val(), caml_val_string_len(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
_wrap_RC4_trad_swapopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_trad_swapopenMTPK (CAML_VALUE args)
Definition at line 2219 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   unsigned char *arg2 = (unsigned char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_trad_swap'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (unsigned char *)caml_string_val(caml_list_nth(args,1));
   }
   {
     arg3 = (unsigned char *)caml_string_val(caml_list_nth(args,2));
   }
   (arg1)->trad_swap(arg2,arg3);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), caml_string_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
_wrap_RC4_XOR_swapopenMTPK()
SWIGEXT CAML_VALUE _wrap_RC4_XOR_swapopenMTPK (CAML_VALUE args)
Definition at line 2247 of file openMTPK_wrap.cxx.
 {
   CAMLparam1(args);
   SWIG_CAMLlocal2(swig_result,rv);
   RC4 *arg1 = (RC4 *) 0 ;
   unsigned char *arg2 = (unsigned char *) 0 ;
   unsigned char *arg3 = (unsigned char *) 0 ;
   if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
     caml_invalid_argument("Incorrect number of arguments passed to 'RC4_XOR_swap'");
   }
   swig_result = Val_unit;
   {
     arg1 = (RC4 *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_RC4);
   }
   {
     arg2 = (unsigned char *)caml_string_val(caml_list_nth(args,1));
   }
   {
     arg3 = (unsigned char *)caml_string_val(caml_list_nth(args,2));
   }
   (arg1)->XOR_swap(arg2,arg3);
   rv = Val_unit;
   swig_result = caml_list_append(swig_result,rv);
   CAMLreturn(swig_result);
 }
References caml_list_append(), caml_list_length(), caml_list_nth(), caml_ptr_val(), caml_string_val(), CAMLreturn, SWIG_CAMLlocal2, and SWIGTYPE_p_RC4.
caml_array_len()
SWIGINTERN int caml_array_len (CAML_VALUE arr)
Definition at line 1170 of file openMTPK_wrap.cxx.
{
     CAMLparam1(arr);
     if( SWIG_Tag_val(arr) == C_array )
         CAMLreturn(Wosize_val(SWIG_Field(arr,0)));
     else if( SWIG_Tag_val(arr) == C_list )
         CAMLreturn(caml_list_length(arr));
     else
         caml_failwith("Need array or list");
     }
References C_array, C_list, caml_list_length(), CAMLreturn, SWIG_Field, and SWIG_Tag_val.
caml_array_new()
SWIGINTERN CAML_VALUE caml_array_new (int n)
Definition at line 1184 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(vv);
     vv = caml_swig_alloc(1,C_array);
     SWIG_Store_field(vv,0,caml_alloc_tuple(n));
     CAMLreturn(vv);
     }
References C_array, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_array_nth()
SWIGINTERN CAML_VALUE caml_array_nth (CAML_VALUE arr, int n)
Definition at line 1160 of file openMTPK_wrap.cxx.
{
     CAMLparam1(arr);
     if( SWIG_Tag_val(arr) == C_array )
         CAMLreturn(SWIG_Field(SWIG_Field(arr,0),n));
     else if( SWIG_Tag_val(arr) == C_list )
         CAMLreturn(caml_list_nth(arr,0));
     else
         caml_failwith("Need array or list");
     }
References C_array, C_list, caml_list_nth(), CAMLreturn, SWIG_Field, and SWIG_Tag_val.
caml_array_set()
SWIGINTERN void caml_array_set (CAML_VALUE arr, int n, CAML_VALUE item)
Definition at line 1154 of file openMTPK_wrap.cxx.
{
     CAMLparam2(arr,item);
     SWIG_Store_field(SWIG_Field(arr,0),n,item);
     CAMLreturn0;
     }
References CAMLreturn0, SWIG_Field, and SWIG_Store_field.
caml_bool_check()
SWIGINTERN int caml_bool_check (CAML_VALUE v)
Definition at line 1440 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     if( !Is_block(v) ) return 0;
     switch( SWIG_Tag_val(v) ) {
     case C_bool:
     case C_ptr:
     case C_string:
         CAMLreturn(1);
     default:
         CAMLreturn(0);
     }
     }
References C_bool, C_ptr, C_string, CAMLreturn, and SWIG_Tag_val.
caml_double_val()
SWIGINTERN double caml_double_val (CAML_VALUE v)
Definition at line 1356 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     if( !Is_block(v) ) return 0.0;
     switch( SWIG_Tag_val(v) ) {
     case C_bool:
     case C_char:
     case C_uchar:
     case C_short:
     case C_ushort:
     case C_int:
         CAMLreturn_type(Int_val(SWIG_Field(v,0)));
     case C_uint:
     case C_int32:
         CAMLreturn_type(Int32_val(SWIG_Field(v,0)));
     case C_int64:
         CAMLreturn_type(SWIG_Int64_val(SWIG_Field(v,0)));
     case C_float:
     case C_double:
         CAMLreturn_type(Double_val(SWIG_Field(v,0)));
     default:
         fprintf( stderr, "Unknown block tag %d\n", SWIG_Tag_val(v) );
         caml_failwith("No conversion to double");
     }
     }
References C_bool, C_char, C_double, C_float, C_int, C_int32, C_int64, C_short, C_uchar, C_uint, C_ushort, CAMLreturn_type, SWIG_Field, SWIG_Int64_val, and SWIG_Tag_val.
Referenced by caml_print_val().
caml_float_check()
SWIGINTERN int caml_float_check (CAML_VALUE v)
Definition at line 1476 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     if( !Is_block(v) ) return 0;
     switch( SWIG_Tag_val(v) ) {
     case C_float:
     case C_double:
         CAMLreturn(1);
     default:
         CAMLreturn(0);
     }
     }
References C_double, C_float, CAMLreturn, and SWIG_Tag_val.
caml_int_check()
SWIGINTERN int caml_int_check (CAML_VALUE v)
Definition at line 1455 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     if( !Is_block(v) ) return 0;
     switch( SWIG_Tag_val(v) ) {
     case C_char:
     case C_uchar:
     case C_short:
     case C_ushort:
     case C_int:
     case C_uint:
     case C_int32:
     case C_int64:
         CAMLreturn(1);
     default:
         CAMLreturn(0);
     }
     }
References C_char, C_int, C_int32, C_int64, C_short, C_uchar, C_uint, C_ushort, CAMLreturn, and SWIG_Tag_val.
caml_list_append()
SWIGINTERN CAML_VALUE caml_list_append (CAML_VALUE lst, CAML_VALUE elt)
Definition at line 1113 of file openMTPK_wrap.cxx.
{
     CAMLparam2(lst,elt);
     SWIG_CAMLlocal3(v,vt,lh);
     lh = Val_unit;
     v = Val_unit;
     /* Appending C_void should have no effect */
     if( !Is_block(elt) ) return lst;
     while( lst && Is_block(lst) ) {
         if( v && v != Val_unit ) {
         vt = caml_alloc_tuple(2);
         SWIG_Store_field(v,1,vt);
         v = vt;
         } else {
         v = lh = caml_alloc_tuple(2);
         }
         SWIG_Store_field(v,0,SWIG_Field(lst,0));
         lst = SWIG_Field(lst,1);
     }
     if( v && Is_block(v) ) {
         vt = caml_alloc_tuple(2);
         SWIG_Store_field(v,1,vt);
         v = vt;
     } else {
         v = lh = caml_alloc_tuple(2);
     }
     SWIG_Store_field(v,0,elt);
     SWIG_Store_field(v,1,Val_unit);
     CAMLreturn(lh);
     }
References CAMLreturn, SWIG_CAMLlocal3, SWIG_Field, and SWIG_Store_field.
Referenced by _wrap_Basics_greatest_poweropenMTPK(), _wrap_Basics_rm_gcdopenMTPK(), _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), _wrap_Cipher_KC_encodeopenMTPK(), _wrap_delete_BasicsopenMTPK(), _wrap_delete_CipheropenMTPK(), _wrap_delete_PrimalityopenMTPK(), _wrap_delete_RC4openMTPK(), _wrap_new_BasicsopenMTPK(), _wrap_new_CipheropenMTPK(), _wrap_new_PrimalityopenMTPK(), _wrap_new_RC4openMTPK(), _wrap_Primality_carmichael_numopenMTPK(), _wrap_Primality_compute_miller_rabinopenMTPK(), _wrap_Primality_ETFopenMTPK(), _wrap_Primality_is_primeopenMTPK(), _wrap_Primality_jacobian_numberopenMTPK(), _wrap_Primality_miller_rabin_primeopenMTPK(), _wrap_Primality_miller_rabinopenMTPK(), _wrap_Primality_mod_powopenMTPK(), _wrap_Primality_pollard_rhoopenMTPK(), _wrap_Primality_sieve_of_eratosthenesopenMTPK(), _wrap_Primality_solovoy_strassenopenMTPK(), _wrap_RC4_byte_swapopenMTPK(), _wrap_RC4_computeopenMTPK(), _wrap_RC4_KSAopenMTPK(), _wrap_RC4_PRGAopenMTPK(), _wrap_RC4_store_hashopenMTPK(), _wrap_RC4_trad_swapopenMTPK(), and _wrap_RC4_XOR_swapopenMTPK().
caml_list_length()
SWIGINTERN int caml_list_length (CAML_VALUE lst)
Definition at line 1147 of file openMTPK_wrap.cxx.
{
     CAMLparam1(lst);
     int i = 0;
     while( lst && Is_block(lst) ) { i++; lst = SWIG_Field(lst,1); }
     CAMLreturn(i);
     }
References CAMLreturn, and SWIG_Field.
Referenced by _wrap_Basics_greatest_poweropenMTPK(), _wrap_Basics_rm_gcdopenMTPK(), _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), _wrap_Cipher_KC_encodeopenMTPK(), _wrap_delete_BasicsopenMTPK(), _wrap_delete_CipheropenMTPK(), _wrap_delete_PrimalityopenMTPK(), _wrap_delete_RC4openMTPK(), _wrap_new_BasicsopenMTPK(), _wrap_new_CipheropenMTPK(), _wrap_new_PrimalityopenMTPK(), _wrap_new_RC4openMTPK(), _wrap_Primality_carmichael_numopenMTPK(), _wrap_Primality_compute_miller_rabinopenMTPK(), _wrap_Primality_ETFopenMTPK(), _wrap_Primality_is_primeopenMTPK(), _wrap_Primality_jacobian_numberopenMTPK(), _wrap_Primality_miller_rabin_primeopenMTPK(), _wrap_Primality_miller_rabinopenMTPK(), _wrap_Primality_mod_powopenMTPK(), _wrap_Primality_pollard_rhoopenMTPK(), _wrap_Primality_sieve_of_eratosthenesopenMTPK(), _wrap_Primality_solovoy_strassenopenMTPK(), _wrap_RC4_byte_swapopenMTPK(), _wrap_RC4_computeopenMTPK(), _wrap_RC4_KSAopenMTPK(), _wrap_RC4_PRGAopenMTPK(), _wrap_RC4_store_hashopenMTPK(), _wrap_RC4_trad_swapopenMTPK(), _wrap_RC4_XOR_swapopenMTPK(), and caml_array_len().
caml_list_nth()
SWIGINTERN CAML_VALUE caml_list_nth (CAML_VALUE lst, int n)
Definition at line 1103 of file openMTPK_wrap.cxx.
{
     CAMLparam1(lst);
     int i = 0;
     while( i < n && lst && Is_block(lst) ) {
         i++; lst = SWIG_Field(lst,1);
     }
     if( lst == Val_unit ) CAMLreturn(Val_unit);
     else CAMLreturn(SWIG_Field(lst,0));
     }
References CAMLreturn, and SWIG_Field.
Referenced by _wrap_Basics_greatest_poweropenMTPK(), _wrap_Basics_rm_gcdopenMTPK(), _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), _wrap_Cipher_KC_encodeopenMTPK(), _wrap_delete_BasicsopenMTPK(), _wrap_delete_CipheropenMTPK(), _wrap_delete_PrimalityopenMTPK(), _wrap_delete_RC4openMTPK(), _wrap_Primality_carmichael_numopenMTPK(), _wrap_Primality_compute_miller_rabinopenMTPK(), _wrap_Primality_ETFopenMTPK(), _wrap_Primality_is_primeopenMTPK(), _wrap_Primality_jacobian_numberopenMTPK(), _wrap_Primality_miller_rabin_primeopenMTPK(), _wrap_Primality_miller_rabinopenMTPK(), _wrap_Primality_mod_powopenMTPK(), _wrap_Primality_pollard_rhoopenMTPK(), _wrap_Primality_sieve_of_eratosthenesopenMTPK(), _wrap_Primality_solovoy_strassenopenMTPK(), _wrap_RC4_byte_swapopenMTPK(), _wrap_RC4_computeopenMTPK(), _wrap_RC4_KSAopenMTPK(), _wrap_RC4_PRGAopenMTPK(), _wrap_RC4_store_hashopenMTPK(), _wrap_RC4_trad_swapopenMTPK(), _wrap_RC4_XOR_swapopenMTPK(), and caml_array_nth().
caml_long_val()
SWIGINTERN long caml_long_val (CAML_VALUE v)
Definition at line 1352 of file openMTPK_wrap.cxx.
{
     return caml_long_val_full(v,0);
     }
References caml_long_val_full().
Referenced by _wrap_Basics_greatest_poweropenMTPK(), _wrap_Basics_rm_gcdopenMTPK(), _wrap_Cipher_C_cipheropenMTPK(), _wrap_Primality_carmichael_numopenMTPK(), _wrap_Primality_compute_miller_rabinopenMTPK(), _wrap_Primality_ETFopenMTPK(), _wrap_Primality_is_primeopenMTPK(), _wrap_Primality_jacobian_numberopenMTPK(), _wrap_Primality_miller_rabin_primeopenMTPK(), _wrap_Primality_miller_rabinopenMTPK(), _wrap_Primality_mod_powopenMTPK(), _wrap_Primality_pollard_rhoopenMTPK(), _wrap_Primality_sieve_of_eratosthenesopenMTPK(), _wrap_Primality_solovoy_strassenopenMTPK(), _wrap_RC4_computeopenMTPK(), _wrap_RC4_KSAopenMTPK(), _wrap_RC4_PRGAopenMTPK(), _wrap_RC4_store_hashopenMTPK(), caml_long_val_full(), and caml_print_val().
caml_long_val_full()
SWIGINTERN long caml_long_val_full (CAML_VALUE v, const char * name)
Definition at line 1316 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     if( !Is_block(v) ) return 0;
     switch( SWIG_Tag_val(v) ) {
     case C_bool:
     case C_char:
     case C_uchar:
     case C_short:
     case C_ushort:
     case C_int:
         CAMLreturn(Int_val(SWIG_Field(v,0)));
     case C_uint:
     case C_int32:
         CAMLreturn(Int32_val(SWIG_Field(v,0)));
     case C_int64:
         CAMLreturn((long)SWIG_Int64_val(SWIG_Field(v,0)));
     case C_float:
     case C_double:
         CAMLreturn((long)Double_val(SWIG_Field(v,0)));
     case C_string:
         CAMLreturn((long)String_val(SWIG_Field(v,0)));
     case C_ptr:
         CAMLreturn((long)SWIG_Int64_val(SWIG_Field(SWIG_Field(v,0),0)));
     case C_enum: {
         SWIG_CAMLlocal1(ret);
         const CAML_VALUE *enum_to_int = caml_named_value(SWIG_MODULE "_enum_to_int");
         if( !name ) caml_failwith( "Not an enum conversion" );
         ret = caml_callback2(*enum_to_int,*caml_named_value(name),v);
         CAMLreturn(caml_long_val(ret));
     }
     default:
         caml_failwith("No conversion to int");
     }
     }
References C_bool, C_char, C_double, C_enum, C_float, C_int, C_int32, C_int64, C_ptr, C_short, C_string, C_uchar, C_uint, C_ushort, caml_long_val(), CAML_VALUE, CAMLreturn, setup::name, SWIG_CAMLlocal1, SWIG_Field, SWIG_Int64_val, SWIG_MODULE, and SWIG_Tag_val.
Referenced by caml_long_val().
caml_print_list()
SWIGINTERN void caml_print_list (CAML_VALUE v)
Definition at line 1092 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     while( v && Is_block(v) ) {
         fprintf( stderr, "[ " );
         caml_print_val( SWIG_Field(v,0) );
         fprintf( stderr, "]\n" );
         v = SWIG_Field(v,1);
     }
     CAMLreturn0;
     }
References caml_print_val(), CAMLreturn0, and SWIG_Field.
Referenced by caml_print_val().
caml_print_val()
SWIGINTERN void caml_print_val (CAML_VALUE v)
Definition at line 1028 of file openMTPK_wrap.cxx.
{
     switch( SWIG_Tag_val(v) ) {
     case C_bool:
         if( Bool_val(SWIG_Field(v,0)) ) fprintf( stderr, "true " );
         else fprintf( stderr, "false " );
         break;
     case C_char:
     case C_uchar:
         fprintf( stderr, "'%c' (\\%03d) ",
              (Int_val(SWIG_Field(v,0)) >= ' ' &&
               Int_val(SWIG_Field(v,0)) < 127) ? Int_val(SWIG_Field(v,0)) : '.',
              Int_val(SWIG_Field(v,0)) );
         break;
     case C_short:
     case C_ushort:
     case C_int:
         fprintf( stderr, "%d ", (int)caml_long_val(v) );
         break;
     case C_uint:
     case C_int32:
         fprintf( stderr, "%ud ", (unsigned int)caml_long_val(v) );
         break;
     case C_int64:
         fprintf( stderr, "%ld ", caml_long_val(v) );
         break;
     case C_float:
     case C_double:
         fprintf( stderr, "%f ", caml_double_val(v) );
         break;
     case C_ptr:
     {
         void *vout = 0;
         swig_type_info *ty = (swig_type_info *)(long)SWIG_Int64_val(SWIG_Field(v,1));
         caml_ptr_val_internal(v,&vout,0);
         fprintf( stderr, "PTR(%p,%s) ",
              vout,
              ty ? ty->name : "(null)" );
     }
     break;
     case C_array:
     {
         unsigned int i;
         for( i = 0; i < Wosize_val( SWIG_Field(v,0) ); i++ )
         caml_print_val( SWIG_Field(SWIG_Field(v,0),i) );
     }
     break;
     case C_list:
         caml_print_list( SWIG_Field(v,0) );
         break;
     case C_obj:
         fprintf( stderr, "OBJ(%p) ", (void *)SWIG_Field(v,0) );
         break;
     case C_string:
     {
         void *cout;
         caml_ptr_val_internal(v,&cout,0);
         fprintf( stderr, "'%s' ", (char *)cout );
     }
     break;
     }
     }
References C_array, C_bool, C_char, C_double, C_float, C_int, C_int32, C_int64, C_list, C_obj, C_ptr, C_short, C_string, C_uchar, C_uint, C_ushort, caml_double_val(), caml_long_val(), caml_print_list(), caml_ptr_val_internal(), swig_type_info::name, SWIG_Field, SWIG_Int64_val, and SWIG_Tag_val.
Referenced by caml_print_list(), and caml_ptr_val().
caml_ptr_check()
SWIGINTERN int caml_ptr_check (CAML_VALUE v)
Definition at line 1490 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     if( !Is_block(v) ) return 0;
     switch( SWIG_Tag_val(v) ) {
     case C_string:
     case C_ptr:
     case C_int64:
         CAMLreturn(1);
     default:
         CAMLreturn(0);
     }
     }
References C_int64, C_ptr, C_string, CAMLreturn, and SWIG_Tag_val.
Referenced by _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), and _wrap_Cipher_KC_encodeopenMTPK().
caml_ptr_val()
SWIGINTERN void* caml_ptr_val (CAML_VALUE v, swig_type_info * descriptor)
Definition at line 1415 of file openMTPK_wrap.cxx.
{
         CAMLparam0();
 #ifdef TYPE_CAST_VERBOSE
     caml_print_val( v );
 #endif
     void *out = NULL;
     if( !caml_ptr_val_internal( v, &out, descriptor ) )
         CAMLreturn_type(out);
     else
         caml_failwith( "No appropriate conversion found." );
     }
References caml_print_val(), caml_ptr_val_internal(), and CAMLreturn_type.
Referenced by _wrap_Basics_greatest_poweropenMTPK(), _wrap_Basics_rm_gcdopenMTPK(), _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), _wrap_Cipher_KC_encodeopenMTPK(), _wrap_delete_BasicsopenMTPK(), _wrap_delete_CipheropenMTPK(), _wrap_delete_PrimalityopenMTPK(), _wrap_delete_RC4openMTPK(), _wrap_Primality_carmichael_numopenMTPK(), _wrap_Primality_compute_miller_rabinopenMTPK(), _wrap_Primality_ETFopenMTPK(), _wrap_Primality_is_primeopenMTPK(), _wrap_Primality_jacobian_numberopenMTPK(), _wrap_Primality_miller_rabin_primeopenMTPK(), _wrap_Primality_miller_rabinopenMTPK(), _wrap_Primality_mod_powopenMTPK(), _wrap_Primality_pollard_rhoopenMTPK(), _wrap_Primality_sieve_of_eratosthenesopenMTPK(), _wrap_Primality_solovoy_strassenopenMTPK(), _wrap_RC4_byte_swapopenMTPK(), _wrap_RC4_computeopenMTPK(), _wrap_RC4_KSAopenMTPK(), _wrap_RC4_PRGAopenMTPK(), _wrap_RC4_store_hashopenMTPK(), _wrap_RC4_trad_swapopenMTPK(), _wrap_RC4_XOR_swapopenMTPK(), caml_string_len(), caml_string_val(), and SwigString_AsString().
caml_ptr_val_internal()
SWIGINTERN int caml_ptr_val_internal (CAML_VALUE v, void ** out, swig_type_info * descriptor)
Definition at line 1381 of file openMTPK_wrap.cxx.
{
     CAMLparam1(v);
     void *outptr = NULL;
         swig_type_info *outdescr = NULL;
         static const CAML_VALUE *func_val = NULL;
     if( v == Val_unit ) {
         *out = 0;
         CAMLreturn_type(0);
     }
     if( !Is_block(v) ) return -1;
     switch( SWIG_Tag_val(v) ) {
     case C_obj:
         if (!func_val) {
             func_val = caml_named_value("caml_obj_ptr");
         }
         CAMLreturn_type(caml_ptr_val_internal(caml_callback(*func_val, v), out, descriptor));
     case C_string:
         outptr = (void *)String_val(SWIG_Field(v,0));
         break;
     case C_ptr:
         outptr = (void *)(long)SWIG_Int64_val(SWIG_Field(v,0));
             outdescr = (swig_type_info *)(long)SWIG_Int64_val(SWIG_Field(v,1));
         break;
     default:
         *out = 0;
         CAMLreturn_type(1);
         break;
     }
     CAMLreturn_type(SWIG_GetPtr(outptr, out, outdescr, descriptor));
     }
References C_obj, C_ptr, C_string, CAML_VALUE, CAMLreturn_type, SWIG_Field, SWIG_GetPtr(), SWIG_Int64_val, and SWIG_Tag_val.
Referenced by caml_print_val(), and caml_ptr_val().
caml_string_len()
SWIGINTERN int caml_string_len (CAML_VALUE v)
Definition at line 1431 of file openMTPK_wrap.cxx.
{
     switch( SWIG_Tag_val(v) ) {
     case C_string:
         return caml_string_length(SWIG_Field(v,0));
     default:
         return strlen((char *)caml_ptr_val(v,0));
     }
     }
References C_string, caml_ptr_val(), SWIG_Field, and SWIG_Tag_val.
Referenced by _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), and _wrap_Cipher_KC_encodeopenMTPK().
caml_string_val()
SWIGINTERN char* caml_string_val (CAML_VALUE v)
Definition at line 1427 of file openMTPK_wrap.cxx.
{
     return (char *)caml_ptr_val( v, 0 );
     }
References caml_ptr_val().
Referenced by _wrap_RC4_computeopenMTPK(), _wrap_RC4_KSAopenMTPK(), _wrap_RC4_PRGAopenMTPK(), _wrap_RC4_store_hashopenMTPK(), _wrap_RC4_trad_swapopenMTPK(), and _wrap_RC4_XOR_swapopenMTPK().
caml_swig_alloc()
SWIGINTERN CAML_VALUE caml_swig_alloc (int x, int y)
Definition at line 1180 of file openMTPK_wrap.cxx.
{
     return caml_alloc(x,y);
     }
Referenced by caml_array_new(), caml_val_bool(), caml_val_char(), caml_val_double(), caml_val_float(), caml_val_int(), caml_val_long(), caml_val_ptr(), caml_val_short(), caml_val_string(), caml_val_string_len(), caml_val_uchar(), caml_val_uint(), caml_val_ulong(), and caml_val_ushort().
caml_val_bool()
SWIGINTERN CAML_VALUE caml_val_bool (int b)
Definition at line 1192 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(bv);
     bv = caml_swig_alloc(1,C_bool);
     SWIG_Store_field(bv,0,Val_bool(b));
     CAMLreturn(bv);
     }
References Python.examples.arithmetic::b, C_bool, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
Referenced by _wrap_Primality_carmichael_numopenMTPK(), _wrap_Primality_compute_miller_rabinopenMTPK(), _wrap_Primality_is_primeopenMTPK(), _wrap_Primality_miller_rabin_primeopenMTPK(), and _wrap_Primality_solovoy_strassenopenMTPK().
caml_val_char()
SWIGINTERN CAML_VALUE caml_val_char (char c)
Definition at line 1200 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(cv);
     cv = caml_swig_alloc(1,C_char);
     SWIG_Store_field(cv,0,Val_int(c));
     CAMLreturn(cv);
     }
References Python.examples.cipher_ex::c, C_char, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_double()
SWIGINTERN CAML_VALUE caml_val_double (double d)
Definition at line 1272 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(fv);
     fv = caml_swig_alloc(1,C_double);
     SWIG_Store_field(fv,0,caml_copy_double(d));
     CAMLreturn(fv);
     }
References C_double, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_float()
SWIGINTERN CAML_VALUE caml_val_float (float f)
Definition at line 1264 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(fv);
     fv = caml_swig_alloc(1,C_float);
     SWIG_Store_field(fv,0,caml_copy_double((double)f));
     CAMLreturn(fv);
     }
References C_float, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_int()
SWIGINTERN CAML_VALUE caml_val_int (int x)
Definition at line 1232 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(iv);
     iv = caml_swig_alloc(1,C_int);
     SWIG_Store_field(iv,0,Val_int(i));
     CAMLreturn(iv);
     }
References C_int, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
Referenced by _wrap_Basics_greatest_poweropenMTPK(), _wrap_Basics_rm_gcdopenMTPK(), _wrap_BITS(), _wrap_BYTE_LIMIT(), _wrap_Primality_ETFopenMTPK(), _wrap_Primality_jacobian_numberopenMTPK(), and SWIG_Ocaml_GetModule().
caml_val_long()
SWIGINTERN CAML_VALUE caml_val_long (long x)
Definition at line 1248 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(lv);
     lv = caml_swig_alloc(1,C_int64);
     SWIG_Store_field(lv,0,caml_copy_int64(l));
     CAMLreturn(lv);
     }
References C_int64, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_obj_helper()
SWIGINTERN CAML_VALUE caml_val_obj_helper (void * v, swig_type_info * type, char * name)
Definition at line 1309 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     CAMLreturn(caml_callback2(*caml_named_value("caml_create_object_fn"),
                  caml_val_ptr(v,type),
                  caml_copy_string(name)));
     }
References caml_val_ptr(), CAMLreturn, and setup::name.
caml_val_ptr()
SWIGINTERN CAML_VALUE caml_val_ptr (void * p, swig_type_info * descriptor)
Definition at line 1280 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(vv);
     vv = caml_swig_alloc(2,C_ptr);
     SWIG_Store_field(vv,0,caml_copy_int64((long)p));
     SWIG_Store_field(vv,1,caml_copy_int64((long)info));
     CAMLreturn(vv);
     }
References C_ptr, caml_swig_alloc(), CAMLreturn, Python.examples.primes_ex::p, SWIG_CAMLlocal1, and SWIG_Store_field.
Referenced by caml_val_obj_helper(), caml_val_string(), caml_val_string_len(), SWIG_Ocaml_ptr_to_val(), and SWIG_Ocaml_SetModule().
caml_val_short()
SWIGINTERN CAML_VALUE caml_val_short (short s)
Definition at line 1216 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(sv);
     sv = caml_swig_alloc(1,C_short);
     SWIG_Store_field(sv,0,Val_int(s));
     CAMLreturn(sv);
     }
References C_short, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_string()
SWIGINTERN CAML_VALUE caml_val_string (const char * str)
Definition at line 1289 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(vv);
     if( !p ) CAMLreturn(caml_val_ptr( (void *)p, 0 ));
     vv = caml_swig_alloc(1,C_string);
     SWIG_Store_field(vv,0,caml_copy_string(p));
     CAMLreturn(vv);
     }
References C_string, caml_swig_alloc(), caml_val_ptr(), CAMLreturn, Python.examples.primes_ex::p, SWIG_CAMLlocal1, and SWIG_Store_field.
Referenced by _wrap_RC4_computeopenMTPK(), and SwigString_FromString().
caml_val_string_len()
SWIGINTERN CAML_VALUE caml_val_string_len (const char * str, int len)
Definition at line 1298 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(vv);
     if( !p || len < 0 ) CAMLreturn(caml_val_ptr( (void *)p, 0 ));
     vv = caml_swig_alloc(1,C_string);
     SWIG_Store_field(vv,0,caml_alloc_string(len));
     memcpy(Bp_val(SWIG_Field(vv,0)),p,len);
     CAMLreturn(vv);
     }
References C_string, caml_swig_alloc(), caml_val_ptr(), CAMLreturn, Python.examples.primes_ex::p, SWIG_CAMLlocal1, SWIG_Field, and SWIG_Store_field.
Referenced by _wrap_Cipher_C_cipheropenMTPK(), _wrap_Cipher_KC_cipheropenMTPK(), _wrap_Cipher_KC_encodeopenMTPK(), and _wrap_RC4_store_hashopenMTPK().
caml_val_uchar()
SWIGINTERN CAML_VALUE caml_val_uchar (unsigned char c)
Definition at line 1208 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(ucv);
     ucv = caml_swig_alloc(1,C_uchar);
     SWIG_Store_field(ucv,0,Val_int(uc));
     CAMLreturn(ucv);
     }
References C_uchar, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_uint()
SWIGINTERN CAML_VALUE caml_val_uint (unsigned int x)
Definition at line 1240 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(uiv);
     uiv = caml_swig_alloc(1,C_int);
     SWIG_Store_field(uiv,0,Val_int(ui));
     CAMLreturn(uiv);
     }
References C_int, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
caml_val_ulong()
SWIGINTERN CAML_VALUE caml_val_ulong (unsigned long x)
Definition at line 1256 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(ulv);
     ulv = caml_swig_alloc(1,C_int64);
     SWIG_Store_field(ulv,0,caml_copy_int64(ul));
     CAMLreturn(ulv);
     }
References C_int64, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
Referenced by _wrap_Primality_mod_powopenMTPK(), and _wrap_Primality_pollard_rhoopenMTPK().
caml_val_ushort()
SWIGINTERN CAML_VALUE caml_val_ushort (unsigned short s)
Definition at line 1224 of file openMTPK_wrap.cxx.
{
     CAMLparam0();
     SWIG_CAMLlocal1(usv);
     usv = caml_swig_alloc(1,C_ushort);
     SWIG_Store_field(usv,0,Val_int(us));
     CAMLreturn(usv);
     }
References C_ushort, caml_swig_alloc(), CAMLreturn, SWIG_CAMLlocal1, and SWIG_Store_field.
SWIG_Cast()
SWIGINTERN int SWIG_Cast (void * source, swig_type_info * source_type, void ** ptr, swig_type_info * dest_type)
Definition at line 967 of file openMTPK_wrap.cxx.
     {
     if( !source ) { /* Special case for NULL.  This is a popular question
          for other modules on the list, so I want an easy way out... */
         *ptr = 0;
         return 0;
     }
 #ifdef TYPE_CAST_VERBOSE
     fprintf( stderr, "Trying to cast %s to %s\n",
          source_type ? source_type->str : "<none>",
          dest_type ? dest_type->str : "<none>" );
 #endif
     if (dest_type != source_type) {
         /* We have a type mismatch.  Will have to look through our type
            mapping table to figure out whether or not we can accept this
            datatype.
            --
            Ignore typechecks for void *.  Allow any conversion. */
         if( !dest_type || !source_type ||
         !strcmp(dest_type->name,"_p_void") ||
         !strcmp(source_type->name,"_p_void") ) {
         *ptr = source;
         return 0;
         } else {
         swig_cast_info *tc =
             SWIG_TypeCheckStruct(source_type, dest_type );
 #ifdef TYPE_CAST_VERBOSE
         fprintf( stderr, "Typecheck -> %s\n",
              tc ? tc->type->str : "<none>" );
 #endif
         if( tc ) {
             int newmemory = 0;
             *ptr = SWIG_TypeCast(tc, source, &newmemory);
             assert(!newmemory); /* newmemory handling not yet implemented */
             return 0;
         } else
             return -1;
         }
     } else {
         *ptr = source;
         return 0;
     }
     }
References swig_type_info::name, swig_type_info::str, SWIG_TypeCast(), SWIG_TypeCheckStruct(), and swig_cast_info::type.
Referenced by SWIG_GetPtr().
SWIG_GetPtr()
SWIGINTERN int SWIG_GetPtr (void * source, void ** result, swig_type_info * type, swig_type_info * result_type)
Definition at line 1015 of file openMTPK_wrap.cxx.
{
     if (intype) {
         return SWIG_Cast(inptr, intype,
                  outptr, outtype) == -1;
     } else {
         *outptr = inptr;
         return 0;
     }
     }
References SWIG_Cast().
Referenced by caml_ptr_val_internal().
SWIG_InitializeModule()
SWIGRUNTIME void SWIG_InitializeModule (SWIG_INIT_CLIENT_DATA_TYPE clientdata)
Definition at line 2688 of file openMTPK_wrap.cxx.
{
   size_t i;
   swig_module_info *module_head, *iter;
   int init;
   /* check to see if the circular list has been setup, if not, set it up */
   if (swig_module.next==0) {
     /* Initialize the swig_module */
     swig_module.type_initial = swig_type_initial;
     swig_module.cast_initial = swig_cast_initial;
     swig_module.next = &swig_module;
     init = 1;
   } else {
     init = 0;
   }
   /* Try and load any already created modules */
   module_head = SWIG_GetModule(clientdata);
   if (!module_head) {
     /* This is the first module loaded for this interpreter */
     /* so set the swig module into the interpreter */
     SWIG_SetModule(clientdata, &swig_module);
   } else {
     /* the interpreter has loaded a SWIG module, but has it loaded this one? */
     iter=module_head;
     do {
       if (iter==&swig_module) {
         /* Our module is already in the list, so there's nothing more to do. */
         return;
       }
       iter=iter->next;
     } while (iter!= module_head);
     /* otherwise we must add our module into the list */
     swig_module.next = module_head->next;
     module_head->next = &swig_module;
   }
   /* When multiple interpreters are used, a module could have already been initialized in
        a different interpreter, but not yet have a pointer in this interpreter.
        In this case, we do not want to continue adding types... everything should be
        set up already */
   if (init == 0) return;
   /* Now work on filling in swig_module.types */
 #ifdef SWIGRUNTIME_DEBUG
   printf("SWIG_InitializeModule: size %lu\n", (unsigned long)swig_module.size);
 #endif
   for (i = 0; i < swig_module.size; ++i) {
     swig_type_info *type = 0;
     swig_type_info *ret;
     swig_cast_info *cast;
 #ifdef SWIGRUNTIME_DEBUG
     printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
 #endif
     /* if there is another module already loaded */
     if (swig_module.next != &swig_module) {
       type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
     }
     if (type) {
       /* Overwrite clientdata field */
 #ifdef SWIGRUNTIME_DEBUG
       printf("SWIG_InitializeModule: found type %s\n", type->name);
 #endif
       if (swig_module.type_initial[i]->clientdata) {
         type->clientdata = swig_module.type_initial[i]->clientdata;
 #ifdef SWIGRUNTIME_DEBUG
         printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
 #endif
       }
     } else {
       type = swig_module.type_initial[i];
     }
     /* Insert casting types */
     cast = swig_module.cast_initial[i];
     while (cast->type) {
       /* Don't need to add information already in the list */
       ret = 0;
 #ifdef SWIGRUNTIME_DEBUG
       printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
 #endif
       if (swig_module.next != &swig_module) {
         ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
 #ifdef SWIGRUNTIME_DEBUG
         if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
 #endif
       }
       if (ret) {
         if (type == swig_module.type_initial[i]) {
 #ifdef SWIGRUNTIME_DEBUG
           printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
 #endif
           cast->type = ret;
           ret = 0;
         } else {
           /* Check for casting already in the list */
           swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
 #ifdef SWIGRUNTIME_DEBUG
           if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
 #endif
           if (!ocast) ret = 0;
         }
       }
       if (!ret) {
 #ifdef SWIGRUNTIME_DEBUG
         printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
 #endif
         if (type->cast) {
           type->cast->prev = cast;
           cast->next = type->cast;
         }
         type->cast = cast;
       }
       cast++;
     }
     /* Set entry in modules->types array equal to the type */
     swig_module.types[i] = type;
   }
   swig_module.types[i] = 0;
 #ifdef SWIGRUNTIME_DEBUG
   printf("**** SWIG_InitializeModule: Cast List ******\n");
   for (i = 0; i < swig_module.size; ++i) {
     int j = 0;
     swig_cast_info *cast = swig_module.cast_initial[i];
     printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
     while (cast->type) {
       printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
       cast++;
       ++j;
     }
     printf("---- Total casts: %d\n",j);
   }
   printf("**** SWIG_InitializeModule: Cast List ******\n");
 #endif
 }
References swig_type_info::cast, swig_module_info::cast_initial, swig_type_info::clientdata, init(), swig_type_info::name, swig_cast_info::next, swig_module_info::next, swig_cast_info::prev, swig_module_info::size, swig_cast_initial, SWIG_GetModule, SWIG_MangledTypeQueryModule(), swig_module, SWIG_SetModule, swig_type_initial, SWIG_TypeCheck(), swig_cast_info::type, swig_module_info::type_initial, and swig_module_info::types.
SWIG_MangledTypeQueryModule()
SWIGRUNTIME swig_type_info* SWIG_MangledTypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
Definition at line 547 of file openMTPK_wrap.cxx.
{
   swig_module_info *iter = start;
   do {
     if (iter->size) {
       size_t l = 0;
       size_t r = iter->size - 1;
       do {
     /* since l+r >= 0, we can (>> 1) instead (/ 2) */
     size_t i = (l + r) >> 1;
     const char *iname = iter->types[i]->name;
     if (iname) {
       int compare = strcmp(name, iname);
       if (compare == 0) {
         return iter->types[i];
       } else if (compare < 0) {
         if (i) {
           r = i - 1;
         } else {
           break;
         }
       } else if (compare > 0) {
         l = i + 1;
       }
     } else {
       break; /* should never happen */
     }
       } while (l <= r);
     }
     iter = iter->next;
   } while (iter != end);
   return 0;
 }
References swig_type_info::name, setup::name, swig_module_info::next, Python.examples.rc4_ex::r, swig_module_info::size, and swig_module_info::types.
Referenced by SWIG_InitializeModule(), and SWIG_TypeQueryModule().
SWIG_Ocaml_GetModule()
static swig_module_info* SWIG_Ocaml_GetModule (void * SWIGUNUSEDPARMclientdata) static
Definition at line 1518 of file openMTPK_wrap.cxx.
{
       CAML_VALUE pointer;
       pointer = caml_callback(*caml_named_value("swig_find_type_info"), caml_val_int(0));
       if (Is_block(pointer) && SWIG_Tag_val(pointer) == C_ptr) {
         return (swig_module_info *)(void *)(long)SWIG_Int64_val(SWIG_Field(pointer,0));
       }
       return 0;
     }
References C_ptr, caml_val_int(), CAML_VALUE, SWIG_Field, SWIG_Int64_val, and SWIG_Tag_val.
SWIG_Ocaml_ptr_to_val()
SWIGINTERN CAML_VALUE SWIG_Ocaml_ptr_to_val (const char * name, void * ptr, swig_type_info * descriptor)
Definition at line 1505 of file openMTPK_wrap.cxx.
{
         CAMLparam0();
         SWIG_CAMLlocal1(result);
         const CAML_VALUE *fromval = caml_named_value(name);
         if (fromval) {
             result = caml_callback(*fromval, caml_val_ptr(ptr, descriptor));
         } else {
             result = caml_val_ptr(ptr, descriptor);
         }
         CAMLreturn(result);
     }
References caml_val_ptr(), CAML_VALUE, CAMLreturn, setup::name, and SWIG_CAMLlocal1.
Referenced by _wrap_new_BasicsopenMTPK(), _wrap_new_CipheropenMTPK(), _wrap_new_PrimalityopenMTPK(), and _wrap_new_RC4openMTPK().
SWIG_Ocaml_SetModule()
static void SWIG_Ocaml_SetModule (swig_module_info * pointer) static
Definition at line 1528 of file openMTPK_wrap.cxx.
{
       CAML_VALUE mod_pointer;
       mod_pointer = caml_val_ptr(pointer, NULL);
       caml_callback(*caml_named_value("swig_set_type_info"), mod_pointer);
     }
References caml_val_ptr(), and CAML_VALUE.
SWIG_OCamlException()
SWIGINTERN void SWIG_OCamlException (int code, const char * msg)
Definition at line 1622 of file openMTPK_wrap.cxx.
{
   CAMLparam0();
   SWIG_OCamlExceptionCodes exception_code = SWIG_OCamlUnknownError;
   switch (code) {
   case SWIG_DivisionByZero:
     exception_code = SWIG_OCamlArithmeticException;
     break;
   case SWIG_IndexError:
     exception_code = SWIG_OCamlIndexOutOfBoundsException;
     break;
   case SWIG_IOError:
   case SWIG_SystemError:
     exception_code = SWIG_OCamlSystemException;
     break;
   case SWIG_MemoryError:
     exception_code = SWIG_OCamlOutOfMemoryError;
     break;
   case SWIG_OverflowError:
     exception_code = SWIG_OCamlOverflowException;
     break;
   case SWIG_RuntimeError:
     exception_code = SWIG_OCamlRuntimeException;
     break;
   case SWIG_SyntaxError:
   case SWIG_TypeError:
   case SWIG_ValueError:
     exception_code = SWIG_OCamlIllegalArgumentException;
     break;
   case SWIG_UnknownError:
   default:
     exception_code = SWIG_OCamlUnknownError;
     break;
   }
   SWIG_OCamlThrowException(exception_code, msg);
   CAMLreturn0;
 }
References CAMLreturn0, SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_MemoryError, SWIG_OCamlArithmeticException, SWIG_OCamlIllegalArgumentException, SWIG_OCamlIndexOutOfBoundsException, SWIG_OCamlOutOfMemoryError, SWIG_OCamlOverflowException, SWIG_OCamlRuntimeException, SWIG_OCamlSystemException, SWIG_OCamlThrowException(), SWIG_OCamlUnknownError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, SWIG_UnknownError, and SWIG_ValueError.
SWIG_OCamlThrowException()
SWIGINTERN void SWIG_OCamlThrowException (SWIG_OCamlExceptionCodes code, const char * msg)
Definition at line 861 of file openMTPK_wrap.cxx.
{
   CAMLparam0();
   SWIG_CAMLlocal1(str);
   switch (code) {
   case SWIG_OCamlIllegalArgumentException:
     caml_invalid_argument(msg);
     break;
   case SWIG_OCamlSystemException:
     str = caml_copy_string(msg);
     caml_raise_sys_error(str);
     break;
   case SWIG_OCamlArithmeticException:
   case SWIG_OCamlIndexOutOfBoundsException:
   case SWIG_OCamlOutOfMemoryError:
   case SWIG_OCamlOverflowException:
   case SWIG_OCamlRuntimeException:
   case SWIG_OCamlUnknownError:
   default:
     caml_failwith(msg);
     break;
   }
   CAMLreturn0;
 }
References CAMLreturn0, SWIG_CAMLlocal1, SWIG_OCamlArithmeticException, SWIG_OCamlIllegalArgumentException, SWIG_OCamlIndexOutOfBoundsException, SWIG_OCamlOutOfMemoryError, SWIG_OCamlOverflowException, SWIG_OCamlRuntimeException, SWIG_OCamlSystemException, and SWIG_OCamlUnknownError.
Referenced by SWIG_OCamlException().
SWIG_PackData()
SWIGRUNTIME char* SWIG_PackData (char * c, void * ptr, size_t sz)
Definition at line 621 of file openMTPK_wrap.cxx.
{
   static const char hex[17] = "0123456789abcdef";
   const unsigned char *u = (unsigned char *) ptr;
   const unsigned char *eu =  u + sz;
   for (; u != eu; ++u) {
     unsigned char uu = *u;
     *(c++) = hex[(uu & 0xf0) >> 4];
     *(c++) = hex[uu & 0xf];
   }
   return c;
 }
References Python.examples.cipher_ex::c, and u.
Referenced by SWIG_PackDataName(), and SWIG_PackVoidPtr().
SWIG_PackDataName()
SWIGRUNTIME char* SWIG_PackDataName (char * buff, void * ptr, size_t sz, const char * name, size_t bsz)
Definition at line 689 of file openMTPK_wrap.cxx.
{
   char *r = buff;
   size_t lname = (name ? strlen(name) : 0);
   if ((2*sz + 2 + lname) > bsz) return 0;
   *(r++) = '_';
   r = SWIG_PackData(r,ptr,sz);
   if (lname) {
     strncpy(r,name,lname+1);
   } else {
     *r = 0;
   }
   return buff;
 }
References setup::name, Python.examples.rc4_ex::r, and SWIG_PackData().
SWIG_PackVoidPtr()
SWIGRUNTIME char* SWIG_PackVoidPtr (char * buff, void * ptr, const char * name, size_t bsz)
Definition at line 665 of file openMTPK_wrap.cxx.
{
   char *r = buff;
   if ((2*sizeof(void *) + 2) > bsz) return 0;
   *(r++) = '_';
   r = SWIG_PackData(r,&ptr,sizeof(void *));
   if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
   strcpy(r,name);
   return buff;
 }
References setup::name, Python.examples.rc4_ex::r, and SWIG_PackData().
SWIG_PropagateClientData()
SWIGRUNTIME void SWIG_PropagateClientData (void)
Definition at line 2835 of file openMTPK_wrap.cxx.
{
   size_t i;
   swig_cast_info *equiv;
   static int init_run = 0;
   if (init_run) return;
   init_run = 1;
   for (i = 0; i < swig_module.size; i++) {
     if (swig_module.types[i]->clientdata) {
       equiv = swig_module.types[i]->cast;
       while (equiv) {
         if (!equiv->converter) {
           if (equiv->type && !equiv->type->clientdata)
           SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
         }
         equiv = equiv->next;
       }
     }
   }
 }
References swig_type_info::cast, swig_type_info::clientdata, swig_cast_info::converter, swig_cast_info::next, swig_module_info::size, swig_module, SWIG_TypeClientData(), swig_cast_info::type, and swig_module_info::types.
SWIG_TypeCast()
SWIGRUNTIMEINLINE void* SWIG_TypeCast (swig_cast_info * ty, void * ptr, int * newmemory)
Definition at line 465 of file openMTPK_wrap.cxx.
{
   return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
 }
References swig_cast_info::converter.
Referenced by SWIG_Cast().
SWIG_TypeCheck()
SWIGRUNTIME swig_cast_info* SWIG_TypeCheck (const char * c, swig_type_info * ty)
Definition at line 411 of file openMTPK_wrap.cxx.
{
   if (ty) {
     swig_cast_info *iter = ty->cast;
     while (iter) {
       if (strcmp(iter->type->name, c) == 0) {
         if (iter == ty->cast)
           return iter;
         /* Move iter to the top of the linked list */
         iter->prev->next = iter->next;
         if (iter->next)
           iter->next->prev = iter->prev;
         iter->next = ty->cast;
         iter->prev = 0;
         if (ty->cast) ty->cast->prev = iter;
         ty->cast = iter;
         return iter;
       }
       iter = iter->next;
     }
   }
   return 0;
 }
References Python.examples.cipher_ex::c, swig_type_info::cast, swig_type_info::name, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
Referenced by SWIG_InitializeModule().
SWIG_TypeCheckStruct()
SWIGRUNTIME swig_cast_info* SWIG_TypeCheckStruct (const swig_type_info * from, swig_type_info * ty)
Definition at line 438 of file openMTPK_wrap.cxx.
{
   if (ty) {
     swig_cast_info *iter = ty->cast;
     while (iter) {
       if (iter->type == from) {
         if (iter == ty->cast)
           return iter;
         /* Move iter to the top of the linked list */
         iter->prev->next = iter->next;
         if (iter->next)
           iter->next->prev = iter->prev;
         iter->next = ty->cast;
         iter->prev = 0;
         if (ty->cast) ty->cast->prev = iter;
         ty->cast = iter;
         return iter;
       }
       iter = iter->next;
     }
   }
   return 0;
 }
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
Referenced by SWIG_Cast().
SWIG_TypeClientData()
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info * ti, void * clientdata)
Definition at line 517 of file openMTPK_wrap.cxx.
{
   swig_cast_info *cast = ti->cast;
   /* if (ti->clientdata == clientdata) return; */
   ti->clientdata = clientdata;
   while (cast) {
     if (!cast->converter) {
       swig_type_info *tc = cast->type;
       if (!tc->clientdata) {
     SWIG_TypeClientData(tc, clientdata);
       }
     }
     cast = cast->next;
   }
 }
References swig_type_info::cast, swig_type_info::clientdata, swig_module_info::clientdata, swig_cast_info::converter, swig_cast_info::next, and swig_cast_info::type.
Referenced by SWIG_PropagateClientData(), and SWIG_TypeNewClientData().
SWIG_TypeCmp()
SWIGRUNTIME int SWIG_TypeCmp (const char * nb, const char * tb)
Definition at line 384 of file openMTPK_wrap.cxx.
{
   int equiv = 1;
   const char* te = tb + strlen(tb);
   const char* ne = nb;
   while (equiv != 0 && *ne) {
     for (nb = ne; *ne; ++ne) {
       if (*ne == '|') break;
     }
     equiv = SWIG_TypeNameComp(nb, ne, tb, te);
     if (*ne) ++ne;
   }
   return equiv;
 }
References SWIG_TypeNameComp().
Referenced by SWIG_TypeEquiv().
SWIG_TypeDynamicCast()
SWIGRUNTIME swig_type_info* SWIG_TypeDynamicCast (swig_type_info * ty, void ** ptr)
Definition at line 473 of file openMTPK_wrap.cxx.
{
   swig_type_info *lastty = ty;
   if (!ty || !ty->dcast) return ty;
   while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
   }
   return lastty;
 }
References swig_type_info::dcast.
SWIG_TypeEquiv()
SWIGRUNTIME int SWIG_TypeEquiv (const char * nb, const char * tb)
Definition at line 403 of file openMTPK_wrap.cxx.
{
   return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
 }
References SWIG_TypeCmp().
Referenced by SWIG_TypeQueryModule().
SWIG_TypeName()
SWIGRUNTIMEINLINE const char* SWIG_TypeName (const swig_type_info * ty)
Definition at line 487 of file openMTPK_wrap.cxx.
{
   return ty->name;
 }
References swig_type_info::name.
SWIG_TypeNameComp()
SWIGRUNTIME int SWIG_TypeNameComp (const char * f1, const char * l1, const char * f2, const char * l2)
Definition at line 369 of file openMTPK_wrap.cxx.
{
   for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
     while ((*f1 == ' ') && (f1 != l1)) ++f1;
     while ((*f2 == ' ') && (f2 != l2)) ++f2;
     if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
   }
   return (int)((l1 - f1) - (l2 - f2));
 }
Referenced by SWIG_TypeCmp().
SWIG_TypeNewClientData()
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info * ti, void * clientdata)
Definition at line 533 of file openMTPK_wrap.cxx.
{
   SWIG_TypeClientData(ti, clientdata);
   ti->owndata = 1;
 }
References swig_module_info::clientdata, swig_type_info::owndata, and SWIG_TypeClientData().
SWIG_TypePrettyName()
SWIGRUNTIME const char* SWIG_TypePrettyName (const swig_type_info * type)
Definition at line 496 of file openMTPK_wrap.cxx.
{
   /* The "str" field contains the equivalent pretty names of the
      type, separated by vertical-bar characters.  Choose the last
      name. It should be the most specific; a fully resolved name
      but not necessarily with default template parameters expanded. */
   if (!type) return NULL;
   if (type->str != NULL) {
     const char *last_name = type->str;
     const char *s;
     for (s = type->str; *s; s++)
       if (*s == '|') last_name = s+1;
     return last_name;
   }
   else
     return type->name;
 }
References swig_type_info::name, and swig_type_info::str.
SWIG_TypeQueryModule()
SWIGRUNTIME swig_type_info* SWIG_TypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
Definition at line 592 of file openMTPK_wrap.cxx.
{
   /* STEP 1: Search the name field using binary search */
   swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
   if (ret) {
     return ret;
   } else {
     /* STEP 2: If the type hasn't been found, do a complete search
        of the str field (the human readable name) */
     swig_module_info *iter = start;
     do {
       size_t i = 0;
       for (; i < iter->size; ++i) {
     if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
       return iter->types[i];
       }
       iter = iter->next;
     } while (iter != end);
   }
   /* neither found a match */
   return 0;
 }
References setup::name, swig_module_info::next, swig_module_info::size, swig_type_info::str, SWIG_MangledTypeQueryModule(), SWIG_TypeEquiv(), and swig_module_info::types.
SWIG_UnpackData()
SWIGRUNTIME const char* SWIG_UnpackData (const char * c, void * ptr, size_t sz)
Definition at line 637 of file openMTPK_wrap.cxx.
{
   unsigned char *u = (unsigned char *) ptr;
   const unsigned char *eu = u + sz;
   for (; u != eu; ++u) {
     char d = *(c++);
     unsigned char uu;
     if ((d >= '0') && (d <= '9'))
       uu = (unsigned char)((d - '0') << 4);
     else if ((d >= 'a') && (d <= 'f'))
       uu = (unsigned char)((d - ('a'-10)) << 4);
     else
       return (char *) 0;
     d = *(c++);
     if ((d >= '0') && (d <= '9'))
       uu |= (unsigned char)(d - '0');
     else if ((d >= 'a') && (d <= 'f'))
       uu |= (unsigned char)(d - ('a'-10));
     else
       return (char *) 0;
     *u = uu;
   }
   return c;
 }
References Python.examples.cipher_ex::c, and u.
Referenced by SWIG_UnpackDataName(), and SWIG_UnpackVoidPtr().
SWIG_UnpackDataName()
SWIGRUNTIME const char* SWIG_UnpackDataName (const char * c, void * ptr, size_t sz, const char * name)
Definition at line 704 of file openMTPK_wrap.cxx.
{
   if (*c != '_') {
     if (strcmp(c,"NULL") == 0) {
       memset(ptr,0,sz);
       return name;
     } else {
       return 0;
     }
   }
   return SWIG_UnpackData(++c,ptr,sz);
 }
References Python.examples.cipher_ex::c, setup::name, and SWIG_UnpackData().
SWIG_UnpackVoidPtr()
SWIGRUNTIME const char* SWIG_UnpackVoidPtr (const char * c, void ** ptr, const char * name)
Definition at line 676 of file openMTPK_wrap.cxx.
{
   if (*c != '_') {
     if (strcmp(c,"NULL") == 0) {
       *ptr = (void *) 0;
       return name;
     } else {
       return 0;
     }
   }
   return SWIG_UnpackData(++c,ptr,sizeof(void *));
 }
References Python.examples.cipher_ex::c, setup::name, and SWIG_UnpackData().
SwigString_AsString()
SWIGINTERNINLINE std::string SwigString_AsString (CAML_VALUE o)
Definition at line 1681 of file openMTPK_wrap.cxx.
{
   return std::string((char *)caml_ptr_val(o,0));
 }
References caml_ptr_val().
SwigString_FromString()
SWIGINTERNINLINE CAML_VALUE SwigString_FromString (const std::string & s)
Definition at line 1676 of file openMTPK_wrap.cxx.
{
   return caml_val_string((char *)s.c_str());
 }
References caml_val_string().
Variable Documentation
_swig_wrap_BITS
int _swig_wrap_BITS = 255 static
Definition at line 1704 of file openMTPK_wrap.cxx.
Referenced by _wrap_BITS().
_swig_wrap_BYTE_LIMIT
int _swig_wrap_BYTE_LIMIT = 256 static
Definition at line 1705 of file openMTPK_wrap.cxx.
Referenced by _wrap_BYTE_LIMIT().
_swigc__p_Basics
swig_cast_info _swigc__p_Basics[] = { {&_swigt__p_Basics, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2611 of file openMTPK_wrap.cxx.
_swigc__p_Cipher
swig_cast_info _swigc__p_Cipher[] = { {&_swigt__p_Cipher, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2612 of file openMTPK_wrap.cxx.
_swigc__p_Primality
swig_cast_info _swigc__p_Primality[] = { {&_swigt__p_Primality, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2613 of file openMTPK_wrap.cxx.
_swigc__p_RC4
swig_cast_info _swigc__p_RC4[] = { {&_swigt__p_RC4, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2614 of file openMTPK_wrap.cxx.
_swigc__p_uint8_t
swig_cast_info _swigc__p_uint8_t[] = { {&_swigt__p_uint8_t, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2615 of file openMTPK_wrap.cxx.
_swigc__p_unsigned_char
swig_cast_info _swigc__p_unsigned_char[] = { {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2616 of file openMTPK_wrap.cxx.
_swigt__p_Basics
swig_type_info _swigt__p_Basics = {"_p_Basics", "Basics *", 0, 0, (void*)0, 0} static
Definition at line 2595 of file openMTPK_wrap.cxx.
_swigt__p_Cipher
swig_type_info _swigt__p_Cipher = {"_p_Cipher", "Cipher *", 0, 0, (void*)0, 0} static
Definition at line 2596 of file openMTPK_wrap.cxx.
_swigt__p_Primality
swig_type_info _swigt__p_Primality = {"_p_Primality", "Primality *", 0, 0, (void*)0, 0} static
Definition at line 2597 of file openMTPK_wrap.cxx.
_swigt__p_RC4
swig_type_info _swigt__p_RC4 = {"_p_RC4", "RC4 *", 0, 0, (void*)0, 0} static
Definition at line 2598 of file openMTPK_wrap.cxx.
_swigt__p_uint8_t
swig_type_info _swigt__p_uint8_t = {"_p_uint8_t", "uint8_t *", 0, 0, (void*)0, 0} static
Definition at line 2599 of file openMTPK_wrap.cxx.
_swigt__p_unsigned_char
swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "unsigned char *", 0, 0, (void*)0, 0} static
Definition at line 2600 of file openMTPK_wrap.cxx.
swig_cast_initial
swig_cast_info* swig_cast_initial[] static
Initial value:
= {
  _swigc__p_Basics,
  _swigc__p_Cipher,
  _swigc__p_Primality,
  _swigc__p_RC4,
  _swigc__p_uint8_t,
  _swigc__p_unsigned_char,
}
Definition at line 2618 of file openMTPK_wrap.cxx.
Referenced by SWIG_InitializeModule().
swig_module
swig_module_info swig_module = {swig_types, 6, 0, 0, 0, 0} static
Definition at line 1567 of file openMTPK_wrap.cxx.
Referenced by SWIG_InitializeModule(), and SWIG_PropagateClientData().
swig_type_initial
swig_type_info* swig_type_initial[] static
Initial value:
= {
  &_swigt__p_Basics,
  &_swigt__p_Cipher,
  &_swigt__p_Primality,
  &_swigt__p_RC4,
  &_swigt__p_uint8_t,
  &_swigt__p_unsigned_char,
}
Definition at line 2602 of file openMTPK_wrap.cxx.
Referenced by SWIG_InitializeModule().
swig_types
swig_type_info* swig_types[7] static
Definition at line 1566 of file openMTPK_wrap.cxx.