openMTPK: R/lib/openMTPK_wrap.cpp File Reference
openMTPK_wrap.cpp File Reference
#include <string.h>
#include <Rdefines.h>
#include <Rversion.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <stdarg.h>
#include <stdexcept>
#include <string>
#include "../../include/arithmetic/arith.hpp"
#include "../../include/number_theory/primes.hpp"
#include "../../include/number_theory/rc4.hpp"
#include "../../include/number_theory/cipher.hpp"
#include <typeinfo>
#include <stddef.h>
#include <algorithm>
#include <vector>
#include <utility>
#include <limits.h>
#include <R_ext/Rdynload.h>
Classes
struct swig_type_info
struct swig_cast_info
struct swig_module_info
struct RCallbackFunctionData
struct RSwigPacked
Macros
#define SWIG_VERSION 0x040100
#define SWIGR
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_TYPE_TABLE_NAME
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIG_BUFFER_SIZE 1024
#define SWIG_POINTER_DISOWN 0x1
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_POINTER_NO_NULL 0x4
#define SWIG_POINTER_CLEAR 0x8
#define SWIG_POINTER_RELEASE (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)
#define SWIG_POINTER_OWN 0x1
#define SWIG_OK (0)
#define SWIG_ERROR (-1)
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)
#define SWIG_IsOK(r) (r >= 0)
#define SWIG_ArgError(r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_AddNewMask(r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_AddCast(r) (r)
#define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define R_NO_REMAP
#define STRICT_R_HEADERS
#define SWIG_ConvertPtr(obj, pptr, type, flags) SWIG_R_ConvertPtr(obj, pptr, type, flags)
#define SWIG_ConvertPtrAndOwn(obj, pptr, type, flags, own) SWIG_R_ConvertPtr(obj, pptr, type, flags)
#define SWIG_NewPointerObj(ptr, type, flags) SWIG_R_NewPointerObj(ptr, type, flags)
#define VMAXTYPE void *
#define SWIG_fail goto fail
#define ADD_OUTPUT_ARG(result, pos, value, name) r_ans = AddOutputArgToReturn(pos, value, name, OutputValues);
#define SWIG_exception_noreturn(code, msg) do { return result; } while(0)
#define SWIG_exception_fail(code, msg) do { SWIG_Error(code, msg); SWIG_fail; } while(0)
#define SWIG_contract_assert(expr, msg) do { if (!(expr)) { SWIG_Error(SWIG_RuntimeError, msg); SWIG_fail; } } while (0)
#define SWIG_exception(code, msg) do { switch (code) {case SWIG_IndexError: return Rf_ScalarLogical(NA_LOGICAL); default: SWIG_Error(code, msg); SWIG_fail;}; } while(0)
#define SWIGTYPE_p_Basics swig_types[0]
#define SWIGTYPE_p_Cipher swig_types[1]
#define SWIGTYPE_p_Primality swig_types[2]
#define SWIGTYPE_p_RC4 swig_types[3]
#define SWIGTYPE_p_char swig_types[4]
#define SWIGTYPE_p_uint8_t swig_types[5]
#define SWIGTYPE_p_unsigned_char swig_types[6]
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a))
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a))
#define SWIG_INIT_CLIENT_DATA_TYPE void *
Typedefs
typedef void *(* swig_converter_func) (void *, int *)
typedef struct swig_type_info *(* swig_dycast_func) (void **)
typedef struct swig_type_info swig_type_info
typedef struct swig_cast_info swig_cast_info
typedef struct swig_module_info swig_module_info
typedef struct RCallbackFunctionData RCallbackFunctionData
Functions
SWIGRUNTIME int SWIG_TypeNameComp (const char *f1, const char *l1, const char *f2, const char *l2)
SWIGRUNTIME int SWIG_TypeCmp (const char *nb, const char *tb)
SWIGRUNTIME int SWIG_TypeEquiv (const char *nb, const char *tb)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (const swig_type_info *from, swig_type_info *ty)
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info *ty, void *ptr, int *newmemory)
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info *ty, void **ptr)
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info *ty)
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info *type)
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME char * SWIG_PackData (char *c, void *ptr, size_t sz)
SWIGRUNTIME const char * SWIG_UnpackData (const char *c, void *ptr, size_t sz)
SWIGRUNTIME char * SWIG_PackVoidPtr (char *buff, void *ptr, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char *c, void **ptr, const char *name)
SWIGRUNTIME char * SWIG_PackDataName (char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackDataName (const char *c, void *ptr, size_t sz, const char *name)
SWIGRUNTIME void SWIG_Error (int code, const char *format,...)
SWIGRUNTIME const char * SWIG_ErrorType (int code)
SWIGRUNTIME SEXP R_SWIG_debug_getCallbackFunctionData ()
SWIGRUNTIME RCallbackFunctionData * R_SWIG_pushCallbackFunctionData (SEXP fun, SEXP userData)
SWIGRUNTIME SEXP R_SWIG_R_pushCallbackFunctionData (SEXP fun, SEXP userData)
SWIGRUNTIME RCallbackFunctionData * R_SWIG_getCallbackFunctionData ()
SWIGRUNTIME void R_SWIG_popCallbackFunctionData (int doFree)
SWIGRUNTIME int R_SWIG_checkInherits (SEXP obj, SEXP tag, const char *type)
SWIGRUNTIME void * R_SWIG_resolveExternalRef (SEXP arg, const char *const type, const char *const argName, Rboolean nullOk)
SWIGRUNTIME void R_SWIG_ReferenceFinalizer (SEXP el)
SWIGRUNTIME SEXP SWIG_MakePtr (void *ptr, const char *typeName, int flags)
SWIGRUNTIME SEXP R_SWIG_create_SWIG_R_Array (const char *typeName, SEXP ref, int len)
SWIGRUNTIME SEXP AddOutputArgToReturn (int pos, SEXP value, const char *name, SEXP output)
SWIGRUNTIMEINLINE SEXP SWIG_R_NewPointerObj (void *ptr, swig_type_info *type, int flags)
SWIGRUNTIMEINLINE int SWIG_R_ConvertPtr (SEXP obj, void **ptr, swig_type_info *ty, int flags)
SWIGRUNTIME swig_module_info * SWIG_GetModule (void *SWIGUNUSEDPARM(clientdata))
SWIGRUNTIME void SWIG_SetModule (void *v, swig_module_info *swig_module)
SWIGRUNTIMEINLINE SEXP RSwigPacked_New (void *ptr, size_t sz, swig_type_info *ty)
SWIGRUNTIME swig_type_info * RSwigPacked_UnpackData (SEXP obj, void *ptr, size_t size)
SWIGRUNTIMEINLINE SEXP SWIG_R_NewPackedObj (void *ptr, size_t sz, swig_type_info *type)
SWIGRUNTIME int SWIG_R_ConvertPacked (SEXP obj, void *ptr, size_t sz, swig_type_info *ty)
SWIGINTERN void SWIG_R_Raise (SEXP obj, const char *msg)
SWIGINTERNINLINE int SWIG_AsVal_long (SEXP obj, long *val)
SWIGINTERNINLINE SEXP SWIG_From_long (long value)
SWIGINTERN int SWIG_AsVal_int (SEXP obj, int *val)
SWIGINTERN char * SWIG_strdup (const char *str)
SWIGINTERN SEXP SWIG_FromCharPtrAndSize (const char *carray, size_t size)
SWIGINTERNINLINE SEXP SWIG_From_std_string (const std::string &s)
SWIGINTERN int SWIG_AsCharPtrAndSize (SEXP obj, char **cptr, size_t *psize, int *alloc)
SWIGINTERN int SWIG_AsPtr_std_string (SEXP obj, std::string **val)
SWIGEXPORT SEXP R_swig_Basics_greatest_power (SEXP self, SEXP n, SEXP p, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Basics_rm_gcd (SEXP self, SEXP x, SEXP y, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_new_Basics ()
SWIGEXPORT SEXP R_swig_delete_Basics (SEXP self)
SWIGEXPORT SEXP R_swig_Primality_is_prime (SEXP self, SEXP n, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_compute_miller_rabin (SEXP self, SEXP d, SEXP n, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_miller_rabin_prime (SEXP self, SEXP n, SEXP iters, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_miller_rabin (SEXP self, SEXP inters, SEXP min_val, SEXP max_val)
SWIGEXPORT SEXP R_swig_Primality_jacobian_number (SEXP self, SEXP a, SEXP n, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_solovoy_strassen (SEXP self, SEXP p, SEXP iters, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_mod_pow (SEXP self, SEXP base, SEXP exponent, SEXP mod, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_carmichael_num (SEXP self, SEXP n, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_sieve_of_eratosthenes (SEXP self, SEXP n)
SWIGEXPORT SEXP R_swig_Primality_pollard_rho (SEXP self, SEXP n, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Primality_ETF (SEXP self, SEXP n, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_new_Primality ()
SWIGEXPORT SEXP R_swig_delete_Primality (SEXP self)
SWIGEXPORT SEXP R_swig_RC4_byte_swap (SEXP self, SEXP a, SEXP b)
SWIGEXPORT SEXP R_swig_RC4_trad_swap (SEXP self, SEXP a, SEXP b)
SWIGEXPORT SEXP R_swig_RC4_XOR_swap (SEXP self, SEXP a, SEXP b)
SWIGEXPORT SEXP R_swig_RC4_KSA (SEXP self, SEXP key, SEXP S, SEXP swap_type)
SWIGEXPORT SEXP R_swig_RC4_PRGA (SEXP self, SEXP S, SEXP plaintext, SEXP ciphertext, SEXP swap_type)
SWIGEXPORT SEXP R_swig_RC4_store_hash (SEXP self, SEXP plaintext, SEXP hashtext, SEXP swap_type, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_RC4_compute (SEXP self, SEXP key, SEXP plaintext, SEXP hashtext, SEXP swap_type)
SWIGEXPORT SEXP R_swig_new_RC4 ()
SWIGEXPORT SEXP R_swig_delete_RC4 (SEXP self)
SWIGEXPORT SEXP R_swig_Cipher_C_cipher (SEXP self, SEXP plaintext, SEXP key, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Cipher_KC_encode (SEXP self, SEXP key, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_Cipher_KC_cipher (SEXP self, SEXP plaintext, SEXP encoded_text, SEXP s_swig_copy)
SWIGEXPORT SEXP R_swig_new_Cipher ()
SWIGEXPORT SEXP R_swig_delete_Cipher (SEXP self)
SWIGRUNTIME void SWIG_InitializeModule (SWIG_INIT_CLIENT_DATA_TYPE clientdata)
SWIGRUNTIME void SWIG_PropagateClientData (void)
SWIGEXPORT void SWIG_init (void)
SWIGEXPORT void R_init_openMTPK (DllInfo *dll)
Variables
static int SWIG_lasterror_code = 0
static char SWIG_lasterror_msg [1024]
static RCallbackFunctionData * callbackFunctionDataStack
static swig_type_info * swig_types [8]
static swig_module_info swig_module = {swig_types, 7, 0, 0, 0, 0}
static swig_type_info _swigt__p_Basics = {"_p_Basics", "Basics *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_Cipher = {"_p_Cipher", "Cipher *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_Primality = {"_p_Primality", "Primality *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_RC4 = {"_p_RC4", "RC4 *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_uint8_t = {"_p_uint8_t", "uint8_t *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "unsigned char *", 0, 0, (void*)0, 0}
static swig_type_info * swig_type_initial []
static swig_cast_info _swigc__p_Basics [] = { {&_swigt__p_Basics, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_Cipher [] = { {&_swigt__p_Cipher, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_Primality [] = { {&_swigt__p_Primality, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_RC4 [] = { {&_swigt__p_RC4, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_char [] = { {&_swigt__p_char, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_uint8_t [] = { {&_swigt__p_uint8_t, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_unsigned_char [] = { {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info * swig_cast_initial []
SWIGINTERN R_CallMethodDef CallEntries []
Macro Definition Documentation
ADD_OUTPUT_ARG
#define ADD_OUTPUT_ARG (result, pos, value, name) r_ans = AddOutputArgToReturn(pos, value, name, OutputValues);
Definition at line 1024 of file openMTPK_wrap.cpp.
R_NO_REMAP
#define R_NO_REMAP
Definition at line 736 of file openMTPK_wrap.cpp.
STRICT_R_HEADERS
#define STRICT_R_HEADERS
Definition at line 739 of file openMTPK_wrap.cpp.
SWIG_AddCast
#define SWIG_AddCast (r) (r)
Definition at line 315 of file openMTPK_wrap.cpp.
SWIG_AddNewMask
#define SWIG_AddNewMask (r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
Definition at line 291 of file openMTPK_wrap.cpp.
SWIG_AddTmpMask
#define SWIG_AddTmpMask (r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
Definition at line 294 of file openMTPK_wrap.cpp.
SWIG_ArgError
#define SWIG_ArgError (r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
Definition at line 277 of file openMTPK_wrap.cpp.
SWIG_as_voidptr
#define SWIG_as_voidptr (a) const_cast< void * >(static_cast< const void * >(a))
Definition at line 1362 of file openMTPK_wrap.cpp.
SWIG_as_voidptrptr
#define SWIG_as_voidptrptr (a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a))
Definition at line 1363 of file openMTPK_wrap.cpp.
SWIG_AttributeError
#define SWIG_AttributeError -11
Definition at line 729 of file openMTPK_wrap.cpp.
SWIG_BADOBJ
#define SWIG_BADOBJ (SWIG_ERROR)
Definition at line 286 of file openMTPK_wrap.cpp.
SWIG_BUFFER_SIZE
#define SWIG_BUFFER_SIZE 1024
Definition at line 175 of file openMTPK_wrap.cpp.
SWIG_CAST_NEW_MEMORY
#define SWIG_CAST_NEW_MEMORY 0x2
Definition at line 180 of file openMTPK_wrap.cpp.
SWIG_CASTRANKLIMIT
#define SWIG_CASTRANKLIMIT (1 << 8)
Definition at line 280 of file openMTPK_wrap.cpp.
SWIG_CheckState
#define SWIG_CheckState (r) (SWIG_IsOK(r) ? 1 : 0)
Definition at line 316 of file openMTPK_wrap.cpp.
SWIG_contract_assert
#define SWIG_contract_assert (expr, msg) do { if (!(expr)) { SWIG_Error(SWIG_RuntimeError, msg); SWIG_fail; } } while (0)
Definition at line 1164 of file openMTPK_wrap.cpp.
SWIG_ConvertPtr
#define SWIG_ConvertPtr (obj, pptr, type, flags) SWIG_R_ConvertPtr(obj, pptr, type, flags)
Definition at line 751 of file openMTPK_wrap.cpp.
SWIG_ConvertPtrAndOwn
#define SWIG_ConvertPtrAndOwn (obj, pptr, type, flags, own) SWIG_R_ConvertPtr(obj, pptr, type, flags)
Definition at line 752 of file openMTPK_wrap.cpp.
SWIG_DelNewMask
#define SWIG_DelNewMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
Definition at line 292 of file openMTPK_wrap.cpp.
SWIG_DelTmpMask
#define SWIG_DelTmpMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
Definition at line 295 of file openMTPK_wrap.cpp.
SWIG_DivisionByZero
#define SWIG_DivisionByZero -6
Definition at line 724 of file openMTPK_wrap.cpp.
SWIG_ERROR
#define SWIG_ERROR (-1)
Definition at line 270 of file openMTPK_wrap.cpp.
SWIG_ERROR_RELEASE_NOT_OWNED
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)
Definition at line 274 of file openMTPK_wrap.cpp.
SWIG_exception
#define SWIG_exception (code, msg) do { switch (code) {case SWIG_IndexError: return Rf_ScalarLogical(NA_LOGICAL); default: SWIG_Error(code, msg); SWIG_fail;}; } while(0)
Definition at line 1168 of file openMTPK_wrap.cpp.
SWIG_exception_fail
#define SWIG_exception_fail (code, msg) do { SWIG_Error(code, msg); SWIG_fail; } while(0)
Definition at line 1162 of file openMTPK_wrap.cpp.
SWIG_exception_noreturn
#define SWIG_exception_noreturn (code, msg) do { return result; } while(0)
Definition at line 1148 of file openMTPK_wrap.cpp.
SWIG_fail
#define SWIG_fail goto fail
Definition at line 805 of file openMTPK_wrap.cpp.
SWIG_IndexError
#define SWIG_IndexError -4
Definition at line 722 of file openMTPK_wrap.cpp.
SWIG_INIT_CLIENT_DATA_TYPE
#define SWIG_INIT_CLIENT_DATA_TYPE void *
Definition at line 2865 of file openMTPK_wrap.cpp.
SWIG_IOError
#define SWIG_IOError -2
Definition at line 720 of file openMTPK_wrap.cpp.
SWIG_IsNewObj
#define SWIG_IsNewObj (r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
Definition at line 293 of file openMTPK_wrap.cpp.
SWIG_IsOK
#define SWIG_IsOK (r) (r >= 0)
Definition at line 276 of file openMTPK_wrap.cpp.
SWIG_IsTmpObj
#define SWIG_IsTmpObj (r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
Definition at line 296 of file openMTPK_wrap.cpp.
SWIG_MangledTypeQuery
#define SWIG_MangledTypeQuery (name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)
Definition at line 1184 of file openMTPK_wrap.cpp.
SWIG_MemoryError
#define SWIG_MemoryError -12
Definition at line 730 of file openMTPK_wrap.cpp.
SWIG_NEWOBJ
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
Definition at line 288 of file openMTPK_wrap.cpp.
SWIG_NEWOBJMASK
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
Definition at line 282 of file openMTPK_wrap.cpp.
SWIG_NewPointerObj
#define SWIG_NewPointerObj (ptr, type, flags) SWIG_R_NewPointerObj(ptr, type, flags)
Definition at line 753 of file openMTPK_wrap.cpp.
SWIG_NullReferenceError
#define SWIG_NullReferenceError -13
Definition at line 731 of file openMTPK_wrap.cpp.
SWIG_OK
#define SWIG_OK (0)
Definition at line 268 of file openMTPK_wrap.cpp.
SWIG_OLDOBJ
#define SWIG_OLDOBJ (SWIG_OK)
Definition at line 287 of file openMTPK_wrap.cpp.
SWIG_OverflowError
#define SWIG_OverflowError -7
Definition at line 725 of file openMTPK_wrap.cpp.
SWIG_POINTER_CLEAR
#define SWIG_POINTER_CLEAR 0x8
Definition at line 182 of file openMTPK_wrap.cpp.
SWIG_POINTER_DISOWN
#define SWIG_POINTER_DISOWN 0x1
Definition at line 179 of file openMTPK_wrap.cpp.
SWIG_POINTER_NO_NULL
#define SWIG_POINTER_NO_NULL 0x4
Definition at line 181 of file openMTPK_wrap.cpp.
SWIG_POINTER_OWN
#define SWIG_POINTER_OWN 0x1
Definition at line 186 of file openMTPK_wrap.cpp.
SWIG_POINTER_RELEASE
#define SWIG_POINTER_RELEASE (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)
Definition at line 183 of file openMTPK_wrap.cpp.
SWIG_RUNTIME_VERSION
#define SWIG_RUNTIME_VERSION "4"
Definition at line 145 of file openMTPK_wrap.cpp.
SWIG_RuntimeError
#define SWIG_RuntimeError -3
Definition at line 721 of file openMTPK_wrap.cpp.
SWIG_SyntaxError
#define SWIG_SyntaxError -8
Definition at line 726 of file openMTPK_wrap.cpp.
SWIG_SystemError
#define SWIG_SystemError -10
Definition at line 728 of file openMTPK_wrap.cpp.
SWIG_TMPOBJ
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
Definition at line 289 of file openMTPK_wrap.cpp.
SWIG_TMPOBJMASK
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
Definition at line 284 of file openMTPK_wrap.cpp.
SWIG_TYPE_TABLE_NAME
#define SWIG_TYPE_TABLE_NAME
Definition at line 153 of file openMTPK_wrap.cpp.
SWIG_TypeError
#define SWIG_TypeError -5
Definition at line 723 of file openMTPK_wrap.cpp.
SWIG_TypeQuery
#define SWIG_TypeQuery (name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
Definition at line 1183 of file openMTPK_wrap.cpp.
SWIG_UnknownError
#define SWIG_UnknownError -1
Definition at line 719 of file openMTPK_wrap.cpp.
SWIG_ValueError
#define SWIG_ValueError -9
Definition at line 727 of file openMTPK_wrap.cpp.
SWIG_VERSION
#define SWIG_VERSION 0x040100
Definition at line 10 of file openMTPK_wrap.cpp.
SWIGEXPORT
#define SWIGEXPORT
Definition at line 98 of file openMTPK_wrap.cpp.
SWIGINLINE
#define SWIGINLINE
Definition at line 35 of file openMTPK_wrap.cpp.
SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
Definition at line 70 of file openMTPK_wrap.cpp.
SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
Definition at line 75 of file openMTPK_wrap.cpp.
SWIGR
#define SWIGR
Definition at line 11 of file openMTPK_wrap.cpp.
SWIGRUNTIME
#define SWIGRUNTIME SWIGINTERN
Definition at line 166 of file openMTPK_wrap.cpp.
SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
Definition at line 170 of file openMTPK_wrap.cpp.
SWIGSTDCALL
#define SWIGSTDCALL
Definition at line 108 of file openMTPK_wrap.cpp.
SWIGTEMPLATEDISAMBIGUATOR
#define SWIGTEMPLATEDISAMBIGUATOR
Definition at line 26 of file openMTPK_wrap.cpp.
SWIGTYPE_p_Basics
#define SWIGTYPE_p_Basics swig_types[0]
Definition at line 1174 of file openMTPK_wrap.cpp.
SWIGTYPE_p_char
#define SWIGTYPE_p_char swig_types[4]
Definition at line 1178 of file openMTPK_wrap.cpp.
SWIGTYPE_p_Cipher
#define SWIGTYPE_p_Cipher swig_types[1]
Definition at line 1175 of file openMTPK_wrap.cpp.
SWIGTYPE_p_Primality
#define SWIGTYPE_p_Primality swig_types[2]
Definition at line 1176 of file openMTPK_wrap.cpp.
SWIGTYPE_p_RC4
#define SWIGTYPE_p_RC4 swig_types[3]
Definition at line 1177 of file openMTPK_wrap.cpp.
SWIGTYPE_p_uint8_t
#define SWIGTYPE_p_uint8_t swig_types[5]
Definition at line 1179 of file openMTPK_wrap.cpp.
SWIGTYPE_p_unsigned_char
#define SWIGTYPE_p_unsigned_char swig_types[6]
Definition at line 1180 of file openMTPK_wrap.cpp.
SWIGUNUSED
#define SWIGUNUSED
Definition at line 50 of file openMTPK_wrap.cpp.
SWIGUNUSEDPARM
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
Definition at line 64 of file openMTPK_wrap.cpp.
VMAXTYPE
#define VMAXTYPE void *
Definition at line 761 of file openMTPK_wrap.cpp.
Typedef Documentation
RCallbackFunctionData
typedef struct RCallbackFunctionData RCallbackFunctionData
swig_cast_info
typedef struct swig_cast_info swig_cast_info
swig_converter_func
typedef void*(* swig_converter_func) (void *, int *)
Definition at line 326 of file openMTPK_wrap.cpp.
swig_dycast_func
typedef struct swig_type_info*(* swig_dycast_func) (void **)
Definition at line 326 of file openMTPK_wrap.cpp.
swig_module_info
typedef struct swig_module_info swig_module_info
swig_type_info
typedef struct swig_type_info swig_type_info
Function Documentation
AddOutputArgToReturn()
SWIGRUNTIME SEXP AddOutputArgToReturn (int pos, SEXP value, const char * name, SEXP output)
Definition at line 1027 of file openMTPK_wrap.cpp.
 {
   SET_VECTOR_ELT(output, pos, value);
   return(output);
 }
References value.
R_init_openMTPK()
SWIGEXPORT void R_init_openMTPK (DllInfo * dll)
Definition at line 3095 of file openMTPK_wrap.cpp.
{
     R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
 SWIG_init();
 SWIG_InitializeModule(0);
 }
References CallEntries, SWIG_init(), and SWIG_InitializeModule().
R_swig_Basics_greatest_power()
SWIGEXPORT SEXP R_swig_Basics_greatest_power (SEXP self, SEXP n, SEXP p, SEXP s_swig_copy)
Definition at line 1543 of file openMTPK_wrap.cpp.
 {
   {
     int result;
     Basics *arg1 = (Basics *) 0 ;
     int arg2 ;
     int arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Basics, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Basics_greatest_power" "', argument " "1"" of type '" "Basics *""'");
     }
     arg1 = reinterpret_cast< Basics * >(argp1);
     arg2 = static_cast< int >(INTEGER(n)[0]);
     arg3 = static_cast< int >(INTEGER(p)[0]);
     result = (int)(arg1)->greatest_power(arg2,arg3);
     r_ans = Rf_ScalarInteger(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Basics::greatest_power(), Python.examples.primes_ex::p, SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Basics, SWIGUNUSED, and VMAXTYPE.
R_swig_Basics_rm_gcd()
SWIGEXPORT SEXP R_swig_Basics_rm_gcd (SEXP self, SEXP x, SEXP y, SEXP s_swig_copy)
Definition at line 1577 of file openMTPK_wrap.cpp.
 {
   {
     int result;
     Basics *arg1 = (Basics *) 0 ;
     int arg2 ;
     int arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Basics, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Basics_rm_gcd" "', argument " "1"" of type '" "Basics *""'");
     }
     arg1 = reinterpret_cast< Basics * >(argp1);
     arg2 = static_cast< int >(INTEGER(x)[0]);
     arg3 = static_cast< int >(INTEGER(y)[0]);
     result = (int)(arg1)->rm_gcd(arg2,arg3);
     r_ans = Rf_ScalarInteger(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Basics::rm_gcd(), SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Basics, SWIGUNUSED, and VMAXTYPE.
R_SWIG_checkInherits()
SWIGRUNTIME int R_SWIG_checkInherits (SEXP obj, SEXP tag, const char * type)
Definition at line 918 of file openMTPK_wrap.cpp.
 {
   SEXP e, val;
   int check_err = 0;
   Rf_protect(e = Rf_allocVector(LANGSXP, 3));
   SETCAR(e, Rf_install("extends"));
   SETCAR(CDR(e), Rf_mkString(CHAR(PRINTNAME(tag))));
   SETCAR(CDR(CDR(e)), Rf_mkString(type));
   val = R_tryEval(e, R_GlobalEnv, &check_err);
   Rf_unprotect(1);
   if(check_err)
     return(0);
   return(LOGICAL(val)[0]);
 }
Referenced by R_SWIG_resolveExternalRef().
R_swig_Cipher_C_cipher()
SWIGEXPORT SEXP R_swig_Cipher_C_cipher (SEXP self, SEXP plaintext, SEXP key, SEXP s_swig_copy)
Definition at line 2583 of file openMTPK_wrap.cpp.
 {
   {
     std::string result;
     Cipher *arg1 = (Cipher *) 0 ;
     std::string arg2 ;
     int arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Cipher_C_cipher" "', argument " "1"" of type '" "Cipher *""'");
     }
     arg1 = reinterpret_cast< Cipher * >(argp1);
     {
       std::string *ptr = (std::string *)0;
       int res = SWIG_AsPtr_std_string(plaintext, &ptr);
       if (!SWIG_IsOK(res) || !ptr) {
         SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_C_cipher" "', argument " "2"" of type '" "std::string""'");
       }
       arg2 = *ptr;
       if (SWIG_IsNewObj(res)) delete ptr;
     }
     arg3 = static_cast< int >(INTEGER(key)[0]);
     result = (arg1)->C_cipher(arg2,arg3);
     r_ans = SWIG_From_std_string(static_cast< std::string >(result));
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_AsPtr_std_string(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_From_std_string(), SWIG_IsNewObj, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_TypeError, SWIGTYPE_p_Cipher, SWIGUNUSED, and VMAXTYPE.
R_swig_Cipher_KC_cipher()
SWIGEXPORT SEXP R_swig_Cipher_KC_cipher (SEXP self, SEXP plaintext, SEXP encoded_text, SEXP s_swig_copy)
Definition at line 2665 of file openMTPK_wrap.cpp.
 {
   {
     std::string result;
     Cipher *arg1 = (Cipher *) 0 ;
     std::string arg2 ;
     std::string arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Cipher_KC_cipher" "', argument " "1"" of type '" "Cipher *""'");
     }
     arg1 = reinterpret_cast< Cipher * >(argp1);
     {
       std::string *ptr = (std::string *)0;
       int res = SWIG_AsPtr_std_string(plaintext, &ptr);
       if (!SWIG_IsOK(res) || !ptr) {
         SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_KC_cipher" "', argument " "2"" of type '" "std::string""'");
       }
       arg2 = *ptr;
       if (SWIG_IsNewObj(res)) delete ptr;
     }
     {
       std::string *ptr = (std::string *)0;
       int res = SWIG_AsPtr_std_string(encoded_text, &ptr);
       if (!SWIG_IsOK(res) || !ptr) {
         SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_KC_cipher" "', argument " "3"" of type '" "std::string""'");
       }
       arg3 = *ptr;
       if (SWIG_IsNewObj(res)) delete ptr;
     }
     result = (arg1)->KC_cipher(arg2,arg3);
     r_ans = SWIG_From_std_string(static_cast< std::string >(result));
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.cipher_ex::encoded_text, SWIG_ArgError, SWIG_AsPtr_std_string(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_From_std_string(), SWIG_IsNewObj, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_TypeError, SWIGTYPE_p_Cipher, SWIGUNUSED, and VMAXTYPE.
R_swig_Cipher_KC_encode()
SWIGEXPORT SEXP R_swig_Cipher_KC_encode (SEXP self, SEXP key, SEXP s_swig_copy)
Definition at line 2625 of file openMTPK_wrap.cpp.
 {
   {
     std::string result;
     Cipher *arg1 = (Cipher *) 0 ;
     std::string arg2 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Cipher_KC_encode" "', argument " "1"" of type '" "Cipher *""'");
     }
     arg1 = reinterpret_cast< Cipher * >(argp1);
     {
       std::string *ptr = (std::string *)0;
       int res = SWIG_AsPtr_std_string(key, &ptr);
       if (!SWIG_IsOK(res) || !ptr) {
         SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_KC_encode" "', argument " "2"" of type '" "std::string""'");
       }
       arg2 = *ptr;
       if (SWIG_IsNewObj(res)) delete ptr;
     }
     result = (arg1)->KC_encode(arg2);
     r_ans = SWIG_From_std_string(static_cast< std::string >(result));
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_AsPtr_std_string(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_From_std_string(), SWIG_IsNewObj, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_TypeError, SWIGTYPE_p_Cipher, SWIGUNUSED, and VMAXTYPE.
R_SWIG_create_SWIG_R_Array()
SWIGRUNTIME SEXP R_SWIG_create_SWIG_R_Array (const char * typeName, SEXP ref, int len)
Definition at line 1010 of file openMTPK_wrap.cpp.
 {
    SEXP arr;
 /*XXX remove the char * cast when we can. MAKE_CLASS should be declared appropriately. */
    Rf_protect(arr = NEW_OBJECT(MAKE_CLASS((char *) typeName)));
    Rf_protect(arr = R_do_slot_assign(arr, Rf_mkString("ref"), ref));
    Rf_protect(arr = R_do_slot_assign(arr, Rf_mkString("dims"), Rf_ScalarInteger(len)));
    Rf_unprotect(3);
    SET_S4_OBJECT(arr);
    return arr;
 }
R_SWIG_debug_getCallbackFunctionData()
SWIGRUNTIME SEXP R_SWIG_debug_getCallbackFunctionData ()
Definition at line 833 of file openMTPK_wrap.cpp.
 {
   int n, i;
   SEXP ans;
   RCallbackFunctionData  *p = callbackFunctionDataStack;
   n = 0;
   while(p) {
     n++;
     p = p->previous;
   }
   Rf_protect(ans = Rf_allocVector(VECSXP, n));
   for(p = callbackFunctionDataStack, i = 0; i < n; p = p->previous, i++)
       SET_VECTOR_ELT(ans, i, p->fun);
   Rf_unprotect(1);
   return(ans);
 }
References callbackFunctionDataStack, and Python.examples.primes_ex::p.
R_swig_delete_Basics()
SWIGEXPORT SEXP R_swig_delete_Basics (SEXP self)
Definition at line 1633 of file openMTPK_wrap.cpp.
 {
   {
     Basics *arg1 = (Basics *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Basics, SWIG_POINTER_DISOWN |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_Basics" "', argument " "1"" of type '" "Basics *""'");
     }
     arg1 = reinterpret_cast< Basics * >(argp1);
     delete arg1;
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     R_ClearExternalPtr(self);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_DISOWN, SWIG_R_ConvertPtr(), SWIGTYPE_p_Basics, SWIGUNUSED, and VMAXTYPE.
R_swig_delete_Cipher()
SWIGEXPORT SEXP R_swig_delete_Cipher (SEXP self)
Definition at line 2737 of file openMTPK_wrap.cpp.
 {
   {
     Cipher *arg1 = (Cipher *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, SWIG_POINTER_DISOWN |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_Cipher" "', argument " "1"" of type '" "Cipher *""'");
     }
     arg1 = reinterpret_cast< Cipher * >(argp1);
     delete arg1;
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     R_ClearExternalPtr(self);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_DISOWN, SWIG_R_ConvertPtr(), SWIGTYPE_p_Cipher, SWIGUNUSED, and VMAXTYPE.
R_swig_delete_Primality()
SWIGEXPORT SEXP R_swig_delete_Primality (SEXP self)
Definition at line 2099 of file openMTPK_wrap.cpp.
 {
   {
     Primality *arg1 = (Primality *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, SWIG_POINTER_DISOWN |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_Primality" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     delete arg1;
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     R_ClearExternalPtr(self);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_DISOWN, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_delete_RC4()
SWIGEXPORT SEXP R_swig_delete_RC4 (SEXP self)
Definition at line 2553 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *arg1 = (RC4 *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, SWIG_POINTER_DISOWN |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_RC4" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     delete arg1;
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     R_ClearExternalPtr(self);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_DISOWN, SWIG_R_ConvertPtr(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_SWIG_getCallbackFunctionData()
SWIGRUNTIME RCallbackFunctionData* R_SWIG_getCallbackFunctionData ()
Definition at line 879 of file openMTPK_wrap.cpp.
 {
   if(!callbackFunctionDataStack) {
     Rf_error("Supposedly impossible error occurred in the SWIG callback mechanism."
             "  No callback function data set.");
   }
   return callbackFunctionDataStack;
 }
References callbackFunctionDataStack.
R_swig_new_Basics()
SWIGEXPORT SEXP R_swig_new_Basics ()
Definition at line 1611 of file openMTPK_wrap.cpp.
 {
   {
     Basics *result = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     result = (Basics *)new Basics();
     r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Basics, SWIG_POINTER_OWN |  0 );
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_as_voidptr, SWIG_ErrorType(), SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_OWN, SWIG_R_NewPointerObj(), SWIGTYPE_p_Basics, SWIGUNUSED, and VMAXTYPE.
R_swig_new_Cipher()
SWIGEXPORT SEXP R_swig_new_Cipher ()
Definition at line 2715 of file openMTPK_wrap.cpp.
 {
   {
     Cipher *result = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     result = (Cipher *)new Cipher();
     r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Cipher, SWIG_POINTER_OWN |  0 );
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_as_voidptr, SWIG_ErrorType(), SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_OWN, SWIG_R_NewPointerObj(), SWIGTYPE_p_Cipher, SWIGUNUSED, and VMAXTYPE.
R_swig_new_Primality()
SWIGEXPORT SEXP R_swig_new_Primality ()
Definition at line 2077 of file openMTPK_wrap.cpp.
 {
   {
     Primality *result = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     result = (Primality *)new Primality();
     r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Primality, SWIG_POINTER_OWN |  0 );
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_as_voidptr, SWIG_ErrorType(), SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_OWN, SWIG_R_NewPointerObj(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_new_RC4()
SWIGEXPORT SEXP R_swig_new_RC4 ()
Definition at line 2531 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *result = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     result = (RC4 *)new RC4();
     r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_RC4, SWIG_POINTER_OWN |  0 );
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_as_voidptr, SWIG_ErrorType(), SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_POINTER_OWN, SWIG_R_NewPointerObj(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_SWIG_popCallbackFunctionData()
SWIGRUNTIME void R_SWIG_popCallbackFunctionData (int doFree)
Definition at line 890 of file openMTPK_wrap.cpp.
 {
   RCallbackFunctionData  *el = NULL;
   if(!callbackFunctionDataStack)
     return ; /* Error !!! */
   el = callbackFunctionDataStack ;
   callbackFunctionDataStack = callbackFunctionDataStack->previous;
   if(doFree)
      free(el);
 }
References callbackFunctionDataStack, RCallbackFunctionData::el, and RCallbackFunctionData::previous.
R_swig_Primality_carmichael_num()
SWIGEXPORT SEXP R_swig_Primality_carmichael_num (SEXP self, SEXP n, SEXP s_swig_copy)
Definition at line 1938 of file openMTPK_wrap.cpp.
 {
   {
     bool result;
     Primality *arg1 = (Primality *) 0 ;
     int arg2 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_carmichael_num" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     arg2 = static_cast< int >(INTEGER(n)[0]);
     result = (bool)(arg1)->carmichael_num(arg2);
     r_ans = Rf_ScalarLogical(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Primality::carmichael_num(), SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_compute_miller_rabin()
SWIGEXPORT SEXP R_swig_Primality_compute_miller_rabin (SEXP self, SEXP d, SEXP n, SEXP s_swig_copy)
Definition at line 1695 of file openMTPK_wrap.cpp.
 {
   {
     bool result;
     Primality *arg1 = (Primality *) 0 ;
     int arg2 ;
     int arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_compute_miller_rabin" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     arg2 = static_cast< int >(INTEGER(d)[0]);
     arg3 = static_cast< int >(INTEGER(n)[0]);
     result = (bool)(arg1)->compute_miller_rabin(arg2,arg3);
     r_ans = Rf_ScalarLogical(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Primality::compute_miller_rabin(), SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_ETF()
SWIGEXPORT SEXP R_swig_Primality_ETF (SEXP self, SEXP n, SEXP s_swig_copy)
Definition at line 2039 of file openMTPK_wrap.cpp.
 {
   {
     int result;
     Primality *arg1 = (Primality *) 0 ;
     unsigned int arg2 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     int val2 ;
     int ecode2 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_ETF" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     ecode2 = SWIG_AsVal_int(n, &val2);
     if (!SWIG_IsOK(ecode2)) {
       SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_ETF" "', argument " "2"" of type '" "unsigned int""'");
     }
     arg2 = static_cast< unsigned int >(val2);
     result = (int)(arg1)->ETF(arg2);
     r_ans = Rf_ScalarInteger(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_AsVal_int(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_is_prime()
SWIGEXPORT SEXP R_swig_Primality_is_prime (SEXP self, SEXP n, SEXP s_swig_copy)
Definition at line 1663 of file openMTPK_wrap.cpp.
 {
   {
     bool result;
     Primality *arg1 = (Primality *) 0 ;
     int arg2 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_is_prime" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     arg2 = static_cast< int >(INTEGER(n)[0]);
     result = (bool)(arg1)->is_prime(arg2);
     r_ans = Rf_ScalarLogical(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Primality::is_prime(), SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_jacobian_number()
SWIGEXPORT SEXP R_swig_Primality_jacobian_number (SEXP self, SEXP a, SEXP n, SEXP s_swig_copy)
Definition at line 1798 of file openMTPK_wrap.cpp.
 {
   {
     int result;
     Primality *arg1 = (Primality *) 0 ;
     long long arg2 ;
     long long arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     long val2 ;
     int ecode2 = 0 ;
     long val3 ;
     int ecode3 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_jacobian_number" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     ecode2 = SWIG_AsVal_long(a, &val2);
     if (!SWIG_IsOK(ecode2)) {
       SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_jacobian_number" "', argument " "2"" of type '" "long long""'");
     }
     arg2 = static_cast< long long >(val2);
     ecode3 = SWIG_AsVal_long(n, &val3);
     if (!SWIG_IsOK(ecode3)) {
       SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "Primality_jacobian_number" "', argument " "3"" of type '" "long long""'");
     }
     arg3 = static_cast< long long >(val3);
     result = (int)(arg1)->jacobian_number(arg2,arg3);
     r_ans = Rf_ScalarInteger(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_AsVal_long(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_miller_rabin()
SWIGEXPORT SEXP R_swig_Primality_miller_rabin (SEXP self, SEXP inters, SEXP min_val, SEXP max_val)
Definition at line 1763 of file openMTPK_wrap.cpp.
 {
   {
     Primality *arg1 = (Primality *) 0 ;
     int arg2 ;
     int arg3 ;
     int arg4 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_miller_rabin" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     arg2 = static_cast< int >(INTEGER(inters)[0]);
     arg3 = static_cast< int >(INTEGER(min_val)[0]);
     arg4 = static_cast< int >(INTEGER(max_val)[0]);
     (arg1)->miller_rabin(arg2,arg3,arg4);
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_miller_rabin_prime()
SWIGEXPORT SEXP R_swig_Primality_miller_rabin_prime (SEXP self, SEXP n, SEXP iters, SEXP s_swig_copy)
Definition at line 1729 of file openMTPK_wrap.cpp.
 {
   {
     bool result;
     Primality *arg1 = (Primality *) 0 ;
     int arg2 ;
     int arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_miller_rabin_prime" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     arg2 = static_cast< int >(INTEGER(n)[0]);
     arg3 = static_cast< int >(INTEGER(iters)[0]);
     result = (bool)(arg1)->miller_rabin_prime(arg2,arg3);
     r_ans = Rf_ScalarLogical(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Primality::miller_rabin_prime(), SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_mod_pow()
SWIGEXPORT SEXP R_swig_Primality_mod_pow (SEXP self, SEXP base, SEXP exponent, SEXP mod, SEXP s_swig_copy)
Definition at line 1884 of file openMTPK_wrap.cpp.
 {
   {
     long long result;
     Primality *arg1 = (Primality *) 0 ;
     long long arg2 ;
     long long arg3 ;
     long long arg4 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     long val2 ;
     int ecode2 = 0 ;
     long val3 ;
     int ecode3 = 0 ;
     long val4 ;
     int ecode4 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_mod_pow" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     ecode2 = SWIG_AsVal_long(base, &val2);
     if (!SWIG_IsOK(ecode2)) {
       SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_mod_pow" "', argument " "2"" of type '" "long long""'");
     }
     arg2 = static_cast< long long >(val2);
     ecode3 = SWIG_AsVal_long(exponent, &val3);
     if (!SWIG_IsOK(ecode3)) {
       SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "Primality_mod_pow" "', argument " "3"" of type '" "long long""'");
     }
     arg3 = static_cast< long long >(val3);
     ecode4 = SWIG_AsVal_long(mod, &val4);
     if (!SWIG_IsOK(ecode4)) {
       SWIG_exception_fail(SWIG_ArgError(ecode4), "in method '" "Primality_mod_pow" "', argument " "4"" of type '" "long long""'");
     }
     arg4 = static_cast< long long >(val4);
     result = (long long)(arg1)->mod_pow(arg2,arg3,arg4);
     r_ans = SWIG_From_long(static_cast< long >(result));
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_AsVal_long(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_From_long(), SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_pollard_rho()
SWIGEXPORT SEXP R_swig_Primality_pollard_rho (SEXP self, SEXP n, SEXP s_swig_copy)
Definition at line 2001 of file openMTPK_wrap.cpp.
 {
   {
     long long result;
     Primality *arg1 = (Primality *) 0 ;
     long long arg2 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     long val2 ;
     int ecode2 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_pollard_rho" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     ecode2 = SWIG_AsVal_long(n, &val2);
     if (!SWIG_IsOK(ecode2)) {
       SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_pollard_rho" "', argument " "2"" of type '" "long long""'");
     }
     arg2 = static_cast< long long >(val2);
     result = (long long)(arg1)->pollard_rho(arg2);
     r_ans = SWIG_From_long(static_cast< long >(result));
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_AsVal_long(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_From_long(), SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_sieve_of_eratosthenes()
SWIGEXPORT SEXP R_swig_Primality_sieve_of_eratosthenes (SEXP self, SEXP n)
Definition at line 1970 of file openMTPK_wrap.cpp.
 {
   {
     Primality *arg1 = (Primality *) 0 ;
     int arg2 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_sieve_of_eratosthenes" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     arg2 = static_cast< int >(INTEGER(n)[0]);
     (arg1)->sieve_of_eratosthenes(arg2);
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_swig_Primality_solovoy_strassen()
SWIGEXPORT SEXP R_swig_Primality_solovoy_strassen (SEXP self, SEXP p, SEXP iters, SEXP s_swig_copy)
Definition at line 1844 of file openMTPK_wrap.cpp.
 {
   {
     bool result;
     Primality *arg1 = (Primality *) 0 ;
     long long arg2 ;
     int arg3 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     long val2 ;
     int ecode2 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_solovoy_strassen" "', argument " "1"" of type '" "Primality *""'");
     }
     arg1 = reinterpret_cast< Primality * >(argp1);
     ecode2 = SWIG_AsVal_long(p, &val2);
     if (!SWIG_IsOK(ecode2)) {
       SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_solovoy_strassen" "', argument " "2"" of type '" "long long""'");
     }
     arg2 = static_cast< long long >(val2);
     arg3 = static_cast< int >(INTEGER(iters)[0]);
     result = (bool)(arg1)->solovoy_strassen(arg2,arg3);
     r_ans = Rf_ScalarLogical(result);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.primes_ex::p, SWIG_ArgError, SWIG_AsVal_long(), SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_Primality, SWIGUNUSED, and VMAXTYPE.
R_SWIG_pushCallbackFunctionData()
SWIGRUNTIME RCallbackFunctionData* R_SWIG_pushCallbackFunctionData (SEXP fun, SEXP userData)
Definition at line 857 of file openMTPK_wrap.cpp.
 {
    RCallbackFunctionData *el;
    el = (RCallbackFunctionData *) calloc(1, sizeof(RCallbackFunctionData));
    el->fun = fun;
    el->userData = userData;
    el->previous = callbackFunctionDataStack;
    callbackFunctionDataStack = el;
    return(el);
 }
References callbackFunctionDataStack, RCallbackFunctionData::el, fun(), and RCallbackFunctionData::userData.
Referenced by R_SWIG_R_pushCallbackFunctionData().
R_SWIG_R_pushCallbackFunctionData()
SWIGRUNTIME SEXP R_SWIG_R_pushCallbackFunctionData (SEXP fun, SEXP userData)
Definition at line 872 of file openMTPK_wrap.cpp.
 {
     R_SWIG_pushCallbackFunctionData(fun, userData);
     return R_NilValue;
 }
References fun(), R_SWIG_pushCallbackFunctionData(), and RCallbackFunctionData::userData.
R_swig_RC4_byte_swap()
SWIGEXPORT SEXP R_swig_RC4_byte_swap (SEXP self, SEXP a, SEXP b)
Definition at line 2129 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *arg1 = (RC4 *) 0 ;
     uint8_t *arg2 = (uint8_t *) 0 ;
     uint8_t *arg3 = (uint8_t *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     void *argp2 = 0 ;
     int res2 = 0 ;
     void *argp3 = 0 ;
     int res3 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_byte_swap" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     res2 = SWIG_R_ConvertPtr(a, &argp2, SWIGTYPE_p_uint8_t, 0 |  0 );
     if (!SWIG_IsOK(res2)) {
       SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "RC4_byte_swap" "', argument " "2"" of type '" "uint8_t *""'");
     }
     arg2 = reinterpret_cast< uint8_t * >(argp2);
     res3 = SWIG_R_ConvertPtr(b, &argp3, SWIGTYPE_p_uint8_t, 0 |  0 );
     if (!SWIG_IsOK(res3)) {
       SWIG_exception_fail(SWIG_ArgError(res3), "in method '" "RC4_byte_swap" "', argument " "3"" of type '" "uint8_t *""'");
     }
     arg3 = reinterpret_cast< uint8_t * >(argp3);
     (arg1)->byte_swap(arg2,arg3);
     r_ans = R_NilValue;
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.arithmetic::b, SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_RC4, SWIGTYPE_p_uint8_t, SWIGUNUSED, and VMAXTYPE.
R_swig_RC4_compute()
SWIGEXPORT SEXP R_swig_RC4_compute (SEXP self, SEXP key, SEXP plaintext, SEXP hashtext, SEXP swap_type)
Definition at line 2474 of file openMTPK_wrap.cpp.
 {
   {
     unsigned char *result = 0 ;
     RC4 *arg1 = (RC4 *) 0 ;
     char *arg2 = (char *) 0 ;
     char *arg3 = (char *) 0 ;
     unsigned char *arg4 = (unsigned char *) 0 ;
     int arg5 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_compute" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     arg2 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(key, 0))));
     arg3 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(plaintext, 0))));
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(hashtext);
         arg4 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg4[_rswigi] = INTEGER(hashtext)[_rswigi];
         }
       }
     }
     arg5 = static_cast< int >(INTEGER(swap_type)[0]);
     result = (unsigned char *)(arg1)->compute(arg2,arg3,arg4,arg5);
     r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_unsigned_char, 0 |  0 );
     free(arg2);
     free(arg3);
     free(arg4);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
     free(arg2);
     free(arg3);
     free(arg4);
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.cipher_ex::hashtext, SWIG_ArgError, SWIG_as_voidptr, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_R_NewPointerObj(), SWIG_strdup(), SWIGTYPE_p_RC4, SWIGTYPE_p_unsigned_char, SWIGUNUSED, and VMAXTYPE.
R_swig_RC4_KSA()
SWIGEXPORT SEXP R_swig_RC4_KSA (SEXP self, SEXP key, SEXP S, SEXP swap_type)
Definition at line 2300 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *arg1 = (RC4 *) 0 ;
     char *arg2 = (char *) 0 ;
     unsigned char *arg3 = (unsigned char *) 0 ;
     int arg4 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_KSA" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     arg2 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(key, 0))));
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(S);
         arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg3[_rswigi] = INTEGER(S)[_rswigi];
         }
       }
     }
     arg4 = static_cast< int >(INTEGER(swap_type)[0]);
     (arg1)->KSA(arg2,arg3,arg4);
     r_ans = R_NilValue;
     free(arg2);
     free(arg3);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
     free(arg2);
     free(arg3);
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_strdup(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_swig_RC4_PRGA()
SWIGEXPORT SEXP R_swig_RC4_PRGA (SEXP self, SEXP S, SEXP plaintext, SEXP ciphertext, SEXP swap_type)
Definition at line 2352 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *arg1 = (RC4 *) 0 ;
     unsigned char *arg2 = (unsigned char *) 0 ;
     char *arg3 = (char *) 0 ;
     unsigned char *arg4 = (unsigned char *) 0 ;
     int arg5 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_PRGA" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(S);
         arg2 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg2[_rswigi] = INTEGER(S)[_rswigi];
         }
       }
     }
     arg3 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(plaintext, 0))));
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(ciphertext);
         arg4 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg4[_rswigi] = INTEGER(ciphertext)[_rswigi];
         }
       }
     }
     arg5 = static_cast< int >(INTEGER(swap_type)[0]);
     (arg1)->PRGA(arg2,arg3,arg4,arg5);
     r_ans = R_NilValue;
     free(arg2);
     free(arg3);
     free(arg4);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
     free(arg2);
     free(arg3);
     free(arg4);
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_strdup(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_swig_RC4_store_hash()
SWIGEXPORT SEXP R_swig_RC4_store_hash (SEXP self, SEXP plaintext, SEXP hashtext, SEXP swap_type, SEXP s_swig_copy)
Definition at line 2421 of file openMTPK_wrap.cpp.
 {
   {
     std::string result;
     RC4 *arg1 = (RC4 *) 0 ;
     char *arg2 = (char *) 0 ;
     unsigned char *arg3 = (unsigned char *) 0 ;
     int arg4 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_store_hash" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     arg2 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(plaintext, 0))));
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(hashtext);
         arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg3[_rswigi] = INTEGER(hashtext)[_rswigi];
         }
       }
     }
     arg4 = static_cast< int >(INTEGER(swap_type)[0]);
     result = (arg1)->store_hash(arg2,arg3,arg4);
     r_ans = SWIG_From_std_string(static_cast< std::string >(result));
     free(arg2);
     free(arg3);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
     free(arg2);
     free(arg3);
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.cipher_ex::hashtext, SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_From_std_string(), SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIG_strdup(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_swig_RC4_trad_swap()
SWIGEXPORT SEXP R_swig_RC4_trad_swap (SEXP self, SEXP a, SEXP b)
Definition at line 2174 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *arg1 = (RC4 *) 0 ;
     unsigned char *arg2 = (unsigned char *) 0 ;
     unsigned char *arg3 = (unsigned char *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_trad_swap" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(a);
         arg2 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg2[_rswigi] = INTEGER(a)[_rswigi];
         }
       }
     }
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(b);
         arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg3[_rswigi] = INTEGER(b)[_rswigi];
         }
       }
     }
     (arg1)->trad_swap(arg2,arg3);
     r_ans = R_NilValue;
     free(arg2);
     free(arg3);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
     free(arg2);
     free(arg3);
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.arithmetic::b, SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_swig_RC4_XOR_swap()
SWIGEXPORT SEXP R_swig_RC4_XOR_swap (SEXP self, SEXP a, SEXP b)
Definition at line 2237 of file openMTPK_wrap.cpp.
 {
   {
     RC4 *arg1 = (RC4 *) 0 ;
     unsigned char *arg2 = (unsigned char *) 0 ;
     unsigned char *arg3 = (unsigned char *) 0 ;
     void *argp1 = 0 ;
     int res1 = 0 ;
     unsigned int r_nprotect = 0;
     SEXP r_ans = R_NilValue ;
     VMAXTYPE r_vmax = vmaxget() ;
     res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
     if (!SWIG_IsOK(res1)) {
       SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_XOR_swap" "', argument " "1"" of type '" "RC4 *""'");
     }
     arg1 = reinterpret_cast< RC4 * >(argp1);
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(a);
         arg2 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg2[_rswigi] = INTEGER(a)[_rswigi];
         }
       }
     }
     {
       {
         int _rswigi;
         int _rswiglen = LENGTH(b);
         arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
         for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
           arg3[_rswigi] = INTEGER(b)[_rswigi];
         }
       }
     }
     (arg1)->XOR_swap(arg2,arg3);
     r_ans = R_NilValue;
     free(arg2);
     free(arg3);
     vmaxset(r_vmax);
     if(r_nprotect)  Rf_unprotect(r_nprotect);
     return r_ans;
     fail: SWIGUNUSED;
     free(arg2);
     free(arg3);
   }
   Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
   return R_NilValue;
 }
References Python.examples.arithmetic::b, SWIG_ArgError, SWIG_ErrorType(), SWIG_exception_fail, SWIG_IsOK, SWIG_lasterror_code, SWIG_lasterror_msg, SWIG_R_ConvertPtr(), SWIGTYPE_p_RC4, SWIGUNUSED, and VMAXTYPE.
R_SWIG_ReferenceFinalizer()
SWIGRUNTIME void R_SWIG_ReferenceFinalizer (SEXP el)
Definition at line 971 of file openMTPK_wrap.cpp.
 {
   void *ptr = R_SWIG_resolveExternalRef(el, "", "<finalizer>",  (Rboolean) 1);
   fprintf(stderr, "In R_SWIG_ReferenceFinalizer for %p\n", ptr);
   Rf_PrintValue(el);
   if(ptr) {
      if(TYPEOF(el) != EXTPTRSXP)
         el = GET_SLOT(el, Rf_mkString("ref"));
      if(TYPEOF(el) == EXTPTRSXP)
         R_ClearExternalPtr(el);
      free(ptr);
   }
   return;
 }
References RCallbackFunctionData::el, and R_SWIG_resolveExternalRef().
Referenced by SWIG_MakePtr().
R_SWIG_resolveExternalRef()
SWIGRUNTIME void* R_SWIG_resolveExternalRef (SEXP arg, const char *const type, const char *const argName, Rboolean nullOk)
Definition at line 940 of file openMTPK_wrap.cpp.
 {
   void *ptr;
   SEXP orig = arg;
   if(TYPEOF(arg) != EXTPTRSXP)
     arg = GET_SLOT(arg, Rf_mkString("ref"));
   if(TYPEOF(arg) != EXTPTRSXP) {
     Rf_error("argument %s must be an external pointer (from an ExternalReference)", argName);
   }
   ptr = R_ExternalPtrAddr(arg);
   if(ptr == NULL && nullOk == (Rboolean) FALSE) {
     Rf_error("the external pointer (of type %s) for argument %s has value NULL", argName, type);
   }
   if(type[0] && R_ExternalPtrTag(arg) != Rf_install(type) && strcmp(type, "voidRef")
       && !R_SWIG_checkInherits(orig,  R_ExternalPtrTag(arg), type)) {
     Rf_error("the external pointer for argument %s has tag %s, not the expected value %s",
              argName, CHAR(PRINTNAME(R_ExternalPtrTag(arg))), type);
   }
   return(ptr);
 }
References R_SWIG_checkInherits().
Referenced by R_SWIG_ReferenceFinalizer().
RSwigPacked_New()
SWIGRUNTIMEINLINE SEXP RSwigPacked_New (void * ptr, size_t sz, swig_type_info * ty)
Definition at line 1094 of file openMTPK_wrap.cpp.
{
   SEXP rptr;
   RSwigPacked *sobj =
   (RSwigPacked*) malloc(sizeof(RSwigPacked));
   if (sobj) {
     void *pack = malloc(sz);
     if (pack) {
       memcpy(pack, ptr, sz);
       sobj->pack = pack;
       sobj->ty   = ty;
       sobj->size = sz;
     } else {
       sobj = 0;
     }
   }
   rptr = R_MakeExternalPtr(sobj, R_NilValue, R_NilValue);
   return rptr;
 }
References RSwigPacked::pack, RSwigPacked::size, and RSwigPacked::ty.
Referenced by SWIG_R_NewPackedObj().
RSwigPacked_UnpackData()
SWIGRUNTIME swig_type_info* RSwigPacked_UnpackData (SEXP obj, void * ptr, size_t size)
Definition at line 1115 of file openMTPK_wrap.cpp.
 {
     RSwigPacked *sobj =
         (RSwigPacked *)R_ExternalPtrAddr(obj);
     if (sobj->size != size) return 0;
     memcpy(ptr, sobj->pack, size);
     return sobj->ty;
 }
References RSwigPacked::pack, RSwigPacked::size, and RSwigPacked::ty.
Referenced by SWIG_R_ConvertPacked().
SWIG_AsCharPtrAndSize()
SWIGINTERN int SWIG_AsCharPtrAndSize (SEXP obj, char ** cptr, size_t * psize, int * alloc)
Definition at line 1483 of file openMTPK_wrap.cpp.
 {
   if (cptr && Rf_isString(obj)) {
     char *cstr = const_cast< char * >(CHAR(STRING_ELT(obj, 0)));
     int len = strlen(cstr);
     if (alloc) {
       if (*alloc == SWIG_NEWOBJ) {
         *cptr = reinterpret_cast< char* >(memcpy(new char[len + 1], cstr, sizeof(char)*(len + 1)));
         *alloc = SWIG_NEWOBJ;
       } else {
         *cptr = cstr;
       }
     } else {
       *cptr = reinterpret_cast< char * >(malloc(len + 1));
       *cptr = strcpy(*cptr, cstr);
     }
     if (psize) *psize = len + 1;
     return SWIG_OK;
   }
   return SWIG_TypeError;
 }
References SWIG_NEWOBJ, SWIG_OK, and SWIG_TypeError.
Referenced by SWIG_AsPtr_std_string().
SWIG_AsPtr_std_string()
SWIGINTERN int SWIG_AsPtr_std_string (SEXP obj, std::string ** val)
Definition at line 1508 of file openMTPK_wrap.cpp.
 {
   char* buf = 0 ; size_t size = 0; int alloc = SWIG_OLDOBJ;
   if (SWIG_IsOK((SWIG_AsCharPtrAndSize(obj, &buf, &size, &alloc)))) {
     if (buf) {
       if (val) *val = new std::string(buf, size - 1);
       if (alloc == SWIG_NEWOBJ) delete[] buf;
       return SWIG_NEWOBJ;
     } else {
       if (val) *val = 0;
       return SWIG_OLDOBJ;
     }
   } else {
     static int init = 0;
     static swig_type_info* descriptor = 0;
     if (!init) {
       descriptor = SWIG_TypeQuery("std::string" " *");
       init = 1;
     }
     if (descriptor) {
       std::string *vptr;
       int res = SWIG_R_ConvertPtr(obj, (void**)&vptr, descriptor, 0);
       if (SWIG_IsOK(res) && val) *val = vptr;
       return res;
     }
   }
   return SWIG_ERROR;
 }
References init(), SWIG_AsCharPtrAndSize(), SWIG_ERROR, SWIG_IsOK, SWIG_NEWOBJ, SWIG_OLDOBJ, SWIG_R_ConvertPtr(), and SWIG_TypeQuery.
Referenced by R_swig_Cipher_C_cipher(), R_swig_Cipher_KC_cipher(), and R_swig_Cipher_KC_encode().
SWIG_AsVal_int()
SWIGINTERN int SWIG_AsVal_int (SEXP obj, int * val)
Definition at line 1427 of file openMTPK_wrap.cpp.
 {
   long v;
   int res = SWIG_AsVal_long (obj, &v);
   if (SWIG_IsOK(res)) {
     if ((v < INT_MIN || v > INT_MAX)) {
       return SWIG_OverflowError;
     } else {
       if (val) *val = static_cast< int >(v);
     }
   }
   return res;
 }
References SWIG_AsVal_long(), SWIG_IsOK, and SWIG_OverflowError.
Referenced by R_swig_Primality_ETF().
SWIG_AsVal_long()
SWIGINTERNINLINE int SWIG_AsVal_long (SEXP obj, long * val)
Definition at line 1402 of file openMTPK_wrap.cpp.
 {
    if (val) *val = Rf_asInteger(obj);
    return SWIG_OK;
 }
References SWIG_OK.
Referenced by R_swig_Primality_jacobian_number(), R_swig_Primality_mod_pow(), R_swig_Primality_pollard_rho(), R_swig_Primality_solovoy_strassen(), and SWIG_AsVal_int().
SWIG_Error()
SWIGRUNTIME void SWIG_Error (int code, const char * format, ...)
Definition at line 769 of file openMTPK_wrap.cpp.
{
   va_list arg;
   SWIG_lasterror_code = code;
   va_start(arg, format);
   vsnprintf(SWIG_lasterror_msg, sizeof(SWIG_lasterror_msg), format, arg);
   va_end(arg);
 }
References SWIG_lasterror_code, and SWIG_lasterror_msg.
SWIG_ErrorType()
SWIGRUNTIME const char* SWIG_ErrorType (int code)
Definition at line 777 of file openMTPK_wrap.cpp.
{
   switch (code) {
   case SWIG_MemoryError:
     return "SWIG:MemoryError";
   case SWIG_IOError:
     return "SWIG:IOError";
   case SWIG_RuntimeError:
     return "SWIG:RuntimeError";
   case SWIG_IndexError:
     return "SWIG:IndexError";
   case SWIG_TypeError:
     return "SWIG:TypeError";
   case SWIG_DivisionByZero:
     return "SWIG:DivisionByZero";
   case SWIG_OverflowError:
     return "SWIG:OverflowError";
   case SWIG_SyntaxError:
     return "SWIG:SyntaxError";
   case SWIG_ValueError:
     return "SWIG:ValueError";
   case SWIG_SystemError:
     return "SWIG:SystemError";
   case SWIG_AttributeError:
     return "SWIG:AttributeError";
   }
   return "SWIG:UnknownError";
 }
References SWIG_AttributeError, SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_MemoryError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, and SWIG_ValueError.
Referenced by R_swig_Basics_greatest_power(), R_swig_Basics_rm_gcd(), R_swig_Cipher_C_cipher(), R_swig_Cipher_KC_cipher(), R_swig_Cipher_KC_encode(), R_swig_delete_Basics(), R_swig_delete_Cipher(), R_swig_delete_Primality(), R_swig_delete_RC4(), R_swig_new_Basics(), R_swig_new_Cipher(), R_swig_new_Primality(), R_swig_new_RC4(), R_swig_Primality_carmichael_num(), R_swig_Primality_compute_miller_rabin(), R_swig_Primality_ETF(), R_swig_Primality_is_prime(), R_swig_Primality_jacobian_number(), R_swig_Primality_miller_rabin(), R_swig_Primality_miller_rabin_prime(), R_swig_Primality_mod_pow(), R_swig_Primality_pollard_rho(), R_swig_Primality_sieve_of_eratosthenes(), R_swig_Primality_solovoy_strassen(), R_swig_RC4_byte_swap(), R_swig_RC4_compute(), R_swig_RC4_KSA(), R_swig_RC4_PRGA(), R_swig_RC4_store_hash(), R_swig_RC4_trad_swap(), and R_swig_RC4_XOR_swap().
SWIG_From_long()
SWIGINTERNINLINE SEXP SWIG_From_long (long value)
Definition at line 1410 of file openMTPK_wrap.cpp.
 {
     return Rf_ScalarInteger((int)value);
 }
References value.
Referenced by R_swig_Primality_mod_pow(), and R_swig_Primality_pollard_rho().
SWIG_From_std_string()
SWIGINTERNINLINE SEXP SWIG_From_std_string (const std::string & s)
Definition at line 1476 of file openMTPK_wrap.cpp.
 {
   return SWIG_FromCharPtrAndSize(s.data(), s.size());
 }
References SWIG_FromCharPtrAndSize().
Referenced by R_swig_Cipher_C_cipher(), R_swig_Cipher_KC_cipher(), R_swig_Cipher_KC_encode(), and R_swig_RC4_store_hash().
SWIG_FromCharPtrAndSize()
SWIGINTERN SEXP SWIG_FromCharPtrAndSize (const char * carray, size_t size)
Definition at line 1451 of file openMTPK_wrap.cpp.
 {
   SEXP t, c;
   if (!carray) return R_NilValue;
 /* See R internals document 1.10.
    MkCharLen was introduced in 2.7.0.  Use that instead of hand
    creating vector.
    Starting in 2.8.0 creating strings via vectors was deprecated in
    order to allow for use of CHARSXP caches. */
   Rf_protect(t = Rf_allocVector(STRSXP, 1));
 #if R_VERSION >=  R_Version(2,7,0)
   c = Rf_mkCharLen(carray, size);
 #else
   c = Rf_allocVector(CHARSXP, size);
   strncpy((char *)CHAR(c), carray, size);
 #endif
   SET_STRING_ELT(t, 0, c);
   Rf_unprotect(1);
   return t;
 }
References Python.examples.cipher_ex::c.
Referenced by SWIG_From_std_string().
SWIG_GetModule()
SWIGRUNTIME swig_module_info* SWIG_GetModule (void * SWIGUNUSEDPARMclientdata)
Definition at line 1077 of file openMTPK_wrap.cpp.
{
   static void *type_pointer = (void *)0;
   return (swig_module_info *) type_pointer;
 }
Referenced by SWIG_InitializeModule().
SWIG_init()
SWIGEXPORT void SWIG_init (void)
Definition at line 3047 of file openMTPK_wrap.cpp.
{
 }
Referenced by R_init_openMTPK().
SWIG_InitializeModule()
SWIGRUNTIME void SWIG_InitializeModule (SWIG_INIT_CLIENT_DATA_TYPE clientdata)
Definition at line 2869 of file openMTPK_wrap.cpp.
{
   size_t i;
   swig_module_info *module_head, *iter;
   int init;
   /* check to see if the circular list has been setup, if not, set it up */
   if (swig_module.next==0) {
     /* Initialize the swig_module */
     swig_module.type_initial = swig_type_initial;
     swig_module.cast_initial = swig_cast_initial;
     swig_module.next = &swig_module;
     init = 1;
   } else {
     init = 0;
   }
   /* Try and load any already created modules */
   module_head = SWIG_GetModule(clientdata);
   if (!module_head) {
     /* This is the first module loaded for this interpreter */
     /* so set the swig module into the interpreter */
     SWIG_SetModule(clientdata, &swig_module);
   } else {
     /* the interpreter has loaded a SWIG module, but has it loaded this one? */
     iter=module_head;
     do {
       if (iter==&swig_module) {
         /* Our module is already in the list, so there's nothing more to do. */
         return;
       }
       iter=iter->next;
     } while (iter!= module_head);
     /* otherwise we must add our module into the list */
     swig_module.next = module_head->next;
     module_head->next = &swig_module;
   }
   /* When multiple interpreters are used, a module could have already been initialized in
      a different interpreter, but not yet have a pointer in this interpreter.
      In this case, we do not want to continue adding types... everything should be
      set up already */
   if (init == 0) return;
   /* Now work on filling in swig_module.types */
 #ifdef SWIGRUNTIME_DEBUG
   printf("SWIG_InitializeModule: size %lu\n", (unsigned long)swig_module.size);
 #endif
   for (i = 0; i < swig_module.size; ++i) {
     swig_type_info *type = 0;
     swig_type_info *ret;
     swig_cast_info *cast;
 #ifdef SWIGRUNTIME_DEBUG
     printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
 #endif
     /* if there is another module already loaded */
     if (swig_module.next != &swig_module) {
       type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
     }
     if (type) {
       /* Overwrite clientdata field */
 #ifdef SWIGRUNTIME_DEBUG
       printf("SWIG_InitializeModule: found type %s\n", type->name);
 #endif
       if (swig_module.type_initial[i]->clientdata) {
     type->clientdata = swig_module.type_initial[i]->clientdata;
 #ifdef SWIGRUNTIME_DEBUG
       printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
 #endif
       }
     } else {
       type = swig_module.type_initial[i];
     }
     /* Insert casting types */
     cast = swig_module.cast_initial[i];
     while (cast->type) {
       /* Don't need to add information already in the list */
       ret = 0;
 #ifdef SWIGRUNTIME_DEBUG
       printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
 #endif
       if (swig_module.next != &swig_module) {
         ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
 #ifdef SWIGRUNTIME_DEBUG
     if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
 #endif
       }
       if (ret) {
     if (type == swig_module.type_initial[i]) {
 #ifdef SWIGRUNTIME_DEBUG
       printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
 #endif
       cast->type = ret;
       ret = 0;
     } else {
       /* Check for casting already in the list */
       swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
 #ifdef SWIGRUNTIME_DEBUG
       if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
 #endif
       if (!ocast) ret = 0;
     }
       }
       if (!ret) {
 #ifdef SWIGRUNTIME_DEBUG
     printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
 #endif
         if (type->cast) {
           type->cast->prev = cast;
           cast->next = type->cast;
         }
         type->cast = cast;
       }
       cast++;
     }
     /* Set entry in modules->types array equal to the type */
     swig_module.types[i] = type;
   }
   swig_module.types[i] = 0;
 #ifdef SWIGRUNTIME_DEBUG
   printf("**** SWIG_InitializeModule: Cast List ******\n");
   for (i = 0; i < swig_module.size; ++i) {
     int j = 0;
     swig_cast_info *cast = swig_module.cast_initial[i];
     printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
     while (cast->type) {
       printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
       cast++;
       ++j;
     }
   printf("---- Total casts: %d\n",j);
   }
   printf("**** SWIG_InitializeModule: Cast List ******\n");
 #endif
 }
References swig_type_info::cast, swig_module_info::cast_initial, swig_type_info::clientdata, init(), swig_type_info::name, swig_cast_info::next, swig_module_info::next, swig_cast_info::prev, swig_module_info::size, swig_cast_initial, SWIG_GetModule(), SWIG_MangledTypeQueryModule(), swig_module, SWIG_SetModule(), swig_type_initial, SWIG_TypeCheck(), swig_cast_info::type, swig_module_info::type_initial, and swig_module_info::types.
Referenced by R_init_openMTPK().
SWIG_MakePtr()
SWIGRUNTIME SEXP SWIG_MakePtr (void * ptr, const char * typeName, int flags)
Definition at line 991 of file openMTPK_wrap.cpp.
 {
   SEXP external, r_obj;
   Rf_protect(external = R_MakeExternalPtr(ptr, Rf_install(typeName), R_NilValue));
   Rf_protect(r_obj = NEW_OBJECT(MAKE_CLASS((char *) typeName)));
   if (flags & SWIG_POINTER_OWN)
     R_RegisterCFinalizer(external, R_SWIG_ReferenceFinalizer);
   r_obj = SET_SLOT(r_obj, Rf_mkString((char *) "ref"), external);
   SET_S4_OBJECT(r_obj);
   Rf_unprotect(2);
   return(r_obj);
 }
References R_SWIG_ReferenceFinalizer(), and SWIG_POINTER_OWN.
SWIG_MangledTypeQueryModule()
SWIGRUNTIME swig_type_info* SWIG_MangledTypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
Definition at line 545 of file openMTPK_wrap.cpp.
{
   swig_module_info *iter = start;
   do {
     if (iter->size) {
       size_t l = 0;
       size_t r = iter->size - 1;
       do {
     /* since l+r >= 0, we can (>> 1) instead (/ 2) */
     size_t i = (l + r) >> 1;
     const char *iname = iter->types[i]->name;
     if (iname) {
       int compare = strcmp(name, iname);
       if (compare == 0) {
         return iter->types[i];
       } else if (compare < 0) {
         if (i) {
           r = i - 1;
         } else {
           break;
         }
       } else if (compare > 0) {
         l = i + 1;
       }
     } else {
       break; /* should never happen */
     }
       } while (l <= r);
     }
     iter = iter->next;
   } while (iter != end);
   return 0;
 }
References swig_type_info::name, setup::name, swig_module_info::next, Python.examples.rc4_ex::r, swig_module_info::size, and swig_module_info::types.
Referenced by SWIG_InitializeModule(), and SWIG_TypeQueryModule().
SWIG_PackData()
SWIGRUNTIME char* SWIG_PackData (char * c, void * ptr, size_t sz)
Definition at line 619 of file openMTPK_wrap.cpp.
{
   static const char hex[17] = "0123456789abcdef";
   const unsigned char *u = (unsigned char *) ptr;
   const unsigned char *eu =  u + sz;
   for (; u != eu; ++u) {
     unsigned char uu = *u;
     *(c++) = hex[(uu & 0xf0) >> 4];
     *(c++) = hex[uu & 0xf];
   }
   return c;
 }
References Python.examples.cipher_ex::c, and u.
Referenced by SWIG_PackDataName(), and SWIG_PackVoidPtr().
SWIG_PackDataName()
SWIGRUNTIME char* SWIG_PackDataName (char * buff, void * ptr, size_t sz, const char * name, size_t bsz)
Definition at line 687 of file openMTPK_wrap.cpp.
{
   char *r = buff;
   size_t lname = (name ? strlen(name) : 0);
   if ((2*sz + 2 + lname) > bsz) return 0;
   *(r++) = '_';
   r = SWIG_PackData(r,ptr,sz);
   if (lname) {
     strncpy(r,name,lname+1);
   } else {
     *r = 0;
   }
   return buff;
 }
References setup::name, Python.examples.rc4_ex::r, and SWIG_PackData().
SWIG_PackVoidPtr()
SWIGRUNTIME char* SWIG_PackVoidPtr (char * buff, void * ptr, const char * name, size_t bsz)
Definition at line 663 of file openMTPK_wrap.cpp.
{
   char *r = buff;
   if ((2*sizeof(void *) + 2) > bsz) return 0;
   *(r++) = '_';
   r = SWIG_PackData(r,&ptr,sizeof(void *));
   if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
   strcpy(r,name);
   return buff;
 }
References setup::name, Python.examples.rc4_ex::r, and SWIG_PackData().
SWIG_PropagateClientData()
SWIGRUNTIME void SWIG_PropagateClientData (void)
Definition at line 3017 of file openMTPK_wrap.cpp.
{
   size_t i;
   swig_cast_info *equiv;
   static int init_run = 0;
   if (init_run) return;
   init_run = 1;
   for (i = 0; i < swig_module.size; i++) {
     if (swig_module.types[i]->clientdata) {
       equiv = swig_module.types[i]->cast;
       while (equiv) {
         if (!equiv->converter) {
           if (equiv->type && !equiv->type->clientdata)
             SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
         }
         equiv = equiv->next;
       }
     }
   }
 }
References swig_type_info::cast, swig_type_info::clientdata, swig_cast_info::converter, swig_cast_info::next, swig_module_info::size, swig_module, SWIG_TypeClientData(), swig_cast_info::type, and swig_module_info::types.
SWIG_R_ConvertPacked()
SWIGRUNTIME int SWIG_R_ConvertPacked (SEXP obj, void * ptr, size_t sz, swig_type_info * ty)
Definition at line 1132 of file openMTPK_wrap.cpp.
{
   swig_type_info *to = RSwigPacked_UnpackData(obj, ptr, sz);
   if (!to) return SWIG_ERROR;
   if (ty) {
     if (to != ty) {
       /* check type cast? */
       swig_cast_info *tc = SWIG_TypeCheck(to->name,ty);
       if (!tc) return SWIG_ERROR;
     }
   }
   return SWIG_OK;
 }
References swig_type_info::name, RSwigPacked_UnpackData(), SWIG_ERROR, SWIG_OK, and SWIG_TypeCheck().
SWIG_R_ConvertPtr()
SWIGRUNTIMEINLINE int SWIG_R_ConvertPtr (SEXP obj, void ** ptr, swig_type_info * ty, int flags)
Definition at line 1050 of file openMTPK_wrap.cpp.
{
   void *vptr;
   if (!obj) return SWIG_ERROR;
   if (obj == R_NilValue) {
     if (ptr) *ptr = NULL;
     return (flags & SWIG_POINTER_NO_NULL) ? SWIG_NullReferenceError : SWIG_OK;
   }
   vptr = R_ExternalPtrAddr(obj);
   if (ty) {
     swig_type_info *to = (swig_type_info*)
       R_ExternalPtrAddr(R_ExternalPtrTag(obj));
     if (to == ty) {
       if (ptr) *ptr = vptr;
     } else {
       swig_cast_info *tc = SWIG_TypeCheck(to->name,ty);
       int newmemory = 0;
       if (ptr) *ptr = SWIG_TypeCast(tc,vptr,&newmemory);
       assert(!newmemory); /* newmemory handling not yet implemented */
     }
   } else {
       if (ptr) *ptr = vptr;
  }
   return SWIG_OK;
 }
References swig_type_info::name, SWIG_ERROR, SWIG_NullReferenceError, SWIG_OK, SWIG_POINTER_NO_NULL, SWIG_TypeCast(), and SWIG_TypeCheck().
Referenced by R_swig_Basics_greatest_power(), R_swig_Basics_rm_gcd(), R_swig_Cipher_C_cipher(), R_swig_Cipher_KC_cipher(), R_swig_Cipher_KC_encode(), R_swig_delete_Basics(), R_swig_delete_Cipher(), R_swig_delete_Primality(), R_swig_delete_RC4(), R_swig_Primality_carmichael_num(), R_swig_Primality_compute_miller_rabin(), R_swig_Primality_ETF(), R_swig_Primality_is_prime(), R_swig_Primality_jacobian_number(), R_swig_Primality_miller_rabin(), R_swig_Primality_miller_rabin_prime(), R_swig_Primality_mod_pow(), R_swig_Primality_pollard_rho(), R_swig_Primality_sieve_of_eratosthenes(), R_swig_Primality_solovoy_strassen(), R_swig_RC4_byte_swap(), R_swig_RC4_compute(), R_swig_RC4_KSA(), R_swig_RC4_PRGA(), R_swig_RC4_store_hash(), R_swig_RC4_trad_swap(), R_swig_RC4_XOR_swap(), and SWIG_AsPtr_std_string().
SWIG_R_NewPackedObj()
SWIGRUNTIMEINLINE SEXP SWIG_R_NewPackedObj (void * ptr, size_t sz, swig_type_info * type)
Definition at line 1125 of file openMTPK_wrap.cpp.
{
   return ptr ? RSwigPacked_New((void *) ptr, sz, type) : R_NilValue;
 }
References RSwigPacked_New().
SWIG_R_NewPointerObj()
SWIGRUNTIMEINLINE SEXP SWIG_R_NewPointerObj (void * ptr, swig_type_info * type, int flags)
Definition at line 1036 of file openMTPK_wrap.cpp.
{
   SEXP rptr;
   if (!ptr) {
      return R_NilValue;
   }
   rptr = R_MakeExternalPtr(ptr,
   R_MakeExternalPtr(type, R_NilValue, R_NilValue), R_NilValue);
   SET_S4_OBJECT(rptr);
   return rptr;
 }
Referenced by R_swig_new_Basics(), R_swig_new_Cipher(), R_swig_new_Primality(), R_swig_new_RC4(), and R_swig_RC4_compute().
SWIG_R_Raise()
SWIGINTERN void SWIG_R_Raise (SEXP obj, const char * msg)
Definition at line 1156 of file openMTPK_wrap.cpp.
{
   Rf_error(Rf_isString(obj) ? CHAR(Rf_asChar(obj)) : msg);
 }
SWIG_SetModule()
SWIGRUNTIME void SWIG_SetModule (void * v, swig_module_info * swig_module)
Definition at line 1083 of file openMTPK_wrap.cpp.
{
 }
Referenced by SWIG_InitializeModule().
SWIG_strdup()
SWIGINTERN char* SWIG_strdup (const char * str)
Definition at line 1443 of file openMTPK_wrap.cpp.
 {
   char *newstr = reinterpret_cast< char * >(malloc(strlen(str) + 1));
   return strcpy(newstr, str);
 }
Referenced by R_swig_RC4_compute(), R_swig_RC4_KSA(), R_swig_RC4_PRGA(), and R_swig_RC4_store_hash().
SWIG_TypeCast()
SWIGRUNTIMEINLINE void* SWIG_TypeCast (swig_cast_info * ty, void * ptr, int * newmemory)
Definition at line 463 of file openMTPK_wrap.cpp.
{
   return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
 }
References swig_cast_info::converter.
Referenced by SWIG_R_ConvertPtr().
SWIG_TypeCheck()
SWIGRUNTIME swig_cast_info* SWIG_TypeCheck (const char * c, swig_type_info * ty)
Definition at line 409 of file openMTPK_wrap.cpp.
{
   if (ty) {
     swig_cast_info *iter = ty->cast;
     while (iter) {
       if (strcmp(iter->type->name, c) == 0) {
         if (iter == ty->cast)
           return iter;
         /* Move iter to the top of the linked list */
         iter->prev->next = iter->next;
         if (iter->next)
           iter->next->prev = iter->prev;
         iter->next = ty->cast;
         iter->prev = 0;
         if (ty->cast) ty->cast->prev = iter;
         ty->cast = iter;
         return iter;
       }
       iter = iter->next;
     }
   }
   return 0;
 }
References Python.examples.cipher_ex::c, swig_type_info::cast, swig_type_info::name, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
Referenced by SWIG_InitializeModule(), SWIG_R_ConvertPacked(), and SWIG_R_ConvertPtr().
SWIG_TypeCheckStruct()
SWIGRUNTIME swig_cast_info* SWIG_TypeCheckStruct (const swig_type_info * from, swig_type_info * ty)
Definition at line 436 of file openMTPK_wrap.cpp.
{
   if (ty) {
     swig_cast_info *iter = ty->cast;
     while (iter) {
       if (iter->type == from) {
         if (iter == ty->cast)
           return iter;
         /* Move iter to the top of the linked list */
         iter->prev->next = iter->next;
         if (iter->next)
           iter->next->prev = iter->prev;
         iter->next = ty->cast;
         iter->prev = 0;
         if (ty->cast) ty->cast->prev = iter;
         ty->cast = iter;
         return iter;
       }
       iter = iter->next;
     }
   }
   return 0;
 }
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
SWIG_TypeClientData()
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info * ti, void * clientdata)
Definition at line 515 of file openMTPK_wrap.cpp.
{
   swig_cast_info *cast = ti->cast;
   /* if (ti->clientdata == clientdata) return; */
   ti->clientdata = clientdata;
   while (cast) {
     if (!cast->converter) {
       swig_type_info *tc = cast->type;
       if (!tc->clientdata) {
     SWIG_TypeClientData(tc, clientdata);
       }
     }
     cast = cast->next;
   }
 }
References swig_type_info::cast, swig_type_info::clientdata, swig_module_info::clientdata, swig_cast_info::converter, swig_cast_info::next, and swig_cast_info::type.
Referenced by SWIG_PropagateClientData(), and SWIG_TypeNewClientData().
SWIG_TypeCmp()
SWIGRUNTIME int SWIG_TypeCmp (const char * nb, const char * tb)
Definition at line 382 of file openMTPK_wrap.cpp.
{
   int equiv = 1;
   const char* te = tb + strlen(tb);
   const char* ne = nb;
   while (equiv != 0 && *ne) {
     for (nb = ne; *ne; ++ne) {
       if (*ne == '|') break;
     }
     equiv = SWIG_TypeNameComp(nb, ne, tb, te);
     if (*ne) ++ne;
   }
   return equiv;
 }
References SWIG_TypeNameComp().
Referenced by SWIG_TypeEquiv().
SWIG_TypeDynamicCast()
SWIGRUNTIME swig_type_info* SWIG_TypeDynamicCast (swig_type_info * ty, void ** ptr)
Definition at line 471 of file openMTPK_wrap.cpp.
{
   swig_type_info *lastty = ty;
   if (!ty || !ty->dcast) return ty;
   while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
   }
   return lastty;
 }
References swig_type_info::dcast.
SWIG_TypeEquiv()
SWIGRUNTIME int SWIG_TypeEquiv (const char * nb, const char * tb)
Definition at line 401 of file openMTPK_wrap.cpp.
{
   return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
 }
References SWIG_TypeCmp().
Referenced by SWIG_TypeQueryModule().
SWIG_TypeName()
SWIGRUNTIMEINLINE const char* SWIG_TypeName (const swig_type_info * ty)
Definition at line 485 of file openMTPK_wrap.cpp.
{
   return ty->name;
 }
References swig_type_info::name.
SWIG_TypeNameComp()
SWIGRUNTIME int SWIG_TypeNameComp (const char * f1, const char * l1, const char * f2, const char * l2)
Definition at line 367 of file openMTPK_wrap.cpp.
{
   for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
     while ((*f1 == ' ') && (f1 != l1)) ++f1;
     while ((*f2 == ' ') && (f2 != l2)) ++f2;
     if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
   }
   return (int)((l1 - f1) - (l2 - f2));
 }
Referenced by SWIG_TypeCmp().
SWIG_TypeNewClientData()
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info * ti, void * clientdata)
Definition at line 531 of file openMTPK_wrap.cpp.
{
   SWIG_TypeClientData(ti, clientdata);
   ti->owndata = 1;
 }
References swig_module_info::clientdata, swig_type_info::owndata, and SWIG_TypeClientData().
SWIG_TypePrettyName()
SWIGRUNTIME const char* SWIG_TypePrettyName (const swig_type_info * type)
Definition at line 494 of file openMTPK_wrap.cpp.
{
   /* The "str" field contains the equivalent pretty names of the
      type, separated by vertical-bar characters.  Choose the last
      name. It should be the most specific; a fully resolved name
      but not necessarily with default template parameters expanded. */
   if (!type) return NULL;
   if (type->str != NULL) {
     const char *last_name = type->str;
     const char *s;
     for (s = type->str; *s; s++)
       if (*s == '|') last_name = s+1;
     return last_name;
   }
   else
     return type->name;
 }
References swig_type_info::name, and swig_type_info::str.
SWIG_TypeQueryModule()
SWIGRUNTIME swig_type_info* SWIG_TypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
Definition at line 590 of file openMTPK_wrap.cpp.
{
   /* STEP 1: Search the name field using binary search */
   swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
   if (ret) {
     return ret;
   } else {
     /* STEP 2: If the type hasn't been found, do a complete search
        of the str field (the human readable name) */
     swig_module_info *iter = start;
     do {
       size_t i = 0;
       for (; i < iter->size; ++i) {
     if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
       return iter->types[i];
       }
       iter = iter->next;
     } while (iter != end);
   }
   /* neither found a match */
   return 0;
 }
References setup::name, swig_module_info::next, swig_module_info::size, swig_type_info::str, SWIG_MangledTypeQueryModule(), SWIG_TypeEquiv(), and swig_module_info::types.
SWIG_UnpackData()
SWIGRUNTIME const char* SWIG_UnpackData (const char * c, void * ptr, size_t sz)
Definition at line 635 of file openMTPK_wrap.cpp.
{
   unsigned char *u = (unsigned char *) ptr;
   const unsigned char *eu = u + sz;
   for (; u != eu; ++u) {
     char d = *(c++);
     unsigned char uu;
     if ((d >= '0') && (d <= '9'))
       uu = (unsigned char)((d - '0') << 4);
     else if ((d >= 'a') && (d <= 'f'))
       uu = (unsigned char)((d - ('a'-10)) << 4);
     else
       return (char *) 0;
     d = *(c++);
     if ((d >= '0') && (d <= '9'))
       uu |= (unsigned char)(d - '0');
     else if ((d >= 'a') && (d <= 'f'))
       uu |= (unsigned char)(d - ('a'-10));
     else
       return (char *) 0;
     *u = uu;
   }
   return c;
 }
References Python.examples.cipher_ex::c, and u.
Referenced by SWIG_UnpackDataName(), and SWIG_UnpackVoidPtr().
SWIG_UnpackDataName()
SWIGRUNTIME const char* SWIG_UnpackDataName (const char * c, void * ptr, size_t sz, const char * name)
Definition at line 702 of file openMTPK_wrap.cpp.
{
   if (*c != '_') {
     if (strcmp(c,"NULL") == 0) {
       memset(ptr,0,sz);
       return name;
     } else {
       return 0;
     }
   }
   return SWIG_UnpackData(++c,ptr,sz);
 }
References Python.examples.cipher_ex::c, setup::name, and SWIG_UnpackData().
SWIG_UnpackVoidPtr()
SWIGRUNTIME const char* SWIG_UnpackVoidPtr (const char * c, void ** ptr, const char * name)
Definition at line 674 of file openMTPK_wrap.cpp.
{
   if (*c != '_') {
     if (strcmp(c,"NULL") == 0) {
       *ptr = (void *) 0;
       return name;
     } else {
       return 0;
     }
   }
   return SWIG_UnpackData(++c,ptr,sizeof(void *));
 }
References Python.examples.cipher_ex::c, setup::name, and SWIG_UnpackData().
Variable Documentation
_swigc__p_Basics
swig_cast_info _swigc__p_Basics[] = { {&_swigt__p_Basics, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2790 of file openMTPK_wrap.cpp.
_swigc__p_char
swig_cast_info _swigc__p_char[] = { {&_swigt__p_char, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2794 of file openMTPK_wrap.cpp.
_swigc__p_Cipher
swig_cast_info _swigc__p_Cipher[] = { {&_swigt__p_Cipher, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2791 of file openMTPK_wrap.cpp.
_swigc__p_Primality
swig_cast_info _swigc__p_Primality[] = { {&_swigt__p_Primality, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2792 of file openMTPK_wrap.cpp.
_swigc__p_RC4
swig_cast_info _swigc__p_RC4[] = { {&_swigt__p_RC4, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2793 of file openMTPK_wrap.cpp.
_swigc__p_uint8_t
swig_cast_info _swigc__p_uint8_t[] = { {&_swigt__p_uint8_t, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2795 of file openMTPK_wrap.cpp.
_swigc__p_unsigned_char
swig_cast_info _swigc__p_unsigned_char[] = { {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}} static
Definition at line 2796 of file openMTPK_wrap.cpp.
_swigt__p_Basics
swig_type_info _swigt__p_Basics = {"_p_Basics", "Basics *", 0, 0, (void*)0, 0} static
Definition at line 2772 of file openMTPK_wrap.cpp.
_swigt__p_char
swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0} static
Definition at line 2776 of file openMTPK_wrap.cpp.
_swigt__p_Cipher
swig_type_info _swigt__p_Cipher = {"_p_Cipher", "Cipher *", 0, 0, (void*)0, 0} static
Definition at line 2773 of file openMTPK_wrap.cpp.
_swigt__p_Primality
swig_type_info _swigt__p_Primality = {"_p_Primality", "Primality *", 0, 0, (void*)0, 0} static
Definition at line 2774 of file openMTPK_wrap.cpp.
_swigt__p_RC4
swig_type_info _swigt__p_RC4 = {"_p_RC4", "RC4 *", 0, 0, (void*)0, 0} static
Definition at line 2775 of file openMTPK_wrap.cpp.
_swigt__p_uint8_t
swig_type_info _swigt__p_uint8_t = {"_p_uint8_t", "uint8_t *", 0, 0, (void*)0, 0} static
Definition at line 2777 of file openMTPK_wrap.cpp.
_swigt__p_unsigned_char
swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "unsigned char *", 0, 0, (void*)0, 0} static
Definition at line 2778 of file openMTPK_wrap.cpp.
callbackFunctionDataStack
RCallbackFunctionData* callbackFunctionDataStack static
Definition at line 829 of file openMTPK_wrap.cpp.
Referenced by R_SWIG_debug_getCallbackFunctionData(), R_SWIG_getCallbackFunctionData(), R_SWIG_popCallbackFunctionData(), and R_SWIG_pushCallbackFunctionData().
CallEntries
SWIGINTERN R_CallMethodDef CallEntries[]
Definition at line 3060 of file openMTPK_wrap.cpp.
Referenced by R_init_openMTPK().
swig_cast_initial
swig_cast_info* swig_cast_initial[] static
Initial value:
= {
  _swigc__p_Basics,
  _swigc__p_Cipher,
  _swigc__p_Primality,
  _swigc__p_RC4,
  _swigc__p_char,
  _swigc__p_uint8_t,
  _swigc__p_unsigned_char,
}
Definition at line 2798 of file openMTPK_wrap.cpp.
Referenced by SWIG_InitializeModule().
SWIG_lasterror_code
int SWIG_lasterror_code = 0 static
Definition at line 767 of file openMTPK_wrap.cpp.
Referenced by R_swig_Basics_greatest_power(), R_swig_Basics_rm_gcd(), R_swig_Cipher_C_cipher(), R_swig_Cipher_KC_cipher(), R_swig_Cipher_KC_encode(), R_swig_delete_Basics(), R_swig_delete_Cipher(), R_swig_delete_Primality(), R_swig_delete_RC4(), R_swig_new_Basics(), R_swig_new_Cipher(), R_swig_new_Primality(), R_swig_new_RC4(), R_swig_Primality_carmichael_num(), R_swig_Primality_compute_miller_rabin(), R_swig_Primality_ETF(), R_swig_Primality_is_prime(), R_swig_Primality_jacobian_number(), R_swig_Primality_miller_rabin(), R_swig_Primality_miller_rabin_prime(), R_swig_Primality_mod_pow(), R_swig_Primality_pollard_rho(), R_swig_Primality_sieve_of_eratosthenes(), R_swig_Primality_solovoy_strassen(), R_swig_RC4_byte_swap(), R_swig_RC4_compute(), R_swig_RC4_KSA(), R_swig_RC4_PRGA(), R_swig_RC4_store_hash(), R_swig_RC4_trad_swap(), R_swig_RC4_XOR_swap(), and SWIG_Error().
SWIG_lasterror_msg
char SWIG_lasterror_msg[1024] static
Definition at line 768 of file openMTPK_wrap.cpp.
Referenced by R_swig_Basics_greatest_power(), R_swig_Basics_rm_gcd(), R_swig_Cipher_C_cipher(), R_swig_Cipher_KC_cipher(), R_swig_Cipher_KC_encode(), R_swig_delete_Basics(), R_swig_delete_Cipher(), R_swig_delete_Primality(), R_swig_delete_RC4(), R_swig_new_Basics(), R_swig_new_Cipher(), R_swig_new_Primality(), R_swig_new_RC4(), R_swig_Primality_carmichael_num(), R_swig_Primality_compute_miller_rabin(), R_swig_Primality_ETF(), R_swig_Primality_is_prime(), R_swig_Primality_jacobian_number(), R_swig_Primality_miller_rabin(), R_swig_Primality_miller_rabin_prime(), R_swig_Primality_mod_pow(), R_swig_Primality_pollard_rho(), R_swig_Primality_sieve_of_eratosthenes(), R_swig_Primality_solovoy_strassen(), R_swig_RC4_byte_swap(), R_swig_RC4_compute(), R_swig_RC4_KSA(), R_swig_RC4_PRGA(), R_swig_RC4_store_hash(), R_swig_RC4_trad_swap(), R_swig_RC4_XOR_swap(), and SWIG_Error().
swig_module
swig_module_info swig_module = {swig_types, 7, 0, 0, 0, 0} static
Definition at line 1182 of file openMTPK_wrap.cpp.
Referenced by SWIG_InitializeModule(), and SWIG_PropagateClientData().
swig_type_initial
swig_type_info* swig_type_initial[] static
Initial value:
= {
  &_swigt__p_Basics,
  &_swigt__p_Cipher,
  &_swigt__p_Primality,
  &_swigt__p_RC4,
  &_swigt__p_char,
  &_swigt__p_uint8_t,
  &_swigt__p_unsigned_char,
}
Definition at line 2780 of file openMTPK_wrap.cpp.
Referenced by SWIG_InitializeModule().
swig_types
swig_type_info* swig_types[8] static
Definition at line 1181 of file openMTPK_wrap.cpp.