openGPMP: modules/complex/openGL_example00.c File Reference
openGL_example00.c File Reference
#include <GL/glut.h>
#include <math.h>
#include <stdio.h>
Macros
#define pi 3.142857
Functions
void myInit (void)
void display (void)
int main (int argc, char **argv)
Macro Definition Documentation
pi
#define pi 3.142857
Definition at line 8 of file openGL_example00.c.
Function Documentation
display()
void display (void)
Definition at line 29 of file openGL_example00.c.
                    {
     glClear(GL_COLOR_BUFFER_BIT);
     glBegin(GL_POINTS);
     float x, y, i;
     // iterate y up to 2*pi, i.e., 360 degree
     // with small increment in angle as
     // glVertex2i just draws a point on specified co-ordinate
     for (i = 0; i < (2 * pi); i += 0.001) {
         // let 200 is radius of circle and as,
         // circle is defined as x=r*cos(i) and y=r*sin(i)
         x = 200 * cos(i);
         y = 200 * sin(i);
         glVertex2i(x, y);
     }
     glEnd();
     glFlush();
 }
References pi.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 49 of file openGL_example00.c.
{
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
     // giving window size in X- and Y- direction
     glutInitWindowSize(1366, 768);
     glutInitWindowPosition(0, 0);
     // Giving name to window
     glutCreateWindow("Circle Drawing");
     myInit();
     glutDisplayFunc(display);
     glutMainLoop();
 }
References display(), and myInit().
myInit()
void myInit (void)
Definition at line 11 of file openGL_example00.c.
                   {
     // making background color black as first
     // 3 arguments all are 0.0
     glClearColor(0.0, 0.0, 0.0, 1.0);
     // making picture color green (in RGB mode), as middle argument
     // is 1.0
     glColor3f(0.0, 1.0, 0.0);
     // breadth of picture boundary is 1 pixel
     glPointSize(1.0);
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     // setting window dimension in X- and Y- direction
     gluOrtho2D(-780, 780, -420, 420);
 }
Referenced by main().