openMTPK: modules/nt/rc5.cpp File Reference
rc5.cpp File Reference
#include <stdint.h>
#include <string.h>
#include <math.h>
#include "../../include/number_theory/rc5.hpp"
Functions
uint32_t shift_left (uint32_t v, uint32_t n)
uint32_t shift_right (uint32_t v, uint32_t n)
uint32_t rotate_left (uint32_t v, uint32_t n)
uint32_t rotate_right (uint32_t v, uint32_t n)
void encrypt (uint32_t S[26], uint32_t inout[4])
void decrypt (uint32_t S[26], uint32_t inout[4])
void expand (uint32_t L[4], uint32_t S[26])
int test (uint32_t S[26], uint32_t messg[4])
Function Documentation
decrypt()
void decrypt (uint32_t S[26], uint32_t inout[4])
Definition at line 21 of file rc5.cpp.
{
 }
encrypt()
void encrypt (uint32_t S[26], uint32_t inout[4])
Definition at line 18 of file rc5.cpp.
{
 }
expand()
void expand (uint32_t L[4], uint32_t S[26])
Definition at line 25 of file rc5.cpp.
{
 }
rotate_left()
uint32_t rotate_left (uint32_t v, uint32_t n)
Definition at line 12 of file rc5.cpp.
{
 }
rotate_right()
uint32_t rotate_right (uint32_t v, uint32_t n)
Definition at line 15 of file rc5.cpp.
{
 }
shift_left()
uint32_t shift_left (uint32_t v, uint32_t n)
Definition at line 6 of file rc5.cpp.
{
 }
shift_right()
uint32_t shift_right (uint32_t v, uint32_t n)
Definition at line 9 of file rc5.cpp.
{
 }
test()
int test (uint32_t S[26], uint32_t messg[4])
Definition at line 29 of file rc5.cpp.
{
 }
Referenced by euclideanDistance(), fillDistances(), KNN(), main(), and manhattanDistance().