openMTPK: openmtpk::primality Interface Reference
openmtpk::primality Interface Reference
Public Member Functions
procedure is_prime => swigf_primality_is_prime
procedure compute_miller_rabin => swigf_primality_compute_miller_rabin
procedure miller_rabin_prime => swigf_primality_miller_rabin_prime
procedure miller_rabin => swigf_primality_miller_rabin
procedure jacobian_number => swigf_primality_jacobian_number
procedure solovoy_strassen => swigf_primality_solovoy_strassen
procedure mod_pow => swigf_primality_mod_pow
procedure carmichael_num => swigf_primality_carmichael_num
procedure sieve_of_eratosthenes => swigf_primality_sieve_of_eratosthenes
procedure pollard_rho => swigf_primality_pollard_rho
procedure etf => swigf_primality_etf
procedure release => swigf_primality_release
generic assignment => swigf_primality_op_assign__
Public Attributes
type(swigclasswrapper), public swigdata
Private Member Functions
procedure, private swigf_primality_op_assign__
type(primality) function swigf_new_primality ()
Detailed Description
Definition at line 20 of file openMTPK.f90.
Member Function/Subroutine Documentation
assignment()
generic openmtpk::primality::assignment
Definition at line 36 of file openMTPK.f90.
References openmtpk::get_bits(), openmtpk::get_byte_limit(), and openmtpk::swigf_primality_op_assign__().
carmichael_num()
procedure openmtpk::primality::carmichael_num
Definition at line 30 of file openMTPK.f90.
compute_miller_rabin()
procedure openmtpk::primality::compute_miller_rabin
Definition at line 24 of file openMTPK.f90.
etf()
procedure openmtpk::primality::etf
Definition at line 33 of file openMTPK.f90.
is_prime()
procedure openmtpk::primality::is_prime
Definition at line 23 of file openMTPK.f90.
jacobian_number()
procedure openmtpk::primality::jacobian_number
Definition at line 27 of file openMTPK.f90.
miller_rabin()
procedure openmtpk::primality::miller_rabin
Definition at line 26 of file openMTPK.f90.
miller_rabin_prime()
procedure openmtpk::primality::miller_rabin_prime
Definition at line 25 of file openMTPK.f90.
mod_pow()
procedure openmtpk::primality::mod_pow
Definition at line 29 of file openMTPK.f90.
pollard_rho()
procedure openmtpk::primality::pollard_rho
Definition at line 32 of file openMTPK.f90.
release()
procedure openmtpk::primality::release
Definition at line 34 of file openMTPK.f90.
sieve_of_eratosthenes()
procedure openmtpk::primality::sieve_of_eratosthenes
Definition at line 31 of file openMTPK.f90.
solovoy_strassen()
procedure openmtpk::primality::solovoy_strassen
Definition at line 28 of file openMTPK.f90.
swigf_new_primality()
type(primality) function openmtpk::primality::swigf_new_primality private
Definition at line 607 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 type(Primality) :: self
 type(SwigClassWrapper) :: fresult
 fresult = swigc_new_primality()
 self%swigdata = fresult
swigf_primality_op_assign__()
procedure, private openmtpk::primality::swigf_primality_op_assign__ private
Definition at line 35 of file openMTPK.f90.
Member Data Documentation
swigdata
type(swigclasswrapper), public openmtpk::primality::swigdata
Definition at line 21 of file openMTPK.f90.
   type(SwigClassWrapper), public :: swigdata
The documentation for this interface was generated from the following file:
Fortran/lib/openMTPK.f90