openMTPK: swig::DestructorPolicy< T, A > Struct Template Reference
swig::DestructorPolicy< T, A > Struct Template Reference
Static Public Member Functions
static SwigClassWrapper destroy (SwigClassWrapper self)
Detailed Description
template<class T, AssignmentType A>
struct swig::DestructorPolicy< T, A >
Definition at line 267 of file openMTPK_wrap.cxx.
Member Function Documentation
destroy()
template<class T , AssignmentType A> static SwigClassWrapper swig::DestructorPolicy< T, A >::destroy (SwigClassWrapper self) inline static
Definition at line 268 of file openMTPK_wrap.cxx.
{
     delete static_cast<T*>(self.cptr);
     return SwigClassWrapper_uninitialized();
   }
References SwigClassWrapper_uninitialized().
Referenced by swig::AssignmentPolicy< T, A >::destroy(), and swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::destroy().
The documentation for this struct was generated from the following file:
Fortran/lib/openMTPK_wrap.cxx