openGPMP: gpmp::mtx< T > Struct Template Reference
gpmp::mtx< T > Struct Template Reference
Matrix struct.
#include <matrix.hpp>
Static Public Member Functions
static Matrix< T > zeros (size_t rows, size_t cols)
Matrix zeros method.
static Matrix< T > ones (size_t rows, size_t cols)
static Matrix< T > randn (size_t rows, size_t cols)
static Matrix< T > rand (size_t rows, size_t cols)
Detailed Description
template<typename T>
struct gpmp::mtx< T >
Matrix struct.
Definition at line 406 of file matrix.hpp.
Member Function Documentation
ones()
template<typename T > static Matrix<T> gpmp::mtx< T >::ones (size_t rows, size_t cols) inline static
Examples
linalg_ops.cpp.
Definition at line 417 of file matrix.hpp.
{
         Matrix<T> MTX{rows, cols};
         MTX.fill_index(T(1));
         return MTX;
     }
References gpmp::Matrix< Type >::fill_index().
Referenced by main().
rand()
template<typename T > static Matrix<T> gpmp::mtx< T >::rand (size_t rows, size_t cols) inline static
Examples
linalg_ops.cpp.
Definition at line 439 of file matrix.hpp.
{
         Matrix<T> MTX{rows, cols};
         std::random_device rd{};
         std::mt19937 gen{rd()};
         std::uniform_real_distribution<T> d{0, 1};
         for (size_t r = 0; r < rows; ++r) {
             for (int64_t c = 0; c < cols; ++c) {
                 MTX(r, c) = d(gen);
             }
         }
         return MTX;
     }
Referenced by main().
randn()
template<typename T > static Matrix<T> gpmp::mtx< T >::randn (size_t rows, size_t cols) inline static
Examples
linalg_ops.cpp.
Definition at line 423 of file matrix.hpp.
{
         Matrix<T> MTX{rows, cols};
         std::random_device rd{};
         std::mt19937 gen{rd()};
         T n(MTX.num_elements);
         T stdev{1 / sqrt(n)};
         std::normal_distribution<T> d{0, stdev};
         for (size_t r = 0; r < rows; ++r) {
             for (uint64_t c = 0; c < cols; ++c) {
                 MTX(r, c) = d(gen);
             }
         }
         return MTX;
     }
Referenced by main(), and gpmp::ml::SecondaryMLP< T >::SecondaryMLP().
zeros()
template<typename T > static Matrix<T> gpmp::mtx< T >::zeros (size_t rows, size_t cols) inline static
Matrix zeros method.
Examples
linalg_ops.cpp.
Definition at line 410 of file matrix.hpp.
{
         Matrix<T> MTX{rows, cols};
         // fill by index
         MTX.fill_index(T(0));
         return MTX;
     }
References gpmp::Matrix< Type >::fill_index().
Referenced by main().
The documentation for this struct was generated from the following file:
include/linalg/matrix.hpp