openMTPK: swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR > Struct Template Reference
swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR > Struct Template Reference
Static Public Member Functions
static SwigClassWrapper destroy (SwigClassWrapper self)
static SwigClassWrapper alias (SwigClassWrapper other)
static SwigClassWrapper move_alias (SwigClassWrapper self, SwigClassWrapper other)
static SwigClassWrapper copy_alias (SwigClassWrapper self, SwigClassWrapper other)
Detailed Description
template<class T>
struct swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >
Definition at line 314 of file openMTPK_wrap.cxx.
Member Function Documentation
alias()
template<class T > static SwigClassWrapper swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::alias (SwigClassWrapper other) inline static
Definition at line 318 of file openMTPK_wrap.cxx.
{
     SwigClassWrapper self;
     self.cptr = new T(*static_cast<T*>(other.cptr));
     self.cmemflags = other.cmemflags | SWIG_MEM_OWN;
     return self;
   }
References SwigClassWrapper::cmemflags, SwigClassWrapper::cptr, and SWIG_MEM_OWN.
copy_alias()
template<class T > static SwigClassWrapper swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::copy_alias (SwigClassWrapper self, SwigClassWrapper other) inline static
Definition at line 330 of file openMTPK_wrap.cxx.
{
     // LHS and RHS should both 'own' their shared pointers
     T *pself = static_cast<T*>(self.cptr);
     T *pother = static_cast<T*>(other.cptr);
     *pself = *pother;
     return self;
   }
References SwigClassWrapper::cptr.
destroy()
template<class T > static SwigClassWrapper swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::destroy (SwigClassWrapper self) inline static
Definition at line 315 of file openMTPK_wrap.cxx.
{
     return DestructorPolicy<T, ASSIGNMENT_SMARTPTR>::destroy(self);
   }
References swig::DestructorPolicy< T, A >::destroy().
move_alias()
template<class T > static SwigClassWrapper swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::move_alias (SwigClassWrapper self, SwigClassWrapper other) inline static
Definition at line 324 of file openMTPK_wrap.cxx.
{
     self = copy_alias(self, other);
     self.cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
     destroy(other);
     return self;
   }
References SwigClassWrapper::cmemflags, swig::AssignmentPolicy< T, A >::copy_alias(), swig::AssignmentPolicy< T, A >::destroy(), and SWIG_MEM_RVALUE.
The documentation for this struct was generated from the following file:
Fortran/lib/openMTPK_wrap.cxx