openMTPK: openmtpk::cipher Interface Reference
openmtpk::cipher Interface Reference
Public Member Functions
procedure c_cipher => swigf_cipher_c_cipher
procedure kc_encode => swigf_cipher_kc_encode
procedure kc_cipher => swigf_cipher_kc_cipher
procedure release => swigf_cipher_release
generic assignment => swigf_cipher_op_assign__
Public Attributes
type(swigclasswrapper), public swigdata
Private Member Functions
procedure, private swigf_cipher_op_assign__
type(cipher) function swigf_new_cipher ()
Detailed Description
Definition at line 66 of file openMTPK.f90.
Member Function/Subroutine Documentation
assignment()
generic openmtpk::cipher::assignment
Definition at line 74 of file openMTPK.f90.
References openmtpk::swigf_cipher_op_assign__(), openmtpk::swigf_new_cipher(), openmtpk::swigf_new_primality(), and openmtpk::swigf_new_rc4().
c_cipher()
procedure openmtpk::cipher::c_cipher
Definition at line 69 of file openMTPK.f90.
kc_cipher()
procedure openmtpk::cipher::kc_cipher
Definition at line 71 of file openMTPK.f90.
kc_encode()
procedure openmtpk::cipher::kc_encode
Definition at line 70 of file openMTPK.f90.
release()
procedure openmtpk::cipher::release
Definition at line 72 of file openMTPK.f90.
swigf_cipher_op_assign__()
procedure, private openmtpk::cipher::swigf_cipher_op_assign__ private
Definition at line 73 of file openMTPK.f90.
swigf_new_cipher()
type(cipher) function openmtpk::cipher::swigf_new_cipher private
Definition at line 931 of file openMTPK.f90.
 use, intrinsic :: iso_c_binding
 type(Cipher) :: self
 type(SwigClassWrapper) :: fresult
 fresult = swigc_new_cipher()
 self%swigdata = fresult
Member Data Documentation
swigdata
type(swigclasswrapper), public openmtpk::cipher::swigdata
Definition at line 67 of file openMTPK.f90.
   type(SwigClassWrapper), public :: swigdata
The documentation for this interface was generated from the following file:
Fortran/lib/openMTPK.f90