openMTPK: swig::AssignmentPolicy< T, A > Struct Template Reference
swig::AssignmentPolicy< T, A > Struct Template Reference
Static Public Member Functions
static SwigClassWrapper destroy (SwigClassWrapper self)
static SwigClassWrapper alias (SwigClassWrapper other)
static SwigClassWrapper move_alias (SwigClassWrapper self, SwigClassWrapper other)
static SwigClassWrapper copy_alias (SwigClassWrapper self, SwigClassWrapper other)
Detailed Description
template<class T, AssignmentType A>
struct swig::AssignmentPolicy< T, A >
Definition at line 290 of file openMTPK_wrap.cxx.
Member Function Documentation
alias()
template<class T , AssignmentType A> static SwigClassWrapper swig::AssignmentPolicy< T, A >::alias (SwigClassWrapper other) inline static
Definition at line 294 of file openMTPK_wrap.cxx.
{
     SwigClassWrapper self = other;
     self.cmemflags &= ~SWIG_MEM_OWN;
     return self;
   }
References SwigClassWrapper::cmemflags, and SWIG_MEM_OWN.
copy_alias()
template<class T , AssignmentType A> static SwigClassWrapper swig::AssignmentPolicy< T, A >::copy_alias (SwigClassWrapper self, SwigClassWrapper other) inline static
Definition at line 305 of file openMTPK_wrap.cxx.
{
     if (self.cmemflags & SWIG_MEM_OWN) {
       destroy(self);
     }
     return capture(other);
   }
References swig::capture(), swig::AssignmentPolicy< T, A >::destroy(), and SWIG_MEM_OWN.
Referenced by swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::move_alias().
destroy()
template<class T , AssignmentType A> static SwigClassWrapper swig::AssignmentPolicy< T, A >::destroy (SwigClassWrapper self) inline static
Definition at line 291 of file openMTPK_wrap.cxx.
{
     return DestructorPolicy<T, A>::destroy(self);
   }
References swig::DestructorPolicy< T, A >::destroy().
Referenced by swig::AssignmentPolicy< T, A >::copy_alias(), swig::AssignmentPolicy< T, A >::move_alias(), and swig::AssignmentPolicy< T, ASSIGNMENT_SMARTPTR >::move_alias().
move_alias()
template<class T , AssignmentType A> static SwigClassWrapper swig::AssignmentPolicy< T, A >::move_alias (SwigClassWrapper self, SwigClassWrapper other) inline static
Definition at line 299 of file openMTPK_wrap.cxx.
{
     if (self.cmemflags & SWIG_MEM_OWN) {
       destroy(self);
     }
     return capture(other);
   }
References swig::capture(), swig::AssignmentPolicy< T, A >::destroy(), and SWIG_MEM_OWN.
The documentation for this struct was generated from the following file:
Fortran/lib/openMTPK_wrap.cxx