/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: linalg/linalg.i

package linalg

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
extern void _wrap_Swig_free_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_linalg_52140ac0f9bac946(swig_intgo arg1);
extern swig_type_1 _wrap_Vectors_add_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_2 arg2, swig_type_3 arg3);
extern void _wrap_delete_Vectors_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_Matrix_data_set_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Matrix_data_get_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_Matrix_dim_set_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Matrix_dim_get_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_Matrix_num_elements_set_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_4 arg2);
extern swig_type_5 _wrap_Matrix_num_elements_get_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_new_Matrix__SWIG_0_linalg_52140ac0f9bac946(swig_type_6 arg1, swig_type_7 arg2);
extern uintptr_t _wrap_new_Matrix__SWIG_1_linalg_52140ac0f9bac946(void);
extern uintptr_t _wrap_Matrix_mult_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Matrix_scalar_mult_linalg_52140ac0f9bac946(uintptr_t arg1, double arg2);
extern uintptr_t _wrap_Matrix_mult_elem_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Matrix_sqr_err_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_add_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Matrix___add___linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Matrix_scalar_add_linalg_52140ac0f9bac946(uintptr_t arg1, double arg2);
extern uintptr_t _wrap_Matrix_sub_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_Matrix_all_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_transpose_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_T_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_sum__SWIG_0_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_sum__SWIG_1_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_8 arg2);
extern uintptr_t _wrap_Matrix_mean__SWIG_0_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_mean__SWIG_1_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_9 arg2);
extern uintptr_t _wrap_Matrix_concatenate_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2, swig_type_10 arg3);
extern uintptr_t _wrap_Matrix_diag_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_Matrix_apply_func_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_Matrix_print_shape_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_Matrix_print_mtx_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_Matrix_fill_index_linalg_52140ac0f9bac946(uintptr_t arg1, double arg2);
extern void _wrap_delete_Matrix_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_MatrixI_data_set_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_MatrixI_data_get_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_MatrixI_dim_set_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_MatrixI_dim_get_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_MatrixI_num_elements_set_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_11 arg2);
extern swig_type_12 _wrap_MatrixI_num_elements_get_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_new_MatrixI__SWIG_0_linalg_52140ac0f9bac946(swig_type_13 arg1, swig_type_14 arg2);
extern uintptr_t _wrap_new_MatrixI__SWIG_1_linalg_52140ac0f9bac946(void);
extern uintptr_t _wrap_MatrixI_mult_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_MatrixI_scalar_mult_linalg_52140ac0f9bac946(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_MatrixI_mult_elem_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_MatrixI_sqr_err_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_add_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_MatrixI___add___linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_MatrixI_scalar_add_linalg_52140ac0f9bac946(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_MatrixI_sub_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_MatrixI_all_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_transpose_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_T_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_sum__SWIG_0_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_sum__SWIG_1_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_15 arg2);
extern uintptr_t _wrap_MatrixI_mean__SWIG_0_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_mean__SWIG_1_linalg_52140ac0f9bac946(uintptr_t arg1, swig_type_16 arg2);
extern uintptr_t _wrap_MatrixI_concatenate_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2, swig_type_17 arg3);
extern uintptr_t _wrap_MatrixI_diag_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_MatrixI_apply_func_linalg_52140ac0f9bac946(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_MatrixI_print_shape_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_MatrixI_print_mtx_linalg_52140ac0f9bac946(uintptr_t arg1);
extern void _wrap_MatrixI_fill_index_linalg_52140ac0f9bac946(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_MatrixI_linalg_52140ac0f9bac946(uintptr_t arg1);
extern uintptr_t _wrap_mtx_zeros_linalg_52140ac0f9bac946(swig_type_18 arg1, swig_type_19 arg2);
extern uintptr_t _wrap_mtx_ones_linalg_52140ac0f9bac946(swig_type_20 arg1, swig_type_21 arg2);
extern uintptr_t _wrap_mtx_randn_linalg_52140ac0f9bac946(swig_type_22 arg1, swig_type_23 arg2);
extern uintptr_t _wrap_mtx_rand_linalg_52140ac0f9bac946(swig_type_24 arg1, swig_type_25 arg2);
extern void _wrap_delete_mtx_linalg_52140ac0f9bac946(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

//export cgo_panic__linalg_52140ac0f9bac946
func cgo_panic__linalg_52140ac0f9bac946(p *byte) {
	s := (*[1024]byte)(unsafe.Pointer(p))[:]
	for i, b := range s {
		if b == 0 {
			panic(string(s[:i]))
		}
	}
	panic(string(s))
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_linalg_52140ac0f9bac946(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrVectors uintptr

func (p SwigcptrVectors) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVectors) SwigIsVectors() {
}

func (arg1 SwigcptrVectors) Add(arg2 int64, arg3 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int64)(C._wrap_Vectors_add_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_2(_swig_i_1), C.swig_type_3(_swig_i_2)))
	return swig_r
}

func DeleteVectors(arg1 Vectors) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Vectors_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

type Vectors interface {
	Swigcptr() uintptr
	SwigIsVectors()
	Add(arg2 int64, arg3 int64) (_swig_ret int64)
}

type SwigcptrMatrix uintptr

func (p SwigcptrMatrix) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMatrix) SwigIsMatrix() {
}

func (arg1 SwigcptrMatrix) SetData(arg2 Std_vector_Sl_double_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_Matrix_data_set_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMatrix) GetData() (_swig_ret Std_vector_Sl_double_Sg_) {
	var swig_r Std_vector_Sl_double_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_double_Sg_)(SwigcptrStd_vector_Sl_double_Sg_(C._wrap_Matrix_data_get_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) SetDim(arg2 Std_tuple_Sl_size_t_Sc_size_t_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_Matrix_dim_set_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMatrix) GetDim() (_swig_ret Std_tuple_Sl_size_t_Sc_size_t_Sg_) {
	var swig_r Std_tuple_Sl_size_t_Sc_size_t_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_tuple_Sl_size_t_Sc_size_t_Sg_)(SwigcptrStd_tuple_Sl_size_t_Sc_size_t_Sg_(C._wrap_Matrix_dim_get_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) SetNum_elements(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Matrix_num_elements_set_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrMatrix) GetNum_elements() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Matrix_num_elements_get_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewMatrix__SWIG_0(arg1 int64, arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_new_Matrix__SWIG_0_linalg_52140ac0f9bac946(C.swig_type_6(_swig_i_0), C.swig_type_7(_swig_i_1))))
	return swig_r
}

func NewMatrix__SWIG_1() (_swig_ret Matrix) {
	var swig_r Matrix
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_new_Matrix__SWIG_1_linalg_52140ac0f9bac946()))
	return swig_r
}

func NewMatrix(a ...interface{}) Matrix {
	argc := len(a)
	if argc == 0 {
		return NewMatrix__SWIG_1()
	}
	if argc == 2 {
		return NewMatrix__SWIG_0(a[0].(int64), a[1].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMatrix) Mult(arg2 Matrix) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_mult_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Scalar_mult(arg2 float64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_scalar_mult_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Mult_elem(arg2 Matrix) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_mult_elem_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Sqr_err() (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_sqr_err_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Add(arg2 Matrix) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_add_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) X__add__(arg2 Matrix) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix___add___linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Scalar_add(arg2 float64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_scalar_add_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Sub(arg2 Matrix) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_sub_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) All() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Matrix_all_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrMatrix) Transpose() (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_transpose_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) T() (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_T_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Sum__SWIG_0() (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_sum__SWIG_0_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Sum__SWIG_1(arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_sum__SWIG_1_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))))
	return swig_r
}

func (p SwigcptrMatrix) Sum(a ...interface{}) Matrix {
	argc := len(a)
	if argc == 0 {
		return p.Sum__SWIG_0()
	}
	if argc == 1 {
		return p.Sum__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMatrix) Mean__SWIG_0() (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_mean__SWIG_0_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Mean__SWIG_1(arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_mean__SWIG_1_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_9(_swig_i_1))))
	return swig_r
}

func (p SwigcptrMatrix) Mean(a ...interface{}) Matrix {
	argc := len(a)
	if argc == 0 {
		return p.Mean__SWIG_0()
	}
	if argc == 1 {
		return p.Mean__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMatrix) Concatenate(arg2 Matrix, arg3 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := arg3
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_concatenate_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_10(_swig_i_2))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Diag() (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_diag_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Apply_func(arg2 Std_function_Sl_double_Sp_double_SS_const_SA__SP__Sg_) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_Matrix_apply_func_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrix) Print_shape() {
	_swig_i_0 := arg1
	C._wrap_Matrix_print_shape_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrMatrix) Print_mtx() {
	_swig_i_0 := arg1
	C._wrap_Matrix_print_mtx_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrMatrix) Fill_index(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Matrix_fill_index_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func DeleteMatrix(arg1 Matrix) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Matrix_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

type Matrix interface {
	Swigcptr() uintptr
	SwigIsMatrix()
	SetData(arg2 Std_vector_Sl_double_Sg_)
	GetData() (_swig_ret Std_vector_Sl_double_Sg_)
	SetDim(arg2 Std_tuple_Sl_size_t_Sc_size_t_Sg_)
	GetDim() (_swig_ret Std_tuple_Sl_size_t_Sc_size_t_Sg_)
	SetNum_elements(arg2 int64)
	GetNum_elements() (_swig_ret int64)
	Mult(arg2 Matrix) (_swig_ret Matrix)
	Scalar_mult(arg2 float64) (_swig_ret Matrix)
	Mult_elem(arg2 Matrix) (_swig_ret Matrix)
	Sqr_err() (_swig_ret Matrix)
	Add(arg2 Matrix) (_swig_ret Matrix)
	X__add__(arg2 Matrix) (_swig_ret Matrix)
	Scalar_add(arg2 float64) (_swig_ret Matrix)
	Sub(arg2 Matrix) (_swig_ret Matrix)
	All() (_swig_ret bool)
	Transpose() (_swig_ret Matrix)
	T() (_swig_ret Matrix)
	Sum(a ...interface{}) Matrix
	Mean(a ...interface{}) Matrix
	Concatenate(arg2 Matrix, arg3 int64) (_swig_ret Matrix)
	Diag() (_swig_ret Matrix)
	Apply_func(arg2 Std_function_Sl_double_Sp_double_SS_const_SA__SP__Sg_) (_swig_ret Matrix)
	Print_shape()
	Print_mtx()
	Fill_index(arg2 float64)
}

type SwigcptrMatrixI uintptr

func (p SwigcptrMatrixI) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMatrixI) SwigIsMatrixI() {
}

func (arg1 SwigcptrMatrixI) SetData(arg2 Std_vector_Sl_int_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_MatrixI_data_set_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMatrixI) GetData() (_swig_ret Std_vector_Sl_int_Sg_) {
	var swig_r Std_vector_Sl_int_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_int_Sg_)(SwigcptrStd_vector_Sl_int_Sg_(C._wrap_MatrixI_data_get_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) SetDim(arg2 Std_tuple_Sl_size_t_Sc_size_t_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_MatrixI_dim_set_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMatrixI) GetDim() (_swig_ret Std_tuple_Sl_size_t_Sc_size_t_Sg_) {
	var swig_r Std_tuple_Sl_size_t_Sc_size_t_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_tuple_Sl_size_t_Sc_size_t_Sg_)(SwigcptrStd_tuple_Sl_size_t_Sc_size_t_Sg_(C._wrap_MatrixI_dim_get_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) SetNum_elements(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_MatrixI_num_elements_set_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_11(_swig_i_1))
}

func (arg1 SwigcptrMatrixI) GetNum_elements() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_MatrixI_num_elements_get_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewMatrixI__SWIG_0(arg1 int64, arg2 int64) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_new_MatrixI__SWIG_0_linalg_52140ac0f9bac946(C.swig_type_13(_swig_i_0), C.swig_type_14(_swig_i_1))))
	return swig_r
}

func NewMatrixI__SWIG_1() (_swig_ret MatrixI) {
	var swig_r MatrixI
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_new_MatrixI__SWIG_1_linalg_52140ac0f9bac946()))
	return swig_r
}

func NewMatrixI(a ...interface{}) MatrixI {
	argc := len(a)
	if argc == 0 {
		return NewMatrixI__SWIG_1()
	}
	if argc == 2 {
		return NewMatrixI__SWIG_0(a[0].(int64), a[1].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMatrixI) Mult(arg2 MatrixI) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_mult_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Scalar_mult(arg2 int) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_scalar_mult_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Mult_elem(arg2 MatrixI) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_mult_elem_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Sqr_err() (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_sqr_err_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Add(arg2 MatrixI) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_add_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) X__add__(arg2 MatrixI) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI___add___linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Scalar_add(arg2 int) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_scalar_add_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Sub(arg2 MatrixI) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_sub_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) All() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_MatrixI_all_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Transpose() (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_transpose_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) T() (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_T_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Sum__SWIG_0() (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_sum__SWIG_0_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Sum__SWIG_1(arg2 int64) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_sum__SWIG_1_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_15(_swig_i_1))))
	return swig_r
}

func (p SwigcptrMatrixI) Sum(a ...interface{}) MatrixI {
	argc := len(a)
	if argc == 0 {
		return p.Sum__SWIG_0()
	}
	if argc == 1 {
		return p.Sum__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMatrixI) Mean__SWIG_0() (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_mean__SWIG_0_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Mean__SWIG_1(arg2 int64) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_mean__SWIG_1_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1))))
	return swig_r
}

func (p SwigcptrMatrixI) Mean(a ...interface{}) MatrixI {
	argc := len(a)
	if argc == 0 {
		return p.Mean__SWIG_0()
	}
	if argc == 1 {
		return p.Mean__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMatrixI) Concatenate(arg2 MatrixI, arg3 int64) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	_swig_i_2 := arg3
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_concatenate_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_17(_swig_i_2))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Diag() (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_diag_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Apply_func(arg2 Std_function_Sl_int_Sp_int_SS_const_SA__SP__Sg_) (_swig_ret MatrixI) {
	var swig_r MatrixI
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (MatrixI)(SwigcptrMatrixI(C._wrap_MatrixI_apply_func_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrMatrixI) Print_shape() {
	_swig_i_0 := arg1
	C._wrap_MatrixI_print_shape_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrMatrixI) Print_mtx() {
	_swig_i_0 := arg1
	C._wrap_MatrixI_print_mtx_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrMatrixI) Fill_index(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_MatrixI_fill_index_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DeleteMatrixI(arg1 MatrixI) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_MatrixI_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

type MatrixI interface {
	Swigcptr() uintptr
	SwigIsMatrixI()
	SetData(arg2 Std_vector_Sl_int_Sg_)
	GetData() (_swig_ret Std_vector_Sl_int_Sg_)
	SetDim(arg2 Std_tuple_Sl_size_t_Sc_size_t_Sg_)
	GetDim() (_swig_ret Std_tuple_Sl_size_t_Sc_size_t_Sg_)
	SetNum_elements(arg2 int64)
	GetNum_elements() (_swig_ret int64)
	Mult(arg2 MatrixI) (_swig_ret MatrixI)
	Scalar_mult(arg2 int) (_swig_ret MatrixI)
	Mult_elem(arg2 MatrixI) (_swig_ret MatrixI)
	Sqr_err() (_swig_ret MatrixI)
	Add(arg2 MatrixI) (_swig_ret MatrixI)
	X__add__(arg2 MatrixI) (_swig_ret MatrixI)
	Scalar_add(arg2 int) (_swig_ret MatrixI)
	Sub(arg2 MatrixI) (_swig_ret MatrixI)
	All() (_swig_ret bool)
	Transpose() (_swig_ret MatrixI)
	T() (_swig_ret MatrixI)
	Sum(a ...interface{}) MatrixI
	Mean(a ...interface{}) MatrixI
	Concatenate(arg2 MatrixI, arg3 int64) (_swig_ret MatrixI)
	Diag() (_swig_ret MatrixI)
	Apply_func(arg2 Std_function_Sl_int_Sp_int_SS_const_SA__SP__Sg_) (_swig_ret MatrixI)
	Print_shape()
	Print_mtx()
	Fill_index(arg2 int)
}

type SwigcptrMtx uintptr

func (p SwigcptrMtx) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMtx) SwigIsMtx() {
}

func MtxZeros(arg1 int64, arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_mtx_zeros_linalg_52140ac0f9bac946(C.swig_type_18(_swig_i_0), C.swig_type_19(_swig_i_1))))
	return swig_r
}

func MtxOnes(arg1 int64, arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_mtx_ones_linalg_52140ac0f9bac946(C.swig_type_20(_swig_i_0), C.swig_type_21(_swig_i_1))))
	return swig_r
}

func MtxRandn(arg1 int64, arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_mtx_randn_linalg_52140ac0f9bac946(C.swig_type_22(_swig_i_0), C.swig_type_23(_swig_i_1))))
	return swig_r
}

func MtxRand(arg1 int64, arg2 int64) (_swig_ret Matrix) {
	var swig_r Matrix
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Matrix)(SwigcptrMatrix(C._wrap_mtx_rand_linalg_52140ac0f9bac946(C.swig_type_24(_swig_i_0), C.swig_type_25(_swig_i_1))))
	return swig_r
}

func DeleteMtx(arg1 Mtx) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_mtx_linalg_52140ac0f9bac946(C.uintptr_t(_swig_i_0))
}

type Mtx interface {
	Swigcptr() uintptr
	SwigIsMtx()
}


type SwigcptrStd_vector_Sl_double_Sg_ uintptr
type Std_vector_Sl_double_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_double_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_function_Sl_int_Sp_int_SS_const_SA__SP__Sg_ uintptr
type Std_function_Sl_int_Sp_int_SS_const_SA__SP__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_function_Sl_int_Sp_int_SS_const_SA__SP__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_tuple_Sl_size_t_Sc_size_t_Sg_ uintptr
type Std_tuple_Sl_size_t_Sc_size_t_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_tuple_Sl_size_t_Sc_size_t_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_function_Sl_double_Sp_double_SS_const_SA__SP__Sg_ uintptr
type Std_function_Sl_double_Sp_double_SS_const_SA__SP__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_function_Sl_double_Sp_double_SS_const_SA__SP__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_int_Sg_ uintptr
type Std_vector_Sl_int_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_int_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

