/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ml/ml.i

package ml

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef _gostring_ swig_type_4;
extern void _wrap_Swig_free_ml_0f907762cc4b2159(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_ml_0f907762cc4b2159(swig_intgo arg1);
extern uintptr_t _wrap_new_Regression_ml_0f907762cc4b2159(void);
extern void _wrap_Regression_calculate_coeffecient_ml_0f907762cc4b2159(uintptr_t arg1);
extern void _wrap_Regression_calculate_constant_ml_0f907762cc4b2159(uintptr_t arg1);
extern swig_type_1 _wrap_Regression_data_size_ml_0f907762cc4b2159(uintptr_t arg1);
extern uintptr_t _wrap_Regression_return_coeffecient_ml_0f907762cc4b2159(uintptr_t arg1);
extern uintptr_t _wrap_Regression_return_constant_ml_0f907762cc4b2159(uintptr_t arg1);
extern void _wrap_Regression_best_fit_ml_0f907762cc4b2159(uintptr_t arg1);
extern void _wrap_Regression_get_input_ml_0f907762cc4b2159(uintptr_t arg1, swig_type_2 arg2);
extern void _wrap_Regression_show_data_ml_0f907762cc4b2159(uintptr_t arg1);
extern uintptr_t _wrap_Regression_predict_ml_0f907762cc4b2159(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Regression_error_square_ml_0f907762cc4b2159(uintptr_t arg1);
extern uintptr_t _wrap_Regression_error_in_ml_0f907762cc4b2159(uintptr_t arg1, uintptr_t arg2);
extern swig_type_3 _wrap_Regression_num_rows_ml_0f907762cc4b2159(uintptr_t arg1, swig_type_4 arg2);
extern void _wrap_delete_Regression_ml_0f907762cc4b2159(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

//export cgo_panic__ml_0f907762cc4b2159
func cgo_panic__ml_0f907762cc4b2159(p *byte) {
	s := (*[1024]byte)(unsafe.Pointer(p))[:]
	for i, b := range s {
		if b == 0 {
			panic(string(s[:i]))
		}
	}
	panic(string(s))
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_ml_0f907762cc4b2159(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrRegression uintptr

func (p SwigcptrRegression) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrRegression) SwigIsRegression() {
}

func NewRegression() (_swig_ret Regression) {
	var swig_r Regression
	swig_r = (Regression)(SwigcptrRegression(C._wrap_new_Regression_ml_0f907762cc4b2159()))
	return swig_r
}

func (arg1 SwigcptrRegression) Calculate_coeffecient() {
	_swig_i_0 := arg1
	C._wrap_Regression_calculate_coeffecient_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrRegression) Calculate_constant() {
	_swig_i_0 := arg1
	C._wrap_Regression_calculate_constant_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrRegression) Data_size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Regression_data_size_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRegression) Return_coeffecient() (_swig_ret Long_SS_double) {
	var swig_r Long_SS_double
	_swig_i_0 := arg1
	swig_r = (Long_SS_double)(SwigcptrLong_SS_double(C._wrap_Regression_return_coeffecient_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRegression) Return_constant() (_swig_ret Long_SS_double) {
	var swig_r Long_SS_double
	_swig_i_0 := arg1
	swig_r = (Long_SS_double)(SwigcptrLong_SS_double(C._wrap_Regression_return_constant_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRegression) Best_fit() {
	_swig_i_0 := arg1
	C._wrap_Regression_best_fit_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrRegression) Get_input(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Regression_get_input_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0), C.swig_type_2(_swig_i_1))
}

func (arg1 SwigcptrRegression) Show_data() {
	_swig_i_0 := arg1
	C._wrap_Regression_show_data_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrRegression) Predict(arg2 Long_SS_double) (_swig_ret Long_SS_double) {
	var swig_r Long_SS_double
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Long_SS_double)(SwigcptrLong_SS_double(C._wrap_Regression_predict_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrRegression) Error_square() (_swig_ret Long_SS_double) {
	var swig_r Long_SS_double
	_swig_i_0 := arg1
	swig_r = (Long_SS_double)(SwigcptrLong_SS_double(C._wrap_Regression_error_square_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRegression) Error_in(arg2 Long_SS_double) (_swig_ret Long_SS_double) {
	var swig_r Long_SS_double
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (Long_SS_double)(SwigcptrLong_SS_double(C._wrap_Regression_error_in_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrRegression) Num_rows(arg2 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_Regression_num_rows_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func DeleteRegression(arg1 Regression) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Regression_ml_0f907762cc4b2159(C.uintptr_t(_swig_i_0))
}

type Regression interface {
	Swigcptr() uintptr
	SwigIsRegression()
	Calculate_coeffecient()
	Calculate_constant()
	Data_size() (_swig_ret int64)
	Return_coeffecient() (_swig_ret Long_SS_double)
	Return_constant() (_swig_ret Long_SS_double)
	Best_fit()
	Get_input(arg2 int64)
	Show_data()
	Predict(arg2 Long_SS_double) (_swig_ret Long_SS_double)
	Error_square() (_swig_ret Long_SS_double)
	Error_in(arg2 Long_SS_double) (_swig_ret Long_SS_double)
	Num_rows(arg2 string) (_swig_ret int64)
}


type SwigcptrLong_SS_double uintptr
type Long_SS_double interface {
	Swigcptr() uintptr;
}
func (p SwigcptrLong_SS_double) Swigcptr() uintptr {
	return uintptr(p)
}

