! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.1.1+fortran
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module openmtpk
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! class mtpk::Basics
 type, public :: Basics
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: greatest_power => swigf_Basics_greatest_power
  procedure :: op_gcd => swigf_Basics_op_gcd
  procedure :: release => swigf_Basics_release
  procedure, private :: swigf_Basics_op_assign__
  generic :: assignment(=) => swigf_Basics_op_assign__
 end type Basics
 type, public :: SWIGTYPE_p_int64_t
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: new_int64_t_ptr
 public :: copy_int64_t_ptr
 public :: delete_int64_t_ptr
 public :: int64_t_ptr_assign
 public :: int64_t_ptr_value
 interface Basics
  module procedure swigf_new_Basics
 end interface

! WRAPPER DECLARATIONS
interface
function swigc_Basics_greatest_power(farg1, farg2, farg3) &
bind(C, name="_wrap_Basics_greatest_power") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
integer(C_INT64_T) :: fresult
end function

function swigc_Basics_op_gcd(farg1, farg2, farg3) &
bind(C, name="_wrap_Basics_op_gcd") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
integer(C_INT64_T) :: fresult
end function

function swigc_new_Basics() &
bind(C, name="_wrap_new_Basics") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_Basics(farg1) &
bind(C, name="_wrap_delete_Basics")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_Basics_op_assign__(farg1, farg2) &
bind(C, name="_wrap_Basics_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_new_int64_t_ptr() &
bind(C, name="_wrap_new_int64_t_ptr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_copy_int64_t_ptr(farg1) &
bind(C, name="_wrap_copy_int64_t_ptr") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT64_T), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_int64_t_ptr(farg1) &
bind(C, name="_wrap_delete_int64_t_ptr")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_int64_t_ptr_assign(farg1, farg2) &
bind(C, name="_wrap_int64_t_ptr_assign")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
end subroutine

function swigc_int64_t_ptr_value(farg1) &
bind(C, name="_wrap_int64_t_ptr_value") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT64_T) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function swigf_Basics_greatest_power(self, n, p) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(Basics), intent(in) :: self
integer(C_INT64_T), intent(in) :: n
integer(C_INT64_T), intent(in) :: p
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT64_T) :: farg2 
integer(C_INT64_T) :: farg3 

farg1 = self%swigdata
farg2 = n
farg3 = p
fresult = swigc_Basics_greatest_power(farg1, farg2, farg3)
swig_result = fresult
end function

function swigf_Basics_op_gcd(self, x, y) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(Basics), intent(in) :: self
integer(C_INT64_T), intent(in) :: x
integer(C_INT64_T), intent(in) :: y
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT64_T) :: farg2 
integer(C_INT64_T) :: farg3 

farg1 = self%swigdata
farg2 = x
farg3 = y
fresult = swigc_Basics_op_gcd(farg1, farg2, farg3)
swig_result = fresult
end function

function swigf_new_Basics() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(Basics) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_Basics()
self%swigdata = fresult
end function

subroutine swigf_Basics_release(self)
use, intrinsic :: ISO_C_BINDING
class(Basics), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_Basics(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_Basics_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(Basics), intent(inout) :: self
type(Basics), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_Basics_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function new_int64_t_ptr() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_int64_t) :: swig_result
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_int64_t_ptr()
swig_result%swigdata = fresult
end function

function copy_int64_t_ptr(value) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_int64_t) :: swig_result
integer(C_INT64_T), intent(in) :: value
type(SwigClassWrapper) :: fresult 
integer(C_INT64_T) :: farg1 

farg1 = value
fresult = swigc_copy_int64_t_ptr(farg1)
swig_result%swigdata = fresult
end function

subroutine delete_int64_t_ptr(obj)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_int64_t), intent(in) :: obj
type(SwigClassWrapper) :: farg1 

farg1 = obj%swigdata
call swigc_delete_int64_t_ptr(farg1)
end subroutine

subroutine int64_t_ptr_assign(obj, value)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_int64_t), intent(in) :: obj
integer(C_INT64_T), intent(in) :: value
type(SwigClassWrapper) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = obj%swigdata
farg2 = value
call swigc_int64_t_ptr_assign(farg1, farg2)
end subroutine

function int64_t_ptr_value(obj) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(SWIGTYPE_p_int64_t), intent(in) :: obj
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = obj%swigdata
fresult = swigc_int64_t_ptr_value(farg1)
swig_result = fresult
end function


end module
