/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040100
#define SWIGR
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2
#define SWIG_POINTER_NO_NULL       0x4
#define SWIG_POINTER_CLEAR         0x8
#define SWIG_POINTER_RELEASE       (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows returning the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
/* Runtime errors are < 0 */
#define SWIG_ERROR                 (-1)
/* Errors in range -1 to -99 are in swigerrors.swg (errors for all languages including those not using the runtime) */
/* Errors in range -100 to -199 are language specific errors defined in *errors.swg */
/* Errors < -200 are generic runtime specific errors */
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)

#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporal objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del object mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) {
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) {
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next cast in linked list */
  struct swig_cast_info  *prev;			/* pointer to the previous cast */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/*
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCmp(const char *nb, const char *tb) {
  int equiv = 1;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (equiv != 0 && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te);
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (strcmp(iter->type->name, c) == 0) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(const swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (iter->type == from) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/*
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  Choose the last
     name. It should be the most specific; a fully resolved name
     but not necessarily with default template parameters expanded. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *cast = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;

  while (cast) {
    if (!cast->converter) {
      swig_type_info *tc = cast->type;
      if (!tc->clientdata) {
	SWIG_TypeClientData(tc, clientdata);
      }
    }
    cast = cast->next;
  }
}
SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}

/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start,
                            swig_module_info *end,
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      size_t l = 0;
      size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	size_t i = (l + r) >> 1;
	const char *iname = iter->types[i]->name;
	if (iname) {
	  int compare = strcmp(name, iname);
	  if (compare == 0) {
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start,
                     swig_module_info *end,
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }

  /* neither found a match */
  return 0;
}

/*
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  const unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/*
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    char d = *(c++);
    unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = (unsigned char)((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = (unsigned char)((d - ('a'-10)) << 4);
    else
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (unsigned char)(d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (unsigned char)(d - ('a'-10));
    else
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/* SWIG Errors applicable to all language modules, values are reserved from -1 to -99 */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13


/* Remove global namespace pollution */
#if !defined(SWIG_NO_R_NO_REMAP)
# define R_NO_REMAP
#endif
#if !defined(SWIG_NO_STRICT_R_HEADERS)
# define STRICT_R_HEADERS
#endif

#include <Rdefines.h>
#include <Rversion.h>

#ifdef __cplusplus
#include <exception>
extern "C" {
#endif

/* for raw pointer */
#define SWIG_ConvertPtr(obj, pptr, type, flags)         SWIG_R_ConvertPtr(obj, pptr, type, flags)
#define SWIG_ConvertPtrAndOwn(obj,pptr,type,flags,own)  SWIG_R_ConvertPtr(obj, pptr, type, flags)
#define SWIG_NewPointerObj(ptr, type, flags)            SWIG_R_NewPointerObj(ptr, type, flags)

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <stdarg.h>

#if R_VERSION >= R_Version(2,6,0)
#define VMAXTYPE void *
#else
#define VMAXTYPE char *
#endif

/* Last error */
static int SWIG_lasterror_code = 0;
static char SWIG_lasterror_msg[1024];
SWIGRUNTIME void SWIG_Error(int code, const char *format, ...) {
  va_list arg;
  SWIG_lasterror_code = code;
  va_start(arg, format);
  vsnprintf(SWIG_lasterror_msg, sizeof(SWIG_lasterror_msg), format, arg);
  va_end(arg);
}

SWIGRUNTIME const char *SWIG_ErrorType(int code) {
  switch (code) {
  case SWIG_MemoryError:
    return "SWIG:MemoryError";
  case SWIG_IOError:
    return "SWIG:IOError";
  case SWIG_RuntimeError:
    return "SWIG:RuntimeError";
  case SWIG_IndexError:
    return "SWIG:IndexError";
  case SWIG_TypeError:
    return "SWIG:TypeError";
  case SWIG_DivisionByZero:
    return "SWIG:DivisionByZero";
  case SWIG_OverflowError:
    return "SWIG:OverflowError";
  case SWIG_SyntaxError:
    return "SWIG:SyntaxError";
  case SWIG_ValueError:
    return "SWIG:ValueError";
  case SWIG_SystemError:
    return "SWIG:SystemError";
  case SWIG_AttributeError:
    return "SWIG:AttributeError";
  }
  return "SWIG:UnknownError";
}

#define SWIG_fail goto fail

/*
  This is mainly a way to avoid having lots of local variables that may 
  conflict with those in the routine.

   Change name to R_SWIG_Callb....
*/
typedef struct RCallbackFunctionData {

  SEXP fun;
  SEXP userData;


  SEXP expr;
  SEXP retValue;
  int errorOccurred;

  SEXP el;  /* Temporary pointer used in the construction of the expression to call the R function. */

  struct RCallbackFunctionData *previous;   /* Stack */

} RCallbackFunctionData;

static RCallbackFunctionData  *callbackFunctionDataStack;


SWIGRUNTIME SEXP
R_SWIG_debug_getCallbackFunctionData()
{
  int n, i;
  SEXP ans;
  RCallbackFunctionData  *p = callbackFunctionDataStack;

  n = 0;
  while(p) { 
    n++;
    p = p->previous;
  }

  Rf_protect(ans = Rf_allocVector(VECSXP, n));
  for(p = callbackFunctionDataStack, i = 0; i < n; p = p->previous, i++) 
      SET_VECTOR_ELT(ans, i, p->fun);

  Rf_unprotect(1);

  return(ans);
}



SWIGRUNTIME RCallbackFunctionData *
R_SWIG_pushCallbackFunctionData(SEXP fun, SEXP userData)
{
   RCallbackFunctionData *el;
   el = (RCallbackFunctionData *) calloc(1, sizeof(RCallbackFunctionData));
   el->fun = fun;
   el->userData = userData;
   el->previous = callbackFunctionDataStack;

   callbackFunctionDataStack = el;

   return(el);
}


SWIGRUNTIME SEXP
R_SWIG_R_pushCallbackFunctionData(SEXP fun, SEXP userData)
{
    R_SWIG_pushCallbackFunctionData(fun, userData);
    return R_NilValue;
}

SWIGRUNTIME RCallbackFunctionData *
R_SWIG_getCallbackFunctionData()
{
  if(!callbackFunctionDataStack) {
    Rf_error("Supposedly impossible error occurred in the SWIG callback mechanism."
            "  No callback function data set.");
  }
  
  return callbackFunctionDataStack;
}

SWIGRUNTIME void
R_SWIG_popCallbackFunctionData(int doFree)
{
  RCallbackFunctionData  *el = NULL;
  if(!callbackFunctionDataStack)
    return ; /* Error !!! */

  el = callbackFunctionDataStack ;
  callbackFunctionDataStack = callbackFunctionDataStack->previous;

  if(doFree)
     free(el);
}


/*
  Interface to S function
      is(obj, type)
  which is to be used to determine if an 
  external pointer inherits from the right class.

  Ideally, we would like to be able to do this without an explicit call to the is() function.
  When the S4 class system uses its own SEXP types, then we will hopefully be able to do this
  in the C code.

  Should we make the expression static and preserve it to avoid the overhead of 
  allocating each time.
*/
SWIGRUNTIME int
R_SWIG_checkInherits(SEXP obj, SEXP tag, const char *type)
{
  SEXP e, val;
  int check_err = 0;

  Rf_protect(e = Rf_allocVector(LANGSXP, 3));
  SETCAR(e, Rf_install("extends"));

  SETCAR(CDR(e), Rf_mkString(CHAR(PRINTNAME(tag))));
  SETCAR(CDR(CDR(e)), Rf_mkString(type));

  val = R_tryEval(e, R_GlobalEnv, &check_err);
  Rf_unprotect(1);
  if(check_err) 
    return(0);


  return(LOGICAL(val)[0]);
}


SWIGRUNTIME void *
R_SWIG_resolveExternalRef(SEXP arg, const char * const type, const char * const argName, Rboolean nullOk)
{
  void *ptr;
  SEXP orig = arg;

  if(TYPEOF(arg) != EXTPTRSXP) 
    arg = GET_SLOT(arg, Rf_mkString("ref"));

  
  if(TYPEOF(arg) != EXTPTRSXP) {
    Rf_error("argument %s must be an external pointer (from an ExternalReference)", argName);
  }


  ptr = R_ExternalPtrAddr(arg);

  if(ptr == NULL && nullOk == (Rboolean) FALSE) {
    Rf_error("the external pointer (of type %s) for argument %s has value NULL", argName, type);
  }

  if(type[0] && R_ExternalPtrTag(arg) != Rf_install(type) && strcmp(type, "voidRef")
      && !R_SWIG_checkInherits(orig,  R_ExternalPtrTag(arg), type)) {
    Rf_error("the external pointer for argument %s has tag %s, not the expected value %s",
             argName, CHAR(PRINTNAME(R_ExternalPtrTag(arg))), type);
  }


  return(ptr);
}

SWIGRUNTIME void
R_SWIG_ReferenceFinalizer(SEXP el)
{
  void *ptr = R_SWIG_resolveExternalRef(el, "", "<finalizer>",  (Rboolean) 1);
  fprintf(stderr, "In R_SWIG_ReferenceFinalizer for %p\n", ptr);
  Rf_PrintValue(el);

  if(ptr) {
     if(TYPEOF(el) != EXTPTRSXP)
        el = GET_SLOT(el, Rf_mkString("ref"));

     if(TYPEOF(el) == EXTPTRSXP)
        R_ClearExternalPtr(el);

     free(ptr);
  }

  return;
}

SWIGRUNTIME SEXP
SWIG_MakePtr(void *ptr, const char *typeName, int flags)
{
  SEXP external, r_obj;

  Rf_protect(external = R_MakeExternalPtr(ptr, Rf_install(typeName), R_NilValue));
  Rf_protect(r_obj = NEW_OBJECT(MAKE_CLASS((char *) typeName)));

  if (flags & SWIG_POINTER_OWN)
    R_RegisterCFinalizer(external, R_SWIG_ReferenceFinalizer);

  r_obj = SET_SLOT(r_obj, Rf_mkString((char *) "ref"), external);
  SET_S4_OBJECT(r_obj);
  Rf_unprotect(2);

  return(r_obj);
}


SWIGRUNTIME SEXP
R_SWIG_create_SWIG_R_Array(const char *typeName, SEXP ref, int len)
{
   SEXP arr;

/*XXX remove the char * cast when we can. MAKE_CLASS should be declared appropriately. */
   Rf_protect(arr = NEW_OBJECT(MAKE_CLASS((char *) typeName)));
   Rf_protect(arr = R_do_slot_assign(arr, Rf_mkString("ref"), ref));
   Rf_protect(arr = R_do_slot_assign(arr, Rf_mkString("dims"), Rf_ScalarInteger(len)));

   Rf_unprotect(3); 			   
   SET_S4_OBJECT(arr);	
   return arr;
}

#define ADD_OUTPUT_ARG(result, pos, value, name)  r_ans = AddOutputArgToReturn(pos, value, name, OutputValues);

SWIGRUNTIME SEXP
AddOutputArgToReturn(int pos, SEXP value, const char *name, SEXP output)
{
  SET_VECTOR_ELT(output, pos, value);

  return(output);
}

/* Create a new pointer object */
SWIGRUNTIMEINLINE SEXP
SWIG_R_NewPointerObj(void *ptr, swig_type_info *type, int flags) {
  SEXP rptr;
  if (!ptr) {
     return R_NilValue;
  }
  rptr = R_MakeExternalPtr(ptr, 
  R_MakeExternalPtr(type, R_NilValue, R_NilValue), R_NilValue); 
  SET_S4_OBJECT(rptr);
  return rptr;
}


/* Convert a pointer value */
SWIGRUNTIMEINLINE int
SWIG_R_ConvertPtr(SEXP obj, void **ptr, swig_type_info *ty, int flags) {
  void *vptr;
  if (!obj) return SWIG_ERROR;
  if (obj == R_NilValue) {
    if (ptr) *ptr = NULL;
    return (flags & SWIG_POINTER_NO_NULL) ? SWIG_NullReferenceError : SWIG_OK;
  }

  vptr = R_ExternalPtrAddr(obj);
  if (ty) {
    swig_type_info *to = (swig_type_info*) 
      R_ExternalPtrAddr(R_ExternalPtrTag(obj));
    if (to == ty) {
      if (ptr) *ptr = vptr;
    } else {
      swig_cast_info *tc = SWIG_TypeCheck(to->name,ty);
      int newmemory = 0;
      if (ptr) *ptr = SWIG_TypeCast(tc,vptr,&newmemory);
      assert(!newmemory); /* newmemory handling not yet implemented */
    }
  } else {
      if (ptr) *ptr = vptr;
 }
  return SWIG_OK;
}

SWIGRUNTIME swig_module_info *
SWIG_GetModule(void *SWIGUNUSEDPARM(clientdata)) {
  static void *type_pointer = (void *)0;
  return (swig_module_info *) type_pointer;
}

SWIGRUNTIME void
SWIG_SetModule(void *v, swig_module_info *swig_module) {
}

typedef struct {
  void *pack;
  swig_type_info *ty;
  size_t size;
} RSwigPacked;

/* Create a new packed object */

SWIGRUNTIMEINLINE SEXP RSwigPacked_New(void *ptr, size_t sz,
		  swig_type_info *ty) {
  SEXP rptr;
  RSwigPacked *sobj = 
  (RSwigPacked*) malloc(sizeof(RSwigPacked));
  if (sobj) {
    void *pack = malloc(sz);
    if (pack) {
      memcpy(pack, ptr, sz);
      sobj->pack = pack;
      sobj->ty   = ty;
      sobj->size = sz;
    } else {
      sobj = 0;
    }
  }
  rptr = R_MakeExternalPtr(sobj, R_NilValue, R_NilValue); 
  return rptr;
}

SWIGRUNTIME swig_type_info *
RSwigPacked_UnpackData(SEXP obj, void *ptr, size_t size)
{
    RSwigPacked *sobj = 
        (RSwigPacked *)R_ExternalPtrAddr(obj);
    if (sobj->size != size) return 0;
    memcpy(ptr, sobj->pack, size);
    return sobj->ty;
}

SWIGRUNTIMEINLINE SEXP
SWIG_R_NewPackedObj(void *ptr, size_t sz, swig_type_info *type) {
  return ptr ? RSwigPacked_New((void *) ptr, sz, type) : R_NilValue;
}

/* Convert a packed pointer value */

SWIGRUNTIME int
SWIG_R_ConvertPacked(SEXP obj, void *ptr, size_t sz, swig_type_info *ty) {
  swig_type_info *to = RSwigPacked_UnpackData(obj, ptr, sz);
  if (!to) return SWIG_ERROR;
  if (ty) {
    if (to != ty) {
      /* check type cast? */
      swig_cast_info *tc = SWIG_TypeCheck(to->name,ty);
      if (!tc) return SWIG_ERROR;
    }
  }
  return SWIG_OK;
}  

#ifdef __cplusplus
#define SWIG_exception_noreturn(code, msg) do { throw std::runtime_error(msg); } while(0)
#else
#define SWIG_exception_noreturn(code, msg) do { return result; } while(0)
#endif

#ifdef __cplusplus
}
#endif


SWIGINTERN void SWIG_R_Raise(SEXP obj, const char *msg) {
  Rf_error(Rf_isString(obj) ? CHAR(Rf_asChar(obj)) : msg);
}



#define SWIG_exception_fail(code, msg) do { SWIG_Error(code, msg); SWIG_fail; } while(0) 

#define SWIG_contract_assert(expr, msg) do { if (!(expr)) { SWIG_Error(SWIG_RuntimeError, msg); SWIG_fail; } } while (0) 



  #define SWIG_exception(code, msg) do { switch (code) {case SWIG_IndexError: return Rf_ScalarLogical(NA_LOGICAL); default: SWIG_Error(code, msg); SWIG_fail;}; } while(0) 



/* -------- TYPES TABLE (BEGIN) -------- */

#define SWIGTYPE_p_Basics swig_types[0]
#define SWIGTYPE_p_Cipher swig_types[1]
#define SWIGTYPE_p_Primality swig_types[2]
#define SWIGTYPE_p_RC4 swig_types[3]
#define SWIGTYPE_p_char swig_types[4]
#define SWIGTYPE_p_uint8_t swig_types[5]
#define SWIGTYPE_p_unsigned_char swig_types[6]
static swig_type_info *swig_types[8];
static swig_module_info swig_module = {swig_types, 7, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */



#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a)) 


#include <stdexcept>


#include <string>


    #include "../../include/arithmetic/arith.hpp"
    #include "../../include/number_theory/primes.hpp"
    #include "../../include/number_theory/rc4.hpp"
    #include "../../include/number_theory/cipher.hpp"


#include <typeinfo>
#include <stdexcept>


#if defined(__GNUC__)
#  if __GNUC__ == 2 && __GNUC_MINOR <= 96
#     define SWIG_STD_NOMODERN_STL
#  endif
#endif


#include <stddef.h>


#include <algorithm>


#include <vector>


#include <utility>


SWIGINTERNINLINE  int
SWIG_AsVal_long (SEXP obj, long *val)
{
   if (val) *val = Rf_asInteger(obj);
   return SWIG_OK;
}


SWIGINTERNINLINE SEXP
SWIG_From_long  (long value)
{
	return Rf_ScalarInteger((int)value);
}


#include <limits.h>
#if !defined(SWIG_NO_LLONG_MAX)
# if !defined(LLONG_MAX) && defined(__GNUC__) && defined (__LONG_LONG_MAX__)
#   define LLONG_MAX __LONG_LONG_MAX__
#   define LLONG_MIN (-LLONG_MAX - 1LL)
#   define ULLONG_MAX (LLONG_MAX * 2ULL + 1ULL)
# endif
#endif


SWIGINTERN int
SWIG_AsVal_int (SEXP obj, int *val)
{
  long v;
  int res = SWIG_AsVal_long (obj, &v);
  if (SWIG_IsOK(res)) {
    if ((v < INT_MIN || v > INT_MAX)) {
      return SWIG_OverflowError;
    } else {
      if (val) *val = static_cast< int >(v);
    }
  }  
  return res;
}


SWIGINTERN char *
SWIG_strdup(const char *str)
{
  char *newstr = reinterpret_cast< char * >(malloc(strlen(str) + 1));
  return strcpy(newstr, str);
}


SWIGINTERN SEXP
SWIG_FromCharPtrAndSize(const char* carray, size_t size) 
{
  SEXP t, c;
  if (!carray) return R_NilValue;
/* See R internals document 1.10.  
   MkCharLen was introduced in 2.7.0.  Use that instead of hand
   creating vector.

   Starting in 2.8.0 creating strings via vectors was deprecated in
   order to allow for use of CHARSXP caches. */

  Rf_protect(t = Rf_allocVector(STRSXP, 1));
#if R_VERSION >=  R_Version(2,7,0)
  c = Rf_mkCharLen(carray, size);
#else
  c = Rf_allocVector(CHARSXP, size);
  strncpy((char *)CHAR(c), carray, size);
#endif
  SET_STRING_ELT(t, 0, c);
  Rf_unprotect(1);
  return t;
}


SWIGINTERNINLINE SEXP
SWIG_From_std_string  (const std::string& s)
{
  return SWIG_FromCharPtrAndSize(s.data(), s.size());
}


SWIGINTERN int
SWIG_AsCharPtrAndSize(SEXP obj, char** cptr, size_t* psize, int *alloc)
{
  if (cptr && Rf_isString(obj)) {
    char *cstr = const_cast< char * >(CHAR(STRING_ELT(obj, 0)));
    int len = strlen(cstr);

    if (alloc) {
      if (*alloc == SWIG_NEWOBJ) {
        *cptr = reinterpret_cast< char* >(memcpy(new char[len + 1], cstr, sizeof(char)*(len + 1)));
        *alloc = SWIG_NEWOBJ;
      } else {
        *cptr = cstr;
      }
    } else {
      *cptr = reinterpret_cast< char * >(malloc(len + 1));
      *cptr = strcpy(*cptr, cstr);
    }
    if (psize) *psize = len + 1;
    return SWIG_OK;
  }
  return SWIG_TypeError;
}


SWIGINTERN int
SWIG_AsPtr_std_string (SEXP obj, std::string **val) 
{
  char* buf = 0 ; size_t size = 0; int alloc = SWIG_OLDOBJ;
  if (SWIG_IsOK((SWIG_AsCharPtrAndSize(obj, &buf, &size, &alloc)))) {
    if (buf) {
      if (val) *val = new std::string(buf, size - 1);
      if (alloc == SWIG_NEWOBJ) delete[] buf;
      return SWIG_NEWOBJ;
    } else {
      if (val) *val = 0;
      return SWIG_OLDOBJ;
    }
  } else {
    static int init = 0;
    static swig_type_info* descriptor = 0;
    if (!init) {
      descriptor = SWIG_TypeQuery("std::string" " *");
      init = 1;
    }
    if (descriptor) {
      std::string *vptr;
      int res = SWIG_R_ConvertPtr(obj, (void**)&vptr, descriptor, 0);
      if (SWIG_IsOK(res) && val) *val = vptr;
      return res;
    }
  }
  return SWIG_ERROR;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT SEXP
R_swig_Basics_greatest_power ( SEXP self, SEXP n, SEXP p, SEXP s_swig_copy)
{
  {
    int result;
    Basics *arg1 = (Basics *) 0 ;
    int arg2 ;
    int arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Basics, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Basics_greatest_power" "', argument " "1"" of type '" "Basics *""'"); 
    }
    arg1 = reinterpret_cast< Basics * >(argp1);
    arg2 = static_cast< int >(INTEGER(n)[0]);
    arg3 = static_cast< int >(INTEGER(p)[0]);
    result = (int)(arg1)->greatest_power(arg2,arg3);
    r_ans = Rf_ScalarInteger(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Basics_rm_gcd ( SEXP self, SEXP x, SEXP y, SEXP s_swig_copy)
{
  {
    int result;
    Basics *arg1 = (Basics *) 0 ;
    int arg2 ;
    int arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Basics, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Basics_rm_gcd" "', argument " "1"" of type '" "Basics *""'"); 
    }
    arg1 = reinterpret_cast< Basics * >(argp1);
    arg2 = static_cast< int >(INTEGER(x)[0]);
    arg3 = static_cast< int >(INTEGER(y)[0]);
    result = (int)(arg1)->rm_gcd(arg2,arg3);
    r_ans = Rf_ScalarInteger(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_new_Basics ( )
{
  {
    Basics *result = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    result = (Basics *)new Basics();
    r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Basics, SWIG_POINTER_OWN |  0 );
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_delete_Basics ( SEXP self)
{
  {
    Basics *arg1 = (Basics *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Basics, SWIG_POINTER_DISOWN |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_Basics" "', argument " "1"" of type '" "Basics *""'"); 
    }
    arg1 = reinterpret_cast< Basics * >(argp1);
    delete arg1;
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    R_ClearExternalPtr(self);
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_is_prime ( SEXP self, SEXP n, SEXP s_swig_copy)
{
  {
    bool result;
    Primality *arg1 = (Primality *) 0 ;
    int arg2 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_is_prime" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    arg2 = static_cast< int >(INTEGER(n)[0]);
    result = (bool)(arg1)->is_prime(arg2);
    r_ans = Rf_ScalarLogical(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_compute_miller_rabin ( SEXP self, SEXP d, SEXP n, SEXP s_swig_copy)
{
  {
    bool result;
    Primality *arg1 = (Primality *) 0 ;
    int arg2 ;
    int arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_compute_miller_rabin" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    arg2 = static_cast< int >(INTEGER(d)[0]);
    arg3 = static_cast< int >(INTEGER(n)[0]);
    result = (bool)(arg1)->compute_miller_rabin(arg2,arg3);
    r_ans = Rf_ScalarLogical(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_miller_rabin_prime ( SEXP self, SEXP n, SEXP iters, SEXP s_swig_copy)
{
  {
    bool result;
    Primality *arg1 = (Primality *) 0 ;
    int arg2 ;
    int arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_miller_rabin_prime" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    arg2 = static_cast< int >(INTEGER(n)[0]);
    arg3 = static_cast< int >(INTEGER(iters)[0]);
    result = (bool)(arg1)->miller_rabin_prime(arg2,arg3);
    r_ans = Rf_ScalarLogical(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_miller_rabin ( SEXP self, SEXP inters, SEXP min_val, SEXP max_val)
{
  {
    Primality *arg1 = (Primality *) 0 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_miller_rabin" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    arg2 = static_cast< int >(INTEGER(inters)[0]);
    arg3 = static_cast< int >(INTEGER(min_val)[0]);
    arg4 = static_cast< int >(INTEGER(max_val)[0]);
    (arg1)->miller_rabin(arg2,arg3,arg4);
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_jacobian_number ( SEXP self, SEXP a, SEXP n, SEXP s_swig_copy)
{
  {
    int result;
    Primality *arg1 = (Primality *) 0 ;
    long long arg2 ;
    long long arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    long val2 ;
    int ecode2 = 0 ;
    long val3 ;
    int ecode3 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_jacobian_number" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    ecode2 = SWIG_AsVal_long(a, &val2);
    if (!SWIG_IsOK(ecode2)) {
      SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_jacobian_number" "', argument " "2"" of type '" "long long""'");
    } 
    arg2 = static_cast< long long >(val2);
    ecode3 = SWIG_AsVal_long(n, &val3);
    if (!SWIG_IsOK(ecode3)) {
      SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "Primality_jacobian_number" "', argument " "3"" of type '" "long long""'");
    } 
    arg3 = static_cast< long long >(val3);
    result = (int)(arg1)->jacobian_number(arg2,arg3);
    r_ans = Rf_ScalarInteger(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_solovoy_strassen ( SEXP self, SEXP p, SEXP iters, SEXP s_swig_copy)
{
  {
    bool result;
    Primality *arg1 = (Primality *) 0 ;
    long long arg2 ;
    int arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    long val2 ;
    int ecode2 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_solovoy_strassen" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    ecode2 = SWIG_AsVal_long(p, &val2);
    if (!SWIG_IsOK(ecode2)) {
      SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_solovoy_strassen" "', argument " "2"" of type '" "long long""'");
    } 
    arg2 = static_cast< long long >(val2);
    arg3 = static_cast< int >(INTEGER(iters)[0]);
    result = (bool)(arg1)->solovoy_strassen(arg2,arg3);
    r_ans = Rf_ScalarLogical(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_mod_pow ( SEXP self, SEXP base, SEXP exponent, SEXP mod, SEXP s_swig_copy)
{
  {
    long long result;
    Primality *arg1 = (Primality *) 0 ;
    long long arg2 ;
    long long arg3 ;
    long long arg4 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    long val2 ;
    int ecode2 = 0 ;
    long val3 ;
    int ecode3 = 0 ;
    long val4 ;
    int ecode4 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_mod_pow" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    ecode2 = SWIG_AsVal_long(base, &val2);
    if (!SWIG_IsOK(ecode2)) {
      SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_mod_pow" "', argument " "2"" of type '" "long long""'");
    } 
    arg2 = static_cast< long long >(val2);
    ecode3 = SWIG_AsVal_long(exponent, &val3);
    if (!SWIG_IsOK(ecode3)) {
      SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "Primality_mod_pow" "', argument " "3"" of type '" "long long""'");
    } 
    arg3 = static_cast< long long >(val3);
    ecode4 = SWIG_AsVal_long(mod, &val4);
    if (!SWIG_IsOK(ecode4)) {
      SWIG_exception_fail(SWIG_ArgError(ecode4), "in method '" "Primality_mod_pow" "', argument " "4"" of type '" "long long""'");
    } 
    arg4 = static_cast< long long >(val4);
    result = (long long)(arg1)->mod_pow(arg2,arg3,arg4);
    r_ans = SWIG_From_long(static_cast< long >(result));
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_carmichael_num ( SEXP self, SEXP n, SEXP s_swig_copy)
{
  {
    bool result;
    Primality *arg1 = (Primality *) 0 ;
    int arg2 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_carmichael_num" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    arg2 = static_cast< int >(INTEGER(n)[0]);
    result = (bool)(arg1)->carmichael_num(arg2);
    r_ans = Rf_ScalarLogical(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_sieve_of_eratosthenes ( SEXP self, SEXP n)
{
  {
    Primality *arg1 = (Primality *) 0 ;
    int arg2 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_sieve_of_eratosthenes" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    arg2 = static_cast< int >(INTEGER(n)[0]);
    (arg1)->sieve_of_eratosthenes(arg2);
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_pollard_rho ( SEXP self, SEXP n, SEXP s_swig_copy)
{
  {
    long long result;
    Primality *arg1 = (Primality *) 0 ;
    long long arg2 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    long val2 ;
    int ecode2 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_pollard_rho" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    ecode2 = SWIG_AsVal_long(n, &val2);
    if (!SWIG_IsOK(ecode2)) {
      SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_pollard_rho" "', argument " "2"" of type '" "long long""'");
    } 
    arg2 = static_cast< long long >(val2);
    result = (long long)(arg1)->pollard_rho(arg2);
    r_ans = SWIG_From_long(static_cast< long >(result));
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Primality_ETF ( SEXP self, SEXP n, SEXP s_swig_copy)
{
  {
    int result;
    Primality *arg1 = (Primality *) 0 ;
    unsigned int arg2 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    int val2 ;
    int ecode2 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Primality_ETF" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    ecode2 = SWIG_AsVal_int(n, &val2);
    if (!SWIG_IsOK(ecode2)) {
      SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "Primality_ETF" "', argument " "2"" of type '" "unsigned int""'");
    } 
    arg2 = static_cast< unsigned int >(val2);
    result = (int)(arg1)->ETF(arg2);
    r_ans = Rf_ScalarInteger(result);
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_new_Primality ( )
{
  {
    Primality *result = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    result = (Primality *)new Primality();
    r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Primality, SWIG_POINTER_OWN |  0 );
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_delete_Primality ( SEXP self)
{
  {
    Primality *arg1 = (Primality *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Primality, SWIG_POINTER_DISOWN |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_Primality" "', argument " "1"" of type '" "Primality *""'"); 
    }
    arg1 = reinterpret_cast< Primality * >(argp1);
    delete arg1;
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    R_ClearExternalPtr(self);
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_byte_swap ( SEXP self, SEXP a, SEXP b)
{
  {
    RC4 *arg1 = (RC4 *) 0 ;
    uint8_t *arg2 = (uint8_t *) 0 ;
    uint8_t *arg3 = (uint8_t *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    void *argp2 = 0 ;
    int res2 = 0 ;
    void *argp3 = 0 ;
    int res3 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_byte_swap" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    res2 = SWIG_R_ConvertPtr(a, &argp2, SWIGTYPE_p_uint8_t, 0 |  0 );
    if (!SWIG_IsOK(res2)) {
      SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "RC4_byte_swap" "', argument " "2"" of type '" "uint8_t *""'"); 
    }
    arg2 = reinterpret_cast< uint8_t * >(argp2);
    res3 = SWIG_R_ConvertPtr(b, &argp3, SWIGTYPE_p_uint8_t, 0 |  0 );
    if (!SWIG_IsOK(res3)) {
      SWIG_exception_fail(SWIG_ArgError(res3), "in method '" "RC4_byte_swap" "', argument " "3"" of type '" "uint8_t *""'"); 
    }
    arg3 = reinterpret_cast< uint8_t * >(argp3);
    (arg1)->byte_swap(arg2,arg3);
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_trad_swap ( SEXP self, SEXP a, SEXP b)
{
  {
    RC4 *arg1 = (RC4 *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    unsigned char *arg3 = (unsigned char *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_trad_swap" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(a);
        arg2 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg2[_rswigi] = INTEGER(a)[_rswigi];
        }
      }
    }
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(b);
        arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg3[_rswigi] = INTEGER(b)[_rswigi];
        }
      }
    }
    (arg1)->trad_swap(arg2,arg3);
    r_ans = R_NilValue;
    
    free(arg2);
    
    
    free(arg3);
    
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
    
    free(arg2);
    
    
    free(arg3);
    
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_XOR_swap ( SEXP self, SEXP a, SEXP b)
{
  {
    RC4 *arg1 = (RC4 *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    unsigned char *arg3 = (unsigned char *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_XOR_swap" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(a);
        arg2 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg2[_rswigi] = INTEGER(a)[_rswigi];
        }
      }
    }
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(b);
        arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg3[_rswigi] = INTEGER(b)[_rswigi];
        }
      }
    }
    (arg1)->XOR_swap(arg2,arg3);
    r_ans = R_NilValue;
    
    free(arg2);
    
    
    free(arg3);
    
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
    
    free(arg2);
    
    
    free(arg3);
    
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_KSA ( SEXP self, SEXP key, SEXP S, SEXP swap_type)
{
  {
    RC4 *arg1 = (RC4 *) 0 ;
    char *arg2 = (char *) 0 ;
    unsigned char *arg3 = (unsigned char *) 0 ;
    int arg4 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_KSA" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    arg2 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(key, 0))));
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(S);
        arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg3[_rswigi] = INTEGER(S)[_rswigi];
        }
      }
    }
    arg4 = static_cast< int >(INTEGER(swap_type)[0]);
    (arg1)->KSA(arg2,arg3,arg4);
    r_ans = R_NilValue;
    free(arg2);
    
    free(arg3);
    
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
    free(arg2);
    
    free(arg3);
    
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_PRGA ( SEXP self, SEXP S, SEXP plaintext, SEXP ciphertext, SEXP swap_type)
{
  {
    RC4 *arg1 = (RC4 *) 0 ;
    unsigned char *arg2 = (unsigned char *) 0 ;
    char *arg3 = (char *) 0 ;
    unsigned char *arg4 = (unsigned char *) 0 ;
    int arg5 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_PRGA" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(S);
        arg2 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg2[_rswigi] = INTEGER(S)[_rswigi];
        }
      }
    }
    arg3 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(plaintext, 0))));
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(ciphertext);
        arg4 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg4[_rswigi] = INTEGER(ciphertext)[_rswigi];
        }
      }
    }
    arg5 = static_cast< int >(INTEGER(swap_type)[0]);
    (arg1)->PRGA(arg2,arg3,arg4,arg5);
    r_ans = R_NilValue;
    
    free(arg2);
    
    free(arg3);
    
    free(arg4);
    
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
    
    free(arg2);
    
    free(arg3);
    
    free(arg4);
    
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_store_hash ( SEXP self, SEXP plaintext, SEXP hashtext, SEXP swap_type, SEXP s_swig_copy)
{
  {
    std::string result;
    RC4 *arg1 = (RC4 *) 0 ;
    char *arg2 = (char *) 0 ;
    unsigned char *arg3 = (unsigned char *) 0 ;
    int arg4 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_store_hash" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    arg2 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(plaintext, 0))));
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(hashtext);
        arg3 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg3[_rswigi] = INTEGER(hashtext)[_rswigi];
        }
      }
    }
    arg4 = static_cast< int >(INTEGER(swap_type)[0]);
    result = (arg1)->store_hash(arg2,arg3,arg4);
    r_ans = SWIG_From_std_string(static_cast< std::string >(result));
    free(arg2);
    
    free(arg3);
    
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
    free(arg2);
    
    free(arg3);
    
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_RC4_compute ( SEXP self, SEXP key, SEXP plaintext, SEXP hashtext, SEXP swap_type)
{
  {
    unsigned char *result = 0 ;
    RC4 *arg1 = (RC4 *) 0 ;
    char *arg2 = (char *) 0 ;
    char *arg3 = (char *) 0 ;
    unsigned char *arg4 = (unsigned char *) 0 ;
    int arg5 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "RC4_compute" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    arg2 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(key, 0))));
    arg3 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(plaintext, 0))));
    {
      {
        int _rswigi;
        int _rswiglen = LENGTH(hashtext);
        arg4 = static_cast< unsigned char * >(calloc(sizeof(unsigned char), _rswiglen));
        for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
          arg4[_rswigi] = INTEGER(hashtext)[_rswigi];
        }
      }
    }
    arg5 = static_cast< int >(INTEGER(swap_type)[0]);
    result = (unsigned char *)(arg1)->compute(arg2,arg3,arg4,arg5);
    r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_unsigned_char, 0 |  0 );
    free(arg2);
    free(arg3);
    
    free(arg4);
    
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
    free(arg2);
    free(arg3);
    
    free(arg4);
    
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_new_RC4 ( )
{
  {
    RC4 *result = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    result = (RC4 *)new RC4();
    r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_RC4, SWIG_POINTER_OWN |  0 );
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_delete_RC4 ( SEXP self)
{
  {
    RC4 *arg1 = (RC4 *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_RC4, SWIG_POINTER_DISOWN |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_RC4" "', argument " "1"" of type '" "RC4 *""'"); 
    }
    arg1 = reinterpret_cast< RC4 * >(argp1);
    delete arg1;
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    R_ClearExternalPtr(self);
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Cipher_C_cipher ( SEXP self, SEXP plaintext, SEXP key, SEXP s_swig_copy)
{
  {
    std::string result;
    Cipher *arg1 = (Cipher *) 0 ;
    std::string arg2 ;
    int arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Cipher_C_cipher" "', argument " "1"" of type '" "Cipher *""'"); 
    }
    arg1 = reinterpret_cast< Cipher * >(argp1);
    {
      std::string *ptr = (std::string *)0;
      int res = SWIG_AsPtr_std_string(plaintext, &ptr);
      if (!SWIG_IsOK(res) || !ptr) {
        SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_C_cipher" "', argument " "2"" of type '" "std::string""'"); 
      }
      arg2 = *ptr;
      if (SWIG_IsNewObj(res)) delete ptr;
    }
    arg3 = static_cast< int >(INTEGER(key)[0]);
    result = (arg1)->C_cipher(arg2,arg3);
    r_ans = SWIG_From_std_string(static_cast< std::string >(result));
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Cipher_KC_encode ( SEXP self, SEXP key, SEXP s_swig_copy)
{
  {
    std::string result;
    Cipher *arg1 = (Cipher *) 0 ;
    std::string arg2 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Cipher_KC_encode" "', argument " "1"" of type '" "Cipher *""'"); 
    }
    arg1 = reinterpret_cast< Cipher * >(argp1);
    {
      std::string *ptr = (std::string *)0;
      int res = SWIG_AsPtr_std_string(key, &ptr);
      if (!SWIG_IsOK(res) || !ptr) {
        SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_KC_encode" "', argument " "2"" of type '" "std::string""'"); 
      }
      arg2 = *ptr;
      if (SWIG_IsNewObj(res)) delete ptr;
    }
    result = (arg1)->KC_encode(arg2);
    r_ans = SWIG_From_std_string(static_cast< std::string >(result));
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_Cipher_KC_cipher ( SEXP self, SEXP plaintext, SEXP encoded_text, SEXP s_swig_copy)
{
  {
    std::string result;
    Cipher *arg1 = (Cipher *) 0 ;
    std::string arg2 ;
    std::string arg3 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, 0 |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "Cipher_KC_cipher" "', argument " "1"" of type '" "Cipher *""'"); 
    }
    arg1 = reinterpret_cast< Cipher * >(argp1);
    {
      std::string *ptr = (std::string *)0;
      int res = SWIG_AsPtr_std_string(plaintext, &ptr);
      if (!SWIG_IsOK(res) || !ptr) {
        SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_KC_cipher" "', argument " "2"" of type '" "std::string""'"); 
      }
      arg2 = *ptr;
      if (SWIG_IsNewObj(res)) delete ptr;
    }
    {
      std::string *ptr = (std::string *)0;
      int res = SWIG_AsPtr_std_string(encoded_text, &ptr);
      if (!SWIG_IsOK(res) || !ptr) {
        SWIG_exception_fail(SWIG_ArgError((ptr ? res : SWIG_TypeError)), "in method '" "Cipher_KC_cipher" "', argument " "3"" of type '" "std::string""'"); 
      }
      arg3 = *ptr;
      if (SWIG_IsNewObj(res)) delete ptr;
    }
    result = (arg1)->KC_cipher(arg2,arg3);
    r_ans = SWIG_From_std_string(static_cast< std::string >(result));
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_new_Cipher ( )
{
  {
    Cipher *result = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    result = (Cipher *)new Cipher();
    r_ans = SWIG_R_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Cipher, SWIG_POINTER_OWN |  0 );
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


SWIGEXPORT SEXP
R_swig_delete_Cipher ( SEXP self)
{
  {
    Cipher *arg1 = (Cipher *) 0 ;
    void *argp1 = 0 ;
    int res1 = 0 ;
    unsigned int r_nprotect = 0;
    SEXP r_ans = R_NilValue ;
    VMAXTYPE r_vmax = vmaxget() ;
    
    res1 = SWIG_R_ConvertPtr(self, &argp1, SWIGTYPE_p_Cipher, SWIG_POINTER_DISOWN |  0 );
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "delete_Cipher" "', argument " "1"" of type '" "Cipher *""'"); 
    }
    arg1 = reinterpret_cast< Cipher * >(argp1);
    delete arg1;
    r_ans = R_NilValue;
    vmaxset(r_vmax);
    if(r_nprotect)  Rf_unprotect(r_nprotect);
    
    R_ClearExternalPtr(self);
    return r_ans;
    fail: SWIGUNUSED;
  }
  Rf_error("%s %s", SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  return R_NilValue;
}


#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_Basics = {"_p_Basics", "Basics *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_Cipher = {"_p_Cipher", "Cipher *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_Primality = {"_p_Primality", "Primality *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_RC4 = {"_p_RC4", "RC4 *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_uint8_t = {"_p_uint8_t", "uint8_t *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "unsigned char *", 0, 0, (void*)0, 0};

static swig_type_info *swig_type_initial[] = {
  &_swigt__p_Basics,
  &_swigt__p_Cipher,
  &_swigt__p_Primality,
  &_swigt__p_RC4,
  &_swigt__p_char,
  &_swigt__p_uint8_t,
  &_swigt__p_unsigned_char,
};

static swig_cast_info _swigc__p_Basics[] = {  {&_swigt__p_Basics, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_Cipher[] = {  {&_swigt__p_Cipher, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_Primality[] = {  {&_swigt__p_Primality, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_RC4[] = {  {&_swigt__p_RC4, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_char[] = {  {&_swigt__p_char, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_uint8_t[] = {  {&_swigt__p_uint8_t, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_unsigned_char[] = {  {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}};

static swig_cast_info *swig_cast_initial[] = {
  _swigc__p_Basics,
  _swigc__p_Cipher,
  _swigc__p_Primality,
  _swigc__p_RC4,
  _swigc__p_char,
  _swigc__p_uint8_t,
  _swigc__p_unsigned_char,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */


/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic
 * memory is used. Also, since swig_type_info structures store pointers to
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization.
 * The idea is that swig generates all the structures that are needed.
 * The runtime then collects these partially filled structures.
 * The SWIG_InitializeModule function takes these initial arrays out of
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned statically to an initial
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded.
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif

#ifndef SWIG_INIT_CLIENT_DATA_TYPE
#define SWIG_INIT_CLIENT_DATA_TYPE void *
#endif

SWIGRUNTIME void
SWIG_InitializeModule(SWIG_INIT_CLIENT_DATA_TYPE clientdata) {
  size_t i;
  swig_module_info *module_head, *iter;
  int init;

  /* check to see if the circular list has been setup, if not, set it up */
  if (swig_module.next==0) {
    /* Initialize the swig_module */
    swig_module.type_initial = swig_type_initial;
    swig_module.cast_initial = swig_cast_initial;
    swig_module.next = &swig_module;
    init = 1;
  } else {
    init = 0;
  }

  /* Try and load any already created modules */
  module_head = SWIG_GetModule(clientdata);
  if (!module_head) {
    /* This is the first module loaded for this interpreter */
    /* so set the swig module into the interpreter */
    SWIG_SetModule(clientdata, &swig_module);
  } else {
    /* the interpreter has loaded a SWIG module, but has it loaded this one? */
    iter=module_head;
    do {
      if (iter==&swig_module) {
        /* Our module is already in the list, so there's nothing more to do. */
        return;
      }
      iter=iter->next;
    } while (iter!= module_head);

    /* otherwise we must add our module into the list */
    swig_module.next = module_head->next;
    module_head->next = &swig_module;
  }

  /* When multiple interpreters are used, a module could have already been initialized in
     a different interpreter, but not yet have a pointer in this interpreter.
     In this case, we do not want to continue adding types... everything should be
     set up already */
  if (init == 0) return;

  /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
  printf("SWIG_InitializeModule: size %lu\n", (unsigned long)swig_module.size);
#endif
  for (i = 0; i < swig_module.size; ++i) {
    swig_type_info *type = 0;
    swig_type_info *ret;
    swig_cast_info *cast;

#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
#endif

    /* if there is another module already loaded */
    if (swig_module.next != &swig_module) {
      type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
    }
    if (type) {
      /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
      if (swig_module.type_initial[i]->clientdata) {
	type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
      }
    } else {
      type = swig_module.type_initial[i];
    }

    /* Insert casting types */
    cast = swig_module.cast_initial[i];
    while (cast->type) {

      /* Don't need to add information already in the list */
      ret = 0;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
      if (swig_module.next != &swig_module) {
        ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
	if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
#endif
      }
      if (ret) {
	if (type == swig_module.type_initial[i]) {
#ifdef SWIGRUNTIME_DEBUG
	  printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
	  cast->type = ret;
	  ret = 0;
	} else {
	  /* Check for casting already in the list */
	  swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
	  if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
#endif
	  if (!ocast) ret = 0;
	}
      }

      if (!ret) {
#ifdef SWIGRUNTIME_DEBUG
	printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
        if (type->cast) {
          type->cast->prev = cast;
          cast->next = type->cast;
        }
        type->cast = cast;
      }
      cast++;
    }
    /* Set entry in modules->types array equal to the type */
    swig_module.types[i] = type;
  }
  swig_module.types[i] = 0;

#ifdef SWIGRUNTIME_DEBUG
  printf("**** SWIG_InitializeModule: Cast List ******\n");
  for (i = 0; i < swig_module.size; ++i) {
    int j = 0;
    swig_cast_info *cast = swig_module.cast_initial[i];
    printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
    while (cast->type) {
      printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
      cast++;
      ++j;
    }
  printf("---- Total casts: %d\n",j);
  }
  printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void) {
  size_t i;
  swig_cast_info *equiv;
  static int init_run = 0;

  if (init_run) return;
  init_run = 1;

  for (i = 0; i < swig_module.size; i++) {
    if (swig_module.types[i]->clientdata) {
      equiv = swig_module.types[i]->cast;
      while (equiv) {
        if (!equiv->converter) {
          if (equiv->type && !equiv->type->clientdata)
            SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
        }
        equiv = equiv->next;
      }
    }
  }
}

#ifdef __cplusplus
#if 0
{ /* c-mode */
#endif
}
#endif


SWIGEXPORT void SWIG_init(void) {

}
#ifdef __cplusplus
extern "C" {
#endif

#include <R_ext/Rdynload.h>

#ifdef __cplusplus
}
#endif

SWIGINTERN R_CallMethodDef CallEntries[] = {
   {"R_swig_Primality_compute_miller_rabin", (DL_FUNC) &R_swig_Primality_compute_miller_rabin, 4},
   {"R_swig_RC4_byte_swap", (DL_FUNC) &R_swig_RC4_byte_swap, 3},
   {"R_swig_new_Primality", (DL_FUNC) &R_swig_new_Primality, 0},
   {"R_swig_delete_RC4", (DL_FUNC) &R_swig_delete_RC4, 1},
   {"R_swig_Primality_carmichael_num", (DL_FUNC) &R_swig_Primality_carmichael_num, 3},
   {"R_swig_RC4_trad_swap", (DL_FUNC) &R_swig_RC4_trad_swap, 3},
   {"R_swig_delete_Primality", (DL_FUNC) &R_swig_delete_Primality, 1},
   {"R_swig_Primality_miller_rabin_prime", (DL_FUNC) &R_swig_Primality_miller_rabin_prime, 4},
   {"R_swig_Cipher_KC_cipher", (DL_FUNC) &R_swig_Cipher_KC_cipher, 4},
   {"R_swig_Primality_sieve_of_eratosthenes", (DL_FUNC) &R_swig_Primality_sieve_of_eratosthenes, 2},
   {"R_swig_Primality_ETF", (DL_FUNC) &R_swig_Primality_ETF, 3},
   {"R_swig_Basics_rm_gcd", (DL_FUNC) &R_swig_Basics_rm_gcd, 4},
   {"R_swig_new_Basics", (DL_FUNC) &R_swig_new_Basics, 0},
   {"R_swig_RC4_PRGA", (DL_FUNC) &R_swig_RC4_PRGA, 5},
   {"R_swig_Primality_pollard_rho", (DL_FUNC) &R_swig_Primality_pollard_rho, 3},
   {"R_swig_delete_Basics", (DL_FUNC) &R_swig_delete_Basics, 1},
   {"R_swig_Basics_greatest_power", (DL_FUNC) &R_swig_Basics_greatest_power, 4},
   {"R_swig_new_RC4", (DL_FUNC) &R_swig_new_RC4, 0},
   {"R_swig_Primality_is_prime", (DL_FUNC) &R_swig_Primality_is_prime, 3},
   {"R_swig_Primality_mod_pow", (DL_FUNC) &R_swig_Primality_mod_pow, 5},
   {"R_swig_RC4_compute", (DL_FUNC) &R_swig_RC4_compute, 5},
   {"R_swig_new_Cipher", (DL_FUNC) &R_swig_new_Cipher, 0},
   {"R_swig_RC4_XOR_swap", (DL_FUNC) &R_swig_RC4_XOR_swap, 3},
   {"R_swig_delete_Cipher", (DL_FUNC) &R_swig_delete_Cipher, 1},
   {"R_swig_Primality_miller_rabin", (DL_FUNC) &R_swig_Primality_miller_rabin, 4},
   {"R_swig_RC4_store_hash", (DL_FUNC) &R_swig_RC4_store_hash, 5},
   {"R_swig_Cipher_C_cipher", (DL_FUNC) &R_swig_Cipher_C_cipher, 4},
   {"R_swig_Cipher_KC_encode", (DL_FUNC) &R_swig_Cipher_KC_encode, 3},
   {"R_swig_Primality_jacobian_number", (DL_FUNC) &R_swig_Primality_jacobian_number, 4},
   {"R_swig_Primality_solovoy_strassen", (DL_FUNC) &R_swig_Primality_solovoy_strassen, 4},
   {"R_swig_RC4_KSA", (DL_FUNC) &R_swig_RC4_KSA, 4},
   {NULL, NULL, 0}
};

extern "C" SWIGEXPORT void R_init_RM_pkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);


SWIG_init();
SWIG_InitializeModule(0);


}

