clean:
	cd arithmetic && rm -rf arithmetic_wrap.* arithmetic.py 
	cd calculus && rm -rf calculus_wrap.* calculus.py 
	cd linalg && rm -rf linalg_wrap.* linalg.py 
	cd ml && rm -rf ml_wrap.* ml.py 
	cd nt && rm -rf nt_wrap.* nt.py 


