# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _number_theory
else:
    import _number_theory

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Primality(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def is_prime(self, n):
        return _number_theory.Primality_is_prime(self, n)

    def compute_miller_rabin(self, d, n):
        return _number_theory.Primality_compute_miller_rabin(self, d, n)

    def miller_rabin_prime(self, n, iters):
        return _number_theory.Primality_miller_rabin_prime(self, n, iters)

    def miller_rabin(self, inters, min_val, max_val):
        return _number_theory.Primality_miller_rabin(self, inters, min_val, max_val)

    def jacobian_number(self, a, n):
        return _number_theory.Primality_jacobian_number(self, a, n)

    def solovoy_strassen(self, p, iters):
        return _number_theory.Primality_solovoy_strassen(self, p, iters)

    def modulo(self, base, exponent, mod):
        return _number_theory.Primality_modulo(self, base, exponent, mod)

    def modulo_pow(self, base, exponent, mod):
        return _number_theory.Primality_modulo_pow(self, base, exponent, mod)

    def carmichael_num(self, n):
        return _number_theory.Primality_carmichael_num(self, n)

    def sieve_of_eratosthenes(self, n):
        return _number_theory.Primality_sieve_of_eratosthenes(self, n)

    def pollard_rho(self, n):
        return _number_theory.Primality_pollard_rho(self, n)

    def ETF(self, n):
        return _number_theory.Primality_ETF(self, n)

    def __init__(self):
        _number_theory.Primality_swiginit(self, _number_theory.new_Primality())
    __swig_destroy__ = _number_theory.delete_Primality

# Register Primality in _number_theory:
_number_theory.Primality_swigregister(Primality)

